### ISSUE TITLE
[Bug]: Compact machine not properly inheriting biome

### ISSUE THREAD

**Issue by SirGeremiah** [FTBTeam/FTB-Modpack-Issues#103]
### Modpack

FTB OceanBlock

### Modpack version

1.2.0

### Describe the bug

According to Compact Machines update logs, current version (version in the modpack) the cube (in the Machine World) should inherit the biome the compact machine is placed in. Currently seeing void as biome in the cube, while the machine is placed in deep warm ocean.

### Steps to reproduce

1. Place a compact machine within the deep warm ocean biome (verified on debug screen).
2. Enter the machine.
3. Check biome inside cube.

### Expected behaviour

Biome inside cube should be "deep_warm_ocean".

### Additional information

I reviewed the update logs of the mod, and the code in the update shows the machine's placement should provide the biome for the cube. This appears to be hard-coded, not a configurable trait.

**Comment by Raidobw2** [comment]
Hello, 

Would it be possible to send us the location where you found those changelogs?

By looking at the code from the Github repository for CompactMachines4 in their latest work, i can only see this:

```
"generator": {
    "type": "minecraft:flat",
    "settings": {
      "biome": "minecraft:the_void"
```
(https://github.com/CompactMods/CompactMachines/blob/1.16.x/src/main/resources/data/compactmachines/dimension/compact_world.json)

Which tells me the biome for all that Compact Machine world is "the_void". I have not seen any reference to dynamic biomes within source files or config files elsewhere within their repo, although i have not checked all of them.

Would it be possible to provide a little more information about it for our modpack developer?

Thank you!

**Comment by Raidobw2** [comment]
Hello,

I did look at that commit, unfortunately it's from 6 years ago, so the code has changed a lot since. Here's the recap:

Introduction to biome inheritance
(2015) Compact Machines
CompactMods/CompactMachines@4025ac7

Initial changes to biome logic
(2017) Compact Machines 3
CompactMods/CompactMachines@7f0e124

Attempted changes to reduce the chance of world generators to generate biome-specific structures in the CM dimension
(2018) Compact Machines 3
CompactMods/CompactMachines@19f6760

Introduced the void world generator instead of custom biomes
(2020) Compact Machines 3
CompactMods/CompactMachines@43ed5f2
The old code from the first commit was now put deprecated (in comment):
https://github.com/CompactMods/CompactMachines/blob/43ed5f20a35fd9e3f263d75807b969bffb69d4ba/src/main/java/com/robotgryphon/compactmachines/block/BlockCompactMachine.java#L226

It looks like the author and package name changed in the summer of 2019 and the vision of the mod was already starting to change in 2018 by a commit by "thraaawn". Probably with the fact that it might have been hard to prevent custom world generation happening in the compact machines dimension due to them being overworld biomes. Hence the introduction of the void dimension which seems to have solved that problem.

We are now in (2021) Compact Machines 4. All other commits mentioned in my posts are pre-minecraft 1.16.
Therefore, i understand that the vision for that mod has changed and it is working as intended.

If you wish to have this changed, please create a new issue on their Github and suggest it.

If your suggestion gets worked on or accepted from them, then the mod will get an update and the normal update cycle for this modpack will continue, meaning that the modpack developer will update the mod once it is released.

Thank you for your comprehension,

R3GEN
