### ISSUE TITLE
[Bug]: FTB-One install script doesn't set up modules to be loaded

### ISSUE THREAD

**Issue by halb** [FTBTeam/FTB-Modpack-Issues#1035]
### Modpack

FTB One

### Modpack version

1.1.0

### Describe the bug

The worldgen doesn't seem to generate rare ores, such as those from Industrial Contraptions (tin, lead, aluminum, uranium, etc).
Running under Minecraft 1.19.1.

### Steps to reproduce

Install dedicated Linux server.
Log in and Mine.

### Expected behaviour

Find at least some of the rare ores

**Comment by halb** [comment]
Looking at this in creative mode - I can't even place the rare ores on the map.  Are there some more log files I can include?  The ones under /logs don't seem very useful.

**Comment by halb** [comment]
This appears to be OBE.  I reran this with a fresh server install and am no longer experiencing the problem.  One thing I noticed is that the new install has a different start.sh file that includes @libraries/net/minecraftforge/forge/1.19-41.0.38/unix_args.txt

**Comment by Raidobw2** [comment]
Hi, if the server is started with the minecraft_server.jar, it will be a vanilla server. We're aware of some issues with our installer script. If you are using Linux, make sure Java is installed on the system before using the installer. As well, if this issue is resolved, please close this ticket and thanks, otherwise let me know if you need more help
