### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by theodoorhughes** [FTBTeam/FTB-Modpack-Issues#1042]
### Modpack

ftb:plexiglass-mountain

### Modpack version

1.1.1

### Describe the bug

mining silver bedrock ore with the enchantment:extraction only gives the regenerative lead cluster.

### Steps to reproduce

see error

### Expected behaviour

mining silver bedrock ore should give a regenerative silver cluster

**Comment by Raidobw2** [comment]
Thanks for the report, this is fixed in-dev at #1013, but not yet released to the public. If you want, the fix is found at that other issue too, it's a very easy fix. This can be done only on the server if you play with friends, or simply in your game as well.

I'll close this since I'll be tracking at the other issue
