### ISSUE TITLE
[Bug]: Unable to craft AE2 Quantum Entangled Singularity

### ISSUE THREAD

**Issue by soraemon139** [FTBTeam/FTB-Modpack-Issues#1054]
### Modpack

FTB Direwolf20 1.18

### Modpack version

1.6.1

### Describe the bug

Currently, you can't use Ender Dust from FTB Industrial Contraptions to craft Quantum Entangled Singularity from AE2. 
Using Ender Dust from AE2 works fine but there's no way to obtain the AE2 version of Ender Dust in survival.

### Steps to reproduce

1. Place down a TNT or Tiny TNT
2. Drop a Singularity and Ender Dust on or near the TNT
3. Ignite the TNT

### Expected behaviour

A pair of Quantum Entangled Singularity

**Comment by Soulflare3** [comment]
I can confirm this affecting other recipes as well

I think it's related to oredict?

If I look at the wireless booster for AE and hover over the ender dust, it has

> accepts any: forge:dusts/ender_pearl

And accepts the AE2 recipe or the Thermal Series recipe, but not the FTB Industrial Contraptions recipe

Enderium dust from FTB Industrial Contraptions also does not have this

The only one you can craft is the FTB Industrial Contraptions recipe, but then it doesn't recognize it for any other recipes

**Comment by TheonlyTazz** [comment]
> I can confirm this affecting other recipes as well
> 
> I think it's related to oredict?
> 
> If I look at the wireless booster for AE and hover over the ender dust, it has
> 
> > accepts any: forge:dusts/ender_pearl
> 
> And accepts the AE2 recipe or the Thermal Series recipe, but not the FTB Industrial Contraptions recipe
> 
> Enderium dust from FTB Industrial Contraptions also does not have this
> 
> The only one you can craft is the FTB Industrial Contraptions recipe, but then it doesn't recognize it for any other recipes

![image](https://user-images.githubusercontent.com/3908847/177291600-fe44ba8b-ccfa-49a1-b9cb-384b826dff83.png)
i can actually use FTB IC Ender Dust for Wireless Booster. Could you check if your FTBIC Ender Dust has the forge:dust/ender_pearl tag, because it does on my testing enviroment

Also using FTB IC Ender Dust for Quantum Entangled Singularities is working for me
![image](https://user-images.githubusercontent.com/3908847/177292171-7e7412ba-3bdb-4ae6-a8ed-73492ed490e1.png)
![image](https://user-images.githubusercontent.com/3908847/177292648-557b2097-77ea-43da-a8b7-23b54825ec8c.png)
![image](https://user-images.githubusercontent.com/3908847/177292670-859f6446-52dc-4ed0-9b8e-e2dfb4f804d0.png)

**Comment by soraemon139** [comment]
So I went back and did some further testing and found some quirky behaviors.
Yes, using FTB IC Ender Dust for Quantum Entangled Singularities does work... BUT there's a 100% of it failing if you throw the Ender Dust first.

Ender Dust then Singularity VS Singularity then Ender Dust:
https://youtu.be/jwLPgo6hn94
