### ISSUE TITLE
[Bug]: Constant errors including Can't keep up! Is the server overloaded?

### ISSUE THREAD

**Issue by Beetlejuicex22** [FTBTeam/FTB-Modpack-Issues#1058]
### Modpack

FTB One

### Modpack version

1.2.1

### Log Files

[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9033122/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9033123/latest.log)
[rei.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9033124/rei.log)

### Describe the bug

Mod pack overloads the server?

### Steps to reproduce

N/A

### Expected behaviour

N/A

### Additional information

There's not much to describe but I by myself or even with my friend will be playing for a while and then all of a sudden we start to get kicked out of the server before it seemed it was connection errors but out internet was fine, yesterday was the first time that i got other errors that seemed different on my screen, sometimes I would not get an error at all, just client goes off looking then get kicked out but the server is still on. 

Ex of other errors :

minecraft/PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket@64029d8, suppressing error

java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.toString()" because "p_130086_" is null

**Comment by Raidobw2** [comment]
Hello, concerning the latest.log you posted, it failed to bind the port:
```
[02Jul2022 13:29:32.941] [Server thread/WARN] [net.minecraft.server.dedicated.DedicatedServer/]: **** FAILED TO BIND TO PORT!
[02Jul2022 13:29:32.942] [Server thread/WARN] [net.minecraft.server.dedicated.DedicatedServer/]: The exception was: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
[02Jul2022 13:29:32.942] [Server thread/WARN] [net.minecraft.server.dedicated.DedicatedServer/]: Perhaps a server is already running on that port?
```
Perhaps something else is using that port, or the server.properties has it wrongly setup. If you don't know what to put in server.properties, leave the server address and port fields blank. It'll default to your public IP for that server and port 25565.

Concerning `minecraft/PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket@64029d8, suppressing error`, if it happens when logging in I'm not sure it's super important. Definitely a mod problem though, but I think that might not affect gameplay. Only from that information I unfortunately don't know what that mod would be.

Concerning `java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.toString()" because "p_130086_" is null`, I've seen a similar error due to Resource Chickens by CreeperHost. If you have Roosts, make sure to clear their inventory and use cables to pull products out all the time. I have reported this to CreeperHost at https://github.com/CreeperHost/Chickens/issues/6.

I'm not exactly sure if that answers one of your questions about those problems since it's currently unclear for me if your server is running properly or not. When the server says "Can't keep up! Is the server overloaded?" usually that's because someone is exploring. Exploration generates new chunks and causes every server to struggle more than normally, since it's very CPU intensive.

If you manage to get the error the client gets and its log, let me know I might be able to help. In any case, let me know if you still need help for anything.

**Comment by Beetlejuicex22** [comment]
Thabk you so much for responding that was alot of great Information. I
switched from pipes mod to hoppers for moving the items from the roots but
I guess I should switch back?
