### ISSUE TITLE
[Bug]: The game crashed whilst unexpected error Error: java.lang.ArrayIndexOutOfBoundsException: 1 Exit-Code: -1

### ISSUE THREAD

**Issue by kienee** [FTBTeam/FTB-Modpack-Issues#108]
### Modpack

FTB Oceanblock

### Modpack version

1.2

### Log Files

[crash-2021-10-09_15.46.25-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7315713/crash-2021-10-09_15.46.25-client.txt)

### Describe the bug

Hey,

recently i get a lot of this unexpected Crashes. Never had it befor with any FTB / Curseforge Modpacks or whatsoever.
I am playing OceanBlock 1.2 atm on a server with a friend and im the only one getting the crashes :/.

### Steps to reproduce

Dont know how to reproduce

### Expected behaviour

Not crashing i guess?

**Comment by Raidobw2** [comment]
Hi kienee!
There is currently a bug from the MineTogether mod that has been fixed in dev for the mod, but not released yet. The details are found at: #67.

When a client disconnects wrongly from a server they will crash with that message. I've observed players having this fixed temporarily by installing the RandomPatches mod on both servers and clients.

This mod makes the login read timeout 3 times higher than normal (90 seconds total) and helps joining the game at times, instead of having a disconnection occur. It is obtainable at https://www.curseforge.com/minecraft/mc-mods/randompatches-forge, but you can also directly install it in the FTB App under the Mods section, in the modpack page.
A reminder that both ends need the mod for it to work!

Let me know if that works as a temporary solution so i can close this ticket since it is a duplicate!

Otherwise i will have you remove the mod and do a special config to allow you to resume playing if RandomPatches didn't work.
