### ISSUE TITLE
[Suggestion]: Replace Akashic Tome with Eccentric Tome

### ISSUE THREAD

**Issue by gargan26** [FTBTeam/FTB-Modpack-Issues#1084]
### Modpack

FTB Direwolf20 1.18

### Is your suggestion related to a problem? Please describe.

Akashic Tome [does not allow multiple books from the same mod to be added](https://github.com/VazkiiMods/AkashicTome/issues/53). I.e., Tinker's Construct, etc.  The developers don't seem to care or have any plans on fixing this bug.  The mod author of [Eccentric Tome](https://www.curseforge.com/minecraft/mc-mods/eccentric-tome) became fed up with this and wrote his mod from scratch as a direct replacement for Akashic Tome to fix this issue.

### Mod suggestion

[Eccentric Tome](https://www.curseforge.com/minecraft/mc-mods/eccentric-tome)
This is a direct replacement for Akashic Tome with the ability to add multiple books from the same mod.

**Comment by InFuRiTy** [comment]
I second that!!!

**Comment by Raidobw2** [comment]
That's odd since the Akashic Tome actually is able to morph into any item looking at its config... For Tinkers guides they all have different ids as well, so this should be no problem. For any Patchouli books, even with the same ids... Akashic Tome & Patchouli are coded by the same author and are compatible.

Normally we don't remove/change mods unless the original mod (Akashic Tome) is broken. While Eccentric Tome might be a direct improvement according to what you were saying, I'm not sure we can have it for this time. Although we will certainly consider it for future packs, thank you (I'll pass the word).

Currently in `akashictome-common.toml` you can define whitelisted items or names (regex):
![image](https://user-images.githubusercontent.com/17010632/178072823-e464b08b-23a1-4c8e-bfcc-a9505c705ec0.png)
In Plexiglass Mountain we have the Tinker Books inside whitelisted items, and even the XP Crystal can go there too, and they all work and appear inside the Akashic Tome with their full functions.

Optionally a recipe for the Akashic Tome receiving the tome fully filled might be good as well.
Example: https://paste.feed-the-beast.com/view/6c43ee2d
This is however not suited perfectly for this pack and the script needs to be adjusted for DW20 1.18.

```
onEvent("recipes", (event) => {
    event.shapeless( /*Full_content_of_slash_kubejs_hand_goes_here_for_the_input*/ , ['minecraft:book', '#forge:bookshelves']).id('akashictome:tome');
});
```

I'll leave the specifics and discretion to swap the mod or configure it if it works to one of my colleagues which currently maintains DW20 1.18.

**Comment by TheonlyTazz** [comment]
going to be adding Eccentric Tome to the Pack. I will keep Akashic Tome in for atleast 1 more Update, so people can convert their existing Tome.
