### ISSUE TITLE
[Bug]: Crash after trying to break Floating Hopperhock from Botania

### ISSUE THREAD

**Issue by Mundif** [FTBTeam/FTB-Modpack-Issues#1088]
### Modpack

FTB Presents Direwolf 20 1.18

### Modpack version

1.7.0

### Log Files

[crash-2022-07-09_16.14.30-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9077368/crash-2022-07-09_16.14.30-client.txt)
[crash-2022-07-09_16.19.23-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9077369/crash-2022-07-09_16.19.23-client.txt)
[crash-2022-07-09_16.23.18-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9077370/crash-2022-07-09_16.23.18-client.txt)
[crash-2022-07-09_16.27.51-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9077371/crash-2022-07-09_16.27.51-client.txt)
[crash-2022-07-09_16.37.27-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9077372/crash-2022-07-09_16.37.27-client.txt)

### Describe the bug

When trying to break Floating Hopperhock game crashes, It doesnt crash when it is instantly mined, used Ars Nouveau break spell to clean it up, creative mode might have worked as well I think.

### Steps to reproduce

Place Floating Hopperhock and attempt to break it, it cant be instant minning like in creative mode, game should crash whille breaking it.

### Expected behaviour

No crash while attempting to break floating hopperhock

**Comment by Mundif** [comment]
Found issue at Botania github that looks very similar to this. 
https://github.com/VazkiiMods/Botania/issues/4067

**Comment by faanlez** [comment]
I can confirm it crashes when trying to break any floating flower without instant mining. Mekanism's Atomic Disassembler or any decently fast shovel can instant mine the floating flowers.

Reverting the `experimentalForgeLightPipelineEnabled` change fixes this in the short term if you don't have anything to instant mine the flowers. Weirdly the crash still happens when using Rubidium where the benefits of that setting do not work anyway.

**Comment by TheonlyTazz** [comment]
i'm reverting the `experimentalForgeLightPipelineEnabled` for now as it seems to cause more harm than good
