### ISSUE TITLE
[Bug]: Game crashing due to chickens?

### ISSUE THREAD

**Issue by wqwq29** [FTBTeam/FTB-Modpack-Issues#1098]
### Modpack

FTB One

### Modpack version

1.2.1

### Log Files

[crash-2022-07-10_17.20.38-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9080014/crash-2022-07-10_17.20.38-client.txt)

### Describe the bug

Everytime we load into a specific area we crash

### Steps to reproduce

Load into server
Crash

### Expected behaviour

Not crashing

**Comment by Raidobw2** [comment]
Hello, that is a bug with Resource Chickens due to a Roost block. I've reported this a few days ago at https://github.com/CreeperHost/Chickens/issues/6.

One solution is to restore a backup. You might lose some progress when doing so. Backups are stored in the `backups` folder of your game, and zip files are contained inside. By extracting/opening a zip file, there is a world folder inside. Take that world folder to your `saves` folder, or if it's a multiplayer server you must replace the current world with it. I don't recommend that option for the simplicity of this issue, but know this is generally useful.

The other solution is to look into your world folder into the `region` folder. Inside are a bunch of files. Find the one called `r.-2.-1.mca` and drag it here if it fits. If it doesn't fit, use a file sharing service -- Google Drive is common and easy to use for that (right click the Google Drive file and share).
I can basically fix the file for you and remove the problematic Roost block. That takes me less than 5 minutes so it's really easy. If you choose that I'll send you the fixed file (which removes the Roost block), and you simply overwrite the file you had at `world/region/r.-2.-1.mca` with the one I'll give you. That'll get you back on track until that bug is fixed.

In either case, that'll fix the crash. If you want to continue using Roost blocks, make sure to use cables/hopper and to always empty the Roosts of any materials they produce, that's my advice.

**Comment by wqwq29** [comment]
Thank you! I ended up just filling the new block placement that broke it and fixed it, just wanted to make sure the bug was known :) is this when a roost is connected with Tom’s Simple Storage? That’s what broke it for me

**Comment by kevinsbarnard** [comment]
FYI, I put in a fix PR: https://github.com/CreeperHost/Chickens/pull/7
