### ISSUE TITLE
[Bug]: FTB Plexiglass Mountain Render Distance Bug

### ISSUE THREAD

**Issue by tinypanda31** [FTBTeam/FTB-Modpack-Issues#1104]
### Modpack

Plexiglass Mountain

### Modpack version

1.1.1

### Describe the bug

I run a server with about two dozen or so people, and this pack is great but we are having a problem on our Ubuntu VPS, it seems as though our render distance in server.properties is ignored and the render distance is stuck at 16 or something.  Not too experienced running servers but if you do your admin analysis in FTB chunks one player is loading almost 1k chunks. Unless it counts subchunks?

### Steps to reproduce

1. Edit server.properties to have a smaller render distance
2. Check how many chunks are loaded with /ftbchunks admin 

### Expected behaviour

Server.properties to listen to my render distance

**Comment by Raidobw2** [comment]
Hello, I'm unsure if the FTB Chunks loaded chunks count is relevant or bugged. I'll pass the message to our mod dev.

Looks like in Singleplayer I'm loading 4k chunks haha:
![image](https://user-images.githubusercontent.com/17010632/178433796-5d7efc8d-17e8-49ab-895f-9ce98d3cdd95.png)
![image](https://user-images.githubusercontent.com/17010632/178433821-88f972d2-9495-4330-8cc9-b3b63c786cdb.png)
That's obviously not possible since the chunks don't load quick enough in sight anyways, so I'd be surprised if that's actually accurate for the current version of the mod.

If you meant force loaded chunks, you can normally remove them with `/ftbchunks admin unload_everything`. That command unloads chunks forced by the player through the FTB Chunks claimed chunks GUI.
Barely visible here, but the chunks at the right with red bars over them are force loaded - always active and ticking:
![image](https://user-images.githubusercontent.com/17010632/178434483-4d8f7cbd-4545-434f-9d9c-c62db6f70abb.png)

By default Crash Utilities is installed on your server, if you press "Ctrl +U" (or rebind it), you'll see actual loaded chunks. There you can make sure it actually respects the 16 chunk render distance.
![image](https://user-images.githubusercontent.com/17010632/178435235-2cb98b95-b35d-46b1-b3f7-f3162b49a826.png)

Let me know if that answers your question, or if you need help diagnosing lag on the server with Spark, if that is the issue.
`/spark profiler` to start the profiler
`/spark profiler --stop` to stop it, 30 seconds to a minute after.

**Comment by Raidobw2** [comment]
Relayed as a bug to the above issue ^

I assume this answered your question so I'll close this issue
