### ISSUE TITLE
[Bug]: Oak Crucibles Inffinity storage.

### ISSUE THREAD

**Issue by ozoomaroo** [FTBTeam/FTB-Modpack-Issues#1147]
### Modpack

FTB Stone BLock 2

### Modpack version

1.22.0 

### Describe the bug

While setting up an automatic Farm to input water into Oak crucibles Via extra utilities.  then Convert that water to clay utilizing a dust input Via extra utilities. as the Fluid transfer pipe Takes in Fluid and scans for output It outputs the water Like normal It filled the first three crucibles Just fine afterward it then continuously Output into the first 3 crucibles.(second row and Third row Left are filled Due to pipe manipulation) Consuming 600K+ buckets of water. in Image 2. One iron Drum is missing as it emptied so I removed it from the node However when replacing the drum it refilled it normally so that narrowed the issue down to the crucibles. 

### Steps to reproduce

1. craft 24 Oak crucibles.
2. connect them via 23 transfer pipes
3. Three Iron drums full of water
4. attach three Fluid transfer pipes.
5. Let's run

### Expected behaviour

Each oak crucible Would fill And then Stop filling like Wooden crucibles entended function.

### Screenshots

![image](https://user-images.githubusercontent.com/109803390/180437926-92e31dcd-9d40-4f87-be5b-c156729c0eca.png)
![image](https://user-images.githubusercontent.com/109803390/180437953-513fa625-915d-4047-8605-55e091dcbc25.png)

### Additional information

Currently, We have the pack running on https://exaroton.com/ A pay-as-you-go Server host. I'm Not entirely sure if this has anything to do with the oddly functioning crucibles.

**Comment by Raidobw2** [comment]
Hello, that is likely a mod interaction and would require a mod update. Unfortunately 1.12.2 is unsupported by most mod authors at that point and there isn't really a way for us to fix that other than disabling the cables.

Since we know those cables work in other scenarios, we'd have to leave them be.

What I recommend instead is to use another pipe to transfer fluids. Fluiducts or fluid conduits are very good at that task and should hopefully interact with the crucibles fine.

Let me know if using another pipe as I suggested worked, since we'll close this issue after
