### ISSUE TITLE
[Bug]: Server Crash - FTB One

### ISSUE THREAD

**Issue by AdamBundschuh** [FTBTeam/FTB-Modpack-Issues#1168]
### Modpack

FTB One

### Modpack version

1.3.0

### Log Files

https://pste.ch/nexobexolu.pl

### Describe the bug

Was just running through the world, wasn't actively using a specific mod or anything.

### Steps to reproduce

World gen while running? Not sure.

### Expected behaviour

Not crashing (sorry, required field)

**Comment by Raidobw2** [comment]
Maybe could be linked to #1156, though I'm unsure. Has this happened consistently or randomly, once?

**Comment by AdamBundschuh** [comment]
The crashes from #1156 and this single one are the only ones I've experienced.

**Comment by Raidobw2** [comment]
Hmm I see. When any of those 2 crashes happen, can you note your players coordinates (if possible) and send us a world download here, with those coordinates?

Watchdog crashes have a tendency to be hard to diagnose, but usually they reappear (since it's basically a mod causing massive lag). The best pointer I've ever had with watchdog crashes are player coordinates within a world, since they allow to see what's around the player that could be causing issues.

There's been one off case of a watchdog crash pattern I've seen in other modpacks we made, though we figured out they were due to RoadRunner, which isn't in FTB One to my knowledge.

**Comment by Saereth** [comment]
This was a bug linked to chunks which is now fixed and included in the ftb one 2.0 update as soon as it's rady
