### ISSUE TITLE
[Bug]: 1.8.0 lan will not work.

### ISSUE THREAD

**Issue by Therippers** [FTBTeam/FTB-Modpack-Issues#1169]
### Modpack

FTB Direwolf 1.18

### Modpack version

1.8.0

### Describe the bug

We been playing on 1.7.0 no issues into connecting to lan world.   When we updated to 1.8.0  My daughter could not see the world anymore or even direct connect.

### Steps to reproduce

1.  down graded back to 1.7  she was able to connect
2. went back to 1.8.0 and she not able to.
3. 

### Expected behaviour

when we updated to current pact she should of still seen the lan world

**Comment by Raidobw2** [comment]
Hmm. There's been a few mentions of this at #1133 and #1162 though I couldn't reproduce it.

Did a fresh installation work or do you have any game logs to help us find the problem? Thank you in advance

Game logs are found in the modpack files. In the FTB App they are in the modpack Settings and click Open Folder. In the `logs` folder is where the `latest.log` file is, which is the main game log.

**Comment by Therippers** [comment]
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9185857/latest.log)

Wife and I are wired to the network and daughter is on the Wi-Fi.  She started 1.7.0   and then took a break for a few days.  Update came out and wife and I updated to 1.8.0 and Sunday  my daughter wanted to play again  so she updates her game to 1.8.0  and tells me  she does not see the lan.  I know we was having difficult with our internet  so  I swapped out internet.  Had her try again  and still nothing so I started investigating.  We both downgraded to 1.7.0  and she was able to see the lan.  Then we went back to 1.8.0 and I opened up the world  and she could not see it again.  I was like  ok maybe the world was going bad.  So I created a test world  and opened up the lan  and  still could not seen the lan.  I check the firewall  and nothing has changed.  I had to buy a server hosting and load the world there so she could play as the update that was done  was great.  I went ahead and added the log file as you asked.   I can also make a video to show you what is going on.

**Comment by Raidobw2** [comment]
I see, that's odd that 1.7.0 works but not 1.8.0. On the problematic computer -- your daughter's computer I'm assuming -- is there any error message on the screen when joining your Open to LAN server?

I've checked the current log you posted though it's composed of a mix of multiple connections and it's difficult to see if at some point your game opened the world to LAN. Could it be possible for you to delete your game log (and your daughter's too) and then start the game, try to Open to LAN and connect the games together. Whatever happens from there, there should be more information in the logs and it should be more clear I think.
If you post those 2 logs here then, I think we might have more clues to what's causing this to happen.

Also as a sidenote, it might be helpful to observe what happens if you switch the sides when opening to LAN. For instance if your daughter hosts the LAN server, what happens? Or if you have the opportunity, you could try wiring your daughter's computer with the Ethernet cable and having either of yours or your wife's computer connected to Wifi instead. Then the one on Wifi can try to host the LAN game to see what happens.

Thanks in advance for trying some of those things and getting back to me!
