### ISSUE TITLE
[Bug]: FTB Direwolf20 1.18 1.8.0 server files batch file not working

### ISSUE THREAD

**Issue by dannyboyzane** [FTBTeam/FTB-Modpack-Issues#1175]
### Modpack

FTB Direwolf20 1.18

### Modpack version

1.8.0

### Log Files

![Direwolf20 1 8 0 server batch file failure](https://user-images.githubusercontent.com/109995763/180883462-52408a8a-cd01-46ac-a13d-b487f77ecdf4.PNG)
![Direwolf20 1 8 0 server batch file failure 2](https://user-images.githubusercontent.com/109995763/180883473-25996854-55e6-4343-b7fb-a098fbfdbdb0.PNG)

### Describe the bug

just get the error and i'm not smart enough to fix it my self...please help

### Steps to reproduce

follow the install steps on the FTB site for PC

### Expected behaviour

the server to start like the steps told me

### Screenshots

![Direwolf20 1 8 0 server batch file failure](https://user-images.githubusercontent.com/109995763/180883749-94fddac1-d23e-4a22-b40d-e5462df45d01.PNG)
![Direwolf20 1 8 0 server batch file failure 2](https://user-images.githubusercontent.com/109995763/180883751-dca77955-8cc4-4eaf-b3d4-5bece5057e35.PNG)

**Comment by Raidobw2** [comment]
Hello, try wrapping your first argument in quotes `"argument"`. Windows will interpret it as multiple arguments because there is a space. So that's why it's saying `E:/Minecraft` is not a valid command, because the space messes with the script.

Try this as it is for the Java, copy with the quotes : `"E:/Minecraft servers/DirewolfServer 1/jre/jdk-17.0.2+8-jre/bin/java.exe"`

**Comment by xSumox** [comment]
> Hello, try wrapping your first argument in quotes `"argument"`. Windows will interpret it as multiple arguments because there is a space. So that's why it's saying `E:/Minecraft` is not a valid command, because the space messes with the script.
> 
> Try this as it is for the Java, copy with the quotes : `"E:/Minecraft servers/DirewolfServer 1/jre/jdk-17.0.2+8-jre/bin/java.exe"`


I had to make an account just to say thank you! This helped very much !

**Comment by Raidobw2** [comment]
Cool, glad to hear that helped. Since that should also be resolved for the original poster with the same solution, I'll close this issue. One of the FTB Discord moderators jikuja also referenced a commit above with the server downloader. I believe that commit should fix a similar issue, which I believe led the OP to write this issue in the first place.
For any other problems don't hesitate to reach out, cheers
