### ISSUE TITLE
[Bug]: Firework Star is unobtainable

### ISSUE THREAD

**Issue by wwrage** [FTBTeam/FTB-Modpack-Issues#1178]
### Modpack

Plexiglass Mountain

### Modpack version

1.1.1

### Describe the bug

Firework star is listed as having no recipe, and as such appears presently unobtainable. The only use for it is for creating the Ars Noveau AOE glyph.

### Steps to reproduce

Search for Firework Star in REI
Click or press "R" (Or key bound to "show recipe")

### Expected behaviour

Should show a recipe or some method of obtaining

**Comment by quietust** [comment]
What happens if you manually place appropriate firework star ingredients (gunpowder, at least one piece of dye, and any optional extra items) in a crafting grid?

According to the Minecraft wiki, there are about 29.6 _quintillion_ unique firework stars, so JEI typically doesn't try to display recipe previews for them. For the same reason, it generally doesn't show Firework Rocket recipes either.

**Comment by Raidobw2** [comment]
I added an information block for it:
![image](https://user-images.githubusercontent.com/17010632/185240645-f398f5b8-9643-462d-a731-09ebd3e244ce.png)
Localization (other languages) comes in a future PGM update, so for now this is only in English

**Comment by Raidobw2** [comment]
The above info should be in 1.2.0 to help making them, press R on firework star to see it

**Comment by ccbmeyer** [comment]
This exact same issue is now in Direwolf20 1.19 1.11.0
