### ISSUE TITLE
[Bug]: Champions Mod Unconfigured

### ISSUE THREAD

**Issue by zig13** [FTBTeam/FTB-Modpack-Issues#1188]
### Modpack

Plexiglass Mountain

### Modpack version

1.1.1

### Log Files

N/A

### Describe the bug

Champion mods can spawn on night 1 in the proximity of a player who has just started and only has a wood sword.
For example a Zombie with Adaptable, Knocking, and Wounding.
The Champions Mod is not configured in the server or singleplayer builds of Plexiglass Mountain 1.1.1 . 
In fact the Champions folder in config is missing so users cannot even configure themselves.

### Steps to reproduce

1 Launch Plexiglass Mountain 1.1.1 server
2 Join server
3 Wait till night
4 Die to Champion monster with no hope of survival

### Expected behaviour

Champion mods should not spawn in the proximity of players who are not ready to deal with them. This can be configured.

**Comment by Raidobw2** [comment]
Hmm, I'll see what I can do about that. The mod is currently configured and almost all champions modifiers are disabled. Only a select few I've left leave the potential for the player to outplay the mob or outrun it. As long as one runs (except maybe the Ars Nouveau mobs, they have more mobility but are nerfed early game for that reason), they won't die from Champions.

Before I had the world spawn be spawn proof for any hostile mobs. I had that removed since it was counter intuitive, so I won't be readding that part.

Though I'll look at my options for disabling Champions mob early on if that's possible. In the case that's not possible, I'll see if I can rebalance their stat modifiers, since I'm aware an unlucky T3 or T4 Champion spawning can one tap a player that has relatively little armor early game.
Though to help with that I added Second Chance, which allows the player to take one lethal hit and run away.

Without them the challenge isn't the same for surviving early game, since PGM is a bit of a hybrid modpack with harder parts, including in recipe progression. I do see potential for improvement, I'll definitely try and ease it a bit for T3 and T4 Champions early game.

P.S. Champions config is inside your world files. In the world folder is a serverconfig folder. Inside the serverconfig folder are (I think?) 4 files for Champions configuration. Changes to those files should immediately take effect while the game is running. If you want to have a look at those files, feel free.

**Comment by zig13** [comment]
Ah thanks for pointing me to that folder. Think their documentation might be out of date as they refer to there being a folder at \Config\Champions. I didn't know the serverconfig folder existed.
The page at https://github.com/TheIllusiveC4/Champions/wiki/Game-Stages-Integration details (though not in any great detail) how "When a mob is spawned and being considered for championship...If no players that meet this requirement is found, that mob will not become a champion." and "...If no players that meet this requirement is found, the champion will not spawn with that rank or anything above it."
That sounds ideal but no menion of what player requirements are supported or how to set them :/
I guess you're right and I could just have run away although running at night would have just spawned more mobs - although hopefully not champion ones. I didn't know what adaptable did, so when I saw the first hit with a wooden sword do a fair bit of damage I thought it was worth persevering. The issue came when it was about to break.
