### ISSUE TITLE
[Bug]: Precision Shears from Miniutilities does not gather Botania tall flowers

### ISSUE THREAD

**Issue by LuciusV** [FTBTeam/FTB-Modpack-Issues#1198]
### Modpack

FTB Oceanblock

### Modpack version

1.14.0

### Describe the bug

Botania tall flowers are supposed to be gathered by shears, vanilla ones do the work, but Precision Shears from Miniutilities destroy flowers without dropping them

### Steps to reproduce

1. Plant mystical petal
2. Use bomemeal on it
3. Use precision shears on tall flowers to see flowers not dropping
4. Use vanilla shears  on tall flowers to see how they should drop
5. Frustrate about wasted petals

### Expected behaviour

Precision shears should drop tall Botania flowers

**Comment by Raidobw2** [comment]
Well, those shears are a bit special, they don't work like normal shears. If you hold left click, it mines the blocks as if it were a stone tool. If you shift right click, it instantly gathers in the way silk touch does and puts the block inside your inventory. They don't work on the tall botania flowers with the shift right click.

https://user-images.githubusercontent.com/17010632/182294375-2d2baa24-69d7-4abb-87c2-094fffda1708.mp4

We can possibly add the shear tag to it to make it a shear (kind of), but it might mess with the purpose of the item. Since it's technically working as intended by the mod, I'll leave it to the discretion of the modpack dev that will update this pack next, as an improvement.

**Comment by TheonlyTazz** [comment]
Plenty of shears in the pack to get tall mystic flowers, If the player wants this to be changed, they can file in a report at the mini utilities github
https://github.com/OneLemonyBoi/MiniUtilities/issues
