### ISSUE TITLE
Quark ancient tomes not spawning in stronghold libraries.

### ISSUE THREAD

**Issue by bubbafett5611** [FTBTeam/FTB-Modpack-Issues#1204]
### Modpack

FTB Presents Direwolf 1.18

### Modpack version

1.8.0

### Describe the bug

I run a small server of 10 or so people, and nobody has been able to loot an ancient tomes from quark in stronghold libraries.

The expectation would be that one of my ten players would have found at least one out of the 6 or so libraries they have looted.

I am not sure if this is related to quark, lootr, or the stronghold overhaul mod.

### Steps to reproduce

1. Find stronghold
2. Loot library
3. No tomes in any library chest

### Expected behaviour

To find tomes in the library chest.

**Comment by TheonlyTazz** [comment]
The reason they do not spawn inside the Stronghold Libraries is because of the way YungsBetterStrongholds handles the Strongholds now and the tomes are not part of their loot tables. 
seeing how this is not a gamebreaking issue, i am going to put this on a lower priority, but will try and come back to it asap
