### ISSUE TITLE
[Bug]: An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by Ingelberg** [FTBTeam/FTB-Modpack-Issues#1206]
### Modpack

FTB Revelation

### Modpack version

BETA 3.6.0

### Log Files

[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9253187/console.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9253188/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9253189/latest.log)

### Describe the bug

On FTB App I can log in to servers, but seconds later I get "kicked" and get the message "Connection Lost
Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host"

But on GDLauncher I can't even join, I get the "Connection Lost
Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host" message straight away.

I removed Mintogether, because otherwise, it wouldn't start.
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1199

### Steps to reproduce

Just need to log into the server. 

### Expected behaviour

Being able to play on server

**Comment by Raidobw2** [comment]
Hi, is the machine the server is on configured properly? Generally that error would happen if the firewall on the server blocks the connection, or the server wrongly sends a packet.

You'd need to allow incoming Java traffic on the server's machine.
As well, if the server has some antivirus on it, this is likely regulating the firewall, so you'd need to configure the antivirus instead (in order to configure the firewall).

Let me know if you've been able to check that on the server. Reversely, you could check the same on your own computer and check if your firewall/antivirus is too restrictive and allow.

If you have a VPN or have Hamachi installed on your computer, I recommend closing both or uninstalling Hamachi if you don't need it. Sometimes that can mess with internet connectivity.

**Comment by Ingelberg** [comment]
it's not my server, it's dirtcraft.

I've checked my PC and still the same problem. I uninstalled my antivirus and VPN and disabled the windows firewall. But it didn't work. 

Tried looking at some more YT videos and did the ipconfig/something. And nothing worked

**Comment by Ingelberg** [comment]
I Fixed it by restarting my router. Weird, because it worked on my old PC.

Thanks anyways!!
