### ISSUE TITLE
[Bug]: Longer daynight cycle

### ISSUE THREAD

**Issue by PatRakowicz** [FTBTeam/FTB-Modpack-Issues#1208]
### Modpack

Plexiglass Mountain

### Modpack version

1.1.1

### Describe the bug

Day Night cycles are almost way to fast. Seems to be night all the time as well as no daytime. Me and my buddy said the exact same thing. 

Just wondering if it would be possible either server side or somewhere in the configs to have the days longer and the nights just as long. 

### Steps to reproduce

1. Start the game
2. load up and play
3. day seems to short
4. night seems to always happen

### Expected behaviour

I would like it to have a daynight cycle that is with the speed of the game so im no in my base for 5 min and when i entered it was day and now its mid night.

**Comment by Raidobw2** [comment]
As far as I know the day in Minecraft lasts for 10 minutes, I don't remember if anything in Plexiglass Mountain changes that, I don't think anything does though. I'll see if I can add a toggle in the near future to allow longer daynight cycle. That toggle would be in the `gamemode.json` once I add it.

**Comment by Raidobw2** [comment]
I'll be looking to add https://www.curseforge.com/minecraft/mc-mods/time-control as a solution to this. I agree that the days should be longer than the night, this would make it a more pleasant experience on servers too.

There's the Comforts mod which also allows getting to the night almost instantly, if players need to grind monster drops, so that should be no issue.

I'll be awaiting mod permission to redistribute since it's all rights reserved to the mod author, although you're free to add it now if you want. If you do, just edit its config before you load the game a second time and double/triple the day time value there, then save the file and start the game.

**Comment by lividsubset3** [comment]
Ok, glad a solution is in the works. I have recently stopped playing the pack. But with hosting the server it would help greatly and be better for the users.
