### ISSUE TITLE
[Issue]: No Nickel or Silver found on server

### ISSUE THREAD

**Issue by glgzachattack** [FTBTeam/FTB-Modpack-Issues#1211]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.8.0

### Describe the bug

Silver and Nickel do not exist in my world. I know it was an issue in an earlier version (im just now starting his YT series) but it seems to also apply to my world. I mined with an almost fully upgraded mining gadget at Y levels -59, -49, -39, -29, -19, -16, 7, 13, 42, 50, 58. Each level for at least an hour, lower levels for about 3 hours each. 0 nickel and 0 silver found. 

### Steps to reproduce

Mine at my Y levels in a fresh world. 

### Expected behaviour

No silver or nickel found

### Screenshots

https://gyazo.com/7aeb9f6f74ca547a0763418dcf41622b
https://gyazo.com/d5cbb60e99db9301c788ce19d414ff22
https://gyazo.com/6d93274c8d2bc19196bc4de3b2a730b4

### Additional information

Let me know if you want a world download or something. It's also a server so you could just join the server.

**Comment by glgzachattack** [comment]
https://gyazo.com/dfbb2d0fdaf2d784285928653fb3900f No silver
https://gyazo.com/696fed68f60795eb66dcd92c3620bda6
https://gyazo.com/0aa1cc656fe146f22c64039f18c28a3e no nickel

**Comment by glgzachattack** [comment]
So in SP it works fine, its just the server, im saving a backup then making a new world on my server to test.

**Comment by Raidobw2** [comment]
How are you starting the server? If it's started with minecraft_server you'll end up with a vanilla server without any mods

**Comment by glgzachattack** [comment]
Did you read description or see the photos? The pack loaded fine with all the mods, it wasnt a vanilla server, but there had to have been some sort of server config that prevented silver and nickel from spawning because i loaded and restarted 3 different worlds and the same issue persisted.

**Comment by AdamBundschuh** [comment]
On our server, only Deepslate silver spawns, no regular silver deposits.

**Comment by Raidobw2** [comment]
Yes, I did read the description and I saw the pictures, but I had to ask to make sure because I'm unable to reproduce the issue.

I've made a local server with a fresh install of both the client on the FTB App and the server from the FTB site with modpack version 1.8.0 for Direwolf20 1.18. The world seed is `-8039168362976922679`.

Silver:
![image](https://user-images.githubusercontent.com/17010632/183318280-e109abfe-cad9-488e-ba20-1345f788eeea.png)
Without silk touch
![image](https://user-images.githubusercontent.com/17010632/183318285-b201317b-d544-4e09-b5e9-e400a53f6da5.png)
With silk touch
![image](https://user-images.githubusercontent.com/17010632/183318289-1a1648b4-1d95-48ea-b93b-84bc7a3747a9.png)

Nickel:
![image](https://user-images.githubusercontent.com/17010632/183318303-ae67af1c-39ef-46fd-9fe8-486ecd03aaa5.png)
Silk touch mode right away
![image](https://user-images.githubusercontent.com/17010632/183318309-2c45b877-7a65-4322-92e6-c441795a4f0a.png)

All ore obtained is from Immersive Engineering and that makes sense, since the Thermal variant of Silver and Nickel appears to be removed at world generation directly with KubeJS:
`kubejs/startup_scripts/worldgen.js`
![image](https://user-images.githubusercontent.com/17010632/183318366-932bc900-7054-4c43-b132-0466f05358ea.png)

Since you've confirmed that is a Forge server, and Silver and Nickel aren't spawning, then I could believe this to be an issue with the server configuration folder. This folder is located in `world/serverconfig` and contains many config files, including the one for Immersive Engineering which is responsible for ore generation.

Here is that file if you need it in any case:
Put it in `world/serverconfig` while the server is offline and rename it to `immersiveengineering-server.toml`.
Additionally you may open the file and enable the retrogen for Silver and Nickel, that should enable it to generate in already existing chunks.
[immersiveengineering-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9277909/immersiveengineering-server.txt)
![image](https://user-images.githubusercontent.com/17010632/183318586-80a4bb4c-41b7-4a2b-b650-4a17775fce49.png)
![image](https://user-images.githubusercontent.com/17010632/183318602-3a85ded4-78f7-4302-89fd-ba3342e1542b.png)

From the previous images you can also confirm that Silver and Nickel spawn at these y values, so after you can test with that information in the Digital Miner:
- Silver: y=-48 to y=42
- Nickel: y=-64 to y=34

The tags are those, just in case:
- `forge:ores/silver`
- `forge:ores/nickel`

Please let me know if that appeared to have been the issue
