### ISSUE TITLE
[Bug]:  Unable to absorb spawner with soul shard.

### ISSUE THREAD

**Issue by ComfyKnight** [FTBTeam/FTB-Modpack-Issues#1221]
### Modpack

FTB Plexiglass Mountain

### Modpack version

1.1.1

### Describe the bug

Unable to absorb spawner with soul shard.

### Steps to reproduce

1. Obtain soul shard of any mob type.
2. Sneak+right-click on a spawner of the same mob type with said soul shard in hand.
3. That should be it.

### Expected behaviour

Spawner breaks and soul shard gains 200 souls.

### Additional information

When trying to sneak+right-click on a vanilla spawner with a soul shard to absorb the spawner of the corresponding mob, the spawner spits out a spawn egg, leaving an empty spawner. This causes a visual bug making it look like the soul shard has absorbed the spawner, but once updated reverts back to the amount it was at before the spawner was clicked. This is a feature from Enhanced mob spawners ('spawnermod' in configs) and can be disabled to allow spawners to to be absorbed by a soul shard, which is what I've done to patch this until a better solution can be found.

Sorry if I did this wrong, this is my first bug report.

**Comment by Raidobw2** [comment]
I'll check, but afaik the Soul Shard should absorb the spawner simply by right clicking, no need to shift right click

**Comment by Raidobw2** [comment]
I've made a report to the author of Enhanced Mob Spawners ^

For now I've disabled the Soul Shard absorption mechanic, disabling Enhanced Mob Spawner's right click interactions would lock out too many options to swap mobs in spawners.

This is also for planning ahead, since I'll be adding a lot more spawn eggs during a next update and these could then be used in the spawners.

So for now -- That config is a workaround

**Comment by Raidobw2** [comment]
The author of enhanced mob spawners managed to make the quickest feature request fix I've seen! I've reverted the soul shards config to normal and fixed the interaction with spawners with that new feature.

**Comment by Raidobw2** [comment]
Fixed in 1.2.0
