### ISSUE TITLE
[Bug]: Quartz Glass texture not showing correctly

### ISSUE THREAD

**Issue by flleeppyy** [FTBTeam/FTB-Modpack-Issues#1223]
### Modpack

FTB Revelation

### Modpack version

3.6.0

### Describe the bug

Quartz Glass from Applied Energistics does not show up properly.

### Steps to reproduce

I'm not exactly sure how to reproduce this, but we're trying to build a dome under water with the openblocks. Refer to screenshots.

### Expected behaviour

Blocks texture should show as normal.

### Screenshots

![2022-08-06_00 02 18](https://user-images.githubusercontent.com/18307183/183238430-a123435a-a96d-4f76-9c04-cdb6c272928f.png)
![2022-08-06_00 02 20](https://user-images.githubusercontent.com/18307183/183238432-89619bb5-57d0-4aa9-b212-138b12fc4463.png)
![2022-08-06_00 02 23](https://user-images.githubusercontent.com/18307183/183238434-5475da7f-474b-4c8c-a3c7-a21223b27fa9.png)

Video
https://0x0.la/u/JsnlnL1.mp4 (Ignore voice at the end, that's my friend)

**Comment by TheonlyTazz** [comment]
this issue is probably caused by optifine and the use of shaders.
i cannot replicate this issue with the default setup of Revelations.

**Comment by flleeppyy** [comment]
Disabled optifine, issue still persists
![2022-08-06_02 34 09](https://user-images.githubusercontent.com/18307183/183243455-b3154913-a77a-4d5c-95f1-9b7dc7b7a46f.png)
![2022-08-06_02 34 12](https://user-images.githubusercontent.com/18307183/183243457-b92ccc12-9581-4fff-bbde-f2ff1a677d32.png)
![2022-08-06_02 34 15](https://user-images.githubusercontent.com/18307183/183243458-b5014f06-6a65-402f-9db7-a1044bb898f7.png)
![2022-08-06_02 34 42](https://user-images.githubusercontent.com/18307183/183243459-27e5fbcc-ce3e-4825-8fda-6c394c98d053.png)
![2022-08-06_02 35 44](https://user-images.githubusercontent.com/18307183/183243472-e67ac63d-fb6a-4f24-8a98-e27f5d4e099d.png)

.

**Comment by Raidobw2** [comment]
Hmm, thanks for trying it without Optifine. I can confirm I can reproduce this, however I'm unsure how we would be able to fix that at all.
![image](https://user-images.githubusercontent.com/17010632/183274947-a4ef2a21-4f88-4edf-a391-368ca7eea19a.png)
It looks like https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4114 was supposed to fix this, since it was reported for rv6-stable-7 on 1.12.2. However it looks like that commit https://github.com/AppliedEnergistics/Applied-Energistics-2/commit/2c0a2975de42db37d0e66eb81216f82215ca51dd made it into AE2 v9 on Fabric which I'm assuming is 1.19+, but was never backported to the original version this was reported on, in 1.12.2.

So normally the version after rv6-stable-7 would have had that bugfix, however I don't see it ever released:
![image](https://user-images.githubusercontent.com/17010632/183274981-5fb664bf-a74a-4c70-9cfc-8a79063df0fe.png)

I've also tried without CTM (Connected textures) to see if that made any difference, it didn't.

AE2 1.12.2 is no longer supported, so this isn't fixable, in the main mod at least
![image](https://user-images.githubusercontent.com/17010632/183275025-270db9d7-a925-4a8b-bb9b-4ddd75c4046a.png)

It does look like that commit from earlier however made it into AE2 Unofficial Extended Life in 1.12.2
https://www.curseforge.com/minecraft/mc-mods/ae2-extended-life
https://github.com/PrototypeTrousers/Applied-Energistics-2/blob/9fdf0345b3f90429534626d1ebdc6aa922c8e9ed/src/main/java/appeng/decorative/solid/BlockQuartzGlass.java#L108

We would have to test it and weight if it's worth it to add it into a future version of Revelation instead, that is the only way I could see this issue being solved. I'll turn this into an enhancement to check when the time comes, however I can't guarantee this will make it in. We'll need to test it thoroughly.
