### ISSUE TITLE
[Bug]: Crash on world creation java.lang.NoSuchMethodError: 'void net.minecraft.server.level.DistanceManager.addRegionTicket

### ISSUE THREAD

**Issue by blk6768** [FTBTeam/FTB-Modpack-Issues#1227]
### Modpack

FTB Direwolf20 118.2

### Modpack version

118.2

### Log Files

[crash-2022-08-06_21.20.36-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9276060/crash-2022-08-06_21.20.36-server.txt)

### Describe the bug

I tried loading a new world on several occasions in the FTB presents Direwolf20 118 modpack and it seems to load fine but crashes before generating a new world. It starts to generate and I get the square with the progress percentage to start but then crashes and goes back to the app. I tried to post the last crash log above and hopefully I did it correctly. I even uninstalled the app, deleted all my worlds and tried reinstalling and starting a new world again but to no avail. Please advise. Honestly, the only reason I have the app is for this pack specifically and the fact that is a Direwolf20 pack. I love his tutorials and you-tube content on all things Minecraft and became a big fan. :)

### Steps to reproduce

see above

### Expected behaviour

umm, expected it load a new world? lol not sure what I was expected to say here

**Comment by Raidobw2** [comment]
Try removing Optifine, it doesn't look compatible with this pack. If you use it for gaining FPS, try some of the alternatives at https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1130#issuecomment-1191028332. If you want this fixed for Optifine, you'd need to report it to their issue tracker, since we don't support it. Let me know if that was the issue

**Comment by blk6768** [comment]
well it's not great, but I did manage to get it to load a new world. I get
around 30-40 FPS with some of the settings turned down so it is playable
but not super smooth. Thank you again for the help! :)

**Comment by Raidobw2** [comment]
No problem, you can try adding Rubidium, that might help further. Look again in my linked comment, all the info should be there towards the bottom with links to the mod. I'll close this issue then, cheers

**Comment by blk6768** [comment]
I tried Rubidium but that caused crashes also so I deleted and am running
without it. So far so good. My next step is a computer to replace my fancy
calculator 🤣🤣🤣

**Comment by blk6768** [comment]
ok and thank you. Will try and see if it fixes it. I like having shaders
mainly for the water but its not a deal breaker if I can get the pack to
play without. I've already tweaked the settings as best I could for FPS. My
comp is a relatively low end so it's not gonna get much, but hoping it will
be playable. 247 mods is a lit lol

**Comment by Raidobw2** [comment]
Shaders can be more resource intensive, for an alternative to enhance your game experience I would recommend some texture packs. They are less CPU intensive than shaders since they mostly use RAM instead. Some people in the FTB Discord mentioned Faithful, Soartex and other texture packs. You could also go in the FTB Discord in the direwolf20 channel and ask for recommendations if you want, I'm sure people know even more options => https://go.ftb.team/discord
