### ISSUE TITLE
[Bug]: Server Resource Pack crashes client on join

### ISSUE THREAD

**Issue by v-tron** [FTBTeam/FTB-Modpack-Issues#1265]
### Modpack

Direwolf20 1.18

### Modpack version

1.9.1

### Log Files

https://pastebin.com/SrEwKpFv

### Describe the bug

I wanted to improve the textures of Pipez on my server with the pretty pipez resource pack. Downloading the pack and activating it manually in the client works fine. 

Now setting the pack as a server resource pack on the server lets the client download it automatically and would ensure every player having the same experience regarding textures on the server. However, after having the client download the pack and it working, every time the client reconnects to the server afterwards the client crashes while loading the texture pack with this error.

### Steps to reproduce

1. Set server resource pack
2. Client downloads server resource pack and everything works
3. On every subsequent disconnect and join client crashes

### Expected behaviour

Resource pack loads correctly

**Comment by Raidobw2** [comment]
I'm not sure if you would be able to fix that, look like an error due to Pipez reading model data. Maybe due to reloads, I've never seen that happen until now.

You can either report to Pipez or the resource pack maker, possibly they'd have a file to edit.

Or, if you want you could have the server texture pack off and tell players they can get the texture pack from curseforge for example.
Another option could be to use the "Share modpack" option of the FTB App and put the texture pack there (I think that'll work?). That way your friends/players can import the modified pack with the share code you give them.

**Comment by v-tron** [comment]
Thanks for the reply, I already removed the pack from the server since it's useless to keep it on there when it only crashes the clients. I will make an bug report to pipez. Though I find it very odd that it crashes when loaded as a server resource pack and doesn't when loaded manually.

**Comment by Raidobw2** [comment]
I have no idea why it would only do it on server sorry. With the server resource pack on the 2nd login you specified it looks like it's trying to get a pipe's model and render it, but fails in doing so, not sure if that can help you in the diagnostic
![image](https://user-images.githubusercontent.com/17010632/184563230-00927464-311a-4604-808d-343db83b6ff5.png)

That's about all I can do to help you on this issue since it's not a modification we ship with the pack / we don't intend to break these things in general. To my opinion that would be caused by Minecraft, Pipez, the texture pack itself or Forge. Looking at the stackstrace perhaps I'm more inclined to say it's Pipez since it's looking into its cache `corelib.CachedValue` to get the model. Hope that helps for your report to Pipez
