### ISSUE TITLE
[Bug]: Server crashes while world generation

### ISSUE THREAD

**Issue by Lauriichan** [FTBTeam/FTB-Modpack-Issues#1275]
### Modpack

FTB One

### Modpack version

1.3.0

### Log Files

https://gist.github.com/Lauriichan/c6d4789f3e4655c8e68d216b53f5239c

### Describe the bug

Server randomly crashes when traveling through the world

### Steps to reproduce

1. Create a FTB One Server
2. Travel quite some time in the overworld
3. Experience a crash at a random time

### Expected behaviour

The server shouldn't crash when generating the world

### Additional information

It seems like the ProductriveBees mod is the reason for this crash see [line 11 in the crash report](https://gist.github.com/Lauriichan/c6d4789f3e4655c8e68d216b53f5239c#file-crashreport-txt-L11)

**Comment by Lauriichan** [comment]
This might be related to #1298 in some way?

**Comment by Raidobw2** [comment]
Sorry for the delay, yes that looks like the same error. In `serverconfig/productivebees-server.toml` find those options and set all to false, that should mitigate the crashes:
![image](https://user-images.githubusercontent.com/17010632/189264481-0d4eaab2-9785-405e-9a10-7e12f0357857.png)

FTB One will likely jump to 1.19.2, so this might be the only "fix" I can offer for now

I will close this in favor of keeping #1298 as our way to track this issue for when we update the pack to 1.19.2 (since it has more info at this time), but thank you for making this original report.
