### ISSUE TITLE
[Bug]: Cannot make iron plates

### ISSUE THREAD

**Issue by Pegoku** [FTBTeam/FTB-Modpack-Issues#1292]
### Modpack

FTB Revelation

### Modpack version

3.6.0

### Describe the bug

I have an MC game with the FTB Revelation 3.6.0 modpack and I started playing it relatively recently (1-2 days), and I have realized that the iron plate recipe does not work, I have tried with the 2 recipes that there are available with the crafting table, I have also tried them in the inventory.

### Steps to reproduce

1. Go to the crafting table
2. Put the hammer in the first box and the iron ingot in the second
3. It gives you nothing

![javaw_5LQoT8P4uu](https://user-images.githubusercontent.com/81113533/186998460-a8b06f43-5426-484f-9618-172a067e7d27.png)

![javaw_6Yni0DJF0F](https://user-images.githubusercontent.com/81113533/186998466-06e19a9d-e7b1-4a79-9a74-b9a33f9a6609.png)

### Expected behaviour

Io give me an iron plate as a result

### Screenshots

![image](https://user-images.githubusercontent.com/81113533/186972127-d72e6629-931c-48e7-99f9-103fbf023aea.png)
JEI ^

![image](https://user-images.githubusercontent.com/81113533/186972105-c41a3f94-f787-44e9-8026-6b0788a03f5b.png)
crafting table ^

### Additional information

I'm running it in a MC server

**Comment by Raidobw2** [comment]
Thanks for the report, but I'll close this issue to avoid redundancy, since we already have a report of this at https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1289. If you want you can subscribe to that other issue for notifications when it will get fixed. Currently we don't have someone looking into this pack at this exact moment, but we do maintenance on it every now and then so this will be fixed eventually.

I've seen people say to use the manual rolling machine for plates, maybe that can help in the meantime. I know compressors from Thermal work well too, I used them last time I played. Cheers

**Comment by nothub** [comment]
#1289 is 404 for me
