### ISSUE TITLE
[Bug]: some items texture are broken

### ISSUE THREAD

**Issue by No-steve** [FTBTeam/FTB-Modpack-Issues#1317]
### Modpack

ftb interactions

### Modpack version

v2.12.1

### Describe the bug

bug

### Steps to reproduce

bug

### Expected behaviour

bug fixes

### Screenshots

![2022-09-11_19 41 52](https://user-images.githubusercontent.com/105639186/189523320-c3afff48-b17b-4990-ba8a-b137dbdc4aa9.png)
![2022-09-11_19 41 48](https://user-images.githubusercontent.com/105639186/189523569-e6e731bb-e2a6-483e-aa48-4cb8b8340382.png)

**Comment by Raidobw2** [comment]
Hi, have you tried backupping all your worlds and reinstalling a second instance to check if the issue is there too? Is it an installation issue, like a file missing?

**Comment by Gideon9212** [comment]
Having same issue here as well. Fresh install.

![image](https://user-images.githubusercontent.com/24485150/197679194-2e200480-eb87-47f9-842c-4d58da49b72f.png)

**Comment by Raidobw2** [comment]
Hmm that's odd. I'm on Windows 10 and installed the pack now to test it, the item(s) do appear fine:
![image](https://user-images.githubusercontent.com/17010632/197695465-3a50721a-4b33-4dfc-9929-59a0f1d3a90f.png)
![image](https://user-images.githubusercontent.com/17010632/197695627-c30ecd9b-2181-4109-b502-a0d86c689e00.png)

I thought this might be due to this: `[01:59:48] [Client thread/WARN] [ResourceLoader]: [NormalResourceLoader] Resource Location contenttweaker:textures/items/skystonelense.png only matches the file skystoneLense.png because RL is running in an environment that isn't case sensitive in regards to file names. This will not work properly on for example Linux.`, but you seem to be using Windows as well like me...

Can you check how many files/folders are in the `resources` folder? You do this by right clicking the folder on Windows and clicking Properties to see it:
![image](https://user-images.githubusercontent.com/17010632/197695857-be438d89-9adb-4807-b905-e20e2d919cf8.png)

Mine says 1401 files and 60 folders. If you have different numbers, try reinstalling. If it's all there, there seem to be some bug going on. If you can add your game log I'd appreciate it, since I can't reproduce it on my end!

**Comment by Saereth** [comment]
I did a fresh install here to test and I'm not experiencing any missing textures. Are you running on linux or mac by chance?

**Comment by Gideon9212** [comment]
I'm reporting from word from mouth from another user as they do not have a github account nor don't think they want to make one. The screenshot is from their pc to be clear. For better context, I'm a server hoster for this modpack so they been directing their issues to me.

We both have used prismlauncher for the modpack for context. On my end I have the correct number of files and folders. I have not been able to confirm on their end yet if they have the correct number of files but I will hopefully have an answer soon on that. We both are using windows.

For me, there is a few RFTools items that are a pink box, IIRC the shield items. For them I think it was the seed and the RFTool stuff as well. 

For another user they reported wrong recipe for the Botania's Mana Spreader for both the book and JEI but haven't got enough info to create an issue or confirm it.

Is there a chance 3rd party modpack managers are the cause for these issues?

**Comment by Gideon9212** [comment]
To confirm my end at least, these are the 5 blocks on my end with the missing textures.

https://user-images.githubusercontent.com/24485150/197881784-f5e68b02-d441-436d-8832-cd3edc938efa.mp4

**Comment by Raidobw2** [comment]
There has been issues with 3rd party launchers before, such as https://github.com/FTBTeam/FTB-Modpack-Issues/issues/30, though they are uncommon.

We recommend using the FTB App for FTB modpacks, since you'll get all the files for sure. If they can try it, they'll be able to compare if it works or not.

Adding game logs / checking file counts will also help locating the source of the problem

**Comment by No-steve** [comment]
I already have used the FTB App
