### ISSUE TITLE
[Bug]: Odd crashes Quark, CCL item rendering that provides light, on Revelation 3.6.0

### ISSUE THREAD

**Issue by CraftierUD** [FTBTeam/FTB-Modpack-Issues#1324]
### Modpack

FTB Revelation

### Modpack version

3.6.0 - Latest

### Log Files

https://paste.feed-the-beast.com/view/9c35b923

### Describe the bug

The mod pack as of today decided to start crashing in the instant a pink slime pops out of my tool. At first I thought it was Optifine so I uninstalled and tried again only to have it fail immediately rather then later. Changing from my standard survival world to my Creative flat grass lead to no change so its clearly something in the pack I can't see. I have no experience reading crash reports or trouble shooting so this post now exists.

Extra mods are installed but nothing I would call major:
Galacticraft
Carryon+
Comforts
Wearable Backpacks
Wolfarmor
Agricraft
Dynamic Surroundings
Optifine - Now removed; not in crash report

I mainly just play in single player for when I want some peaceful gaming and vibing to music so any assistance is greatly appreciated. 

### Steps to reproduce

Start the game.

### Expected behaviour

Just playing normally despite the immense processing of many machines.

**Comment by CraftierUD** [comment]
Update: It seams version 3.6.0 is incapable of running normally in singleplayer as it crashed still with no changes or additions.

**Comment by Raidobw2** [comment]
From the first crash log you posted that looks to be caused by Quark's config, maybe it got corrupted or something. Have you tried installing a second instance (without the added mods too) and putting your save there? See if it starts up and let me know. If it crashes, it's always helpful to post the new crash log

**Comment by CraftierUD** [comment]
Indeed I have, I get the same results after a longer period but with the same "Exception ticking world" or rendering item crash with a fresh new instance.

**Comment by Raidobw2** [comment]
For the other crash reports you get, you can post them here. It's always useful to me

Also, if you don't mind sending me your save, I can probably fix the few oddities that make it crash, since I'll assume I'll get ticking world/rendering item crashes as well.

Easiest is using Google Drive, but use any file sharing service you wish

**Comment by CraftierUD** [comment]
Well the fresh new instance, my world is already gone as I did not know.

Either way I just keep testing now to try and get it working.
Heres the latest with extras: https://paste.feed-the-beast.com/view/5dae89b0
Happened when I was just flipin around fighting the Chaos Guardian in Creative.

**Comment by Raidobw2** [comment]
I see, is this issue still a problem within your save that you currently play on in that case? Maybe the issue could come from outside the modpack, make sure you're up to date on your GPU drivers.

If you have an antivirus, maybe check it or turn it off to see if that's the issue.

Also, when it crashes, check the Event Viewer (program in Windows) at the time of the problem and see if Windows has any more information on the error, when a device is defective (due to a driver usually) it can see it there.

The latest crash you posted does have some info which is similar to the item crash you mentioned. It does look like CodeChickenLib would be trying to render an item that gives off light and it crashes. I'm unsure if that is an item in-world, or in the JEI grid/inventory for example.

Since you put some steps to reproduce and posted a relevant crash, I'll turn this into a bug ticket so we can have a look at it when we pick the pack for updating again, thanks for that info

**Comment by CraftierUD** [comment]
I am just refreshing the instance and making new worlds in creative to try and recreate it since I no longer have a world.

In trying to recreate a loading problem with a fresh instance lead to nothing, even when settings are at default (Max) and chunk range increased to 18 with minimal performance change so it is one of my additional mods, which one I have no idea. Even slayed a Chaos Guardian with those settings with little trouble. This time when I added the mods back in, the instance failed to load almost immediately. 

`AdditionalEnchantedMiner (Or super buildcraft quarry) Might try without that first.
`Agricraft - updated InfinitLib (Though the new version did not have the old one it seams)
Carryon
Comforts
DynamicSurroundings - OreLib
Eyesinthedarkness (Still need to figure out that blacklist on that btw)
`Galacticraft/Gala-Planets/Micdoodlecore
`OpenModularTurrets - omlib
WearableBackpacks
Wolfarmor

Mods that may cast light "`"

Confused with the latest crash in why google needs to be involved in a offline program.
https://paste.feed-the-beast.com/view/220d17f9

**Comment by Raidobw2** [comment]
Forge (the modloader) or BuildCraft is probably using a library from Google, so that's why it would be referenced in the stacktrace.

Keep in mind this tracker can be used for support for the base pack, since if you modify things, it's likely to crash and I can't support that fully. If I assume the base pack doesn't crash but it only crashes when adding the mods, then this would not be an issue in the base Revelation pack.

You can modify it -- but if it crashes, I recommend either playing the base or adding the mods one by one.

If you need more help I can suggest the FTB Discord https://go.ftb.team/discord or the Modded MC Discord as well, since a lot of people play custom packs there.
I can help you as long as the issue concerns something in the base pack, please let me know if that is not the case

**Comment by CraftierUD** [comment]
Well after a while, the pack seam to stable out for unknown reasons but now I had a fail to launch caused by a java error (Java 8 341 x64)?
This was after a quick KSP session and I did have problems with nvidea drivers a few months ago playing Destiny. Maybe this could be related and the source, so now I wonder about the integrity of my drivers since all recent reports were related to rendering as this kind of crash did happen ONCE on an unmodified instance. I did notice that nvidea driver 516 has been a pain for multiple games for people that have 3080's

I'll try playing without hardware scheduling after double checking drivers.
I have also duplicated the instance for a base version.

https://paste.feed-the-beast.com/view/2e7a6b89

**Comment by Raidobw2** [comment]
Sorry for the late reply, the crash you posted refers to Itemduct covers. It seems unable to find code chicken lib, but it's in your files. Could be an error with thermal dynamics in 1.12.2, or a problem with one of the extra mods you have installed.

I'd recommend trying with a copy of the world without the added mods and seeing if that works

**Comment by CraftierUD** [comment]
Well I think I found the solution: Foamfix
Apparently a couple years ago, allot of people were having this same issue on a different forum and the fix was increasing the _deduplicateModelsMaxRecursion_ config from 6 to its default 9.

I have since removed the AEM mod (Because I had no idea about the RFtool builder quarry card), applied this change in the config and have a substantial improvement. I have gone 3 whole days without a single crash, only miner loading lag that is barley noticeable. I have even gone long enough to regrow all my plants to Agricraft level 10, No issues.

After I say a week I will give an update if anything changes. Thanks for the additional info, it did in fact help me identify the issue: Foamfix not giving enough resources to JEI rendering.
