### ISSUE TITLE
[Bug]: recipe block of lapis

### ISSUE THREAD

**Issue by WorkiTT250** [FTBTeam/FTB-Modpack-Issues#1335]
### Modpack

ftb one

### Modpack version

1.3.0

### Describe the bug

Im not sure if it a bug, but the recipe to transform a block of lapis into 9 lapis does not exist anymore?

I simply added the craft for my game so I don't have this problem anymore.

### Steps to reproduce

just start a game 
craft or give you a block of lapis
then try to turn it back into lapis 

### Expected behaviour

having the recipe

**Comment by Raidobw2** [comment]
Thanks for reporting! Interestingly enough I don't know what caused that to happen, we'll have a look at it when the pack jumps to 1.19.2. Glad you could figure out a workaround for now at least. For those needing that recipe, open your modpack folder and create a new file called `lapis.js` (make sure file extensions aren't hidden in Explorer) in `kubejs/server_scripts`, and put this inside then save the file:
```js
// priority: 100
onEvent("recipes", (event) => {
    event.shaped("minecraft:lapis_block", ["LLL", "LLL", "LLL"], {
        L: "minecraft:lapis_lazuli"
    });
});
```

This can be done while the game is running in singleplayer, or can also be done on a server that's currently running. If so, type `/reload` in-game should show the recipe again after a few seconds.

Otherwise, launching the game again also works after placing the script in the correct spot
