### ISSUE TITLE
[Bug]:  keep disconnecting from server with infinity evolved lite

### ISSUE THREAD

**Issue by twitchbanane** [FTBTeam/FTB-Modpack-Issues#134]
### Modpack

Infinty Evolved Lite

### Modpack version

1.10

### Describe the bug

i'm kicked from the server within 30 seconds and the problem is that another guy playing on the same server has no similar issues. I tried everything like a whole new installation of the ftb legacy launcher bc the new one has no infinity evolved lite, starting mc with the normal launcher or using a proxy/vpn. And no the server is not overloaded bc the server has an 32 core threadripper, 256gb of ram and an 1gbits networking access

### Steps to reproduce

1. Start Minecraft over the Ftb legacy launcher
2. Joining our server
3. staying on the server for 30s to 2 min and then get kicked
4. despairing and asking why im doing this :(

### Expected behaviour

normal playing on the server

### Screenshots

https://user-images.githubusercontent.com/92547708/137386971-9cc41120-a4e6-41c6-a096-68c974d57349.png

**Comment by Raidobw2** [comment]
I assume you are playing FTB Infinity Lite 1.10 (Minecraft 1.10)?

I have a few suggestions for you about that network problem:

How is the server firewall configured, maybe adding a rule for Minecraft and the port you're using would help?
The server location can play a big factor, having it closer to the players is better.
Lowering the server's render distance can help.
256GB of RAM is super overkill :D try giving it only what it needs! For 2 players you would not even need 4GB, and 10 players probably not even 8GB.
Try adding the JVM argument `-Dfml.readTimeout=90` on both your server and all clients, make sure everyone is using Java 8 in the latest update.
Try without a VPN if you're using one.
Run a trace route test to the server to make sure it's not a ping issue. On Windows for example, you can open a command prompt and do a trace route test towards Google's DNS like so: `tracert 8.8.8.8`.

Try some of these since I'm out of ideas for now! Network problems are hard to solve. Let me know after how it went.
