### ISSUE TITLE
[Bug]: [FTB IC Quarry]: Deleted items with Sort inventory

### ISSUE THREAD

**Issue by ErdnusBuddha** [FTBTeam/FTB-Modpack-Issues#1349]
### Modpack

FTB One

### Modpack version

1.3.0

### Describe the bug

If you sort the inventory of the quarry all items in the quarry inventory will disappear.

### Steps to reproduce

1. Gett the Quarry from FTB Industrial Contraptions
2. let the Quarry run 
3. Press the Key for Inventory sort (maybe you need to bind it first)
4. All items in the quarry inventory will disappear (And the upgrades and battery's)

### Expected behaviour

The items in the inventory sould be sorted (not the upgrades or the barrery) or  at least sould not  disappear

**Comment by Raidobw2** [comment]
Hi, I've checked and there might not be a "fix" in the current 1.19 version to avoid sorting it since the InventorySorter mod config does not work it seems (I've tried configurating it both in-game and through files).

We'll have a look in 1.19.2 since the InventorySorter mod has updated now and that's FTB One's next Minecraft version for its update.

For the moment, the way around this is to avoid sorting the quarry's inventory

**Comment by cTurtle98** [comment]
I am experiencing this in ftb one 1.3.0
