### ISSUE TITLE
[Bug]: "main menu" audio

### ISSUE THREAD

**Issue by redgoblin88** [FTBTeam/FTB-Modpack-Issues#1355]
### Modpack

FTB Inferno

### Modpack version

1.0.0

### Describe the bug

when you go to change the keybind settings the "main menu music" seems to abruptly stop, upon exiting out of changing keybinds the music is restarted from the beginning

also when you create a new world it seems the song starts and restarts and restarts and restarts rather than continually playing or not playing at all

### Steps to reproduce

open "change keybinds" and exiting, "create new world" seems to also cause it to occur, unsure about joining an already made world

### Expected behaviour

keybinds: the song to carry on or "remember" here it is. joining world: either carry on playing or not play at all

**Comment by Raidobw2** [comment]
This might be due to the reloads happening while a world is loaded, about the keybinds, unsure.

This option (`config/fancymenu/config.txt`) did not fix the music while the world is loading:
![image](https://user-images.githubusercontent.com/17010632/192878887-436666f9-4fc4-49bc-954a-f355f3d8824f.png)

**Comment by Saereth** [comment]
yeah that setting should be false

**Comment by rmedzihradsky** [comment]
Same thing happens when creating a new world and going to "Game Rules"

**Comment by Saereth** [comment]
opened an issue with FMM dev
https://github.com/Keksuccino/FancyMenu/issues/388

**Comment by Keksuccino** [comment]
Hey, dev of FancyMenu here!

This is **not** a bug in FancyMenu, but in the modpack.

The modpack dev forgot to enable customizations for the menus the music is stopping in.

I started the modpack and tried to enable all menus they forgot.
It should work in almost every menu know, except of the resourepack menu, because that one doesn't like to get customized (I need to fix that already ehem).

You can fix this by yourself by simply replacing the `config/fancymenu/customizablemenus.txt` file with that one:
[customizablemenus.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9796097/customizablemenus.txt)

Will close the issue in the FancyMenu repo now, but feel free to open a new one if you have more questions/issues! :)

**Comment by Saereth** [comment]
@Keksuccino thanks so much for popping by, I had already sorted this based on your reply for our update that will go out weds so no other users should experience this then. Meant to respond to you sooner but I got busy.
