### ISSUE TITLE
questbook only accepts vanilla variations in some instances[Bug]: 

### ISSUE THREAD

**Issue by Ledonton1** [FTBTeam/FTB-Modpack-Issues#1358]
### Modpack

ftb Inferno

### Modpack version

1.0.0

### Describe the bug

neither warped chest nor blackstone furnace was able to count towards questbook quests. in each instance i had to put it in the crafting menu to get vanilla counterpart in order to complete the quest.

### Steps to reproduce

1. create (warped chest or blackstone furnace)

2. check relevant quest ( furnace in a dark forest tab for the furnace, chest in Tiamat's Horde for the chest)

3. put item in crafting menu to receive vanilla counterpart and quest completes.

### Expected behaviour

quest to complete when making the item that is relevant to the realm and not need the extra step.

**Comment by Saereth** [comment]
This is intentional because although you can make the variants for decorative reason the non variants are needed for some recipes in the pact that dont support tags unfortunately so its to make sure people know how to craft to the vanilla variants. If/When the mod(s) in question eventually getting around to sorting this we will change the quests
