### ISSUE TITLE
[Bug]: Stuck at reading world

### ISSUE THREAD

**Issue by AliRezaGamerARG** [FTBTeam/FTB-Modpack-Issues#136]
### Modpack

FTB OceanBlock

### Modpack version

1.3.0

### Log Files

[crash-2021-10-15_15.18.39-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7353243/crash-2021-10-15_15.18.39-server.txt)

### Describe the bug

Hello, i was playing the FTB OceanBlock Modpack for a while, it was smooth and pretty good but after i finished i click on save and exit. when i was on FTB app after closing the game, power suddenly ran out. now when i want to load my save its shows me the "reading world" and after that only the screen without any text, and the only option that i have is alt f4 or restarting the pc because it won't do anything.

i uploaded my game save too ( https://www.mediafire.com/file/5zes2fx9msu55id/Lets_Play_OceanBlock.zip/file )

i tried the backup of my game and it loads so there is nothing wrong with the game, but the backup is for yesterday and i don't want to do everything again if there is any way to solve this problem.

### Steps to reproduce

1. exit your game by click the save and exit button.
2. when the game closed and you saw the ftb app shut down the system by power out or restarting it.
3. now you can't open your save anymore

### Expected behaviour

Game should have saved better and bugs shouldn't have happend.

### Additional information

(sorry for my bad english)

**Comment by Raidobw2** [comment]
Hey that was kind of bright to upload your world with it too, I could find the solution and give to you straight away.
Normally `level.dat` is the one to get corrupted on power fails, but looks like this time it was serverconfig.

What you're going to do is delete everything but one file in `saves/Lets Play OceanBlock/serverconfig`. The only file you keep is `better_diving-server.toml`, and the folder `ftbranks` if you use that. Otherwise deleting everything else in that serverconfig folder.

Then try to join your world, and it will work.
Close this issue if this solved it for you, and cheers.

**Comment by AliRezaGamerARG** [comment]
tnx a lot i got it fixed.
