### ISSUE TITLE
[Bug]: vengeful ring

### ISSUE THREAD

**Issue by demoniclords** [FTBTeam/FTB-Modpack-Issues#1362]
### Modpack

inferno

### Modpack version

1.0.0

### Describe the bug

after you use the vengful ring one time it will always spawn a vengeful spirit even why you deactivate it and put it in a chest

### Steps to reproduce

get a vengeful ring 
turn it on
turn it off
kill something

### Expected behaviour

when you kill something it will spawn a vengeful spirit

### Additional information

re-logging and dying don't change the result

**Comment by Saereth** [comment]
this is not a bug, vengeful spirits do always spawn but until you had the ring and /or are in creative you could never see them. Use a dark gem torch nearby to prevent spirits. The ring and things like the vengeance pickaxe/other evilcraft items can increase the rate at which spirits spawn but they always can spawn which is why we have a quest that triggers explaining them when you get hit
