### ISSUE TITLE
[Bug]: Dying causes inaccessibility to minecolonies 

### ISSUE THREAD

**Issue by MisterZam** [FTBTeam/FTB-Modpack-Issues#1389]
### Modpack

FTB Inferno

### Modpack version

1.0.1

### Describe the bug

After dying i cannot access my colony's workstation 

### Steps to reproduce

1. Have a Minecolonies setup
2. Get killed or die
3. Try right clicking any workstation
4. It wont do anything 

### Expected behaviour

The gui opens

**Comment by Saereth** [comment]
gate trial code has nothing at all to do with mine colonies, which workstation cant you access/

**Comment by Leannuts** [comment]
If by gate trial you mean where suddenly a bunch of mobs spawn. I have the same issue. After dying numerous times to magma cubes, I can no longer do anything with minecolonies. When clicking on my clipboard it shows what's needed but instead of a name it shows <UNKNOWN>. When going over to my colony I can't click on any of the blocks or talk to any of the colonist.

**Comment by Saereth** [comment]
someone else on discord ran into this as well, seems to be tied to dying though, not specifically the gateways but I'll get the issue on over to minecolonies to look at

**Comment by MisterZam** [comment]
Yep its tied to dying. I always die every time a gate open and so i thought its the gate but its actually the dying part
