### ISSUE TITLE
[Bug]: Sigil of Green Grove gets eaten when applying bonemeal effect on non standard items

### ISSUE THREAD

**Issue by Firedomo** [FTBTeam/FTB-Modpack-Issues#1398]
### Modpack

Inferno

### Modpack version

1.0.2

### Describe the bug

When bonemealing sugarcane or cactus, the sigil of the green grove gets used up and dissapears.

### Steps to reproduce

1.)Obtain Sigil of Green Grove
2.) Use the right-click feature to simulate a bonemeal use
3.) Sigil should disappear

### Expected behaviour

The sigil should not be used up when right-clicking a crop.

**Comment by Raidobw2** [comment]
I'm not sure exactly what's going on with that, so I'll leave Saereth to check it. It seems like in an instance only with `BloodMagic-1.18.2-3.2.6-41.jar` and Patchouli, you cannot bone meal Sugar Cane with the Sigil of the Green Grove.
I did not see scripts for handling that either in the pack, so maybe it's a custom mod in Inferno or cross mod interaction? Hoping this helps Saereth, since it doesn't seem to be a BM issue

https://user-images.githubusercontent.com/17010632/194501146-93d933dc-ad90-4f9b-a995-691ddfe124b2.mp4

**Comment by tyler489** [comment]
Does this also happen with bamboo?

**Comment by Firedomo** [comment]
It 100% is, just a compat issue, I imagine it would be on universal bonemeals end, not too sure though

**Comment by Raidobw2** [comment]
That would make sense, I've relayed this to the author of Universal Bone Meal. Thanks for the info

**Comment by Saereth** [comment]
Will need to be fixed on BM's Side
https://github.com/WayofTime/BloodMagic/issues/1933

**Comment by Raidobw2** [comment]
I suggest leaving this opened until Blood Magic fixes it, that way we can track it more easily and Saereth can include the information in the changelog, thanks

**Comment by Saereth** [comment]
closing this as its long stale and out of our hands
