### ISSUE TITLE
[Bug]: FTB Chunks map crash when pressing M

### ISSUE THREAD

**Issue by JunaidA197** [FTBTeam/FTB-Modpack-Issues#142]
### Modpack

Ftb University 

### Modpack version

1.2.0

### Log Files

https://pastebin.com/c8660Qxy

### Describe the bug

Server reset the end/twilight/nether, now we can't open the map either through M or through inventory icon in top left. Im guessing its because some people had claims in those dimensions pre delete. (Not confirmed this is the issue)

### Steps to reproduce

1.) click M or map button
2.) crash

### Expected behaviour

Map to open

### Additional information

Attached the crashlog, it crashes to main menu not the whole game. I've tried deleting ftbchunks data and changing server name and it still crashes, same with a reinstall

**Comment by JunaidA197** [comment]
A server restart seemed to fix it, but unsure of the underlying issue....

**Comment by Raidobw2** [comment]
Cannot reproduce currently with a few tries with OceanBlock 1.3.0 by wiping dimensions, claiming chunks, loading chunks, etc.
Dropping prio for devs since more reports or testing will probably be needed to try and pin down the issue, linked issue currently encountered the bug with E6.
As time allows, I'll see if I can look further into this.
