### ISSUE TITLE
[Bug]: Socket Sigil Whitelisting

### ISSUE THREAD

**Issue by Malquen** [FTBTeam/FTB-Modpack-Issues#1420]
### Modpack

FTB Inferno

### Modpack version

1.0.2

### Describe the bug

The Socket Sigil item appears to not work with tools/weapons from several mods, including Reliquary, Quark, and Cataclysm. 

### Steps to reproduce

1. Place Socket Sigil in off hand. 

2. Place item from one of the affected mods in main hand. 

3. Right Click. Observe nothing. 

4. Swap main hand for a weapon or tool from vanilla, MineColonies, or other mods - repeat, observe that it rolls sockets on the item. 

### Expected behaviour

The Socket Sigil should be rolling sockets on any weapons or tools capable of using gems (all weapons/tools).

**Comment by Saereth** [comment]
The item must specifically be tagged as a weapon or armor for the sigil to work as this is how the apotheosis dev recommended we check for item validity. Socketing an invalid item will result in a ton of log spam from apotheosis. The mods in question generally have extra functionality beyond just a weapon which is why they arent tagged as things valid for socketing. 

This is something we can correct on a case by case basis if you think there are specific items that should qualify but arent feel free to give us a list of the items and I'll trial and error check if tagging them in will cause issues or not.

**Comment by iasazo** [comment]
Blood magic armor is missing the tag in v1.02.
