### ISSUE TITLE
[Bug]: Ore miner Djinni doesn't generate Lapis

### ISSUE THREAD

**Issue by iasazo** [FTBTeam/FTB-Modpack-Issues#1443]
### Modpack

FTB Inferrno

### Modpack version

1.0.3

### Describe the bug

Ore miner Djinni does not generates Lapis. Since raree ores are generated by the Djinni this would seem to be an oversight.

### Steps to reproduce

1. Place Ore Miner Djinni in Dimensional Mineshaft
2. Wait for ores to generate
3. Observe lack of Lapis

### Expected behaviour

For lapis to get generated.

**Comment by Saereth** [comment]
Its set to do lapis but it doesnt work. Acutally using default configs for lapis but I verified it doesnt spawn. Since you can get a steady supply from the miner, fisher and bees however I'm not gonna leave this open as an important pack issue as it doesnt really impact the pack. Reported to Occultism dev for them to look into
