### ISSUE TITLE
[Bug]: Enchian keys (Woot) wont spawn / generate

### ISSUE THREAD

**Issue by ValonInc** [FTBTeam/FTB-Modpack-Issues#15]
### Modpack

FTB University 1.16

### Modpack version

1.2

### Log Files

/

### Describe the bug

The Enchian keys from woot dont appear in end city chests.

I have looted around 30 end citys (each with atleast 1 chest) and found 0 keys in the chests.

I have generated 100 chests with the end city loot table with `/setblock ~ ~ ~ chest{LootTable:"minecraft:chests/end_city_treasure"} destroy` Again with 0 Keys.

Loot from other mods appear in the chests (Ars Nouveau, Artifacts)

### Steps to reproduce

1. Create new world
2. Enter the end
3. Locate end city
4. Loot chests
5. Repeat 3-4

OR

1. Spawn chest with the command in the description
2. Look inside
3. Repeat 1-2

### Expected behaviour

When spawing the 100 chests around 15 keys should have spawned. But exaclty 0 spawned.

### Additional information

I have Optifine installed.

**Comment by Raidobw2** [comment]
Ipsis/Woot#530
Trying to create a temporary KubeJS script as a solution, I'll probably post again during the next days.

**Comment by Raidobw2** [comment]
aaronhowser1 or people coming across this post, you can add that script as a workaround. In `kubejs/server_scripts`, I created a `loot_tables/woot.js` script with this as the contents:
```
// priority: 99
//[Render thread/INFO]: ExoticDrops rolls:1 chance:15.0 weights:[4, 4, 2, 1, 1]
onEvent('chest.loot_tables', event => {
  event.modify('minecraft:end_city_treasure', table => {
    table.addPool(pool => {
      pool.rolls = 1
      pool.bonusRolls = 1
      pool.addCondition({
        "condition": "minecraft:random_chance",
        "chance": 0.15 //Generate this loot pool only 15% of the time
      })
      pool.addItem('woot:exotic_a', 4)
      pool.addItem('woot:exotic_b', 4)
      pool.addItem('woot:exotic_c', 2)
      pool.addItem('woot:exotic_d', 1)
      pool.addItem('woot:exotic_e', 1)
    })
  })
})
```
Reload or restart the game, and that's solved.
As a bonus, if players have the luck effect they can get 2 keys instead of one, in one chest.
To test it in-game spawn a chest with that loot table on top of you: `/setblock ~ ~ ~ minecraft:chest{LootTable:"minecraft:chests/end_city_treasure"}`.
15% of the time the chest will contain a key from Woot, or 2 keys if you have the minecraft luck effect (if you can get it, somehow).
Cheers.

**Comment by aaronhowser1** [comment]
Added, thank you very much for the script!
