### ISSUE TITLE
FTB Inferno Closes without Saving Access Exception Violation

### ISSUE THREAD

**Issue by Prisonshanke** [FTBTeam/FTB-Modpack-Issues#1505]
### Modpack

FTB Inferno

### Modpack version

1.03

### Log Files

<Deleted for security reasons> 

### Describe the bug

Modpack closes at random times, have to restart computer to get it to work again.

### Steps to reproduce

Play the pack
It just happens?

### Expected behaviour

Its never consistent in when it crashes but the crash is the same, Minecraft closes.

**Comment by Raidobw2** [comment]
Hi, I'd say do a memory test, looks like that is a JVM crash and not caused by the modpack.

Type "memory" on the Windows button, and choose the Windows Memory Diagnostics option that shows up.

Follow instructions on screen, your computer will have to reboot. If there are issues with your RAM sticks, it will tell you.
Also, has this issue happened in other modpacks before?

**Comment by Nagapito** [comment]
@Raidobw2 please remove/hide that crash log, it contains private information.

**Comment by TheonlyTazz** [comment]
I have removed your JVM Log file as it contained private information.

**Comment by Saereth** [comment]
it's been a few weeks with no response, feel free to reopen if you're stil having problems.
