### ISSUE TITLE
[Bug, ProjectRed]: Project Red Integration Timer Crash 

### ISSUE THREAD

**Issue by Zoeyowo** [FTBTeam/FTB-Modpack-Issues#151]
### Modpack

FTB Oceanblock

### Modpack version

1.3.0

### Log Files

https://paste.feed-the-beast.com/view/b41d28af

### Describe the bug

Some of the ProjectRed Integration item icons when rendered by a refined storage pattern seem to crash the game I think the item that crashed me this time was the Timer item

### Steps to reproduce

Using a refined storage pattern grid, make a pattern of a ProjectRed Integration and make the item icon appear such as by holding shift or putting the pattern into a crafter.

### Expected behaviour

The game not crashing

**Comment by Raidobw2** [comment]
ProjectRed Integration released an update with a fix to CurseForge. This will prevent future crashes, but the item still won't be rendered in the pattern. RefinedStorage needs to fix that part still (linked issue still above and opened).

**Comment by judos** [comment]
Had same issue, just checked ProjectRed was released but there's no update to FTB OceanBlock yet in 1.9.0 with the updated mod.
Changelog: https://feed-the-beast.com/modpack/ftb_oceanblock
RefinedStorage Ticket: https://github.com/refinedmods/refinedstorage/issues/3110
ProjectRed Ticket: https://github.com/MrTJP/ProjectRed/issues/1686

**Comment by Raidobw2** [comment]
The mod was updated yes, but not with the patch it seems. It's not in their changelog, so we're waiting for the next update.
This is what the workaround should look like, a print instead of an exception:
![image](https://user-images.githubusercontent.com/17010632/143797990-54834852-f924-439c-8eab-49e42a3dd0d1.png)
This is how the code actually looks like in version 4.10.0 of Project Red Integration, throws an exception, not a print:
![image](https://user-images.githubusercontent.com/17010632/143798089-3ebdbdd6-9b2e-4f8e-9e49-eedd0d069484.png)
The original crash states a `scala.MatchError` exception, so this makes perfect sense and the version 4.10.0 does not contain the fix yet.
Therefore we have to wait for the next version.

**Comment by Raidobw2** [comment]
Seems fixed in 1.10.1 with mod updates, works in a crafter too, no crashes:
![pattern_example](https://user-images.githubusercontent.com/17010632/145513634-f521194d-8132-4df2-acee-706ccd0f02be.gif)
