### ISSUE TITLE
[Bug]: Game crashes when trying to enter any menu past the main screen

### ISSUE THREAD

**Issue by snowman909** [FTBTeam/FTB-Modpack-Issues#1526]
### Modpack

FTB Inferno

### Modpack version

1.1.1

### Log Files

[crash-2022-10-29_15.26.28-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9893013/crash-2022-10-29_15.26.28-client.txt)
[crash-2022-10-29_15.38.21-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9893014/crash-2022-10-29_15.38.21-client.txt)

### Describe the bug

After loading into the main menu, clicking on any of the buttons such as Options, Singleplayer or Multiplayer causes the game to hang for a second and then crash. 

### Steps to reproduce

1. Click on any button from the main menu

### Expected behaviour

I expected the multiplayer/options screen to open

### Additional information

I'll be honest, this may be an issue unique to my aging potato of a computer

**Comment by Saereth** [comment]
I'm afraid I cant reproduce this but it looks like some of the menu assets are failing to be read/loaded by your machine. You can try a checkdsk/reinstall but beyond that I dont have much advice

**Comment by Raidobw2** [comment]
Your advice sounds right Saereth, I cannot see otherwise for these crashes. I'd recommend a modpack reinstall on the FTB App and if it's still an issue, let us know here. There appears to be missing or corrupted modpack files in your modpack install
![image](https://user-images.githubusercontent.com/17010632/199430439-69911829-e443-4532-8ce6-12e4b4222439.png)

**Comment by Raidobw2** [comment]
Ahh I see, I'm glad you could figure that out, thanks for letting us know what caused the issue as well. If you need more help for future problems, let us know by making a new issue!
Have fun playing!
