### ISSUE TITLE
[Bug]: Worlds crashing on load in 

### ISSUE THREAD

**Issue by Ftb-Is-Life** [FTBTeam/FTB-Modpack-Issues#1538]
### Modpack

FTB MindCrack 

### Modpack version

8.3.2

### Log Files

https://pastebin.com/v01XktXa

### Describe the bug

Launching from FTB Overwolf app. Pack will load and bring up main menu. After making the world it will either crash while loading or load the world and crash instantly.

### Steps to reproduce

1. Go to Mindcrack pack and Launch.
2. Click single player and create a world
3. After creating the world it crashes.

### Expected behaviour

Expected behavior is world correctly loading and playable 

### Screenshots

![image](https://user-images.githubusercontent.com/117189977/199287130-08a45d73-5d7b-46c3-8393-540dc5d56809.png)

### Additional information

It seems to do this with any other 1.4.7 modpack aswell.
I have tested other packs not on 1.4.7 and they run flawlessly (Inferno, Ultimate, etc).

**Comment by Ftb-Is-Life** [comment]
Forgot to add, I also completely reset my computer and wiped the hard drive to do a clean install of everything, and the problem still consisted.

**Comment by Raidobw2** [comment]
Did a little googling, looks like that's a bit of a silly error:
`This is due to corrupt code in IC2.`
`Its because IC2 has some Haloween mobs set to spawn on Haloween... Just put date on your pc 1 month forward for couple of days and then return to original date.`

This post has more information and some workarounds if you want to look at it: https://forum.feed-the-beast.com/threads/exception-ticking-world-are-you-crashing-30-10-2013-crashes-fix-here-read.33658/

Read the last line if you want an easy workaround for now, add 2 days to your current date and time:
![image](https://user-images.githubusercontent.com/17010632/199433436-3775c7df-daa3-4371-880c-e08c27a63c34.png)

**Comment by Raidobw2** [comment]
Please leave this issue opened! We'll get to fixing this eventually in all those older packs. Having the issue opened also helps other players see the workaround when searching issues on the modpack tracker :)
I assume that worked, so have fun in the modpack!
