### ISSUE TITLE
[Bug]: Server crash due to watchdog and Metspace issues

### ISSUE THREAD

**Issue by battery3996** [FTBTeam/FTB-Modpack-Issues#1573]
### Modpack

StoneBlock 3

### Modpack version

1.0.0

### Log Files

Watchdog crash: https://pste.ch/pixelevisa.sql

Metaspace Crash: https://pste.ch/nogakakada.pl

### Describe the bug

Server is being ran on a Server Host - Nodecraft
Currently running it with 14gb of ram with 2gb of garbage collection room. 

Watchdog crash: It looks like FTB Backups 2 stalled and watchdog crashed the server.

Metaspace Crash: I upped the server Metaspace to 512 to assist with this one.

### Steps to reproduce

n/a

### Expected behaviour

server crashes

**Comment by Raidobw2** [comment]
Hmm, looks like that's coming from the JVM arguments you have set up (or NodeCraft has it set up?):
`-XX:MaxMetaspaceSize=256M`

If you can't remove it or change it to put it higher, ask NodeCraft to check for it instead.

Class metadata is information about objects and how to create them, or how they operate and talk with another. If you don't have class metadata, you don't have any definitions of what those objects are or what they do.
Mods can have quite a few classes to define what their mod does, so they require space to work! There's also some special kind of objects that belong to classes that are stored in there.
And that space is the metaspace, for class metadata and static objects.

The metaspace grows automatically to JVM's needs, so my suggestion would be to remove the MaxMetaspaceSize argument, since it will only use what it needs.
