### ISSUE TITLE
[Bug]: Cannot connect to authorization servers (play online/on servers)

### ISSUE THREAD

**Issue by TheMasterTM69** [FTBTeam/FTB-Modpack-Issues#1592]
### Modpack

Stoneblock 3

### Modpack version

1.0.1

### Describe the bug

Downloading the pack, i tried playing with a friend but every time i open the game and go to "multiplayer" the online status shows up as "?" and when trying to connect it will say that the Authorization servers cannot be reached.
re-logging the account on FTB App and other minecraft sites does not help, restarting PC and internet does not help either.
my friend does not have this issue and it is only on my side.
Vanilla MC works just fine and does not show up with such errors

### Steps to reproduce

1. Launch pack
2. Go to multiplayer
3. Try connecting to server

### Expected behaviour

No online issues, able to connect to multiplayer servers

### Screenshots

![image](https://user-images.githubusercontent.com/75620187/199690693-3b042877-fb64-42e8-9629-cd3410d2b7be.png)
![image](https://user-images.githubusercontent.com/75620187/199690727-0369f910-81a7-4273-995c-5e5f1733c3e7.png)

**Comment by Raidobw2** [comment]
Hi, I've seen the issue twice so far.

One fixed by restarting the router, the other by taking off the time rules (or parental control) in the router.

There's a few more options, I'll list them below, try them and let me know if it works at some point:
- If you have a VPN, turn it off
- If you have Hamachi, uninstall it or remove its network adapter
- If you have an antivirus or your firewall is configured, try turning it off briefly while logging in ReAuth or launching the game. Or allow Java to communicate both in inbound and outbound rules for this test. The runtime on the FTB App is at `C:\Users\%username%\AppData\Local\.ftba\bin\runtime\jdk-17.0.2+8-jre\bin\server\java.exe` on Windows.
- If you are connected to a school network, try another network like a phone hotspot for comparison
- Flush the DNS in a command prompt with `ipconfig /flushdns`
- Check the hosts file in `c:\Windows\System32\Drivers\etc` with Notepad and remove any lines that don't start with `#`, then save the file.

If none of this works and you've already restarted the router, there might be another program on your computer preventing the game from functioning properly.

You may add your game logs if you want, they could help
