### ISSUE TITLE
[Bug]: Creating world on server isn't generating the lobby and only spawning in overworld

### ISSUE THREAD

**Issue by IReed123** [FTBTeam/FTB-Modpack-Issues#1676]
### Modpack

Stoneblock 3

### Modpack version

1.0.2

### Describe the bug

Creating world on server isn't generating the lobby and only spawning in overworld.

### Steps to reproduce

1. Server created 
2. World generation fails to recognize Lobby
3. Generates default overworld every time

### Expected behaviour

Does not spawn Lobby for server

**Comment by 1Diamond1** [comment]
Are you opening the server using the start.bat? Because if you start the server by opening the server.jar (or something along those lines), it won't run with the provided jvm arguments and will create a vanilla world.

**Comment by IReed123** [comment]
Using MCProHosting so not messing with anything file wise.

**Comment by Raidobw2** [comment]
You should check with your host, you need to install Forge for Minecraft 1.18.2 to start the server, otherwise it will be as you describe, without mods (and not in a cave).
https://mcprohosting.com/billing/knowledgebase/419/How-to-Install-Forge.html
![image](https://user-images.githubusercontent.com/17010632/200159670-42a457bf-3d09-4cd0-98c2-36d93ae605c4.png)
