### ISSUE TITLE
[Suggestion]:  Separate threads for different packs. Make searching easier 

### ISSUE THREAD

**Issue by Chinthor** [FTBTeam/FTB-Modpack-Issues#1706]
### Modpack

All FTB packs in this thread

### Is your suggestion related to a problem? Please describe.

Linking here from the FTB page's entry for one pack (DW20 1.18.x) I find all the issues coming from every pack listed together. Hard to search for a particular problem that is pack specific when I'm getting search hits for mods not even in this pack. Please consider subdividing this section per pack. And of course have a few more for the FTB Launcher or website, etc.

**Comment by tyler489** [comment]
If you click on the flare for your pack on any post, it will sort them, but I agree that separating the issues would be nice.

**Comment by Raidobw2** [comment]
As tyler489 pointed out, if you click a label for a modpack or filter by modpacks like so:
![image](https://user-images.githubusercontent.com/17010632/200465539-5ed171fd-de76-4361-b4a5-c503b3910c03.png)

Then you can type any term in the search bar to look up issues, such as "blood magic":
![image](https://user-images.githubusercontent.com/17010632/200465787-886aa0a5-bc56-4c20-ab24-0182b266015f.png)

We've been using this system for about a year now, and it's smooth sailing and improves our efficiency for sorting issues and fixing them in modpacks. When there's a massive flow of new issues such as the release of SB3 for instance, it does get harder to sort quickly, so I can understand if people make duplicate issues and I still thank them for reporting.

There's even some cases like this one https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1373 or this one https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1099 where we're tracking a same issue over multiple packs.
This is great when modpack developers don't always work on the same timezone, one eventually finds a solution or makes a report to the mod author. This make it easier after when going back on those packs and patching things, since it was already solved.

It also ensures myself and the rest of the triage team can give regular answers to the people reporting problems, since there is one spot for all issues.

The only improvement I see is adding a github bot that auto labels per pack, this way you can always search for a specific pack and don't need to wait for us to label them fully. I'll pass the issue to the rest of the modpack development team to hear their opinion about this
