### ISSUE TITLE
[Bug]:  AE Additions is adding "extra cells" that are included in this version of AE2.

### ISSUE THREAD

**Issue by Chinthor** [FTBTeam/FTB-Modpack-Issues#1707]
### Modpack

DW20 1.18

### Modpack version

1.9.1

### Describe the bug

AE Additions is adding storage parts that are now redundant. AE2 already includes many of them. They have different sprite artwork, item ID's, and descriptions. But they have the same crafting recipe, same function, same storage size, and **usually** show as oredict interchangable. Still plays heck with an autocrafting system. Until I test each case, I don't know what version will come out of each crafter, table, or terminal. And even with "allow substitutions" I don't know what version the system is going to insist on having before it gets hung up.

### Steps to reproduce

look up 256 or 1024 in JEI to locate the 256k or 1024k storage parts and storage cells.

note the recipe, entity model, and parent mod for each

attempt to have an AE2 molecular assembler craft a storage part 1024k or larger

Watch as it complains about not missing recipe parts from one mod or the other, ignoring the "substitutions" setting

### Expected behaviour

Any overlapping recipe would be pruned out. The first AE Additions part that doesn't overlap would use AE2 parts.

**Comment by TheonlyTazz** [comment]
as far as i could tell, the only storage component AE2 offers is upto 256k
![grafik](https://user-images.githubusercontent.com/3908847/201181622-ab75e93d-9834-428c-9029-1fb1b7942783.png)

AE-Additions starts at 1024k and works from the 256k
![grafik](https://user-images.githubusercontent.com/3908847/201181765-adb18edd-bebf-46c6-89ab-a7452de062a0.png)


feel free to show me otherwise, but i could not find AE2 offering 1024k storage cells

**Comment by Chinthor** [comment]
My bad. I was looking at the totally wrong items. Sorry about this
