### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ArjunGandotra** [FTBTeam/FTB-Modpack-Issues#1759]
### Modpack

FTB StoneBlock 3

### Modpack version

1.1

### Log Files

https://drive.google.com/file/d/15SXGUIKmIFXRKMH71k1Tkgm_hcQ2z7Ag/view?usp=sharing

### Describe the bug

The launcher started crashing while opening the game after today's launcher update files downloaded. Please help!!!

The game crashed whilst rendering block entity
Error: java.lang.ClassCastException: class net.minecraft.world.entity.animal.Pig cannot be cast to class net.creeperhost.chickens.entity.EntityChickensChicken (net.minecraft.world.entity.animal.Pig is in module minecraft@1.18.2 of loader 'TRANSFORMER' @22a6d75c; net.creeperhost.chickens.entity.EntityChickensChicken is in module chickens@1.0.25 of loader 'TRANSFORMER' @22a6d75c)

### Steps to reproduce

1. Just open the launcher and it will download the update files.
2. After that it will start fluctuating between online and offline mode.
3. When you launch, it will crash as soon as you enter the world.

### Expected behaviour

Normal Functioning

**Comment by Raidobw2** [comment]
Are you using Rubidium? Looks like that's causing the issue: `at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:281) ~[rubidium-0.5.4.jar%23224!/:?]`
It's having problems rendering the Roost block, this should be reported to Rubidium, since it's not something we can fix on our end or in the Chickens mod
