### ISSUE TITLE
[Bug]: custom crafting recipes gone

### ISSUE THREAD

**Issue by GermanPITA** [FTBTeam/FTB-Modpack-Issues#1760]
### Modpack

stoneblock 2

### Modpack version

1,16,1

### Describe the bug

when i joined my world it gave me a notification that balanced clay was missing when i looked at the crafting recipes for the transmutation table it was the one that comes with project e and not the one used for the modpack i looked at a few other recipes including the avaridia armor and they were all the ones that come with the mod and not the ones used in the modpack

### Steps to reproduce

im not sure what happened i just launched the forge modpack like normal but ive since relaunched it and it didnt fix the issue

### Expected behaviour

i just want to play the pack

**Comment by Raidobw2** [comment]
Make sure you use the version from the FTB App, the version of the CurseForge App is deprecated and very old.
The version of CurseForge App: `1.16.1`
The version of FTB App: `1.22.0`

This means there are a lot of bugs fixed in the version on the FTB App, which can include the ones you mentioned

Here's where you can get it https://www.feed-the-beast.com/ftb-app, or from the Overwolf store directly as well if you already have it installed

**Comment by GermanPITA** [comment]
can i move my world over to the ftb app?

**Comment by Raidobw2** [comment]
Yes. Don't delete anything from anywhere yet though. Get the latest 1.22.0 from the FTB App, then you'll be able to open the instance folder from the "..." button next to "Play".

In there will be the `saves` folder, which is where you can copy your world to. Afterwards, you can launch the modpack from there and play it. If that solves it, let me know

**Comment by GermanPITA** [comment]
is the ftb app a complete replacement for the curseforge app?

**Comment by Raidobw2** [comment]
Hmm, it depends what you do with modpacks. If you play a lot of FTB, go for the FTB App, since it supports CurseForge modpacks as well. You also receive modpack updates easily on the FTB App and for popular packs like StoneBlock 3 (yes! There's another version of StoneBlock that just came out, the third!), they come often so it's useful.

If you play more CurseForge modpacks or like to modify your game files often (configs, mods), you could stick with the CurseForge App and use the FTB App when you play FTB modpacks for example, up to your preference.

For example us modpack devs basically use the CurseForge App for developing modpacks, and the FTB App for playing them.

Choose based on that, and if you can't decide, there's nothing wrong with keeping both :)

**Comment by GermanPITA** [comment]
it seems to have fixed the problem thanks for the help
