### ISSUE TITLE
[Bug]: Enriched gold is not being outputted

### ISSUE THREAD

**Issue by MajorGhosty** [FTBTeam/FTB-Modpack-Issues#1773]
### Modpack

FTB StoneBlock 3

### Modpack version

1.2.0

### Describe the bug

Enriched gold is not being outputted in the Enrichment Chamber from Mekanism, instead gold ingots are being outputted.

### Steps to reproduce

Put gold dust in enrichment chamber, gold ingot will be outputted instead of enriched gold

### Expected behaviour

Enriched gold it supposed to be outputted

### Screenshots

![image](https://user-images.githubusercontent.com/110222875/200692006-1957fec0-d390-4b8d-a982-ffe90e3905be.png)

### Additional information

I think the reason why enriched gold is not being outputted is because there are two recipes in the enrichment chamber that use gold dust.

**Comment by InFuRiTy** [comment]
I think dust variants in general shouldn't have recipes in the EC since you can just smelt them in any kind of furnace and then use the ingots to enrich them for their bonus processing material later on.
Also the EC uses raw ores/blocks to make bonus dusts. Why would it use those dusts again to make ingots or enriched versions of them? That way breaks usability of other blocks/machines which is kinda the essence of progression in a pack.

EC is mainly used for early ore multiplication, bonus material enrichment for other recipes and for various blocks/items conversion.

That's just my personal opinion, I could be wrong here as I don't use that machine very often across packs!
