### ISSUE TITLE
[Bug]: Crushed blocks recipes missing for crusher machines, ex: IE, ae2, integrated dynamics

### ISSUE THREAD

**Issue by sarim** [FTBTeam/FTB-Modpack-Issues#181]
### Modpack

FTB OceanBlock

### Modpack version

1.4.1

### Describe the bug

Crushed netherrack, basalt, endstone etc.. blocks recipe only has hammering, mekanism crusher, thermal pulverizer. No recipes for similiar crushing machines from other mods like IE crusher, integrated dynamics squeezer etc..

Edit: some thermal ingot to dust (ex: signalum) crushing recipes are also only provided for mekanism crusher and thermal pulverizer.

For example look up recipe for iron dust, and its seen a dozen recipes from different crushing machines from different mods show up.

### Steps to reproduce

1. Open JEI
2. Search crushed netherrack, click on it to show recipes.
3. Observe as only hammering, mekanism crusher, thermal pulverizer appears.

### Expected behaviour

See recipes for crushing all equivalent machine of all mods 

### Additional information

Seems like a compat issue?

**Comment by Raidobw2** [comment]
Hello, this is usually because all mods are aware that iron exists, but not that signalum exists for example.

Thermal has it built-in and Mekanism might have gone out of their way to make that compatible. Immersive Engineering might have not for example, hence there is no recipe from it.

This can be fixed by our modpack dev when time allows, at it is not a gamebreaking bug. He will also be able to fix the crushed versions of blocks as long as other mods allow the modification of their recipes. Immersive Engineering should definitely be doable since LatvianModder coded a plugin for those.

This will be done through KubeJS scripts mostly, but is not a mod issue.
