### ISSUE TITLE
[Bug]: Crash when /reload is run.

### ISSUE THREAD

**Issue by SGZ-Creations** [FTBTeam/FTB-Modpack-Issues#1817]
### Modpack

FTB StoneBlock 3

### Modpack version

1.2.0 

### Log Files

[crash-2022-11-10_05.41.49-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9977405/crash-2022-11-10_05.41.49-server.txt)

### Describe the bug

Ether i add a data pack or i want to adjust the EMC value. 

After that it ether run the reload it self or it tells me to run / reload tho because of low tick it end's up crashing and I've played many other mod pack where this is not an issues so i would like this to be looked  at and hope it will be fixed for i use a workaround that i won't say is the best.

### Steps to reproduce

Option 1:
Step1: Add EMC to a non item or chance a current one.
Step2: Do /Reload in game using an admin.
Step3 :Crash. May not add EMC value as for the crash.

Option 2:
Step1: Add a data pack that will add a recipe that dose not exist: example (Enchanted golden apple)
Step 2 Activate the data pack and see the reload happen.
Step3 :Crash and recipe added complete.

### Expected behaviour

Not crashing just timing out. Or noting. Completes it's task and not fail.

**Comment by Raidobw2** [comment]
Hi, if the game has an invalid datapack... it will crash, that's normal. Vanilla does this if you add an invalid datapack. /Reload simulates that, so it can crash as well.

As for modifying the pack... It's not something we can give support for, since we'd need to accomodate each user that did their own modifications and we don't have the staff for that. If you think some values are not properly adjusted or some items are missing, we can fix it for you. Just mention here a few/all items you'd want to have modified, and why as well, then I'll be able to turn this into an enhancement ticket.

P.S. Alternative to /reload is relaunching the server. If it crashes there too, there's likely something wrong in your modifications that the mod doesn't like

**Comment by SGZ-Creations** [comment]
I was not asking u to change any EMC value nor was i asking for any modification support made by the player as i just intended datapack to be used privately anyway. Just that the server tick reaches it's max and closes with a crash and was hoping that could be look at and possibly fixed i even included the crash file that say it reached the limit of 60 seconds. i did do a work around for this now tho still annoying running the /reload always crashes due to EMC values taking to log to load just by the default values.

Tho since u say u are willing to add some values i would be happy to see the covalence dusts getting a value according to the resource use and the reason is that the point of ProjectE is having it's items attached to a value so any item at least ProjectE has one so not only giving the dust one but the condenser and any other i haven't seen right now.

**Comment by Xiarno** [comment]
The server tick hanging out too long and crashing is a vanilla Minecraft server feature. That's perfectly normal.
You can disable that by opening `server.properties` and setting `max-tick-time` to `-1`.

**Comment by SGZ-Creations** [comment]
ok then there's nothing more here thanks.

**Comment by SGZ-Creations** [comment]
Please re-enable the EMC command. didn't mean to get it disabled version 1.2.1

**Comment by SGZ-Creations** [comment]
Nvm forgot to op myself after update Crying inside
