### ISSUE TITLE
[Suggestion]: balancing on servers

### ISSUE THREAD

**Issue by minecrafterseppe** [FTBTeam/FTB-Modpack-Issues#1852]
### Modpack

FTB stoneblock 3

### Is your suggestion related to a problem? Please describe.

the modpack is fun to a degree but im running into a few issues 

1  some of the singularitie crafting are taking WAAY to long 
(example  balloon singularity,emerald crystal,)
the main problem is to do with not being able to use the dark matter pedestals + watch of flowing time on MOST servers
due to degrading performance       for example with emerald crystals ive calculated u need around 3 MILLION   to collect all the singularities needed to make all the endgame crafts (1635 stars)
the pack seems to be designed to spam dark matter pedestals everwhere 
wich seems like bad balancing  
my suggestion is to nerf most of the singularities
and completely remove the watch of flowing time   as it breaks servers      and the only purpose of it is to get many of a certain item wich shouldent be a thing if it was all balanced

**Comment by richie3366** [comment]
I concur with @minecrafterseppe, I was going to report an issue about the watch being banned on most (if not all) the servers, which is making impossible to craft the Gem Leggings _(although after many attempts, I finally managed to find a sneaky way to do it)_

But yes, I'm astonished by the very high amount of items being required to reach the very endgame items.
For starters, I'd suggest to make infinity ingots crafted with only one Infinity Catalyst (circled by 8 neutronium, then by 16 crystal matrix). It makes me think about Inferno, in which you only had to combine 1 neutronium with 1 Infinity Catalyst.

As for the amounts required on each singularity, I invite @minecrafterseppe to suggest what amounts he has in mind, because I'm not (yet) as involved as he is into making them.

**Comment by richie3366** [comment]
(sorry for the double comment)
If you happen to ban the watch completely from the pack, don't forget to set the `timePedBonus` to `0` in projectE server config file. It will prevent players who already own a watch from using its effect again.

**Comment by phit** [comment]
not sure if the pack should be balanced around servers disabling core items, if you are already changing the pack so much, you could just tweak the values for singularities too to balance out the changes you've made

**Comment by richie3366** [comment]
I think @minecrafterseppe suggested it alongside because it makes sense to disable an item that could break the (new/upcoming) balance.

**Comment by richie3366** [comment]
@phit You may be a server admin yourself, you are not yet dealing with the same amount of [online or not] players than the most popular ones (and I'm not making any judgement, just speaking out a fact). And when you face this kind of frequentation, your only availlable call is to ban most of the TPS-eating items.

A modpack published alongside a server bundle should either propose a server-friendly version of it (with the balance being readjusted) or acknowledge generally that the progression cannot (should not) involve spamming pedestals with watch on them.

**Comment by minecrafterseppe** [comment]
le me phrase it different the watch    is currently NEEDED for the emerald singularities   wich takes exactly  3.348.480 clusters 
for all 1635 singularities approx 147 ingots    (+ some extra stars for the actual items)   to craft all infinity stuff

lets say without the watch a    crystal growss every 2 minutes (wich it by a long shot doesent)
this would take 401.817.600 minutes (764.4 years)
to get all of them needed
this is a very rough estimate  based on a fully grow crystal growing every 2 minutes(wich does not happen by far)

thats the reason the watch is needed for this craft
and on MOST servers a item like that watch is banned due to 1 of them being able bring any server to its knees even with an optimal setup

i want an alternative to making that specific crystal

maybe a mixer recipy with emerald blocks/amethyst ? even neutronium maybe

**Comment by Sunekaer** [comment]
We ran our beta testing with watches enabled, and our server ran just fine.
That said, our player does also not over use the watches and make extremely huge farms to try and complete the pack in 10sec, I can't really do anything about players wanting to rush things because they deadlocked on finishing 1 singularity before moving on to the next.

I am open to tweaking numbers and have additional recipes.
But its something there has to make sense also, the numbers in the current recipes were calculated base beta testers play-throughs

**Comment by richie3366** [comment]
## About lag issues caused by the watch
I quote SystemCollapse's video published today (he had an early access to the pack & he's playing 1.3.0) who used pedestals to progress on making singularities:

> "when [...], we can turn that off, [...], this is gonna reduce a lot of lag in my world"

[https://youtu.be/iTQVpelrMTQ?t=109](https://youtu.be/iTQVpelrMTQ?t=109) (01:49)

He's playing on SP, so I let you guess how that would go on a public MP server. x)

## FTB poll
A majority of players (and I'd guess that a majority of them are playing in SP) answered to the recent poll posted by FTB Twitter account that they'd appreciate if the singularities were nerfed to require less grind.
https://strawpoll.com/polls/7rnzGYvm3gO/results

15.27% of the responders still think it'd be not enough of a nerf. Imo, since they represent nearly 1/6th of the players, their input should count nonetheless.

'fun' fact, the poll text says "whilst fine on servers", which shows how disconnected some of the FTB team members/devs can be. Yes, on servers between friends with a quota of 16 chunks permaloaded, the grind would be fine (and would also benefit of the watch not being banned/disabled). But on public servers, autoloaded chunks are only granted to longtime-players &/or donators (and this is completely understandable), so yeah, the grind is not easier on all servers. x)

## Additional recipes... or maybe mechanics?
The top-priority singularity to make more grindable on public servers is the emerald cluster one. I'd suggest a way to make it grow via deployers holding an emerald.

I've already dev'd two possible implementations, a simple one using the randomTicks method, the other one growing the surrounding crystals forcefully.

### Simple
```javascript
onEvent("block.right_click", (event) => {
  if (event.block.id === 'buddingcrystals:budding_emerald') {
    if (event.item && event.item.id === 'minecraft:emerald') {
      let bs = event.block.getBlockState();
      let l = event.block.getLevel().getMinecraftLevel();
      for (let i = 0; i < 20; i++) bs.randomTick(l, event.block.getPos(), l.random)
      event.item.setCount(event.item.getCount() - 1);

      // optional, shows the green particules growing effect
      // l.levelEvent(1505, event.block.getPos(), 0);
    }
  }
});
```

### Complex but more complete & ticktime-efficient
(and also: includes all other budding types)
It grows all the buds around the block by one step
<details><summary>Show/hide 80 lines of javascript code</summary>
<p>

```javascript
const MOD_PREFIX = 'buddingcrystals:';
const ACTUAL_PLAYER = 'net.minecraft.server.level.ServerPlayer';

const DIRECTIONS = [
  Direction.UP,
  Direction.DOWN,
  Direction.NORTH,
  Direction.SOUTH,
  Direction.WEST,
  Direction.EAST
];

const buddingMaterials = {
diamond: 'minecraft:diamond',
redstone: 'minecraft:redstone',
emerald: 'minecraft:emerald',
lapis_lazuli: 'minecraft:lapis_lazuli',
glowstone: 'minecraft:glowstone_dust',
nether_quartz: 'minecraft:quartz',
prismarine: 'minecraft:prismarine',
certus_quartz: 'ae2:certus_quartz_crystal',
fluix: 'ae2:fluix_crystal',
salt: 'mekanism:salt',
fluorite: 'mekanism:fluorite_gem'
};

// Store block references ahead to double the perf(!)
const BuddingBudBlocks = {};
Object.entries(buddingMaterials).forEach(
  ([material, v]) => 
    ['small_', 'medium_', 'large_', ''].forEach(prefix => {
      let resLoc = `${MOD_PREFIX}${prefix}${material}${prefix ? '_bud' : '_cluster'}`;
      BuddingBudBlocks[resLoc] = Block.getBlock(ResourceLocation(resLoc));
    })
);

onEvent("block.right_click", (event) => {
  if (event.block.id.startsWith(`${MOD_PREFIX}budding_`)) {// && event.block.id.endsWith('_bud')) {
    let material = event.block.id.replace(`${MOD_PREFIX}budding_`, '');
    
    if (event.item.id === buddingMaterials[material]) {
      let l = event.block.getLevel().getMinecraftLevel();  
      let hasGrown = false;
      const {FACING} = BuddingBudBlocks[`${MOD_PREFIX}${material}_cluster`];

      for (let dir of DIRECTIONS) {
        let newBlock = null;
        
        let b = event.block.offset(dir);
        let bs = b.getBlockState();
        if (b.id === 'minecraft:air')
          newBlock = `small_${material}_bud`;
        else if (b.id.includes(':small_') && bs.getValue(FACING) == dir)
          newBlock = `medium_${material}_bud`;
        else if (b.id.includes(':medium_') && bs.getValue(FACING) == dir)
          newBlock = `large_${material}_bud`;
        else if (b.id.includes(':large_') && bs.getValue(FACING) == dir)
          newBlock = `${material}_cluster`;
        
        // This block can be uncommented to test a cycling example
        //else if (b.id.endsWith('_cluster') && bs.getValue(FACING) == dir)
        //  newBlock = 'minecraft:air';

        if (newBlock) {
          let newBlockstate;
          if (newBlock === 'minecraft:air') newBlockstate = AIR_BLOCK.defaultBlockState();
          else newBlockstate = BuddingBudBlocks[MOD_PREFIX + newBlock].defaultBlockState().setValue(FACING, dir);
          l.setBlockAndUpdate(b.getPos(), newBlockstate);
          hasGrown = true;
        }
      } 

      if (hasGrown) {
        event.item.setCount(event.item.getCount() - 1);
        // Play an effect when it's a player, to show that it works
        if (event.player.minecraftEntity.getClass().getName() === ACTUAL_PLAYER)
          l.levelEvent(1505, event.block.getPos(), 0);
      }
    }
  }
});
```

</p>
</details>

### Recipes? Not a big fan, but here are some:
I don't know what to suggest, but it could be just an emerald cluster with a block of emerald in a Mixer, giving out four clusters.
Or an orb recipe energizing a spirited crystal + a crystal catalyst to give a stack of emerald clusters?

I'd personally keep the original way (with the ability to growth) rather than adding an alternative method: it required a specific setup to gather them, and I think that would be a bit of a loss to allow another method. But you're the one to decide, I wouldn't complain if there was two or three ways, but I know I'll probably use the easiest one in my own LP. x)

**Comment by tjd2013** [comment]
I did make a suggestion on singularities on the discord, and after coming here found this issue which is pretty similar.

The emerald singularity is the main issue when you dont have chunk loading or watches enabled, like the server I am playing on.

With some rough napkin math on my setup i have 160 clusters and its going to take around 3 years at 24 hours a day afking to complete them.

I agree with some of the above comments, there needs to be a more automation way to farm them, either adding them to a machine like phyto or cloche or something to allow them to be grown faster and not rely on random ticks.
