### ISSUE TITLE
[Suggestion]: Make it obvious that cosmic meatballs are not a shape-less craft on mechanical crafters

### ISSUE THREAD

**Issue by MisterSoandSo** [FTBTeam/FTB-Modpack-Issues#1865]
### Modpack

StoneBlock 3

### Is your suggestion related to a problem? Please describe.

It quite annoying to mechanically craft the late game items when they kept popping of complete 21 crafter setups. I didn't realize that meatball recipe wasn't shapeless. I assume this issue would be similar with the soup as well.

![1](https://user-images.githubusercontent.com/16674113/201369828-7b266f48-8cda-4189-911c-c7adf86297e1.jpg)
![2](https://user-images.githubusercontent.com/16674113/201369834-086449db-a8b4-431a-8802-bb20c998d18a.jpg)

It would be helpful note in the questbook or in the REI menu

**Comment by IThundxr** [comment]
No need its simple create in create all mech crafter recipes are not shapeless

**Comment by richie3366** [comment]
Now that I'm thinking about it, if the Mixer is able to receive this big amount of items, I would find it way more appropriate to have the ultimate STEW and the MEATBALLS made in it rather than mechanical blocks. It would make a lot of sense.

(checking the max number of different items it can receive)

oooh it can't :(
Max number of different items is 9 (makes sense).

**Comment by Sunekaer** [comment]
I have no control over how Create shows their recipes in JEI/REI, so sadly nothing really i can do about this.
