### ISSUE TITLE
[Bug]: tungsten seeds and chrome seeds are given as quest rewards 

### ISSUE THREAD

**Issue by JTHm3** [FTBTeam/FTB-Modpack-Issues#188]
### Modpack

FTB Oceanblock

### Modpack version

1.5.0

### Describe the bug

The seeds are given as quest rewards, but have no use.
(I received them in an earlier version so sorry if this has already been fixed)

### Steps to reproduce

claim quest reward

### Expected behaviour

have use for essence or not get the seeds

**Comment by set92** [comment]
Was going to open another issue, but basically is this, I got the graphite seed from a quest reward in 1.5, but the graphite essence don't work for anything. At first, I thought it could be to do graphite electrodes from IE, but it already has another seed.

There are more essences without recipe, so maybe it would be better to disable those seeds? In 1.6 I'm seeing mithril, tungsten, brass, graphite, chrome, platinum, iridium essences without uses. Since I don't know how to check the possible rewards of quests, I can't check if the seeds of those essences are in there.

**Comment by Raidobw2** [comment]
Yes, another issue please, since that last problem was resolved and closed in the last milestone!
