### ISSUE TITLE
[Suggestion]: Change GC to Shenandoah instead of G1GC

### ISSUE THREAD

**Issue by Anzulo1984** [FTBTeam/FTB-Modpack-Issues#1880]
### Modpack

FTB Inferno/Stoneblock 3

### Is your suggestion related to a problem? Please describe.

Since both modpacks run on Java 17 and Shenandoah GC performs way better than G1GC and causes less server laggs, it should be considered to run Shenandoah as default GC and tweak the settings further for better performance, includeing:

- Xms and Xmx have same value, since dynamically changing the memory pool size can result in performance issues

**Comment by Raidobw2** [comment]
Hi, I've looked into this quickly with the FTB App team and while the option to choose the GC is not currently configurable in the FTB App, it is in their notes and they said they would be looking into it at some point (G1GC vs Shenandoah vs ZGC vs others if any).
That's all I can help you on this one, and since this is not really an issue inside a modpack, I'll shortly close this case.

Note: Servers (installed with the server installer from the FTB website) are fully configurable on the other hand and you can remove the G1GC line and replace it with Shenandoah, change the Xms/Xmx, etc
