### ISSUE TITLE
[Suggestion]: enable life essence pumping with create

### ISSUE THREAD

**Issue by minecrafterseppe** [FTBTeam/FTB-Modpack-Issues#1921]
### Modpack

FTB stoneblock 3

### Is your suggestion related to a problem? Please describe.

enable players to make a basin with 10.000 buckets to then infinitly pump blood from with create 

it is an alternative to having a player needing to run a well of suffering (ak having a bunch of mobs) nonstop

mostly for servers           will be a improvement to performance for mid-late game players
and making a basin with so much life essence is way more efford then making a well of suffering

**Comment by Sunekaer** [comment]
Im not sure what you mean with "basin with 10.000 buckets"

Are you talking about making a Mixing recipe that gives Life Essen?

**Comment by Bluberry-Kat** [comment]
I think they may be referring to the Hose Pulley's ability to have "infinite" pools of fluid if they are sufficiently large.  
It's a fluid tag these days, `#create:bottomless/allow`

**Comment by richie3366** [comment]
That would consist in adding this line to `onEvent("tags.fluids"...` inside `kubejs/server_scripts/_core/tags.js`:
```javascript
  event.add("create:bottomless/allow", ["bloodmagic:life_essence_fluid"]);
```

**Comment by richie3366** [comment]
I think @minecrafterseppe was proposing this in order to produce Life Essence in the most server-friendly way (without having to spawn mobs with the well of suffering):

> mostly for servers will be a improvement to performance for mid-late game players

I think that the time/effort taken by the player should be disregarded if it's higher than what it is making it worth (to your opinion). Seppe's demand is more a possibility rather than a quest/guide route.
