### ISSUE TITLE
[Bug]: Textrures Load Issue

### ISSUE THREAD

**Issue by Repla7Noobx** [FTBTeam/FTB-Modpack-Issues#1929]
### Modpack

StoneBlock3

### Modpack version

1.2.1

### Log Files

https://pste.ch/siqifimoma.sql

### Describe the bug

There is a render issue in some chunks. I don't know why

### Steps to reproduce

1. Break or place blocks
2. Textures are not rendering
3. Reload Chunks with F3+A 
4. It renders nut some chunks wont render properly

### Expected behaviour

Everything renders normally.

### Screenshots

![2022-11-13_20 53 36](https://user-images.githubusercontent.com/52977994/201537365-bed2ddba-eea4-4dcf-947f-49da7f7f530e.png)
![2022-11-13_20 53 42](https://user-images.githubusercontent.com/52977994/201537369-09dfc170-2d17-471d-b26f-ffe4d7f1b341.png)
![2022-11-13_20 53 53](https://user-images.githubusercontent.com/52977994/201537371-554b0a8e-018f-4a47-b0d9-452f699dd93d.png)
![2022-11-13_20 53 56](https://user-images.githubusercontent.com/52977994/201537374-f6850951-e27a-4189-b995-f21317be76d0.png)

**Comment by Sunekaer** [comment]
Does this happen still after a restart of the game?

**Comment by Repla7Noobx** [comment]
> Does this happen still after a restart of the game?

Yes. I restarted game multiple times.

**Comment by Repla7Noobx** [comment]
Yes. I restarted game several times. Nothing changed. I loaded from backups too.

**Comment by Sunekaer** [comment]
Can you send a log from where you only had the world open for like 1,2 min as there are a lot of errors in the log, which means the one you send is only part of it

**Comment by Repla7Noobx** [comment]
https://pste.ch/xifiqixori.md

**Comment by Repla7Noobx** [comment]
> Can you send a log from where you only had the world open for like 1,2 min as there are a lot of errors in the log, which means the one you send is only part of it

https://pste.ch/ijaxibaber.md 
This is 11.13-1 log

**Comment by Repla7Noobx** [comment]
No i didn't cahnged anything from modpack. This issue is only at chunks that near spawn. Like when i go mother silverfish arena and place, break blocks  nothing happens.

**Comment by Sunekaer** [comment]
Honestly not sure what the issue is

**Comment by Raidobw2** [comment]
In-game would you be able to press and hold "F3 + C"? This will make your game crash after around 10 seconds, this is called a manual crash.

If you can then go in the `crash-reports` folder and put your latest crash report here, that will help me see the version and brand of the graphics card you currently are using for the game.

For some cases I've seen where people use a laptop to play games, they have both integrated graphics and dedicated graphics on. Minecraft will then use the integrated graphics, which most of the time cannot run the game properly and end up causing graphical issues.

Make sure your graphics card driver is up to date, then if you're using a laptop, you likely still have both video cards on. Make sure the dedicated card is being used instead of the integrated graphics.

The path to the Java being used in the FTB App for SB3 is: `C:\Users\%username%\AppData\Local\.ftba\bin\runtime\jdk-17.0.2+8-jre\bin\javaw.exe`. You might need that to configure the video card control panels, see below:

Nvidia (GeForce, RTX)
![image](https://user-images.githubusercontent.com/17010632/205246252-aceb8b25-b54c-426d-8cc3-f53e1a3b9642.png)

AMD (Radeon)
![image](https://user-images.githubusercontent.com/17010632/205246385-5915bdfb-3f14-4602-9630-5edf3968d691.png)

(For advanced users: You can disable the integrated graphics in the BIOS, but I won't go into details since that is more complex. The BIOS is the brand you see on screen before the Windows logo, that's the company that made your motherboard. Check on your motherboard manual (found on your manufacturer's site, say the logo is Lenovo, then it's on the Lenovo site) or google something like "disable integrated graphics bios lenovo" if Lenovo is the brand.)

Remember to post your manual crash report here if the above doesn't solve it. Thanks in advance!

**Comment by Sunekaer** [comment]
Hmm i no issues when dying -.-
