### ISSUE TITLE
[Bug]: java.io.IOException: Failed to update AssetIndexManifest, Disk cache does no exist

### ISSUE THREAD

**Issue by WhoAmEis** [FTBTeam/FTB-Modpack-Issues#1949]
### Modpack

FTB Tech World 2

### Modpack version

1.1.6

### Log Files

[FTB APP] [INFO] Pre-Start Task
[FTB APP] [INFO] Validate Java Runtime
[FTB APP] [INFO] Validate assets

### Describe the bug

When I try to start Tech World 2 it's loading and then crashing with:

An Error Occured Whilst Launching

Failed to prepare instance 'FTB Tech World2' (cdobb5e-ecdc-4a98-b723-7bea2ddf62f8).
because.. java.io.IOException: Failed to update AssetIndexManifest, Disk cache does not exist.

I have Java 8 351 installed

### Steps to reproduce

1. start Tech World 2

### Expected behaviour

Help?

**Comment by Raidobw2** [comment]
Does this persist even after installing a new instance of the modpack?

**Comment by WhoAmEis** [comment]
Yes i tryed to reinstall Techworld 2 and also reinstalled, FTB App and java. --Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 18.11.22, 08:49 schrieb R3GEN ***@***.***>:

   
  Does this persist even after installing a new instance of the modpack?

**Comment by Raidobw2** [comment]
Hmm, I see, thanks for the info. Sorry for the delay, been a lot busy lately...

Since I'm able to launch it properly on my side after a quick test (with 127 mods loaded in main menu), I'd say that might be an app bug instead of a modpack issue.

Would you be able to go in the [FTB Discord](https://go.ftb.team/discord) and use the debug tool to upload your game logs? If you write "!ftbdebug" in the ftb-app-support channel (and press Enter), the FTB Bot will link the debug tool. Upon using the tool you'll get a code, which you can either post here, or if you prefer you can also tag me directly in the Discord (`@R3GEN`) and we'll continue there.

Also tagging me on Discord would allow my colleagues to help further since they don't always see all issues on the tracker here, but app issues are commonly discussed in the ftb-app-support channel.
Thanks in advance

**Comment by manmaed** [comment]
This i an old mod pack and is unlikely to get updated added @Raidobw2 if he gets time

**Comment by Gaz492** [comment]
This looks as it may have been an app issue which has since been fixed as the modpack loaded up fine for me using the latest version of the FTB app.
