### ISSUE TITLE
[Bug]: Can't produce Thermal series Enderium

### ISSUE THREAD

**Issue by Kevin-Marsh** [FTBTeam/FTB-Modpack-Issues#2]
### Modpack

FTB OceanBlock

### Modpack version

1.1.0

### Describe the bug

I am trying to produce Enderium. usually you would crush up some ender pearls in a crusher and mix the blend. However, while crushing ender pearls in a crusher or theoretically any other way produces the ender dust,  the recipe for Enderium doesn't work with this ender dust. It appears that the recipe is being hijacked by Mini utilities with their ender dust. Normally this wouldn't be a problem but you can't produce the mini utilities ender dust since there is no ore generation. You could in theory silk touch an ore from the end and run it through a washing factory into a fermentation station and finally into a fluid sieving machine but that is the only way that it says that you can produce the mini utilities version of ender dust.

### Steps to reproduce

Try to produce Enderium with thermal series ender dust.

### Expected behaviour

Process ender pearls into Enderium for Thermal Series

**Comment by sme23** [comment]
It's configured to set all instances of ender pearl dust to `forge:dusts/ender` but only mini utilities ender dust is tagged `forge:dusts/ender`, thermal's ender dust is `forge:dusts/ender_pearl` and because it also sets all ender dust recipes it can to output thermal's ender dust this makes pretty much anything that needs ender dust uncraftable.

Changing lines 170-172 of `kubejs/server_scripts/resources/unify.js` to the following fixes this:

```
    event.replaceInput("appliedenergistics2:ender_dust", "#forge:dusts/ender_pearl");
    event.replaceInput("miniutilities:ender_dust", "#forge:dusts/ender_pearl");
    event.replaceInput("thermal:ender_pearl_dust", "#forge:dusts/ender_pearl");
```
