### ISSUE TITLE
[Bug]: Very long load times and very low FPS after 1.3.0 update

### ISSUE THREAD

**Issue by Red072** [FTBTeam/FTB-Modpack-Issues#2000]
### Modpack

StoneBlock 3

### Modpack version

1.3.0

### Describe the bug

My wife started experiencing very long load times after the 1.3.0 update (5-10 minutes to load a world).  When in-game her FPS sits around 2-4.  We tried disabling mipmap, and that netted 20-25 fps, but the game still lags when opening chests and menus, and still the long load times.  We tried single player and our Aternos server.  We tried rolling back to 1.2.0.  We tried uninstalling modpack and reinstalling.  We tried restarting computer.  Nothing seems to solve this issue.

Before the update, my wife had pretty decent FPS (not sure how much), fast load times (less than a minute to load a world), and no noticeable lag when interacting with the game world.  She was playing the modpack for about a week with no issues prior to this.

My game on my machine has had no issues with the new update, and I can't figure out what is causing hers to suddenly not work.

I tried contacting the FTB Support Discord Server, but got no response.  Please let me know if you have any insight into this problem.

### Steps to reproduce

Update StoneBlock 3 modpack from 1.2.0 to 1.3.0.
Enter the game.
Experience long load times.
Experience very low FPS.

### Expected behaviour

Quick(er) load times, 60fps, no interactables lag

### Screenshots

![2022-11-14_19 43 19](https://user-images.githubusercontent.com/118412978/202345113-8c1dec86-d9df-4887-8ea3-30c01684fa36.png)

**Comment by Yarikmessi20073588987** [comment]
I have the same error, only I have it with an optifine, and without an optifine, there are some lags on the assembly. Found how to fix it?

**Comment by Raidobw2** [comment]
Try a few of those:
- Keep mipmapping off for an AMD graphics card
- `In your modpack folder, open the config folder and the file forge-client.toml with a text editor. Change the setting alwaysSetupTerrainOffthread to true, save the file, and start your game. This setting boosts FPS mostly in Singleplayer, since rendering will be done on a separate thread. It also solves lag related to block placement.`
- Rubidium could improve performance a lot, I'm unsure if it's meant to be fully compatible with SB3 but you can try adding it https://www.curseforge.com/minecraft/mc-mods/rubidium
- Update the cards' driver in the Radeon software

On 1.2.0 is the FPS good?

Also feel free to ping me in the FTB Discord directly (`@R3GEN`), I'm likely to answer quicker there and we can talk in a thread which is similar to a post here.

**Comment by Red072** [comment]
Yes, we had been playing for about a week, and she had played some prior to that.  She had great FPS and load time prior to the 1.3.0 update.  I'm not sure what could have changed to tank her performance.  I even tried rolling back to the previous update, but that didn't help.

I have already turned off mipmaps, and I will try the other fixes you suggested.

Thanks for the response!

**Comment by Red072** [comment]
I think it was our fault.  I discovered that my wife had accidentally turned on power-save mode, and I think that might have been inhibiting the game.  I switched it to high-performance mode and now she's getting about 40 fps, with much better response time for interactables.  Loading faster too.  I will continue to monitor it to see if there are any more performance issues.

**Comment by Raidobw2** [comment]
Sorry for the delay, if it's on a laptop that could make sense. Have the laptop charging and see if that helps as well. Let me know if the issue seems solved
