### ISSUE TITLE
[Bug]: emc link and me storage bus

### ISSUE THREAD

**Issue by NordicGamerFE** [FTBTeam/FTB-Modpack-Issues#2028]
### Modpack

FTB Stoneblock 3

### Modpack version

1.3.0

### Log Files

N/A

### Describe the bug

Everything worked fine, But after going past around 9E emc I been having issues with the items displaying in my me. It seems like the system get confused and don't think I have certain items, some items display 2 billion some don't exist 

### Steps to reproduce

get like 9E emc
connect a bunch of compressed emc links to a me system via me storage buses
add loads of items and check if they all display in the me system, I've also had issues where I try to take out of the link directly and it don't work and also sometimes it works but keep filling my inventory with said item not stopping filling my inventory until I relog

### Expected behaviour

for everything to display correctly in my me system like before

**Comment by NordicGamerFE** [comment]
After a closer look it seems like its items with a emc value of 1 that gets bugged

**Comment by NordicGamerFE** [comment]
![image](https://user-images.githubusercontent.com/18188155/202648726-26d3c9a4-215b-4852-8b1c-179c095f240d.png)
Think this is also something to do with the issue

**Comment by NordicGamerFE** [comment]
dupe of #1979 i'll just leave it here until you decide what to do since I brought forward some more info

**Comment by Zonk1987** [comment]
I have the same issue with this but with refined storage.
I can confirm that it is related to items that have 1 EMC.
It is also often the case that if I want to take Cobblestone directly from the EMC link, it simply doesn't work and then if I click often enough, my inventory is suddenly full of Cobblestone.
https://www.youtube.com/watch?v=Ik7YYM6TYfc

In other cases, I suddenly get so many items out of the Refined Storage System even though I only wanted one stack so that my entire inventory and the floor under me is full of the item. When I then try to pack all the items back into the system, there are so many that all my disks are full and it seems to me that the items on the floor below me are endless.
https://www.youtube.com/watch?v=PBC21e0JFZE

I hope this helps to fix this Issue

**Comment by Sunekaer** [comment]
Should be solved in the newest update of the pack
