### ISSUE TITLE
[Bug]:  Red text reappears after game crash

### ISSUE THREAD

**Issue by GamerRy123** [FTBTeam/FTB-Modpack-Issues#2041]
### Modpack

FTB Inferno

### Modpack version

1.3.0

### Describe the bug

Game crashed and now all the red text is back under items and I assume my world kind of corrupted as I had to delete my ender storage file too although the world itself seems fine

### Steps to reproduce

I have no idea how this happened or how to reproduce all I know is that it was caused by a game crash

### Expected behaviour

not to have my gamestates reset

### Screenshots

![image](https://user-images.githubusercontent.com/99148503/202784070-d67fe819-6e4e-4359-b5de-3504fe4dc55e.png)
![image](https://user-images.githubusercontent.com/99148503/202784303-33fb681c-4192-4de2-85e2-d9c9a5e40be4.png)

**Comment by Saereth** [comment]
we cant account for crashes or issues beyond normal pack operations mucking with save data as far as your game stages go. We literally way to know if save data was corrupted and cant account for it. Your best bet is to restore from a backup. What would be useful is a new issue with your crash log to try to resolve that, otherwise those stages are all tied to quests
