### ISSUE TITLE
[Bug]: Issues when trying to close the world to the menu

### ISSUE THREAD

**Issue by nc19gaming** [FTBTeam/FTB-Modpack-Issues#2096]
### Modpack

FTB Stoneblock3

### Modpack version

1.3.0

### Describe the bug

When I try to close to the main menu, the game freezes at the saving game screen. I've left it running over night to see if it would eventually close out and it doesnt. it just sticks there and doesnt move. I end up having to force quit the game entirely.

### Steps to reproduce

Idk i just quit to menu from singleplayer game.

### Expected behaviour

i expected the game to close to menu

**Comment by Sunekaer** [comment]
Can you please attach your latest log from when this happens?

**Comment by NordicGamerFE** [comment]
![image](https://user-images.githubusercontent.com/18188155/204006801-458dc486-de96-4261-960a-8218d7421452.png)
![image](https://user-images.githubusercontent.com/18188155/204006974-10127455-3f38-4d7a-8ac9-2aca3f95a058.png)
copy paste the content of that file into https://pastebin.com give the thing a name and press create new paste

**Comment by nc19gaming** [comment]
um it says it exceeds the max size for paste bin

**Comment by nc19gaming** [comment]
https://pastebin.com/59BT0YtD   part 1

https://pastebin.com/1SMMyRB1   part 2

https://pastebin.com/EjYKdyEE  part 3

**Comment by NordicGamerFE** [comment]
are you still on 1.3.0?

**Comment by nc19gaming** [comment]
um i updated today so no its 1.4.2 sorry

**Comment by nc19gaming** [comment]
any news?

**Comment by Raidobw2** [comment]
Hmm, logs don't seem to show the error. Best is if you're able to upload your world (as a zip file) to Google Drive and share it here with a share link.
That way I can check for what's locking your world, and in the case I need to remove some blocks, even fix it.
The world is found inside the `saves` folder instead of the `logs` folder.

By right clicking the folder inside `saves` you can "Send To" > Archive/Zip File, and that's how you zip a folder.

When you do ping me with my name that way I can see your message quicker `@Raidobw2`. Thanks!
