### ISSUE TITLE
[Bug]: Entity function seems to cause lag and crash. mixins: BetterDiving, ObdisianBoat, RoadRunner, Aquafied.

### ISSUE THREAD

**Issue by Diversion98** [FTBTeam/FTB-Modpack-Issues#211]
### Modpack

FTB OceanBlock

### Modpack version

1.4.1

### Log Files

https://paste.feed-the-beast.com/view/49da57ad

### Describe the bug

The server lags sometimes and not just some small lag. look next line.

[net.minecraft.server.MinecraftServer/]: Can't keep up! Is the server overloaded? Running 527333ms or 10546 ticks behind

So what I did is said the max tick time to 60000 so I could get a crash report. (look paste)

### Steps to reproduce

unknown, sorry

### Expected behaviour

no big lag :p

**Comment by Elliona** [comment]
I have a similar problem on my Server. No Crashes, thanks to `max-tick-time=-1` but performance is overall bad, with TPS ranging from 8-16.
I was using version 1.15 and 1.16.
Sparklog: [https://spark.lucko.me/pIfgqccRJz](url)

I have deleted all Obsidianboats, Blursed Earth deactive.

If i can help with any additional informations I gladly help out.

**Comment by Raidobw2** [comment]
Interesting, the spark report shows WYML as the lag source. This was a problem we had in earlier versions but is supposed to be fixed. Perhaps it's different a bit this time. So we can correctly report this to the mod author if it's needed, which version of OceanBlock are you currently using?

**Comment by Elliona** [comment]
The Log was created using Version 1.16. I'm running this Version aswell atm.

**Comment by Raidobw2** [comment]
To dev: Sunekaer, could this be a WYML problem?
![image](https://user-images.githubusercontent.com/17010632/140636204-c1c8c170-74ad-46db-85e9-53dfcc384f7c.png)

**Comment by Sunekaer** [comment]
Im not sure, ill forward the issue

**Comment by Sunekaer** [comment]
Is this in SP or MP that it happens?
If MP how many players is on when it happens?
What kinda hardware are you running this on?
Have you changed any configs or removed mods?

**Comment by Elliona** [comment]
This is on a MP Server, with just one player online at that time.
Its running on a VPS with and AMD EPYC 7282 16 Core 32GB Ram (Oceanblock gets 16 of them) 
Other then Spark i have not changed anything.

**Comment by Sunekaer** [comment]
Okay then it shouldnt be WYML, causing lag.
Just to check could you upload the wyml.json from config folder

**Comment by Elliona** [comment]
For some reason it wont let me upload the .json.
[wyml.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7493071/wyml.txt)

**Comment by TilBlechschmidt** [comment]
We've been experiencing the very same issue where the server occasionally runs into tick times upwards of 60sec and crashes (as per `max-tick-time`). To me, the crash logs contain seemingly random stack traces. Over the past couple of days, this happened both with players online but also with the server just "idling" (but chunk loaded islands). Our tech-level is medium to low with mostly sluices, smelteries, some Mekanism machines, and one player with a small ME system.

We suspected Chisel & Bits because that mod started glitching after updating to 1.7.0, however, the crashes also happens with it removed. The server crashes both on 1.6.0 and 1.7.0. I've attached a ZIP file with all the crash reports. The world save is too large for GitHub, but in case it helps, I can upload it elsewhere. If there is anything else I can do to provide more information, let me know.

(The hardware is a dedicated server with four AMD EPYC CPU cores and 16G RAM which usually runs the server at ~15ms per tick so I do not suspect hardware performance to be an issue — especially since we ran FTB Revelation on it earlier this year just fine

#### Crash reports

[1.6-crashes.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7526890/1.6-crashes.zip)
[1.7-crashes.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7526887/1.7-crashes.zip)

#### Debug logs

[1.6-debug.log.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7526903/1.6-debug.log.txt)
[1.7-debug.log.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7526904/1.7-debug.log.txt)

**Comment by Raidobw2** [comment]
Thanks for the info, we'll try and sort that out soon, the error is a bit peculiar so it's not easy to find the cause. I've checked the linked issue and just so you are aware, the current branch for Spark on github is probably for Minecraft 1.17. This MC version had a huge change in Java and exclusively uses Java 16+. Minecraft before 1.17, such as 1.16.5, uses Java 8, 11, sometimes 16.
On the CurseForge page, which is were you normally get the mods, you'll find different Spark releases and even more with the Files tab at the top. (https://www.curseforge.com/minecraft/mc-mods/spark).
A view from the quick lateral downloads, not all the available files.
![image](https://user-images.githubusercontent.com/17010632/141471777-aa20e7d4-f3a0-4a22-a5de-b2b88923adfb.png)
I see you got it compiled yourself which is amazing! However, I suspect the highlighted version to be compatible with Java 8, since it's for Minecraft 1.16.5 (the version OceanBlock uses) and I've used it in the past while doing tests.
Just some knowledge that might save you some time for the future!

**Comment by TilBlechschmidt** [comment]
Well, thanks for the tip. Totally did not consider checking CurseForge 😅

Anyways, the self-compiled version works like a charm. I'll report back when it yields any results (aka the server crashed again). Question is whether or not Spark auto-uploads the current profile when the server crashes or I have to catch it right as it crashes to stop the profile. Either way, I'll try my best ^^

**Comment by Sunekaer** [comment]
Hey, So we honestly think this is down to the CPU being to slow to handle this modpack, do you have another system with a faster CPU that you can test on?

**Comment by TilBlechschmidt** [comment]
I have to politely disagree. The server is running with a 95-percentile tick time of ~30ms and CPU utilisation of the core used by the Minecraft server is below 40% on average. Our server runs on dedicated cores of a AMD EPYC 7702P 64-Core Processor. While this is a server-chip with a single-core performance that is only around 55% of what desktop-class chips can deliver, profiling and system load monitoring indicates that it is not fully utilised.

Additionally, the symptoms are very short-term and localised. The server runs just fine on average with a maximum recorded tick time of 120ms during a GC cycle with a majority of players online. Just before it crashes, it continuously starts lagging behind over a time period of maybe 30-60sec. From the players perspective, it goes from 20TPS to 0TPS instead of gradually slowing down.

In the report below, collected with spark, you can see that the TPS, tick duration, and CPU utilisation are all well within limits.
![telegram-cloud-photo-size-2-5224287310370160594-x](https://user-images.githubusercontent.com/5037967/141655360-f2f9e2b2-3b2a-4b22-b7ab-3e9a991688c4.jpg)

I am by no means an expert in modding Minecraft, but from my DevOps background I'd consider the (linux) server absolutely healthy with no single core approaching limits. Unfortunately, I do not have any other machine to run the server on. However, in typical fashion it did not crash over the past 48 hours since I've added the monitoring mod.

If there is anything else I can test for or examine, let me know.

**Comment by TilBlechschmidt** [comment]
However, one possibility I can not deny is that our server hoster did some weird shenanigans which resulted in the machine overall slowing down for just long enough so that the Minecraft server would crash. I do not have anything in favour or against this theory though 🤷

**Comment by Sunekaer** [comment]
7792P is still only a 2.0 GHZ CPU, which isnt great for modern minecraft.

**Comment by Raidobw2** [comment]
Hmm. I wonder if potentially all people in this post could be using online hosts, and that this could be the results of lag spikes which can happen at times.

I've especially had that problem with hosts that share CPU between instances, but I've never experienced crashes because `max-tick-time` is always set to `-1` to prevent lag spike crashes for that matter (it has happened before I started using it on online hosts back then, hence why I'm using it now!).

We have not heard from the original user in a while and all issues seem semi-random. Some crash reports are mentioning Sheeps, other Zombies or Horses to cause lag, but all mention the watchdog (aka Lag Watcher). We cannot replicate it as well... therefore;
If I can get confirmation from people on this post that haven't answered yet:
- Are you using an online host?
- Did setting `max-tick-time=-1` in `server.properties` solve the issues?
- Did you speak with your hosts to know if the CPU had been experiencing stress when crashes occur? (yes, if you pay for it you should be able to ask for that info).

Based on the answers, I could potentially close this issue, as all seems to point at lag spikes. Thanks in advance for anyone who will be responding.

P.S.: If your players are using Blessed or Cursed earth farms, chunkloaded and on 24/7 I'd expect the CPU to try and catch a break at some point (stacktrace mentions Sheep, Zombie and Horse). I'd recommend shutting those farms off when you don't need them and observing the server's behavior after setting `max-tick-time`.

**Comment by Elliona** [comment]
- Yes, im using an online host
- Yes, i did set `max-tick-time=-1`. The server didn't crash, but the lag was still there.
- I have not, will do next thing in the morning. 
As for the CPU, mine runs at 2.8GHZ.

Hope the info helps.

**Comment by Elliona** [comment]
I can confirm that the CPU was under high load when the major lag spikes occurred. So for me it was most likely that.

**Comment by Raidobw2** [comment]
Thanks for the feedback!

**Comment by JeNoVaViRuS** [comment]
Good day,

I am hosting Minecraft Modpacks on private servers for about 10 years already and this is the first pack I have major issues with. I can confirm the seemingly random high ticks and all the exact behaviour mentioned above (sudden spikes that are gone again immdiately, sometimes it just works with no lags at all, sometimes it lags 2-3 seconds every 30 seconds). My server has 4v Cores of a Ryzen 9 3900X, 16GB RAM and an NVMe SSD. This is not an issue about hardware specs. I also experience crashes with almost the same crash log (except my crash log mentions a PigEntity).

This is the first time I couldn't analyse the source of lags. I just can't pinpoint it at all no matter which chunks I load/unload.

The weird thing is.....if I download the world and start it in singleplayer mode then there seem to be no bad TPS at all (analyzed with spark). Am I missing something? Are the spawn and other players chunks not loaded if I start it in singleplayer mode?

My pack is on version 1.9.0
[crash-2021-11-27_01.05.32-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7610987/crash-2021-11-27_01.05.32-server.txt)
.

**Comment by Raidobw2** [comment]
Hi @JeNoVaViRuS, could it be possible to send us the world download of that server? We'll check and load as many sources of lag as we can to replicate it. We'll have time to test that in about a week, at maximum two, so it won't be an instant fix.

We've tried to pinpoint the error but the stacktraces are so random and it's lag... Could be anything in-game.
However I'll label potential culprits as WYML, RoadRunner, Minecraft Water ticks or MiniUtilities (earths that spawn mobs) -- optimization mods (I think water ticks is vanilla though) and one content mod that as been relatively laggy apparently.

You could try the Observable mod and looking onto Cursed/Blursed/Blessed earth, you'll see what I mean.

Thanks in advance if you send us the world for us to test. If you want to keep it private, you can message me on the FTB Discord (name will be "R3GEN") and send a Google drive link or something.

**Comment by JeNoVaViRuS** [comment]
Hi @Raidobw2,
I have already tried disabling WYML but it didn't have any effect.

I have uploaded the world folder:
[](https://mega.nz/folder/UpJTVKZb#DQgC8T9Ip0sTCa-KvkJoMw)

Thank you very much for taking the time to analyze it!

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue?
If you are, would you be able to upload new log files for us so we can take a further look?
