### ISSUE TITLE
[Bug]: When I walk my character "staggers"

### ISSUE THREAD

**Issue by olivier5874** [FTBTeam/FTB-Modpack-Issues#2112]
### Modpack

FTB Stoneblock 3

### Modpack version

1.3.0

### Describe the bug

when I walk only with my forward key, you can see with the view that the character is moving forward, stopping, moving forward, stopping until I run or move to the left or right

### Steps to reproduce

I only press "z" once.
And I already tried to rebind it it does not work

### Expected behaviour

walking normally

### Screenshots

https://user-images.githubusercontent.com/31547101/203847884-8de99c21-0fb8-41e8-a8eb-cffd12e73e99.mp4

### Additional information

I have the impression that the problem occurred when I looked for the f3+h tooltip but before that I tried several keys since it doesn't work
I tried to rebind my key for advance, deleted the modpack and game files nothing works

**Comment by Raidobw2** [comment]
This might sound like much... but do you have access to a second keyboard you could test this with?

Seeing how you reinstalled the modpack, rebound the key... maybe the issue is with the hardware since I did not have this issue at all (actually I've never seen this all modpacks wide...).

You can also check in Device Manager and uninstall keyboard drivers, then plug your keyboard back in your PC (then start the game). Plugging it into your PC will install some basic drivers again.

If you can do any of this please let me know if the issue seems fixed or not!
