### ISSUE TITLE
[Bug]: IntegratedCrafting Crash

### ISSUE THREAD

**Issue by sgtkwol** [FTBTeam/FTB-Modpack-Issues#215]
### Modpack

FTB Oceanblock

### Modpack version

1.5.0

### Log Files

https://paste.ee/p/4DZN4

### Describe the bug

Causes 60 second tick crash when trying to craft a crafting interface using a crafting interface to a vanilla chest. No machines involved. Works when I use pack version 1.3.0.

### Steps to reproduce

1 connect item interface to storage, logic cable, and crafting interface to a crafting table.
2 setup recipes to break down logs to planks, Pistons, sticky Pistons, etc, and load them into interface
3 attempt to craft
4 crash

### Expected behaviour

No crash

**Comment by Raidobw2** [comment]
@sgtkwol Hello, could you set `max-tick-time=-1` in the server's `server.properties` file and report back here if the issue persists?
Also you can do a `/forge tps` in-game before trying the craft and post the image here.

**Comment by Varzeki** [comment]
I am also experiencing this, both on 1.5 and now on 1.6
1.5 was worse - no crafting was possible at all

Now on 1.6, items can be crafted unreliably

Crash seems loosely tied to amount

Timeline of testing:
-Updated to 1.6
-OK crafting 2 items
-Crashed crafting 2 stacks
-Changed max-tick-time to -1 while server was down
-OK crafting one stack
-OK crafting 2 stacks (despite earlier this causing a crash)
-Crashed when shift clicking item directly into inventory instead of using the UI to specify amount
-Crashed crafting 400 items (using UI again)
  
/forge tps pre craft:
![image](https://user-images.githubusercontent.com/10348132/140483500-d1354738-dd5a-4375-ad09-bb99f9290456.png)

/forge tps during a craft of two stacks (which did not cause a crash):
![image](https://user-images.githubusercontent.com/10348132/140483726-a132dd94-ed5f-4298-80bb-a4b7c2cea59f.png)

Log:
https://gist.github.com/Varzeki/90a6166f995e508eaf20c16b6d85e058

**Comment by Sunekaer** [comment]
Could you tell me if this also is an issue in 1.7.0 of the pack?
