### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by SchlumpfkopfYT** [FTBTeam/FTB-Modpack-Issues#2167]
### Modpack

StoneBlock 3 

### Modpack version

1.4.2

### Log Files

https://pste.ch/akayujisoq.md

### Describe the bug

I join and get kicked again since the update it's like this

### Steps to reproduce

I tried to ask on the FTB discord and there would be no correct deletion

### Expected behaviour

/

**Comment by Sunekaer** [comment]
A lot of broken recipes, try and redownload all the mods and see if that helps

**Comment by RaVenInTheDark** [comment]
The client logs provided don't really give anything useful. Please provide server logs.

**Comment by Raidobw2** [comment]
Does creating a new world work? That would be the first thing to check. If that doesn't work, I'd try downloading a server install from our website https://www.feed-the-beast.com/modpacks/100-ftb-stoneblock-3 and to paste all the server files on top of your client files. (doing this way instead of through the FTB App, since you said you reinstalled already many times).

If the new world works, might be the `serverconfig` folder acting weird or maybe your character's data. The data for your character is in the `level.dat` file that's directly inside the world's folder.

If you wanna test this:
- Copy your current world.
- Take the `level.dat` from the new world you created as a test, paste it onto the copy's files, overwrite that one file.
- Try and enter the copy in the singleplayer menu.

If that works too, then something is corrupted in that original `level.dat` file (from your main world). Add the extension `.txt` to it and drag it here, or put it on Google Drive to share the file here and I can have a look into fixing it without causing progression/inventory loss if I'm able to.

**Comment by SchlumpfkopfYT** [comment]
https://drive.google.com/file/d/1JBVw8t_YE9U2X4TplnjtCntb2cfEjjDc/view?usp=share_link 


This is the level.dat and I also tested it on a single player. Everything loads for me but the world is just black and I can't move


These are the server files all listed https://pste.ch/oyizogiyav.sql
