### ISSUE TITLE
[Bug]: Draconic Evolution Autofeed Module Unusable

### ISSUE THREAD

**Issue by allout58** [FTBTeam/FTB-Modpack-Issues#217]
### Modpack

FTB Oceanblock

### Modpack version

1.5.0

### Describe the bug

I believe the autofeed module from Draconic Evolution is designed to go in the Draconic Helm, but since that doesn't look to be available, could you remove the recipe from the game?

### Steps to reproduce

1) Craft Auto-Feed module
2) Attempt to put in chest piece (only available DE armor)
3) See it not be allowed in the chestpiece

### Expected behaviour

Craftable items should be usable

**Comment by Raidobw2** [comment]
To dev: Either await mod update or remove from JEI.
Removing from JEI will require you to revert the changes once the mod updates, so maybe this instead:

Add a lore note onto the item to tell that this feature has no been implemented yet.

**Comment by weszhuang** [comment]
Currently on OceanBlock 1.8.0 and the issue seems to be already resolved as I have been using it fine. Shouldn't this be closed as it works fine in the chestplate as of currently.

**Comment by Raidobw2** [comment]
You're absolutely right, it does work, I've never tested it until now. Closing this since the mod works properly, and autofeeds the player. Thank you!
![image](https://user-images.githubusercontent.com/17010632/143514210-869dffaa-c3d3-41f0-bbc6-decbdd01c269.png)
![image](https://user-images.githubusercontent.com/17010632/143514157-1ed89f0a-0504-45e0-9262-33d9d8a26b43.png)
