### ISSUE TITLE
[Bug]: Screen turns black when holding Items

### ISSUE THREAD

**Issue by MS206206** [FTBTeam/FTB-Modpack-Issues#2176]
### Modpack

FTB Infinity Evolved

### Modpack version

1.7 3.1.0

### Describe the bug

Anytime I try to hold an item in my hands the screen turns black. Sometimes it turns to other colours like blue or white but mostly black. If I change back to empty hands the blackscreen disappears and I can see normal. Sometimes there are other bugs following after I hold an item like seeing through a wall for some time then they will disappear too. The issue just occures on my PC. On my old one it does work. They are both running on windows btw. I downloaded Minecraft, the FTB App and the 
modpack multiple times
### Steps to reproduce

Try to hold an item in Minecraft Infinity Evolved

### Expected behaviour

Screen turns black

**Comment by 5ully** [comment]
Do you have 2 GPU? Im guessing one of them is a Intel GPU? This is probably gonne fix itself if you switch what GPU ur PC is using for minecraft. Its not really something we can fix since it is an issue created by Intel dropping support for old stuff.

**Comment by MS206206** [comment]
Hey 5ully thx, that was the problem. Now it's working as it should :)

**Comment by Raidobw2** [comment]
I see 5ully's got it :) I'll eventually get to make docs to help with that, for now the info is a bit scattered.
For others having this problem and coming here, see https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1929#issuecomment-1334893829 and make java use your dedicated GPU, or ask us in the [FTB Discord](https://go.ftb.team/discord) for help.
I'll be closing this then, since that seems fixed. Have fun!
