### ISSUE TITLE
Cant Interact with inventories or place blocks

### ISSUE THREAD

**Issue by Minerofthedark** [FTBTeam/FTB-Modpack-Issues#2231]
### Modpack

FTB StoneBlock 3

### Modpack version

1.18.2

### Describe the bug

I was doing fine until I used the chisel mod, I held a chisel and a bit bag, and I used the plane setting to destroy a wool block into bits, after that I was unable to place blocks, interact with blocks, interact with doors/trapdoors, or use items with inventories. I have removed the rechisled mod and restarted my game twice and the issue still persists. The game never crashed btw.

### Steps to reproduce

I mentioned how it happened in the description, but I don't have any files pertaining to the issue.

### Expected behaviour

I expected to be able to collect several blocks with chisel and use the bit bag to sort and hold them.

### Additional information
I may just go to a save from 12 hours ago but ill leave this here in case someone can find out what happened.
(UPDATE) the backup save from before the issue did not work, the issue persists through.
I used the mine together chat to try and ask for help but was mostly just ignored so I came here.

**Comment by Rider7417** [comment]
I am having a similar problem it just randomly started happening and every time that I open my inventory my game crashes and it's happened in every world that I have made since

**Comment by Raidobw2** [comment]
Hi, I've tried reproducing the issue, but unfortunately all works. I'm able to break a wool block with the chisel, and it places the bits inside the bag as well.

After that I can still break blocks, place blocks, and open machine user interfaces.

Also, Rider 7417, I've done today a bunch of inventory fixes that targeted crashes.

Next week we'll release 1.6.0 which should fix some issues. Since the pack version was not written exactly and this report has some time on it already, it might have been an issue in older versions of the pack, so I'll assume they have been fixed since I do not seem to be able to reproduce them. The pack version is 1.4.2, 1.5.0 for example. 1.18.2 is the Minecraft version! Confusing, but you'll know for next time 🙂 thanks for reporting in any case, I got to doublecheck those issues at least!
