### ISSUE TITLE
[Bug]: IE and Thermal sawmill missing recipe compared to Mekanism sawmill

### ISSUE THREAD

**Issue by sarim** [FTBTeam/FTB-Modpack-Issues#226]
### Modpack

FTB OceanBlock

### Modpack version

1.5.0

### Describe the bug

IE and Thermal Sawmill has less recipes than Mekanism sawmill, And IE and thermal has some that are missing from Mekanism sawmill. See below for recipe count.

I actually stumbled upon this when trying to find way to make coal in JEI. A recipe showed up -> **Torch(4) => Stick + Coal**. IMO there should be a way to mass produce coal easily, maybe a recipe to convert it from charcoal? While as fuel coal and charcoal is equivalent there are quite a few recipes where only coal is accepted. Should I create another issue for this?

### Steps to reproduce

1. Open JEI
2. Look up usage of IE, Thermal and Mekanism Sawmill.
3. Mekanism Precision Sawmill has 41 recipes. Looks like I has many recipes for wood based products like door, fence, bed etc... But missing log => plank recipes for modded wood types.
4. Thermal Series sawmill is missing those wood based product recipes. Though It has modded logs recipes.
5. IE sawmill is missing some modded logs recipes, also missing those wood based products recipes.

### Expected behaviour

All sawmill has same functionalities. Able to produce all items.

**Comment by Raidobw2** [comment]
Thanks for the reports. The modpack developer will look at those.

As for coal, you can already mass produce it: seeds, sluicing, botania catalysts, laser drills, etc.
If you look at the torch recipe, it can already take charcoal. Using them in a sawmill would indeed convert your charcoal to coal for your case. I suggest you look at the other torch recipes as well.
![image](https://user-images.githubusercontent.com/17010632/139659232-e7cf4889-26b0-4bfa-9748-40974b876a09.png)


As for sawmill functionalities, usually mods implement what they feel is right for their mods. Our modpack dev will look at it when he gets the time as unification is always an issue in modpacks.
![image](https://user-images.githubusercontent.com/17010632/139659604-8340dc48-f4dc-45b4-afcf-2d2b7a9fd36c.png)
For example, Mekanism's sawmill doesn't use the "minecraft:logs" tag, while Thermal probably does. They each do their own integration with other mods as well -- for example Thermal processes Menril wood despite it being only tagged specifically for Integrated Dynamics, Mekanism doesn't do that integration.
I'll leave that to the modpack dev's discretion as that can get time consuming since he'll have to implement all modded wood probably one by one.

**Comment by Sunekaer** [comment]
Ill add the log -> stripped -> plank, but i wont be copying all the others.
