### ISSUE TITLE
Sudden Crash

### ISSUE THREAD

**Issue by WanweiInMod** [FTBTeam/FTB-Modpack-Issues#2263]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.2

### Log Files

Link：https://pan.baidu.com/s/1u-SEyA1aMmIEbS7b1AVHOw?pwd=0000 
Password：0000

### Describe the bug

When loading game data, suddenly reload resource pack then crash.
But some hours ago it can be loaded correctly.
The report said it may caused by "Better than Llama" mod.

### Steps to reproduce

1.Launch game
2.Waiting for data loading
3.Auto reloading resource pack (unexpected)
4.Game crash and exit

### Expected behaviour

Complete loading and show menu.

### Additional information

Maybe there's some trouble reading the log cause I use Chinese :(

**Comment by andrewjbennett** [comment]
This bug is from "BetterThanLlamas", which has an "Easter Egg Day" on the 1st of April and 9th of December (with a bug that prevents the game from loading). You can work around it by changing your computer's date, waiting until tomorrow to play, or just removing the mod entirely. 

https://github.com/iChun/BetterThanLlamas/issues/3

**Comment by manmaed** [comment]
Duplicate of #2269
