### ISSUE TITLE
Make an FTBOres mod similar to AllTheOres, to pre-unify ore/ingot recipes

### ISSUE THREAD

**Issue by DizzyDJW** [FTBTeam/FTB-Modpack-Issues#2311]
### Modpack

FTB Presents Direwolf20 1.19

### Is your suggestion related to a problem? Please describe.

Not much more to say than the title.

FTB modpacks need a Unifying mod made for all packs similar to how ATM team made and uses AllTheOres to have oredict and ore unification, preset and pre-determined.

Would save TONS of time on future modpacks.

I mention this because this modpack has so many issue with ores, ingots, and raw resource recipes.

All recipes that typically multiply ores are still using vanilla ore blocks when raw ores have been out for several versions now.

Create needs vanilla ore blocks for the Crushing Wheels.
Integrated Dynamics needs vanilla ore blocks for the Squeezers.
Cyclic needs vanilla ore blocks for the Macerator.
The list goes on.

### Mod suggestion

Similarly, there'd be no harm adding AllTheOres to the pack in the meantime to fix the MANY issues with ore and ingot recipes.

**Comment by Hazmatik** [comment]
The ore multiplying recipes are still using the ore blocks because the raw ore drops are effected by fortune and therefore would be really broken to have 1 raw ore be doubled when you can get 10+ raw ores from one ore block with the right level of fortune. Other mods like Thermal and Mekanism have adopted a 33% chance for an extra dust from processing the raw ores. What an ore unification mod would help with is the fact that Osmium can't be processed in a pulverizer, or that Bauxite and Zinc can't be processed in an enrichment chamber, etc. This is my biggest issue right now is that I have to set up multiple different ore processing setups depending on what mod the ore is from.

**Comment by Saereth** [comment]
we have something like this planned, no eta though
