### ISSUE TITLE
Inventory Crash 

### ISSUE THREAD

**Issue by Rider7417** [FTBTeam/FTB-Modpack-Issues#2328]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.3

### Describe the bug

Every time when I load up my game it lets me in to my world and runs a little slowly but still works fine but when ever I open something with an inventory my game freezes than crashes 

### Steps to reproduce

Load up world and open anything with an inventory 

### Expected behaviour

I can open my inventory

**Comment by Raidobw2** [comment]
I've fixed multiple crash occurrences today, mostly with inventory recipes/uses and moving items around in crafting tables. I assume I've fixed this, since I'm not experiencing that issue in development.

If you still experience this, please add a crash log, it will be helpful to me for debugging the problem further. Thanks!
