### ISSUE TITLE
Ran out of memory issue

### ISSUE THREAD

**Issue by TheLittleDude** [FTBTeam/FTB-Modpack-Issues#2352]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.2

### Describe the bug

For some reason no matter how much ram I allocate to this modpack, it gives me a ran out of memory error. I have allocated 7gbs which should be enough. I have linked it to a memory leak issue but have no idea how to fix it. 

### Steps to reproduce

1. Load up Stoneblock 3
2. Enter world
3. wait about a minute with f3 menu up
4. memory slowly creeps up to limit until it freezes
5. ran out of memory error
6. memory still doesn't go back down and crashes the game

### Expected behaviour

memory shouldn't be climbing, it should be offloading and keep stable.

### Additional information

Same problem on 1.4.3, on servers, and singleplayer.

**Comment by Raidobw2** [comment]
Hi, if the game crashes, you will find crash logs inside the `crash-reports` folder inside the modpack instance. These would be useful to have to identify the cause in order to fix it.

Also, how much memory is installed on your computer? How much is free when you load the game? Allocating 7GB still requires the operating system to have at least 7GB free in Task Manager, for example. Let me know how much memory you have free and thanks!

Also feel free to post screenshots, that can help as well 🙂
