### ISSUE TITLE
After attempting to use Create's Schematic Cannon, server constantly crashes and fails to start again.

### ISSUE THREAD

**Issue by Dan-Mizu** [FTBTeam/FTB-Modpack-Issues#2364]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.3

### Log Files

https://pastebin.com/EGcbk5nj

(All log files have the same error)

### Describe the bug

I run a Stoneblock 3 server. Has been running perfectly fine. I am now in the endgame (only need to automate polonium and ethereal slates) and was trying to move one of my machines with the schematic feature in Create but when I tried to use the Schematic Cannon it crashed the server, and now it fails to startup producing the same crash log every time.

### Steps to reproduce

Craft Schematic Cannon
Place Schematic in the Schematic Cannon
Press the "play" or "start" button on the Cannon.
Server should crash, and continue to crash everytime it tries to start up.

### Expected behaviour

I expected the server to stay up and not crash due to the usage of the Schematic Cannon in the Create mod.

**Comment by DinnerBeef** [comment]
Are you able to send the schematic file that is crashing your game, as I am unable to reproduce this on my end?
You can find the schematic files in the "schematics" folder of your instance

**Comment by Dan-Mizu** [comment]
Not sure if it was fixed in a recent update or not as I finished the pack a while ago, but i believe these are the files anyway:
[schematics.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11364017/schematics.zip)

**Comment by LandofHeros2234** [comment]
Do you have any blocks that are NBT dependent placed in the area you saved with the schematic? NBT dependent blocks and Create Schematics don't mix, because Create removes all NBT data from blocks when placing Schematics to prevent duplication of items. Because NBT dependent blocks require NBT data to function correctly, they crash the game when loaded with a Schematic, and continue to do so as long as the chunk where you tried to load the Schematic is loaded. As far as I have seen most other things don't cause problems for Schematics.

**Comment by UnRealDinnerbone** [comment]
Mod have been updated since this issue was made. It this still and issue?
