### ISSUE TITLE
[Bug]: Placing down sluice results in weird position and placing mesh in said sluice crashes game

### ISSUE THREAD

**Issue by KotonoHanako** [FTBTeam/FTB-Modpack-Issues#239]
### Modpack

FTB Ocean Block

### Modpack version

1.5.0

### Describe the bug

Placing the sluice down in any direction results in the sluice turning into a wood texture (if it's not a wooden sluice), facing the wrong direction (the direction of the water does not go down the sled), or both. Placing a mesh in the sluice results in a game crash. 
I play on a server, and my friend is able to place down the sluice and put a mesh in. However on my end the direction of the sluice is bugged too. 
![2021-11-03_15 48 44](https://user-images.githubusercontent.com/81602511/140191567-fc373c1c-ba29-4b39-80b2-c0e729497504.png)
![2021-11-03_15 50 20](https://user-images.githubusercontent.com/81602511/140191581-03c53487-6362-4ca0-b2f7-143064e91c5a.png)

### Steps to reproduce

1. Make a sluice
2. Place it in any direction
3. Place mesh in

### Expected behaviour

crash

**Comment by Sunekaer** [comment]
What the heck, how did you do that?!
could you try on 1.6 of the pack? 
Maybe a video of how you place it

**Comment by minsterxev** [comment]
This is happening in 1.6 as well.  I had previously placed 5 netherite sluices and after the update they were all broken like above and visually looked like diamond sluices.  I was able to break them and they showed up as netherite in my inventory but I crash when attempting to place them back down. It doesn't appear to matter where I place them.  Crash report attached. 

[crash-2021-11-03_18.44.51-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7471206/crash-2021-11-03_18.44.51-client.txt)

**Comment by Raidobw2** [comment]
Do you still have the sluices in your inventory? Please drop your playerdata file that contains your inventory or post a screenshot of it being edited with NBTExplorer. I'm curious to see what kind of tags these sluices have, I'll be testing it quickly too.

**Comment by Raidobw2** [comment]
Actually, my bad, hold the sluice in your hand and type `/kubejs hand` and then copy the text that appears or post a screenshot of it, that'd be appreciated.

**Comment by Raidobw2** [comment]
I'm unable to replicate sadly. I've updated from 1.6.0 to 1.7.0
I've placed a lot of sluices in 1.6.0 in this pattern:
![image](https://user-images.githubusercontent.com/17010632/140237817-8d90ee64-ea7a-46b6-90e3-8cc69e3dc04d.png)
I updated to 1.7.0, then placed the new sluice and meshes:
![image](https://user-images.githubusercontent.com/17010632/140237841-56f4b899-03b1-4a6d-b26a-2a323b196d32.png)
Did a `/kubejs export` on the client (while not connected to a server) and these are the export entries and registries I get:
Tags: `"ftbsluice:sluices":["ftbsluice:oak_sluice","ftbsluice:iron_sluice","ftbsluice:diamond_sluice","ftbsluice:netherite_sluice","ftbsluice:empowered_sluice"]`

Recipes: `"recipes":{"ftbsluice:empowered_sluice":{"recipe":{"type":"minecraft:crafting_shaped","pattern":["DDX","SDX","AAA"],"key":{"S":{"item":"ftbsluice:netherite_sluice"},"D":{"tag":"forge:ingots/netherite"},"X":{"item":"minecraft:diamond_block"},"A":{"item":"minecraft:gold_block"}},"result":{"item":"ftbsluice:empowered_sluice"}},"inputs":[{"item":"ftbsluice:netherite_sluice"},{"tag":"forge:ingots/netherite"},{"item":"minecraft:diamond_block"},{"item":"minecraft:gold_block"}],"outputs":[{"item":"ftbsluice:empowered_sluice","count":1}],"removed":true}}`
Note the presence of "removed:true", but I think that's normal. The normal recipe got changed to this, using scripts:
![image](https://user-images.githubusercontent.com/17010632/140238099-b9caaddc-1cdc-4dd3-a918-efc821bb01a1.png)
And registry entries, items and blocks: `"registries":{"items":"ftbsluice:empowered_sluice"}` and `"registries":{"blocks":"ftbsluice:empowered_sluice"}`.

From the crash-report that was posted here I see: `java.lang.NullPointerException: Registry Object not present: ftbsluice:empowered_sluice`, so I would recommend 2 things:
1. Check the presence of the registry by doing a `/kubejs export` or post the file here so we can check. This will be generated in `kubejs/exported/kubejs-server-export.json` in the modpack folder.
2. Backup all your save data and try a reinstall of the modpack.

It does look like the client is missing those registry entries, but how, that I don't know.
The mod build from the crash is good `ftb-sluice-forge-1.0.8-build.30.jar` but for some reason it looks corrupted since that registry entry is not there.
Maybe it's due to a download problem or the FTB App, and not the mod itself?

Both cases are also using Servers: `Server type: Non-integrated multiplayer server` and `I play on a server`, but => `and my friend is able to place down the sluice and put a mesh in` seems to point at the client.
This means this is probably a client issue related to the mod install, and not a server issue.
Unless your friend and the server didn't get the updated version but only you did!

**Comment by MichaelHillcox** [comment]
@KotonoHanako could you send me your world? If you don't want to put it here, you can send me an email at mikey@feed-the-beast.com. I wanna see if I can replicate the issue as this is concerning but could just be an update issue

**Comment by KotonoHanako** [comment]
Sorry guys, was busy today and wasn't able to quickly answer all your questions. 

> @KotonoHanako could you send me your world? If you don't want to put it here, you can send me an email at [mikey@feed-the-beast.com](mailto:mikey@feed-the-beast.com). I wanna see if I can replicate the issue as this is concerning but could just be an update issue

Given this isn't my world (multiplayer server), do I just ask my friend to send me the world? If yes, which files?


> I'm unable to replicate sadly. I've updated from 1.5.0 to 1.6.0 I've placed a lot of sluices in 1.5.0 in this pattern: ![image](https://user-images.githubusercontent.com/17010632/140237817-8d90ee64-ea7a-46b6-90e3-8cc69e3dc04d.png) I updated to 1.6.0, then placed the new sluice and meshes: ![image](https://user-images.githubusercontent.com/17010632/140237841-56f4b899-03b1-4a6d-b26a-2a323b196d32.png) Did a `/kubejs export` on the client (while not connected to a server) and these are the export entries and registries I get: Tags: `"ftbsluice:sluices":["ftbsluice:oak_sluice","ftbsluice:iron_sluice","ftbsluice:diamond_sluice","ftbsluice:netherite_sluice","ftbsluice:empowered_sluice"]`
> 
> Recipes: `"recipes":{"ftbsluice:empowered_sluice":{"recipe":{"type":"minecraft:crafting_shaped","pattern":["DDX","SDX","AAA"],"key":{"S":{"item":"ftbsluice:netherite_sluice"},"D":{"tag":"forge:ingots/netherite"},"X":{"item":"minecraft:diamond_block"},"A":{"item":"minecraft:gold_block"}},"result":{"item":"ftbsluice:empowered_sluice"}},"inputs":[{"item":"ftbsluice:netherite_sluice"},{"tag":"forge:ingots/netherite"},{"item":"minecraft:diamond_block"},{"item":"minecraft:gold_block"}],"outputs":[{"item":"ftbsluice:empowered_sluice","count":1}],"removed":true}}` Note the presence of "removed:true", but I think that's normal. The normal recipe got changed to this, using scripts: ![image](https://user-images.githubusercontent.com/17010632/140238099-b9caaddc-1cdc-4dd3-a918-efc821bb01a1.png) And registry entries, items and blocks: `"registries":{"items":"ftbsluice:empowered_sluice"}` and `"registries":{"blocks":"ftbsluice:empowered_sluice"}`.
> 
> From the crash-report that was posted here I see: `java.lang.NullPointerException: Registry Object not present: ftbsluice:empowered_sluice`, so I would recommend 2 things:
> 
> 1. Check the presence of the registry by doing a `/kubejs export` or post the file here so we can check. This will be generated in `kubejs/exported/kubejs-server-export.json` in the modpack folder.
> 2. Backup all your save data and try a reinstall of the modpack.
> 
> It does look like the client is missing those registry entries, but how, that I don't know. The mod build from the crash is good `ftb-sluice-forge-1.0.8-build.30.jar` but for some reason it looks corrupted since that registry entry is not there. Maybe it's due to a download problem or the FTB App, and not the mod itself?
> 
> Both cases are also using Servers: `Server type: Non-integrated multiplayer server` and `I play on a server`, but => `and my friend is able to place down the sluice and put a mesh in` seems to point at the client. This means this is probably a client issue related to the mod install, and not a server issue. Unless your friend and the server didn't get the updated version but only you did!

Alright, I'll try to do it tonight or tomorrow.

**Comment by MichaelHillcox** [comment]
Yeah, if you can just ask for a zip of the world folder and send that over, I can have a look. Are you running any extra mods?

**Comment by KotonoHanako** [comment]
> I'm unable to replicate sadly. I've updated from 1.5.0 to 1.6.0 I've placed a lot of sluices in 1.5.0 in this pattern: ![image](https://user-images.githubusercontent.com/17010632/140237817-8d90ee64-ea7a-46b6-90e3-8cc69e3dc04d.png) I updated to 1.6.0, then placed the new sluice and meshes: ![image](https://user-images.githubusercontent.com/17010632/140237841-56f4b899-03b1-4a6d-b26a-2a323b196d32.png) Did a `/kubejs export` on the client (while not connected to a server) and these are the export entries and registries I get: Tags: `"ftbsluice:sluices":["ftbsluice:oak_sluice","ftbsluice:iron_sluice","ftbsluice:diamond_sluice","ftbsluice:netherite_sluice","ftbsluice:empowered_sluice"]`
> 
> Recipes: `"recipes":{"ftbsluice:empowered_sluice":{"recipe":{"type":"minecraft:crafting_shaped","pattern":["DDX","SDX","AAA"],"key":{"S":{"item":"ftbsluice:netherite_sluice"},"D":{"tag":"forge:ingots/netherite"},"X":{"item":"minecraft:diamond_block"},"A":{"item":"minecraft:gold_block"}},"result":{"item":"ftbsluice:empowered_sluice"}},"inputs":[{"item":"ftbsluice:netherite_sluice"},{"tag":"forge:ingots/netherite"},{"item":"minecraft:diamond_block"},{"item":"minecraft:gold_block"}],"outputs":[{"item":"ftbsluice:empowered_sluice","count":1}],"removed":true}}` Note the presence of "removed:true", but I think that's normal. The normal recipe got changed to this, using scripts: ![image](https://user-images.githubusercontent.com/17010632/140238099-b9caaddc-1cdc-4dd3-a918-efc821bb01a1.png) And registry entries, items and blocks: `"registries":{"items":"ftbsluice:empowered_sluice"}` and `"registries":{"blocks":"ftbsluice:empowered_sluice"}`.
> 
> From the crash-report that was posted here I see: `java.lang.NullPointerException: Registry Object not present: ftbsluice:empowered_sluice`, so I would recommend 2 things:
> 
> 1. Check the presence of the registry by doing a `/kubejs export` or post the file here so we can check. This will be generated in `kubejs/exported/kubejs-server-export.json` in the modpack folder.
> 2. Backup all your save data and try a reinstall of the modpack.
> 
> It does look like the client is missing those registry entries, but how, that I don't know. The mod build from the crash is good `ftb-sluice-forge-1.0.8-build.30.jar` but for some reason it looks corrupted since that registry entry is not there. Maybe it's due to a download problem or the FTB App, and not the mod itself?
> 
> Both cases are also using Servers: `Server type: Non-integrated multiplayer server` and `I play on a server`, but => `and my friend is able to place down the sluice and put a mesh in` seems to point at the client. This means this is probably a client issue related to the mod install, and not a server issue. Unless your friend and the server didn't get the updated version but only you did!

![2021-11-05_10 43 00](https://user-images.githubusercontent.com/81602511/140538219-bb4c1460-7aa4-4d09-b5fe-77405a08e0c7.png)
https://streamable.com/4vw6jk
I cannot run the `/kubejs export` on the server, probably because commands are off?
Strangely if I try to replicate the issue in a single player world, everything is placed down normally and I can put a mesh into it.

**Comment by MichaelHillcox** [comment]
My only assumption here is that you've got another mod doing something weird.

**Comment by KotonoHanako** [comment]
> My only assumption here is that you've got another mod doing something weird.

https://drive.google.com/file/d/1LgfDjChMIa_ltSzmnQBQXtzALG5I1zhj/view
Here is the world file.

**Comment by Raidobw2** [comment]
Just dropping this here since I'm seeing some connections. Had a case in the FTB Discord about that and also on other updates before. This might be due to the FTB App update mechanism, I'm not sure. To be determined.
Basically:
![image](https://user-images.githubusercontent.com/17010632/140601650-b0ed0bd3-0818-4aef-94b3-cc6115789b16.png)
They had that same weird issue and crashes, and since a registry was missing from their game but not mine from a fresh install, I assumed something might have broke in the download/install stage.
The summary is to backup your worlds and to clean reinstall the clients on 1.6.0 (I would have said 1.5.0 but it got updated again!😃 ). My guess is your client is missing that registry from the server, which would also explain why it works in Singleplayer. You could clear the `.localCache` folder in your instances folder before reinstalling just to be sure it's "clean" too.

As for the red X message, I'll leave Freebi85, another modpack developer explain that to you, their explanation is very good:
![image](https://user-images.githubusercontent.com/17010632/140601738-ad28c4a2-3d66-47f0-af5c-f95bfee94e9e.png)
Hoping that helps and please try clean installing clients and reporting back here :)
We'll forward it to App devs if it's a FTB App issue :o

**Comment by KotonoHanako** [comment]
> Just dropping this here since I'm seeing some connections. Had a case in the FTB Discord about that and also on other updates before. This might be due to the FTB App update mechanism, I'm not sure. To be determined. Basically: ![image](https://user-images.githubusercontent.com/17010632/140601650-b0ed0bd3-0818-4aef-94b3-cc6115789b16.png) They had that same weird issue and crashes, and since a registry was missing from their game but not mine from a fresh install, I assumed something might have broke in the download/install stage. The summary is to backup your worlds and to clean reinstall the clients on 1.6.0 (I would have said 1.5.0 but it got updated again!smiley ). My guess is your client is missing that registry from the server, which would also explain why it works in Singleplayer. You could clear the `.localCache` folder in your instances folder before reinstalling just to be sure it's "clean" too.
> 
> As for the red X message, I'll leave Freebi85, another modpack developer explain that to you, their explanation is very good: ![image](https://user-images.githubusercontent.com/17010632/140601738-ad28c4a2-3d66-47f0-af5c-f95bfee94e9e.png) Hoping that helps and please try clean installing clients and reporting back here :) We'll forward it to App devs if it's a FTB App issue :o

Ok. If I were to clean install, what files should I save, stuff like settings?

**Comment by KotonoHanako** [comment]
Now to add to this mess, a friend that plays with us (not the server owner) also has their sluices facing weirdly. I've asked them to replicate my issue on the server.

**Comment by Raidobw2** [comment]
Take in backup the `local` and `saves` folder as well as `options.txt` to keep keybindings.

According to #268 this is caused by an outdated server, and I thought it was client only...

If you can try and narrow that out and see on which side the problem is that would help me greatly in giving the right solution in the future.

Try updating the server to 1.6.0 first, then join. If that works, that's outcome 1.

If you still crash,  delete the `.localCache` folder in your instances folder and reinstall the modpack, after having backupped the files I mentioned above for the client. Then join the up-to-date 1.6.0 server with the brand new client. If that works, that's outcome 2.

If those two didn't work => outcome 3 and we need to do research, I don't have an immediate solution.

Please let me know what was the outcome of those operations, I expect it to work mostly at 2.

**Comment by KotonoHanako** [comment]
Sorry for taking so long. currently I am deleting the modpack (after saving local and options.txt), and reinstalling to 1.5.0 (server owner hasn't updated yet).
I will try and reproduce the sluice placing and mesh placing in.

**Comment by KotonoHanako** [comment]
OK, everything is all fine. Just had to uninstall the modpack, reinstall, update to 1,6.0, go to bed and wake up to discover that it updated to beta 1.7.0, then _downgrade_ to 1.5.0, and the sluices appear normal, and they let me place a mesh in without crashing. Yay!

![image](https://user-images.githubusercontent.com/81602511/140983864-97a91f28-ed12-459d-88da-cc86ec91fb31.png)

Now another issue but not as game crashing, how do I extend the JEI wider, and have the search below my inventory?

**Comment by Raidobw2** [comment]
You won't like that one. You need to update to 1.7.0, see #155 for reference. It might be wise to clean install 1.7.0 by clearing `.localCache`, and then updating your server as well. Effectively killing two birds with one stone, this issue, and your JEI problem.
Backup worlds on client/server at all times during the process.
