### ISSUE TITLE
Cannot join singleplayer world due to multiplayer issue

### ISSUE THREAD

**Issue by Unexian** [FTBTeam/FTB-Modpack-Issues#2397]
### Modpack

FTB Plexiglass Mountain

### Modpack version

1.2.4

### Describe the bug

I literally cannot join my single-player worlds.
When I try to join, it gives me an `Invalid player data` error.
I think this error is only supposed to show up on multiplayer worlds.

### Steps to reproduce

I have no idea how to reproduce the issue
All I know is I was using a fresh install on GDLauncher.

### Expected behaviour

I join my singleplayer world

**Comment by Raidobw2** [comment]
Please see https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1039 and consider using the [FTB App](https://go.ftb.team/app) to support us. The FTB App will solve the issue as well since it will use absolute paths instead of relative paths, which is what is causing the problem in the Capsule mod (which gives you that `Invalid player data` error).
