### ISSUE TITLE
Refined Storage + JEI lag when recipe uses ore dictionary  

### ISSUE THREAD

**Issue by fbigummy** [FTBTeam/FTB-Modpack-Issues#2426]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.4

### Describe the bug

When in the refined storage system and you look at a item/blocks recipe if that item/block uses ore dictionary (e.g. can use a variety of planks to craft) The game becomes incredibly laggy 

### Steps to reproduce

1. Open a refined storage grid 
2. look at an item recipe for example a chest 
3. Game becomes laggy  

### Expected behaviour

No difference in performance to other recipes

**Comment by ChemistForTehWin** [comment]
This also happens when using Wireless Crafting Grid of any sort. 
Although, i would say it appears not when you look at ANY recipe, no. For me, it's when i lookup possible recipes using U (for default hotkeys). If i save recipes outside the Crafting Grid withing the JEI window (using A button), that specific recipes cause no problem in Crafting Grid.

**Comment by Saereth** [comment]
I can't reproduce this on version 1.1.0 please reopen if you're still having this issue
