### ISSUE TITLE
[Bug]: Flux networks , network disconects client on Lan server

### ISSUE THREAD

**Issue by zxn3** [FTBTeam/FTB-Modpack-Issues#247]
### Modpack

FTB OceanBlock

### Modpack version

1.5.0 & 1.6.0

### Describe the bug

We are playin in a LAN server ( opened wit comand "/publish 25565" ), with a network from the mod Flux NetWorks created and running the other players (not host), can´t log in ( log in , log out  in chat  ,  the get a logout message "disconected"), when the netowrk is deleted they can join in . .  If a new network is created  with the player logged in work fine , but when restarting te server it happens again.

### Steps to reproduce

1. Start Lan server.
2. Have a FLux NetWorks running
3. Have a player try to log in to the server.

### Expected behaviour

Player log in successfully

### Screenshots

![Screenshot_1](https://user-images.githubusercontent.com/9337968/140397295-c0c5e418-26c2-4aff-831f-d40c8bd0782e.png)

**Comment by Raidobw2** [comment]
Is it possible to have the snippet of their latest.log when they join your server, as they get disconnected? The reason should normally be written there. You can doublecheck their log snippet and remove the IP addresses that show in there, if there are any, for your privacy (there is one usually when the client establishes the first contact with the server).

You can use https://paste.feed-the-beast.com/ to upload that snippet of the log, otherwise our devs will try and reproduce it on LAN when they get the time. This would speed it up a bit and would be appreciated!

**Comment by zxn3** [comment]
This is te sipet form de client that gets disconnected from the server https://paste.feed-the-beast.com/view/1195a199.
And this one is form the host client ( the one that opens to lan ) https://paste.feed-the-beast.com/view/853d416f.

**Comment by zxn3** [comment]
This is te sipet form de client that gets disconnected from the server https://paste.feed-the-beast.com/view/1195a199.
And this one is form the host client ( the one that opens to lan ) https://paste.feed-the-beast.com/view/853d416f.

**Comment by Raidobw2** [comment]
Hmm thanks, we'll look into it, that's a network issue it looks like.

I'm curious if using a more recent version of Java will fix this, since it's a netty issue.
For Windows, use https://www.java.com/en/download/manual.jsp to install Java 8 64 bits.
![image](https://user-images.githubusercontent.com/17010632/140601177-403dada7-5388-42bb-b391-628b90af0ece.png)
For Linux and MacOS you can get Java 8 64 bits from there or on Adopt OpenJDK's site for example.
Once that's installed, add `-version:1.8+` in the modpack's "JAVA RUNTIME ARGUMENTS" on the FTB App, or in any other launcher you use (JVM arguments).
Then start you game and ask your friend to connect. You both must use the most recent version of Java, by following this mini procedure.

I'm unsure that'll work, if it doesn't we'll have to dig some answers probably, since right now I'm otherwise in the dark.

**Comment by zxn3** [comment]
We both tried update java to the lates version (1.8.0_311) and the error still persist. 

![image](https://user-images.githubusercontent.com/9337968/140603694-16d1f070-d16d-42cb-873d-6b7adf50ebfe.png)

**Comment by Raidobw2** [comment]
Ok, thanks for getting back to me. The devs will look into that in LAN when they have the time. This depends on the availability of 2 devs at the same time and same place, and happens at times but it might take some time, be aware of that.

As a solution for now, you can try installing a local server and booting it up, and connecting to it.
- Get the files from https://www.feed-the-beast.com/modpack/ftb_oceanblock in the "Server Files" tab.
- Create a new folder for your server (e.g. Oceanblock_Server) and put the installer from your Downloads inside.
- Follow this procedure to install the server: https://help.ftb.team/help/en-gb/1/73
- Once the server is started, use a cmd prompt and type in `ipconfig`. Note the ipv4 field value (192.168.X.X)
- Pass that ip to your friend, they will enter it with the port in multiplayer: e.g.: `192.168.1.12:25565`. This is the address for them.
- You connect to the server using the ip and port: `localhost`, since you host it from your computer.

To add your Singleplayer world:
- You can open `server.properties` with Notepad and change `level-name` to match your world's name.
- Take your world from Singleplayer and put it in the server files, at the same place the `world` folder originally was in the server.
- Boot the server again and everything should be like last time, and hopefully it works. In that case, cheers.

**Comment by zxn3** [comment]
"...   This depends on the availability of 2 devs at the same time and same place ... "
We are opening it to LAN but we are not in the same local network , 1 person open to lan an with a public ip the other person connects ( with DMZ an port opening in the router ).

**Comment by Raidobw2** [comment]
Alright, thanks for the info. I still recommend you try with an actual server instead of LAN for the meantime, as that debugging can take us some time (unless you'd rather remove FluxNetworks instead).

You'd replace all local ips with public ips in my small procedure, the way to install it is very similar. We'll look into this as time allows!

**Comment by kane-thornwyrd** [comment]
Also crash on Arch Linux host with Linux Mint and Fedora clients.

**Comment by kane-thornwyrd** [comment]
Also, as a temporary measure I tracked down, in survival, every flux network points, plugs and energy storage and I replaced them with tesseracts and powah alternatives.

**Comment by Raidobw2** [comment]
I can confirm that this is a mod issue. We had another case in the FTB Discord and the user removed Flux Networks and their friend could join again. Thanks all.
Other log info: https://paste.feed-the-beast.com/view/6c5ea462
With that same error
`[Netty Server IO #10/ERROR] [net.minecraft.network.NettyPacketEncoder/]: Error encoding packet io.netty.util.IllegalReferenceCountException: refCnt: 0`
This happened for the user using MineTogether connect, whichs mimics a LAN server, hosted from a singleplayer world.
Reporting to mod author and taking in charge, hopefully this can be resolved for the future.

For those that come across this issue with the same error, use alternatives to flux networks as a workaround for now.

**Comment by Raidobw2** [comment]
Hello, there was an update to FluxNetworks that could fix this. The file is obtainable at https://www.curseforge.com/minecraft/mc-mods/flux-networks/files/3601194. You can replace the one in your clients as well as the one on the server.
For those of you that are still playing and can test this, thank you in advance.
We will be testing this as well with the mod update and probably push another modpack update soon with it.
