### ISSUE TITLE
Crashing when trying to load in Server or Single player

### ISSUE THREAD

**Issue by Romero1021** [FTBTeam/FTB-Modpack-Issues#2479]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.1.0

### Log Files

[latest (1).log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10378809/latest.1.log)

### Describe the bug

Lets Me Log in For One Second and than Game Crashes

### Steps to reproduce

N/A

### Expected behaviour

For it to not Crash

**Comment by Kingpeck** [comment]
I'm seeing similar problems myself.

Running a server that was version 1.0.4, updated that to 1.1.0 and copied over world and configs.

Client is a fresh instance from the FTBApp on 1.1.0 and seeing same things as OP attached latest.log

Client can create and run single player world fine. Joining server gets to last step of Terrain rendering then crashes to desktop. 

Any other info you might need to assist, let me know.

**Comment by markiem32** [comment]
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10386488/latest.log)
[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10386490/console.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10386492/debug.log)

Same problem. Create world or try to join existing one, world loads, terrain loads, and then you might join for a brief moment then crash or it may crash before you even see that.

**Comment by elgreams** [comment]
[log.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10388000/log.txt)
Exact same Problem here with a few people trying to join our recently updated server. Here is on of their logs.

**Comment by MoonStalk** [comment]
Maybe related to a mod containing embedded flywheel code, and some mod since 1.0.4 has introduced the flywheel config file.  as a possible work around, try this: find flywheel-client.toml in configs directory:

changing backend = "INSTANCED" to backend = "OFF"

My crash log
[hs_err_pid5388.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10391836/hs_err_pid5388.log)

**Comment by MoonStalk** [comment]
appears to be related to create, but I could be wrong, as it include flywheel

**Comment by twipsta** [comment]
I ran in to this problem on two machines as well, both with AMD GPUs.
After changing the backend option to OFF, it seems to have solved the issue for both machines. So far I have been in the problematic area for over an hour now.

It seems to be effecting AMD, as the third player on our server has an Nvidia GPU and has had no issues visiting the same area. I know this is only a sample size of 3, but I did also find a ticket open on the Flywheel GitHub with two other people using AMD GPUs
[https://github.com/Jozufozu/Flywheel/issues/168](https://github.com/Jozufozu/Flywheel/issues/168)

I was able to load in to my base fine, but something around the other players base seems to be interacting badly with Flywheel because as soon as I teleported to them I also crashed, but the guy running an Nvidia GPU had no issues at all.
This issue seems to be new as we were able to have hours long sessions in 1.04 without problem, and it started happening immediately after updating. 

All players were in their respective bases and so were in already generated chunks, so I don't think it was any of the newly added mods causing issues. I've been going through the list of updated mods to find differences between my base and the players base causing the crash and they do have a small Minecolonies camp going which I don't, but not much else. This is just a guess tho. I also saw mention of Domum Ornamentum in the java crash log (around line 1989) but I didn't see that in the updated mods list - but I only mention that because there are some barrels around the base from that mod which I also did not have.

Here are the log files of the most recent crash, hopefully it may help narrow things down.
[2023-01-12-2.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10395926/2023-01-12-2.log)
[debug-2.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10395928/debug-2.log)
[hs_err_pid2836.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10395932/hs_err_pid2836.log)

**Comment by markiem32** [comment]
#Moonstalk Your workaround worked for me. Saw it in another thread and came here to tell people about it, lol.

**Comment by CaptRenault** [comment]
Another AMD user checking in to say that the flywheel config change has also fixed my problem. Haven’t played much to test it, but I will update y’all if anything changes.

**Comment by Marfjeh** [comment]
I suspect that it is probably an AMD Driver issue.
I explained my findings in: https://github.com/Jozufozu/Flywheel/issues/168#issuecomment-1379995675

**Comment by CaptRenault** [comment]
Hello!

Greatly appreciate your quick response!  I tried setting the flywheel
config you mentioned to BATCHING and that also resulted in crashing for
me.  However, setting it to OFF does work for me.  Hopefully this helps
other folks as well.

Thank you for your time!
Alec

**Comment by Marfjeh** [comment]
Yup, Off is indeed the most stable. :p

12 Jan 2023 19:22:53 CaptRenault ***@***.***>:

> Hello!
> 
> Greatly appreciate your quick response! I tried setting the flywheel
> config you mentioned to BATCHING and that also resulted in crashing for
> me. However, setting it to OFF does work for me. Hopefully this helps
> other folks as well.
> 
> Thank you for your time!
> Alec
>

**Comment by Saereth** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2490
