### ISSUE TITLE
Duplicated itens in Extreme Crafting Table from Avaritia

### ISSUE THREAD

**Issue by Paxtel-code** [FTBTeam/FTB-Modpack-Issues#2496]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Describe the bug

When crafting complex itens like transmutation tablet or any part of the infinity armor or weapons, some of the itens remaings in the crafting part, instead of being completely used

### Steps to reproduce

1. Open extreme crafting table
2. copy recipe from JEI
3. craft the item

### Expected behaviour

All itens being used and recieve the crafted item

### Screenshots

https://user-images.githubusercontent.com/73308247/212119697-c7c6807a-8a60-42a6-844d-c3f5d44096f6.mp4

**Comment by BrettMoan** [comment]
Can confirm, that I see this bug as well. https://imgur.com/a/3PjvCCm I don't know if @Paxtel-code is on SP or MP, but I am on a MP server, so that may be a part of the issue.

additionally, it appears the table is only duping when  `<shift> + <right click>` the left over items. if i try to right click the remaining items, they will disappear.

**Comment by Gamoranin** [comment]
Can also confirm, still exists in v1.6.1 Am on a MP server.

Clip of the dupe:
https://clips.twitch.tv/FrailMiniatureCatEleGiggle-ijC_aJWdePUYUeUV

If you leave the table and come back, it will dupe endlessly. If you pull it out twice, the second time will use the ingredients.

**Comment by Sunekaer** [comment]
#1903
