### ISSUE TITLE
Pity machine frame game crash

### ISSUE THREAD

**Issue by GaliWest** [FTBTeam/FTB-Modpack-Issues#2534]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Describe the bug

When I place a Pity Machine Frame in a crafting station, exit the crafting menu and try to re-open the crafting menu for the crafting station, my game crashes.

### Steps to reproduce

1. Make a pity machine frame
2. Place it inside of a crafting station from tinkers construct
3. Exit the crafting menu of the crafting station
4. Right click the crafting station

### Expected behaviour

My game wouldn't crash

**Comment by GaliWest** [comment]
Something else; interacting with the Pity machine frame (checking the recipe or uses with JEI (whatever its called)) crashes my game

**Comment by Raidobw2** [comment]
Most likely due to IE's shader grabbag recipe;
Open `kubejs/server_scripts/mods/immersiveengineering.js` with Notepad and before the last `});` insert this:

```
//Fix the Shader Grabbag recipe interactions causing a lot of crashes
//by removing recipes, then manually re-adding them
//https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2464
//https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2583
event.remove({ type: "immersiveengineering:shader_bag" });
event.shapeless("immersiveengineering:shader_bag_common", "immersiveengineering:shader_bag_uncommon");
event.shapeless("immersiveengineering:shader_bag_uncommon", "immersiveengineering:shader_bag_rare");
event.shapeless("immersiveengineering:shader_bag_rare", "immersiveengineering:shader_bag_epic");
event.shapeless("immersiveengineering:shader_bag_epic", "immersiveengineering:shader_bag_ie_masterwork");
```

![image](https://user-images.githubusercontent.com/17010632/214729219-522b4690-9c8f-4ef0-8986-73a5a4460949.png)

You can do this while in-game if you want, just type `/reload` afterwards and wait about a minute and it should be solved.

You can let me know if that worked, I'll appreciate it for sure. Until then, i'll assume that was the issue, thank you for reporting :)

(in-dev both the crafting station & checking uses/recipes for pity machine frame no longer crashes! But I do have some other fixes in as well. This will be SB3 v1.6.0 for next week)

**Comment by SamPlews** [comment]
Cheers, I was experiencing the problem and it fixed it for me.
