### ISSUE TITLE
[Inventory Management] Ctrl+Shift+Click causes odd behaviors

### ISSUE THREAD

**Issue by 2ndRecon** [FTBTeam/FTB-Modpack-Issues#2560]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.0.0

### Log Files

N/A

### Describe the bug

Case 1 - Making torches - Place a stack of coal inside the 2x2. Place LESS than a stack of sticks. Shift+Click the result of craft (torches).. ALL the possible torches you can craft will go into your inventory AND the craft will continue to use any surplus coal to make 'black dye'.

Expected result - The result of the torch craft should halt any further crafting in the 2x2

Case 2 - Using Ctrl + Shift + Click causes all armor and items to unequip. 
Duplicate - I regularly use ctrl+shift+click to dump my inventory into a chest, for instance. Using ctrl+shift+click in this pack causes all armor and off-hand items to un-equip.

Expected Behavior - Ctrl+Shift+Click should have NO effect on equipped armor or offhand items. (or toolbar)

### Steps to reproduce

Put on some armor items.

Have some items in inventory.

Place a chest.

Open the chest and attempt to control+shift+click an inventory item to place all items in chest.

Armor will become unequipped.

### Expected behaviour

Armor should not become unequipped unless you manually choose to unequip it.

**Comment by mellamokb** [comment]
Is this modpack dead already?  It's been over two months since this was reported.  I downloaded the pack for the very first time today and after playing for an hour, ran into this issue twice.  Also when I pull charcoal out of a furnace it disappears, and appears to be stuck in the '2x2' crafting area of my inventory, and when I pull it out it goes right back.  Very strange that crafting ingredients can stay in the '2x2' crafting area in the first place, no other modpack I've ever used had that behavior.

**Comment by Gaz492** [comment]
Ive not been able to reproduce this issue on the latest version of the pack, are you able to confirm if you are still having the issue on the latest version of the pack?

**Comment by 2ndRecon** [comment]
> Ive not been able to reproduce this issue on the latest version of the pack, are you able to confirm if you are still having the issue on the latest version of the pack?

Gaz, Sorry just getting back around to taking a crack at this.

I will put some playtime in and report back by this weekend. (2024-07-13)
