### ISSUE TITLE
Quiver arrow dupe bug

### ISSUE THREAD

**Issue by tyler489** [FTBTeam/FTB-Modpack-Issues#2562]
### Modpack

FTB Legend of the Eyes

### Modpack version

1 0

### Describe the bug

When shooting an arrow from a quiver with a crystalline bow, the quiver does not consume arrows. Additionally you can pick up the shot arrows leading to duped arrows of any sort.

### Steps to reproduce

See above

### Expected behaviour

Should be obvious.

**Comment by TheonlyTazz** [comment]
does this only happen with the Crystalline Bow? 

I will need to check this issue later today to see if this is an Quiver (Supplementaries) or a Bow (More Bows: Restrung) issue

**Comment by tyler489** [comment]
Im assuming it happens with all modded bows from that mod, however I am not able to check this week.

**Comment by tyler489** [comment]
I recall something like this being reported previously and it being an issue with the modded bow, not the quiver but I could be wrong.

**Comment by NeRdTheNed** [comment]
Hi, More Bows author here! I'd be happy to fix any incompatibilities with other mods. The known quiver issue was an incompatibility with Nyf's Quivers, which is currently fixed. If there's still mod incompatibilities caused by More Bows, could an issue please be created at https://github.com/NeRdTheNed/More-bows? Thanks!
