### ISSUE TITLE
Cooked items disappear in the brass funnel of Create

### ISSUE THREAD

**Issue by Epicycle23** [FTBTeam/FTB-Modpack-Issues#2575]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.1.0

### Describe the bug

When cooking items like eggs using a fan from create (bulk smoking) the cooked item disappears in a brass funnel setup with an attribute filter (whitelist #c:cooked_eggs).
Tried several other food items and all disappeared e.g. mutton chops.

### Steps to reproduce

1. Setup a belt with encased fans and lava in front and a brass funnel with an attribute filter (whitelist: #c:cooked_eggs) at the end of the belt attached to a chest
2. Put an egg on the belt
3. Wait until the egg is cooked/goes into the funnel

### Expected behaviour

The chest contains the cooked egg/item

### Screenshots
![2023-01-24_20 27 31](https://user-images.githubusercontent.com/11072734/214390013-d799665f-ac67-4853-a560-c55cb7a7fd48.png)

**Comment by TheonlyTazz** [comment]
The issue is not the Funnel, but the blasting itself.

Blasting and Smoking are 2 diffrent things in Create

cobblestone needs to be blasted 
![image](https://user-images.githubusercontent.com/3908847/214616586-0b2e3c29-1017-4726-9e16-a52aa8b49fd6.png)

Food items need to be smoked
![image](https://user-images.githubusercontent.com/3908847/214616731-e71ccf42-8b42-4b34-a42b-6b2594744902.png)
