### ISSUE TITLE
[Bug]: Powah cable bundle crash -- packet too large

### ISSUE THREAD

**Issue by MormonBoy** [FTBTeam/FTB-Modpack-Issues#261]
### Modpack

FTB Oceanblock

### Modpack version

1.#.# (Issue found in 1.3.0 and 1.6.0)

### Log Files

[Uploading latest.zip…]()

### Describe the bug

When getting sufficiently far in the modpack, as per the nature of the modpack, there are a lot of machines, storage systems etc per chunk leading to too much information per chunk.

Internal Exception io.netty.handler.codec.DecoderException: Badly compressed packet - size of 2143243 is larger than protocol maximum of 2097152.

This has now happened to us on 2 playthroughs once we start to get very high level automation i.e. draconic sort of level.

Here is a link to the world folder as the dropbox link
https://www.dropbox.com/s/4bpf98me6z7zseb/world.zip?dl=0

### Steps to reproduce

1. Join World
2. Move to our Island (I don't know the coords as I cant join the world, these can be extracted from my playerdata im sure)
2. Error

### Expected behaviour

Max data in chunk should be larger

**Comment by Raidobw2** [comment]
Hello, as I suspected this is a bug with Powah. See #195.
This is the problematic chunk in your save, which is were your character is standing as well:
![image](https://user-images.githubusercontent.com/17010632/140604608-299df629-56c2-44c6-99ba-90f99dcbfcb8.png)
Big cable bundles of Powah cables hold too much information, so this causes crashes because the packets are too big.
See the linked issue 195 and the other one inside linked directly to Powah's issue tracker for the full briefing.

Your best solution is to restore a backup and stop using Powah cables until this is fixed. I recommend to break them all once you load in after a restore and replace them with other cables, like Pipez or Mekanism.

There are other options than using a backup, but the backup is the most time efficient in all cases usually.
If you are unable to restore a working backup (I doubt, but I'm throwing the option), you've put a world download so I'll fix it for you. However, please be considerate as that will take me some time to get it to work, so please really try a backup before going with that option.

That's all, sorry about that and I hope you can resume playing soon!

P.S.: Leaving the issue opened until you've fixed this or not, let me know. If it's solved, please close the issue.

**Comment by Raidobw2** [comment]
Closing as duplicate, if you still have the error come see me in the FTB Discord until this gets resolved from the Powah mod author.
