### ISSUE TITLE
Copper Tiles Recipe Incorrect

### ISSUE THREAD

**Issue by hopey3182** [FTBTeam/FTB-Modpack-Issues#2645]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.2.0

### Describe the bug

In the stonecutter a block of copper is supposed to be converted into 4 copper tile blocks but instead it's a 1 to 1 conversion.

### Steps to reproduce

1. Put vanilla block of copper in stonecutter
2. Select copper tiles
3. 1 to 1 ratio instead of 1 to 4

### Expected behaviour

1 block of copper is supposed to be able to be converted into 4 copper tile blocks in the stone cutter.

### Screenshots

Recipe as shown in REI:
![2023-02-02_11 15 45](https://user-images.githubusercontent.com/23436444/216380731-7172f49a-8326-492c-b637-ff18766d21ad.png)

Actual recipe in stonecutter:
![2023-02-02_11 15 57](https://user-images.githubusercontent.com/23436444/216380931-2475217e-1835-4a48-bfb2-74f2311bf87d.png)

**Comment by TheonlyTazz** [comment]
This is just a glitch shown in REI
it should be 1:1 bcause
![image](https://user-images.githubusercontent.com/3908847/216438361-af3b6ab8-66b4-4041-a8af-a19952380971.png)
Copper tiles also give 9 copper back
Also, the reason this has been changed is because of consistencyPlus, but it seems that it doesnt wanna play nice with the REI integration
