### ISSUE TITLE
Invasions

### ISSUE THREAD

**Issue by Denthris** [FTBTeam/FTB-Modpack-Issues#2666]
### Modpack

FTB Inferno

### Modpack version

1.5.0

### Describe the bug

Not sure there seems to be a consistent bug with invasions. That I don't think I have ever gotten to every single wave of some of them. Probably for the past 4 or 5, I've slaughtered the first wave or two, and then their is 1 or two mobs remaining. In the last two waves, I have noticed that I was missing two mobs, and I had two creepers that blew up and were not "killed" and I had two kills left, so I am wondering if the creepers did not get counted.

This is also quite often true with the triggered portals such as the Bell Ringer boss fight. Three times I wasted the materials to summon it, only to kill 3 or 4, only to have 1 or two mobs no be there to kill. I'm near the portal, and they have wandered off somewhere else... Which means even if I knew where they were if they went out of range, I can't chase them because the I fail the moment I get two far away from the portal.

The Witches in the Bellringer fight, don't attack. They just run and heal themselves endlessly. Making them harder to put down than the boss itself, so far now three times wasting my stupid time limit.

Kanda hate the timers on these things as well, but that's less of a bug and more of a complaint.

### Steps to reproduce

1. Wait for Invasion or  OR Tigger an Invasion that has multiple mobs to fight.
2. Kill all visiable mobs.
3. See couple mobs remaining, don't see them around, don't see any red dots on map signifying a nearby mob.

### Expected behaviour

Mobs to actually not be able to leave the area you can leave, or all the killed mobs to count as killed.

**Comment by Saereth** [comment]
following up with shadows on this

**Comment by SuperJuib** [comment]
I just wanted to confirm this issues. And the culprit is usually creepers. This makes guards and other allies more of a hindrance than help.

**Comment by ekdeans** [comment]
Can confirm, I haven't been able to get past the second round of the "infernal soldier" invasion since I got to tier two, though that could just be because witches scatter to the four winds while I'm blinded. I haven't experienced major issues with the boss summons in this patch thankfully, but in older ones I managed to drag the missing mobs out of the portal using /tp (much easier on boss summons since the pearl tells you what to expect).

No idea what's causing the creepers to not count or the portal sticking, but I think at least some of the issues could be alleviated by giving all the mobs a glowing effect so it's harder to lose track of them? And if at all possible prevent them from having champion abilities, the fact that some of these mobs can be invisible doesn't help.

**Comment by Denthris** [comment]
I find with Creepers that if they get killed they tend to count towards the kills. Yet in the horde situations that the portal fights tend to be. Its easy to not properly kill the creepers, and they blow up killing themselves, and NOT descresing the Mob counter. So 10 mobs spawn, you have 10 to kill, three creepers spawn. 2 blow up, one gets killed, kill the other 7 mobs. And you then get to watch the Timer count down as I have found that it consitently has the 2 mobs remaining, and seeing as the creeper blew up, their is no two mobs to kill. Theoettically I would have to test it again, but the creeper explosion could be killing another mob and that is what is not counting, but can't remember the several pearl or gateway fights with creepers as that was now a bit ago.

**Comment by Saereth** [comment]
Just letting you guys know I'm still waiting on a fix from shadows for this but its definitely still on my radar

**Comment by Saereth** [comment]
removed all creepers from invasions as well to mitigate
