### ISSUE TITLE
[Bug]: New version of java causes irreperable damage to modpack

### ISSUE THREAD

**Issue by Pantheris2019** [FTBTeam/FTB-Modpack-Issues#273]
### Modpack

FTB Revelation

### Modpack version

3.5.0, 3.4.0

### Describe the bug

New java update bricks connection with server if not running windows update KB5006738, produces an error where fastworkbench produces and unregistered item.  Upgrading to Win11 fixes the issue but do not consider unless running INTEL CPU gen 9-11. AMD will experience 15% performance drop platform wide in OS upgrade. Information provided from client experiencing error also reports brick of FTB app not installing minecraft when command is run via interface.  AVOID JAVA UPDATE.  Update decreases modpack performance significantly on loading and client takes approximately 20s to return to stable framerate upon chunkload.  This is a java update issue.  Recommend announcing immediately.  Loading time increased by 25% upon installing update.  Memory consumption also increased by 1GB from 6GB to 7GB while loading.

### Steps to reproduce

1. install java update on system not running update KB5006738
2. install FTB app and modpack using normal procedure.
3. connect to FTB revelation server.
-ISSUE HAPPENS.-
To Fix:
1. apply update KB5006738.
OR
1. upgrade OS to win11 for intel system gen 9-11.
-MEMORY CONSUMPTION AND LOAD SPEED DECREASE ISSUE PERSISTS.-
Removing FastWorkbench will create other issues unless removed before modpack instance is run FOR THE FIRST TIME.

### Expected behaviour

Error depicted to be that FastWorkbench produces unregistered item.

**Comment by Raidobw2** [comment]
Hello, if you're having issues with a modpack and need support, please come in the FTB Discord in the support channel. We use the Github for bug tracking only.

I've seen a lot of errors and on Revelation as well, but I've never heard of a "Java update" breaking the game, or it being related to Windows at all. Most bugs got fixed in 3.5.0. I see you mention 3.4.0 and 3.5.0, if you did update through the FTB App right now I'm suspecting there is a bug related to downloading update files and it could cause mod issue with servers -- the devs have been made aware of this fully.

If you have references to that issue with Java either on a Microsoft or Oracle article then I will gladly read it and hand it out to the devs for that issue, since it will probably arise with other modpacks that meet the criteria you describe here.

As well, if you have crash-logs or simply your latest.log and post it here or on the Discord, myself or other team members should be able to look at it and tell you what the issue was, it might have been a mod.

I'll leave this open once so you can ask questions if needed, but I'll need to close it right after, come see me in the Discord if it persists after.

P.S.: The FTB App uses a bundled Java 8u51 version, and currently it's bugged and not possible to use other Java versions other than Java 8 versions, by using `-version:1.8+` in the JVM arguments. Which means that it's most likely impossible that the Java update messed something up, I'm really more suspecting the FTB App update logic on that case. Deleting the `.localCache` folder in your instances folder, backing up the worlds for the game and reinstalling the modpack, in order, should resolve similar issues if you updated the modpack recently.
