### ISSUE TITLE
[Bug]: (FTB Academy 1.16) Cannot complete school quests

### ISSUE THREAD

**Issue by Waoweens** [FTBTeam/FTB-Modpack-Issues#274]
### Modpack

FTB Academy 1.16

### Modpack version

1.2.0

### Describe the bug

When clicking a school quest's task, you get teleported to school, but the task doesn't get checked and the quest doesn't get completed.

When attempting to complete the quest using Editing Mode, an error gets thrown into the console:
`[Server thread/ERROR] [KubeJS Server/]: Error occurred while handling event 'ftbquests.completed.5513AF634204A9B4': Wrapped java.lang.NullPointerException (server_scripts:quests.js#37)`

Happens on both singleplayer and multiplayer (server).

### Steps to reproduce

1. Open a school quest
2. Click the checkbox
3. Get teleported to school
4. Exit school
5. See that the quest isn't completed

### Expected behaviour

The task gets checked and quest completes

### Screenshots

![image](https://user-images.githubusercontent.com/30313089/140712016-399bbb28-b43a-4c38-99d9-2ba1e03c0750.png)

**Comment by Raidobw2** [comment]
Hi, this is intended behavior. The quest is repeatable so you can return to schools if you need to learn something again:
![image](https://user-images.githubusercontent.com/17010632/140715614-c96b070c-0210-4d6c-9afa-2f5c9ba81378.png)
You will never be able to "complete" that quest because it's only a helper quest to go to the school more easily than typing a command, as seen in the picture above.
I hope you're learning a lot and having fun, that's a super cool modpack! :)
