### ISSUE TITLE
[Bug]: fluid level emitter not accepting item

### ISSUE THREAD

**Issue by marburps** [FTBTeam/FTB-Modpack-Issues#275]
### Modpack

FTB Direwolf20 1.16

### Modpack version

1.11

### Describe the bug

The ME fluid level emitter doesn't accept any item to be dragged onto it.

### Steps to reproduce

Put fluid level emitter on Me cable,
Open fluid level emitter dialog
Try to drag any liquid item on it. e.g. lava (bucket, tank, ...)
The emitter will not accept any item. It also doesn't generate any entry in the log files.
(the bug doesn't exist for item/energy level emitters).

### Expected behaviour

The fluid level emitter should accept a liquid

**Comment by Raidobw2** [comment]
Hello, the UI is just a bit bugged for now for the mod. A tip, normally inventories will accept stuff that you Shift + Left Click into them. For instance it will take the fluid bucket if you do this, but as you see, the location of the container is bugged but it works.
![emitter](https://user-images.githubusercontent.com/17010632/140871661-123d387f-cb38-4102-9216-c8068015e0a3.gif)
This will be fixed on the next development cycle for that pack, since an update for the mod is available: AppliedEnergistics/Applied-Energistics-2#5365.

**Comment by Raidobw2** [comment]
Fixed in-dev
![image](https://user-images.githubusercontent.com/17010632/141660274-3a2a2419-e398-4b5c-9ae4-00595001e450.png)
