### ISSUE TITLE
Timeout when opening sunken ship chests

### ISSUE THREAD

**Issue by Dycilia** [FTBTeam/FTB-Modpack-Issues#2825]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.6.1

### Log Files

-None-

### Describe the bug

When we try to open a sunken ship chest the entire server gets timed out.
 No crash, so there is no log.
 And when we log back in it can be opened.
 So far a 100% on 5 sunken ship chests.

### Steps to reproduce

Find sunken ship.
Dive down to chest with maps and paper.
Open it and get timed out.

### Expected behaviour

Opening chest to get loot without a timeout.

**Comment by Chirimorin** [comment]
I bet each of those 5 chests had a treasure map in them. 

Those treasure maps get generated the moment you open the chest. To do this, the server has to load (and possibly generate) the entire area on the map. If this generation takes too long, your client disconnects with a timeout (because the server isn't responding). This is not a server crash, the server is still churning away in the background.

What can also happen is that the server hang watchdog notices a tick taking over 60 seconds (configurable in server.properties) causing it to kill the server. This will generate a generic "a single tick took over 60 seconds" crash log.

I'm not sure if this is an issue specifically with the modpack or just an issue with the server being too slow at world generation (needing more single-core CPU power). The server I run uses quite an old CPU which could explain the slow generation.

**Comment by Saereth** [comment]
please provide the server's latest.log when this happens, it will help us see what's going on. Without logs we can only guess but Chirimorin's initial analysis does seem like the likely scenario here.
