### ISSUE TITLE
[Bug]: Domum Ornamentum Mod and Oak Plank Items

### ISSUE THREAD

**Issue by dragonwarrior00** [FTBTeam/FTB-Modpack-Issues#2846]
### Mod

Domum Ornamentum

### Mod version

domum_ornamentum-1.19-1.0.83-ALPHA-universal

### Forge / Fabric version

1.5.1 (FTB)

### Modpack & version

Direwolf20 1.19 - 1.6.1

### What issue are you having?

The Domum Ornamentum mod will not render both icon and texture of any item that requires an oak plank as material for cutting. The texture does not render in Architects Cutter, Inventory, Resource Scroll, and when item is placed in the world. The items are being requested for the buildings for MineColonies using "The Shire" theme. See attached pics.

Requested Items are not rendering on Resource Scroll:
![Pic1](https://user-images.githubusercontent.com/42704866/225215673-c8c8db8f-4302-4a0b-830f-d9648240aea1.png)

Mouse on item that is being used in building but not rendering:
![Pic2](https://user-images.githubusercontent.com/42704866/225215699-078e1454-c933-46e5-b3e7-a34b77bc0983.png)

No rendering within Architects Cutter:
![Pic3](https://user-images.githubusercontent.com/42704866/225215711-f6ada3cf-1977-4a23-928a-7a162363bc9d.png)

### Steps to reproduce

Crafting, keep in inventory, or placing in world shows no texture of items that require oak plank. These are items that are created using the Architects Cutter. Both for items that use 1 oak plank and 2 oak planks to be created. 

### Anything else to note?

Have not confirmed that other material can or can not render properly. Just oak plank only as this is main request for minecolonies buildings theme.

**Comment by Zoidey** [comment]
I believe that this is an issue with the texture pack, not the mod. I've had the same issue with ATM8 and if you use PureBDcraft texture pack then you'll have the issue. There are two ways that I know of to get around this issue. However, I didn't have the whole texture fail to render as I would have the cobblestone render but not the oak wood frame around the cobblestone or paper block for example if you get what I mean.

1) Either use ValliaBDcraft instead of PureBDcraft.
2) Patch PureDBcraft with older style textures for the parts not showing up / invisible (wood planks are the biggest culprits here) or replace the textures that don't render from PureBDcraft with VanillaBDcraft.

Other options are to either use PureBDcraft and ignore the unrendered blocks from Domum Ornamentum or use now texture pack (both options even I couldn't imagine myself doing lol).

I could be wrong but the creator of Domum Ornamentum doesn't believe there is anything wrong with their mod as it's not a mod issue to them and PureBD believe it's a mod issue and not their Texturepack that's the problem. From what I have seen when I've done a bit of research in searching for a fix to a similar issue. So I could be wrong but I hope this helps in some way.

**Comment by dragonwarrior00** [comment]
You are correct. This appears to be the texture pack. I disabled PureBDcraft and it render with normal minecraft texture. Should have thought of testing that first. Thanks for the customization link.
