### ISSUE TITLE
pedestal work tool uncraftable

### ISSUE THREAD

**Issue by kareem69420** [FTBTeam/FTB-Modpack-Issues#2973]
### Modpack

FTB Skies

### Modpack version

1.0.1

### Describe the bug

cant make work area cards for the Pedestals mod

### Steps to reproduce

go to rei, look up work area cards click for the recipe for the work tool

### Expected behaviour

for a recipe to appear

**Comment by WhitePhant0m** [comment]
Shift right click the Upgrade tool in the air

**Comment by togreglove** [comment]
I had the same concern, indeed it is a form of the Upgrade tool, but there is absolutely no indication that you should start with the upgrade tool to get it.  Maybe a tool tip would be in order?

**Comment by PorkchopNation82** [comment]
> Shift right click the Upgrade tool in the air

For the win! Legend status ^^^

**Comment by Nekosity12** [comment]
> I had the same concern, indeed it is a form of the Upgrade tool, but there is absolutely no indication that you should start with the upgrade tool to get it. Maybe a tool tip would be in order?

Idk if the quest existed in this version but def in later versions (at least v1.0.6) there's a quest that explains how the upgrade tool can be swapped to different tools: https://i.imgur.com/diENaQf.png

Additionally, although admittedly not entirely clear what it means exactly, the work tool info in JEI states you can sneak right click to switch tools: https://i.imgur.com/fXxXmkH.png (as of AT LEAST v1.0.6)

Just thought I'd add this incase it satisfies the issue

**Comment by osirisgothra** [comment]
same problem, places the stick (supplementals) which is annoying, even if i swap hands, still does not work. I ended up having to make a roller and make the copper rod to do it. For some reason the linking tool worked with stick+emerald, but had to make the backward linking tool (stick in offhand), and sneak+click air to get it to be normal to finish the quest, for the UPGRADE tool, I could not use a stick at all, I tried for about 15 minutes every way I could think of, but all it did was place it on the bookcase, regardless of which hand i was using, regardless of sneaking or not, regardless of how close I was standing to the bookcase, regardless of what KIND of bookcase (oak, dark oak, spruce, etc.). It was quite annoying since I had plenty of sticks at the time and didn't want to use up other resources for it or jump ahead just to make a single rod. 

Personally I think the fix should be to just allow use of stone rods, that would probably be the quickest way to fix that and not have to change much, maybe adding a note in the questbook about the issue and alternate item suggestion.
