### ISSUE TITLE
[Bug]: Oceanblock 1-2 FPS, please help!

### ISSUE THREAD

**Issue by GiuseppeCamole** [FTBTeam/FTB-Modpack-Issues#305]
### Modpack

FTB Oceanblock

### Modpack version

1.6.0 and 1.7.0

### Describe the bug

I can't get past 1 - 2 FPS in modpack.
I've already put everything to a minimum and it still doesn't work.
Other modpacks in the same version work, like CourseForge Better Minecraft.
I already turned on forge's multiple chunk rendering and it still didn't work.
It doesn't have foamfix to disable the animations.

### Steps to reproduce

Starting minecraft normally, always putting 8GB of RAM

### Expected behaviour

Expected 60FPS

### Screenshots

![image](https://user-images.githubusercontent.com/94216957/141610526-41c78887-d5d0-48e9-8b03-318fb0b251b6.png)

**Comment by Raidobw2** [comment]
For support always come in the FTB Discord. On Github it's for bugs and suggestions only, not support.

Disabling mipmapping on an AMD graphics card will boost FPS. This is because AMD handles OpenGL mipmapping differently than NVIDIA does, and it makes the graphics card work super hard. Open the menu in-game and click *Options*, then *Video Settings*. Slide the *Mipmap Levels* slider to the left to "OFF", and resume playing.

In your launcher/FTB App open the instance folder and then the `config` folder. Open the `forge-client.toml` file with a text editor like Notepad/TextEdit/etc and change that setting to `true` instead of `false`:
```
#Not recommended for computers without a significant number of cores available.
	alwaysSetupTerrainOffThread = false
```
becomes
=> `alwaysSetupTerrainOffThread = true`

Relaunch your game and it'll be fine after that. For future issues with the game, go in the FTB Discord, there are ressources available to help you there.
