### ISSUE TITLE
Refined Storage Items stuck

### ISSUE THREAD

**Issue by Elgato8725** [FTBTeam/FTB-Modpack-Issues#3124]
### Modpack

FTB Skies

### Modpack version

1.0.6

### Describe the bug

My refined storage setup has stopped allowing me to access items stored in it. I tried reverting to an older version of the modpack, as this is a beta, but that did not help. The items are still there and searchable, but clicking on them does not pick them up. That said, the only workaround I have been able to find is to access the items using the crafting segment of the crafting grid, so non-craftable items are still inaccessible and items can only be pulled out one at a time. I have no idea how this started, I was building out my base when it became an issue.

### Steps to reproduce

As I don't know the cause, I can't say how to reproduce the issue.

### Expected behaviour

Items would be pulled out in stacks if clicked, or half stacks if right clicked. Shift clicking would put a stack of said items into my inventory.

### Additional information

Not sure how to provide further information, but feel free to reach out should you have any questions.

**Comment by MechBFP** [comment]
Check your storage drives or blocks and make sure you didn’t accidentally apply an item filter. Alternatively you may have changed the interface to only allow imports. Check all the icons/buttons.

**Comment by Flekrad** [comment]
Playing on a server using version 1.0.6 I was also unable to remove any items .
I had the refined storage system linked to a functional drawer setup (via an external storage)
If I disconnected the external storage I could see and access items on the disks.
Workaround -->
Created a controller extension (Functional storage) and connected the external storage to this instead of the actual controller (functional storage) 
Now I can access items on either the disks or in the drawers.
![2023-04-16_23 29 47](https://user-images.githubusercontent.com/29991384/232319639-30bfc3f9-bae8-4566-86f4-9f100dc72b2e.png)

**Comment by Elgato8725** [comment]
The workaround that was recommended by @Flekrad works! The odd part was that even though I had items stored in both the functional drawers and refined storage, I was previously unable to access items from either. With the controller extension workaround I am now able to access both. Huge thank you!

**Comment by manmaed** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3031#issuecomment-1506055194
