### ISSUE TITLE
[Any kind of tree doesnt appear to grow besides birch at the start of the modpack?]: 

### ISSUE THREAD

**Issue by Keiizen** [FTBTeam/FTB-Modpack-Issues#313]
### Modpack

stoneblock 2

### Modpack version

1.12.1

### Describe the bug

nothing really to describe, any kind of tree besides birch doesnt seem to grow.

### Steps to reproduce

nothing really to describe, any kind of tree besides birch doesnt seem to grow.

### Expected behaviour

I expected every tree type to grow

**Comment by Raidobw2** [comment]
Hello. Please use our Discord for support issues like that one. StoneBlock's start is underground and having the sapling too close to a wall or not waiting long enough in some cases will make it fail to grow.

My suggestions would be to make the area wider and higher if that's the problem.

You can enable cheats and use `/gamerule randomTickSpeed 300` and wait a minute. This will make it so that trees grow 100x quicker than normal, so they will grow fast and you'll see it.

Once you've seen that they grow, you can revert the tick speed with `/gamerule randomTickSpeed 3` and your game will be normal again.

If you encounter other issues related to that modpack, please come to the FTB Discord first. We'll likely solve your issue, and there's a specific channel for StoneBlock 2 too!
