### ISSUE TITLE
Everything turned black and white

### ISSUE THREAD

**Issue by User1857B** [FTBTeam/FTB-Modpack-Issues#3142]
### Modpack

FTB Skies

### Modpack version

1.0.6

### Describe the bug

I was in the Nether and all of a sudden everything turned black and white,  my inventor and chests are in color but everyting else isn't. 

### Steps to reproduce

?

### Expected behaviour

?

**Comment by xAsger** [comment]
Have you checked to see that you have a wither skeleton skull on your head? in the helmet space

**Comment by afolk2** [comment]
Not unique to wither skeleton skulls. This also happens with zombie heads. It might just be undead heads in general.

**Comment by Saereth** [comment]
yeah seems to be the case here, send me a world save if not

**Comment by Malucatent** [comment]
I was back from farming mobs and sorting when I found a new music disc. After putting it in, it was Jazz ans I continued sorting, then I realized everything was back and white. I did put on a skeleton head, but at that moment I thought it was because of the jazz and like a methaphor for a grey world view. Well in the end i found the scull, but at that moment it was a very cool easter egg
