### ISSUE TITLE
[Bug]: The modpack fails to initialize the minecraft engine

### ISSUE THREAD

**Issue by Dahaka917** [FTBTeam/FTB-Modpack-Issues#320]
### Modpack

FTB Stoneblock 2

### Modpack version

1.21.1

### Log Files

https://pastebin.com/p9zsZDLk

### Describe the bug

Game crashes when trying to initialize minecraft engine... I have allocated 6gb of ram to stoneblock so it should work 

### Steps to reproduce

I have NO idea

### Expected behaviour

The game should run properly without any problems

### Screenshots

![image](https://user-images.githubusercontent.com/67931015/141921804-33a30caf-490b-436e-a882-98b54a450a8a.png)

### Additional information

I have tried everything possible to get the game to load correctly, 
the only mods i added are [Inventory HUD+, StackUp, updated version of Hammer lib,Optifine, charset lib]

**Comment by Raidobw2** [comment]
Check your RAM in Task Manager. If it's full, the pack will never load. With 8GB total this is going to be difficult to run.

Close unused programs or even close the FTB App once the modpack starts, if that's what you're using.

You can also disable programs on Startup and reboot your PC. This would also help.

I'll leave this open so you can reply, although for support issues in the future please use our Discord, here we keep track of bugs for modpack development mostly.

**Comment by quietust** [comment]
According to the log, it seems to have crashed due to the "LLibrary" mod being unable to fetch its list of Patrons from a particular Github Gist entry (which, indeed, does not exist anymore).

**Comment by Dahaka917** [comment]
So the problem was caused by mod that is unable to load something that doesnt exsist ?
Sorry for my bad english but i think you may understand what im trying to say/type

**Comment by quietust** [comment]
It looks like an updated version of LLibrary was released about a year ago which seems to fix this problem ("Don't print a misleading crash report on failure to receive data from URL").

Said updated version can be found on CurseForge:
https://www.curseforge.com/minecraft/mc-mods/llibrary/files/3116493

If you replace the "llibrary-1.7.19-1.12.2.jar" file in the "mods" folder with the above-linked "llibrary-1.7.20-1.12.2.jar" file, the pack might start working properly, but I can't guarantee anything.

**Comment by Dahaka917** [comment]
i forgot to add in the beggining but i was hosting my minecraft world for my close mate and i was using hamachi 
so _he_ shoud replace that mod for better compability too, right?

**Comment by Dahaka917** [comment]
> Check your RAM in Task Manager. If it's full, the pack will never load. With 8GB total this is going to be difficult to run.
> 
> Close unused programs or even close the FTB App once the modpack starts, if that's what you're using.
> 
> You can also disable programs on Startup and reboot your PC. This would also help.
> 
> I'll leave this open so you can reply, although for support issues in the future please use our Discord, here we keep track of bugs for modpack development mostly.

in the task manager it shows me 3GB and in the game it shows 2.4GB
I allocated 6GB of RAM for Minecraft

**Comment by Dahaka917** [comment]
[DxDiag.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7550561/DxDiag.txt)
here are my pc specs...

**Comment by quietust** [comment]
> [My pc specs](https://pastebin.com/PqVxbA0t)

According to that, you're running on a laptop which only has 6GB **total** memory, so if you want to play this modpack it sounds like you're going to need to get a better computer.

**Comment by Dahaka917** [comment]
I have optifine and it worked fine ...
that's funny ... dark souls 1 works fine, but this modpack doesn't work any longer after some time
then how much is needed for this modpack? 8GB minimum?
there was no information about the minimum requirements for this modpack... nice

**Comment by Raidobw2** [comment]
Indeed it's caused by your computer specs.
The required amount of RAM to play might vary between 4-6, it's the general RAM usage for FTB modpacks -- they run well on computers with medium, or "normal" specs. On the FTB App this is set automatically for you, and StoneBlock 2 presents those values to users:
```
"minimumMemory": 4096MB
"recommendedMemory": 6122MB
```
Which is effectively between 4 and 6GB.

Even if you allocate 6GB and your PC has that amount it's already using some of it, you'll never truly get 6GB in-game.
Start your computer and look in Task Manager. You'll see it's already using some of the RAM for programs and your OS -- which doesn't leave enough space for the modpack. Modded Minecraft is much more memory hungry than other games.

Your options are to play lighter modpacks. You can achieve similar experiences while you save up for a new computer, if you feel the need for it. I'll enumerate some for you in case you want to try them:

FTB Academy 1.16, FTB Cotton, FTB Ultimate Reloaded, FTB Presents Direwolf20 1.12, etc.
These all have a smaller memory footprint, using about 4GB instead of 6GB.

You might also be able to play either FTB Presents SkyFactory 3 or Skyfactory One (by Darkosto), and they offer a similar experience since they are also skyblock-like, just like StoneBlock 2, and lightweight.
You could also try StoneBlock (1), I would think it has a smaller memory footprint too. "Create Together" could be a lightweight option if you want to try the Create mod.

Best of luck to you.

**Comment by Dahaka917** [comment]
[*sigh* ](https://youtu.be/mNj-HJQ96Vo)[Really??](https://youtu.be/36VbMtVivGU)

**Comment by Raidobw2** [comment]
You're free to try those optimizations, and if it works, great.
However RAM =/= FPS. RAM is mainly used for loading assets in memory, and even with optimization mods like FoamFix or TexFix, you still need need to somehow loads all those textures and blocks to actually play the game.

JVM optimization relates mostly to garbage collection, that helps with lag spikes and heap space a little bit.
Using the GPU in Minecraft will only help with FPS, and will not reduce RAM usage.

RAM (random access memory) = used for loaded assets and workspace for mods.

Running modded MC on a Notebook with 1.7GHz CPU and 6GB of RAM, you will have a hard time just loading the game. Modded MC is not an optimized game at all.
That's why I've recommended you other options that are as fun but that you can more easily run on your computer.

I hope this post was informative enough to enlighten you a bit more on how the game works. If you want to discuss more about it, I'd invite you to join the FTB Discord and talk in the channels about optimization. You'll get the opinion of other players and not just me: this can be valuable feedback, perhaps you'll even get more tips.
