### ISSUE TITLE
Flying Mobs not Dying to the Void

### ISSUE THREAD

**Issue by ChosenArchitect** [FTBTeam/FTB-Modpack-Issues#3247]
### Modpack

FTB Skies

### Modpack version

1.0.7

### Describe the bug

Mobs such as bees will build up under the islands and cause lag. They are not taking any kind of damage to the void.

### Steps to reproduce

just let the bees spawn and over time it will happen

### Expected behaviour

The mobs should take damage killing them and preventing lag

**Comment by davidthehat** [comment]
It's actually a vanilla issue https://bugs.mojang.com/browse/MC-167279

Should still implement some sort of fix for a skyblock pack that auto-spawns bees

**Comment by Saereth** [comment]
I think I'll need to just do some kube work so that if a bee gets below a certain y level they despawn

**Comment by Saereth** [comment]
I toyed with autopurging below y level 1 but that was killing people's bees that intentionally build down there, and since they dont actually go all the way down into the void they never die. I think the best thing is just adding the quest text to tell people to turn them off when they no longer need bees or go kill them occasionally
