### ISSUE TITLE
[Bug]: Occultism Crusher Spirit Outputs Barrier Blocks

### ISSUE THREAD

**Issue by PichiCookie** [FTBTeam/FTB-Modpack-Issues#3336]
### Mod

Occultism

### Mod version

occultism-1.19.2-1.77.5.jar

### Forge / Fabric version

Forge 43.2.10

### Modpack & version

FTB Presents Direwolf20 1.19.2 ver. 1.10.0

### What issue are you having?

I tossed raw iron to the crusher foliot from occultism to get iron dust, but it outputted barrier blocks

### Steps to reproduce

1.) Summon crusher foliot
2.) Give it raw iron
3.) Obtain dropped barriers

**Comment by tekktonic** [comment]
At a glance I think this means that the pack is missing a mod. This has been reported in the Occultism discord before and the response was that the foliot was trying to generate an item which doesn't exist. I don't see any mention of mods it depends on, so maybe as part of the modpack integration the occultism ore dusts were removed and that mod wasn't updated to use the mekanism ones?

**Comment by abint** [comment]
The issue occurs as well with copper, silver, gold, & iesnium.
The issue recipes have the following IDs:
occultism:crushing/copper_dust_from_raw
occultism:crushing/gold_dust_from_raw
occultism:crushing/iron_dust_from_raw
occultism:crushing/iesnium_dust_from_raw
occultism:crushing/silver_dust_from_raw
occultism:crushing/silver_dust
occultism:crushing/copper_dust_from_ingot
occultism:crushing/iron_dust_from_ingot
occultism:crushing/gold_dust_from_ingot
occultism:crushing/iesnium_dust_from_ingot
occultism:crushing/silver_dust_from_ingot

One recipe works half the time, occultism:crushing/gold_dust_from_raw, because it has two entries. Replacing the bad recipes with absolute ones should remedy the problem in this pack

**Comment by trolltoll533** [comment]
How do I do this? Do I have to do something to the server and it will work for everyone or is it client side?
