### ISSUE TITLE
[Bug]: Mega Torches and similar items to prevent mob spawning do not work.

### ISSUE THREAD

**Issue by BennyOfEarth** [FTBTeam/FTB-Modpack-Issues#337]
### Modpack

FTB Oceanblock

### Modpack version

1.8.0

### Describe the bug

Mega Torches and similar items to prevent mob spawning do not work, a user said this was due to the wyml mod taking over the mob spawning. I've seen others complaining about this in the FTB discord.

### Steps to reproduce

Place a mega torch or dread lamp for example and wait

### Expected behaviour

Mobs will spawn anyways

**Comment by Raidobw2** [comment]
Hello, yeah we've had this issue for a while. Recently it looks like the devs talked to each other and that this should be sorted in a future mod update.

See #16 for details. You can subscribe to the other issue since I'll be closing this, since the issues are the same: we'll just keep one for our tracking.

Thanks for your report and sorry about that bug!
