### ISSUE TITLE
Once launched, it says me kubejs doesn't load properly

### ISSUE THREAD

**Issue by Jarvissen** [FTBTeam/FTB-Modpack-Issues#3415]
### Modpack

FTB StoneBlock 3

### Modpack version

1.7.0

### Log Files

[crash-2023-05-23_13.05.46-fml.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11539828/crash-2023-05-23_13.05.46-fml.txt)

### Describe the bug

kubejs doesn't load

### Steps to reproduce

Launch the game as shown in the screenshot without any changes to the integration pack

### Expected behaviour

I'd love to play this pack normally

### Screenshots

![810813530619664f462da48392c4bf6](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/134359220/22df42c9-d27e-48e4-b50d-e38a2c93c883)

**Comment by UnRealDinnerbone** [comment]
Please also upload logs/kubejs/startup.txt so we can track down what causing this error

**Comment by osego** [comment]
I've run into this and the cause was similar to what's described in #2468 - mods that cannot be downloaded though the curseforge api weren't loaded. I took a look at the crash log posted by @Jarvissen and it seems to be the same problem: the mod list is missing `ftb-stoneblock-companion`, `justhammers`, `accelerated-decay` and `extendedexchange`.
