### ISSUE TITLE
Rocket returns to starting ship 

### ISSUE THREAD

**Issue by LynchMatias** [FTBTeam/FTB-Modpack-Issues#3476]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Describe the bug

Even if I launch the rocket from my base, when relaunching from where I landed, from any planet, I get sent back to the starting ship, losing my rocket because it falls into the void.

### Steps to reproduce

1. Launch a rocket and travel to a planet
2. Land
3. Launch the rocket from where you landed and travel back to earth.
4. Lose rocket

### Expected behaviour

The rocket returns to the original launch position in the base.

**Comment by Saereth** [comment]
duplicate issue, not really a bug as you're returning to overworld which is the lobby, just an unfortunate side effect. This has been reported and I'm considering some janky kube work to maybe fix it but for now its low priority since there is no reason to fly back to overworld when you can always just /home or /spawn
