### ISSUE TITLE
RS bug unable to retrieve items from Crafting GRID

### ISSUE THREAD

**Issue by Daelin1977** [FTBTeam/FTB-Modpack-Issues#3477]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Describe the bug

I am unable to get items out of the Refined Storage block from the inventory area.  I am able to craft only from JEI pull to crafting grid.  Even in Wireless Grid unable to take items.

### Steps to reproduce

1.  Open RS crafting grid
2.  Click on items in Grid's Inventory side.
3. Will NOT be able to grab items to place in crafting area or in player inventory.

### Expected behaviour

able to retrieve items to own inventory or drag to crafting area of RS 

### Additional information

Have tried exiting and restarting multiple times.

**Comment by TheBread113** [comment]
I just got this bug.

It was because I had an external storage bus hooked up to a Functional Storage Storage Controller connected to a Controller Extender. The Controller Extender causes the bug.

I was able to fix it by breaking and replacing the Storage Controller and re-linking the drawers... and not using an Extender.

Note: This also becomes a dupe bug because anything that is moved to the crafting grid is not removed from your Refined Storage system.

**Comment by IronHide4** [comment]
This also causes the grid screens to not update properly.  when you are viewing a grid (crafting, pattern, etc) any new items added to the system will get new entries on the screen instead of adding to existing stacks.  These new entries cannot be taken out of the system.  When you exit and reopen the grid the numbers have updated properly, but the problems starts again.

**Comment by Saereth** [comment]
duplicate isssue, we've been waiting on a fix from RS for a while now unfortunately...
