### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Furious85** [FTBTeam/FTB-Modpack-Issues#35]
When i go to type dr in JEI my game crashes then i went to type chest and it crashed again and i feel like the draconium chest is breaking my game but i am not sure and idk where to find the crash report

This is in FTB OceanBlock

**Comment by MichaelHillcox** [comment]
Go the Draconic config and disable shaders. I'm assuming you have an AMD GPU?

**Comment by Furious85** [comment]
yes ok i will do that

**Comment by Raidobw2** [comment]
This this fix the issue?

Otherwise, to get your logs using the FTB App:
Open the modpack page and select Settings at the right.
Scroll down and select Open Folder.
Navigate to the folder `crash-reports` or `logs` if crash-report is non-existent.
Take the latest crash-report OR your `latest.log` in the worst case and upload it to https://paste.feed-the-beast.com/.
Post the link to that log here.

**Comment by Furious85** [comment]
> This this fix the issue?
> 
> Otherwise, to get your logs using the FTB App: Open the modpack page and select Settings at the right. Scroll down and select Open Folder. Navigate to the folder `crash-reports` or `logs` if crash-report is non-existent. Take the latest crash-report OR your `latest.log` in the worst case and upload it to https://paste.feed-the-beast.com/. Post the link to that log here.

so i found out thats its something with optifine and brandon core so draconic evolution.
the weird thing is that it might do it 2-3 times and then its fine

**Comment by Sunekaer** [comment]
AMD gpu doesnt work well with shaders in Minecraft.
Go the Draconic config and disable shaders and also we don't support optifine
