### ISSUE TITLE
Occultism crushers produce barrier blocks instead of ore dust

### ISSUE THREAD

**Issue by MiriamAlter** [FTBTeam/FTB-Modpack-Issues#3504]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.11.1

### Describe the bug

**Expected:** When a player gives an Occultism crusher spirit a material to process, the spirit will return the crushed version of that material as listed in JEI. (Example: 1 raw gold yields 2-6 gold dust depending on the spirit's level.)
**Actual:** For many materials, including all metals, the crusher spirit returns barrier blocks in item form.

### Steps to reproduce

1. Summon any crusher spirit from Occultism via the corresponding ritual.
2. Crouch + right click on the spirit to open its GUI.
3. Put any raw metal or ingot with a crusher recipe in JEI into the item slot. (Example: Any vanilla metal)
4. Wait for the spirit to throw out the resulting item.

### Expected behaviour

All JEI recipes - details in bug description

### Screenshots

Examples of crusher recipes in JEI
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/46386049/042b5261-b655-4da3-a917-9365f2454991)

**Comment by rex3125** [comment]
this is still happening on 1.12 i gave it both iron and copper ores, which it turned into barrier blocks, which then it somehow processed those into fluorite

**Comment by maraudir** [comment]
This is happening to me as well in 1.12

**Comment by Dambob** [comment]
I think the issue is in kubejs\server_scripts\unification.js - line 135. The recipes are replaced, but the condition tag is missing. By adding this in, the functionality seems to be working again. I've only done a quick test on this, so I'm not sure if this would break anything else.

Potential Working Version:
`oresToDust.forEach((material) =>
        event.custom({
            "type": "occultism:crushing",
            "ingredient": {
                "tag": material[0]
            },
            "result": {
                "item": material[1],
                "count": 2
            },
            "conditions": [
                {
                    "type": "forge:not",
                    "value": {
                    "type": "forge:tag_empty",
                    "tag":  material[0]
                    }
                },
                {
                    "type": "forge:not",
                    "value": {
                    "type": "forge:tag_empty",
                    "tag":  material[0]
                    }
                }
            ],
            "crushing_time": 200,
            "ignore_crushing_multiplier": false,
        })
    )`

Source: Recipe definitions from [Occultism github repo](https://github.com/klikli-dev/occultism/blob/version/1.20.1/src/generated/resources/data/occultism/recipes/crushing/copper_dust.json).

This may also fix: #3336
