### ISSUE TITLE
Waystone Duplication Bug

### ISSUE THREAD

**Issue by CSMaybee** [FTBTeam/FTB-Modpack-Issues#3505]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.7.0

### Describe the bug

I have experienced a duplication bug involving the modular drill from Industrial Revolution equip with the range (3x3) upgrade. 
What happens is if you break a waystone with the range module activated, the 3x3 function makes the waystone drop 2 waystone items when broken.

### Steps to reproduce

1. Get a modular drill with the range module.
2. Activate the range module
3. Break a waystone so the extended range breaks the top and bottom block at the same time

### Expected behaviour

Should only drop 1 waystone

**Comment by deltafreeze7** [comment]
I have been experiencing this bug too, the thing is that the 2 waystones also have the exact same NBT tags (it seems) and when you place the second one, the first of the two you placed takes the name of the last and becomes unusable, making the bug unexploitable (and very annoying because it makes the waystones you places useless)

**Comment by DinnerBeef** [comment]
It won't be fixed, as the mod dev does not support older versions of the mod.
