### ISSUE TITLE
Integration By Parts dX crashes when opening the draconic evolution quest tab

### ISSUE THREAD

**Issue by salviija** [FTBTeam/FTB-Modpack-Issues#3542]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.1.0

### Log Files

https://mclo.gs/AAZxXwD

### Describe the bug

When opening the Draconic Evolution quest tab the game crashes to desktop.

### Steps to reproduce

1. Open questbook
2. Select the DE quest tab

### Expected behaviour

The quest tab was supposed to open without any crash.

**Comment by DizzyDrwaf** [comment]
so can't get to the moon because u need to get to a elven portal to get the oxigen thing but to get a elven portal u need the tier 3 astra altar and to get that u need to get to the moon its a loop so u can't get to the moon. so it's broken or im just a idiot and can't find the way to get to the moon

**Comment by pikminman13** [comment]
issue # 40 (it is pinned)
