### ISSUE TITLE
[Bug]: Unpacked metals don't show up in Compacting Drawers

### ISSUE THREAD

**Issue by Tokoshoran** [FTBTeam/FTB-Modpack-Issues#357]
### Modpack

Oceanblock

### Modpack version

1.9.0

### Describe the bug

Compacting drawers seem to be able to recognize compacting recipes perfectly fine, but struggle with unpacking recognition. Tested with silver, nickel, tin, copper, lead, titanium, electrum, and steel.

### Steps to reproduce

1. Create a compacting drawer
2. Put a modded ingot or block in
3. Realize you can't get the lesser stage out

### Expected behaviour

You should be able to grab the unpacked version out of the compacting drawer, as you can with vanilla metals. Combined with external storages, this would allow you to create items needing the ingots or nuggets without actually needing to unpack.

### Screenshots

![2021-11-20_17 50 08](https://user-images.githubusercontent.com/5721448/142746266-0e08b46f-5831-41ea-b0c5-90cc5104408a.png)

**Comment by Raidobw2** [comment]
I've marked this as recipes. Potentially scripts, Sunekaer? Could be mod issue too, on their integration

**Comment by JeffBittle** [comment]
Hmm, I did just test this in 1.9.0 and yes it's being pretty weird.  It seems like if you set up the drawer by inserting a nugget first, the drawer will work as expected, but if the first thing you insert is a higher order version of the material, you won't be able to get the lower version out.  So if you set it up by putting in an ingot, you can get ingots and blocks out, but not nuggets, and if you set it up by putting in a block first, you can't get ingots or nuggets out of it.  And yes, it seems to be modded metals specifically, at least vanilla stuff still works fine.  I even tested Cinnbar also from Thermal Series and putting in a block of Cinnbar as the first item still lets you pull a piece of Cinnbar out of the drawer, so that's working correctly as well.

**Comment by Sunekaer** [comment]
Not a script issue, but storage drawers getting confused.
i think the only way to fix this if possible is to add every metal to the rules list in the config, but that's something ill have to do some testing on
