### ISSUE TITLE
Mason don't learn the end portal frame recipe

### ISSUE THREAD

**Issue by DFran49** [FTBTeam/FTB-Modpack-Issues#3570]
### Modpack

FTB Inferno

### Modpack version

1.9.0

### Describe the bug

I was on the way to kill the ender dragon to progress, but I did the research to unlockk the recipe before I upgraded the mason to level 3, and now I can't request the craft of theese.

### Steps to reproduce

1. Unlock the research "Infernal Mastery" with mason at level 2
2. Upgrade the mason to lvl 3
3. See the recipes that knows
4. There is no end portal frame

### Expected behaviour

I expedted the mason to be able to create end portal frames

**Comment by Saereth** [comment]
This is likely infernal mastery not being fully researched, the mason building not completed to level 3 or a bug. Unfortunately this seems to be working fine on my test server. Couple of options we can do, if you're playing on a server somewhere I could hop on and check it out, otherwise you can give yourself the endportalframe gamestage which enables you to just craft them yourself. 

A screenshot of the stone mason's hutt block interface would be useful as well as a screenshot of your research in the library in the unlockables/hidden section

**Comment by DFran49** [comment]
Thanks for answering.
While taking the screenshots I realised that the research was somehow reset and i had to research it again. I looked so many times, but I don't know why now.
Really, thank you :3

**Comment by Saereth** [comment]
np, glad you got it sorted!
