### ISSUE TITLE
[FTB Skies] Singleplayer standart Island Nether portal linkup is bugged.

### ISSUE THREAD

**Issue by Amakaphobia** [FTBTeam/FTB-Modpack-Issues#3586]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Describe the bug

- Im on a standard island singleplayer in the latest stable version of ftb skies, the coords of the island are around 0 0 .
- after building a nether portal and going through the portal in the netherworld is generated around 10k blocks away from spawn in both x and y direction.
- when exiting the nether the return portal is generated according to my position in the nether and i am stranded somewhere far away from my island

### Steps to reproduce

1 Build nether portal
2 walk through
3 return back

### Expected behaviour

the nether portal should link to the nether portal I build in my dimension

**Comment by Lostmindy** [comment]
Same issue here! 

Just to mention, I was able to go in and back from the nether once before without any issues (probably in my first day playing) and then today I tried to go back into the nether and got the same bug. Teleporting to coordinates 0 0 0 sent me to the ship and my world is apparently gone forever?

I thought it was better to add to this topic instead of opening another one, sorry if I shouldn't have.

**Comment by Ssausio** [comment]
Sadly, I still had this issue in the current release(1.9.0)

When I went back through the portal I was at very high coordinates in the starting-ship-world.
The only way to get back to my Island was jumping into the void.
"/ftbdim home" just gave an error
