### ISSUE TITLE
Server No Start

### ISSUE THREAD

**Issue by CyberWarden** [FTBTeam/FTB-Modpack-Issues#3590]
### Modpack

FTB Skies

### Modpack version

1.3.0

### Log Files

[crash-2023-06-27_11.53.11-fml.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11886271/crash-2023-06-27_11.53.11-fml.txt)

### Describe the bug

Server fails to start.

### Steps to reproduce

Fresh install and try to start it.

### Expected behaviour

Server starts

**Comment by TrelLyX** [comment]
Good day,

I also have this error on my dedicated server.
This is caused by the mod "Experience Obelisk"".
The version 1.4.4 has in the "Server" version a client code is executed and thereby causes errors on a dedicated server.

Fix: Update "Experience Obelisk" to version 1.4.5.
https://www.curseforge.com/minecraft/mc-mods/experience-obelisk/files/4611584
