### ISSUE TITLE
Pedestals Round Robin Augment and Capacity Augment not working with Export Upgrade

### ISSUE THREAD

**Issue by eyeroknee** [FTBTeam/FTB-Modpack-Issues#3618]
### Modpack

FTB Skies

### Modpack version

1.3.1

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11929880/latest.log)

### Describe the bug

Export upgrade does not receive more than 4 items at a time after installing capacity augments, export upgrade sometimes randomly (unknown conditions) swaps between linked pedestals but usually stays on a single pedestal for extended periods of time after installing round robin augment

### Steps to reproduce

1. Place pedestal on a 2x2 drawer.
2. Right click pedestal with export upgrade in offhand.
3. Right click pedestal with round robin upgrade in offhand.
4. Right click pedestal with capacity upgrade in offhand 4 times.
5. Crouch right click pedestal with export upgrade installed with a linking tool.
6. Crouch right click pedestal to be exported from with the same linking tool.
7. Repeat steps 5 and 6 for 2+ pedestals to be exported from.

### Expected behaviour

12 items exported at a time, alternating between selected pedestals

### Screenshots

![2023-07-02_23 10 35](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/52496059/99706057-3aba-44bf-a639-fc29a9d2e86e)

**Comment by mfrankov** [comment]
Augments modify the base pedestal behavior (so a capacity augment changes how many items the pedestal you insert it to can send to another pedestal for each transfer action). They have no impact on the upgrade that is on the pedestal.

For an upgrade, you need to perform a modification infusion. In this specific case it sounds like you're looking to have `Item Capacity` on your export upgrade which would allow it to export more items per operation. To do this, you'll need a `Modification Infusion` upgrade on a different pedestal setup.

As for the round-robin augment, that changes the behavior of the **sender** pedestal. There's no way to control that from the receiver pedestal end. The only work around I could offer here is to addition ally infuse `Speed` on the `Export Upgrade` to make it run faster (given you have 4 senders you'd need at least 30 Speed as that makes it take 10 ticks down from 40), and then add a 3 `Storage Augment`s (any tier) on the pedestal so that it can hold more 4 item stacks to ensure you have enough space for your sender pedestals to never fail to send.
