### ISSUE TITLE
Pedestals Obsidian Generation not working.

### ISSUE THREAD

**Issue by Furious1964** [FTBTeam/FTB-Modpack-Issues#3620]
### Modpack

FTB Skies

### Modpack version

1.3.1

### Describe the bug

Placed Crying Obsidian under a pedestal with a Material Generator Upgrade installed and lava inside pedestal and it will not generate obsidian.

### Steps to reproduce

1. Place pedestal with upgrade on top of Cry obsidian
2. fill pedestal with lava
3. Nothing happend.

### Expected behaviour

I expected it to work properly.

### Screenshots

![2023-07-02_14 42 53](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/2803725/4fcc02c9-c4d4-4999-9451-16873006b96c)

### Additional information

It should be doing something.

**Comment by mfrankov** [comment]
I believe I discussed this with you over on the Discord -- you had infused your `Material Generator` with `Item Capacity`, but due to https://github.com/Mowmaster/Pedestals/issues/230 the `Material Generator` can't craft less than it's full capacity worth of items at a time.

As mentioned, this is resolved and released in Pedestals version 0.2.52, so when the modpack updates you should no longer experience this particular issue. In the meantime, you can use a `Material Generator` with less than 16 `Item Capacity`.
