### ISSUE TITLE
Client Crash on using RefinedStorage Grid

### ISSUE THREAD

**Issue by PinkieIcePie** [FTBTeam/FTB-Modpack-Issues#3660]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.3.0

### Log Files

https://pastebin.com/BEjpmvCG

### Describe the bug

Client game crashes back to launcher when user attempts to remove items from a RefinedStorage Grid

### Steps to reproduce

1. Setup a basic storage system as described in the mod wiki
2. Place an item in the storage grid
3. Attempt to remove item from the grid
4. crash.

### Expected behaviour

Item is picked up into 'hand' (mouse) when clicked

**Comment by PinkieIcePie** [comment]
Tested JEI in place of REI and crash does not occur on the client, allowing use of the storage grid.

**Comment by epicdad843** [comment]
ooh, ok imma try JEI also because I am getting the same crash

**Comment by PinkieIcePie** [comment]
This has also been reported to REICompatabilities Issues: https://github.com/shedaniel/REIPluginCompatibilities-Issues/issues/49

**Comment by PinkieIcePie** [comment]
UPDATE: I have noticed on my server that the players using REI are now able to access the grid without the game crashing... Not sure if something has changed behind the scenes... I'll monitor it and see what I can discover :)

**Comment by secretbetta** [comment]
Hello! I am also having this issue but on FTB Unstable 1.20.1 Forge v1.5.0. Client crashes in both single and multiplayer. It happens whenever there is an interaction with any item (even when hovering over the item and closing the grid). 

Thanks for the solution @PinkieIcePie! I removed REI, REP, and REI Plugins Compatibilities and added JEI and JEP to get it working.

**Comment by Helcostr** [comment]
> the players using REI are now able to access the grid without the game crashing...

There seems to be an issue with https://github.com/shedaniel/REIPluginCompatibilities-Issues/issues/49 that got resolved in build 67+.

Because Mods like RS and AE2 have JEI integration, I suspected that that the `REIPlugingCompatabilities` would be the fix.

Updating the following fixed my JEI/REI related issues (pulling lava out of AE2 interface, and pressing ESC to exit the AE2 craft preview):

- `Roughly Enough Items (REI)` - from `12.0.634` to `12.0.684`
   - whoops I didn't realize that 67+ was referring to REI Plugin Compatibilities
- `REI Plugin Compatibilities` - from `12.0.55` to `12.0.93`

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.

Keep an eye on our social media as we may have something unstable coming out soon.
