### ISSUE TITLE
Not disappearing portal

### ISSUE THREAD

**Issue by GrishaCrysta** [FTBTeam/FTB-Modpack-Issues#3695]
### Modpack

FTB Skies

### Modpack version

1.3.1

### Describe the bug

When pick up end portal frames, portal doesn't disappear

### Steps to reproduce

1. build the correct portal
2. pick up any frame

### Expected behaviour

disappearing portal

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/111286512/4f017871-8782-4cad-9e8c-d68e9197e454)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/111286512/68f5dccb-1125-4374-8ce2-2b142f5bb89c)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/111286512/9197dd2b-fef8-4f91-a689-1a3e8dc4d63c)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/111286512/6fa5f9a4-9e86-4900-a501-71c73b961aac)

**Comment by lysinelai** [comment]
This is vanilla behavior of end portal. However, I do agree that since you can put down your own end portal in this pack, you should be able to easily move them elsewhere too. I suggest making the player able to break end portal block itself using the same code that let you pick up end portal frame in kubejs.
