### ISSUE TITLE
chunk loader from MFR

### ISSUE THREAD

**Issue by greatmonkey** [FTBTeam/FTB-Modpack-Issues#3741]
### Modpack

FTB Infinity Evolved Skyblock

### Modpack version

2.0.1

### Describe the bug

unable to craft the chunk loader from MineFactory Reloaded.  Looks like the issue might be because it using the capacitor bank from Ender IO but it is saying it has been deprecated and the ID is different from what is shown in NEI.

### Steps to reproduce

get items needed to craft,
See that you cant craft it

### Expected behaviour

to be able to craft the chunk loader

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates so this issue is likely never going to be resolved.
Any updates to this pack will only be released if there is a security issue.

An alternative to the chunk loader mentioned would be to use the FTB Utilities Chunk loader from the inventory screen.
