### ISSUE TITLE
bdlib clashing with minecraft version

### ISSUE THREAD

**Issue by dimoundk** [FTBTeam/FTB-Modpack-Issues#3743]
### Modpack

FTB Presents Skyfactory 3

### Modpack version

3.0.21

### Log Files

https://mclo.gs/qJDeTmd

### Describe the bug

The mod 'bdlib' is not compatible

### Steps to reproduce

go to a server hosting service like atenos
try to start up server after installing the modpack

### Expected behaviour

The server will say The mod bdlib does not wish to run

### Additional information

The modpack worked yesterday

**Comment by edegeltje** [comment]
I'm having the same problem.
I tried to create a new server with Aternos, installed the SkyFactory 3 modpack, and then tried starting it. It failed to do so, with the following logs:
https://mclo.gs/iCepCBs

additionally, i did some digging, and according to the modpack page, the last update to the modpack was last updated on the 1st of april, 2020. (see [the modpack page for SkyFactory 3](feed-the-beast.com/modpacks/25)) 
the [bdlib github](https://github.com/bdew-minecraft/bdlib) doesn't show a change either.

because of this, it seems to me that this may be a problem with the Aternos servers, not the modpack. i created a ticket with Aternos support, about which i have not yet received any response (which i will post when i get it).

however, if there was a change with the modpack which was not reflected in the FTB info page for the modpack, it might still be the cause.

**Comment by edegeltje** [comment]
I've been asked by Aternos support to try it again, and it worked. I have no further issues.
