### ISSUE TITLE
[Suggestion]: 1x compressed sand to sand in compacting drawer

### ISSUE THREAD

**Issue by andrewgrasman** [FTBTeam/FTB-Modpack-Issues#376]
### Modpack

FTB Oceanblock

### Is your suggestion related to a problem? Please describe.

Sand reacts differently than other compressible due to sandstone recipe. It is a simple config change that gives what I see as intended functionality. 

### Mod suggestion

add: "rid:1x_compressed_sand, minecraft:sand, 9"
to compactingRules in config/storagedrawers-common.toml

**Comment by Raidobw2** [comment]
Hi, thanks for the suggestion, however this won't be added in the game. I've talked with the modpack dev the other day to confirm that statement, and this change, even though requested a lot, will not happen.
You can read #263 where our modpack dev answers the question. The reason is that we won't override vanilla behaviour in certain mods, such as this one.
Thanks anyways!
