### ISSUE TITLE
[Suggestion]: Add Compressed Sand as default for sand in Compact Drawers

### ISSUE THREAD

**Issue by weszhuang** [FTBTeam/FTB-Modpack-Issues#377]
### Modpack

FTB OceanBlock

### Is your suggestion related to a problem? Please describe.

Issue: Placing sand in a compacting drawer will compact it to Sandstone by default with no way without changing configs to have it compact to 1x Compressed Sand. 
 tested non config methods: 
- The old trick of locking and placing the 1x compressed in doesn't appear to work in this version of storage drawers. 
- Placing sand in the drawer defaults to sandstone
- all of 1x compressed, 2x compressed, and 3x compressed sand get set to compact with the 1x compressed sand as the base compresed up to 3x compressed no matter the slot clicked on

Proposed fix:
Set the default compacting drawer config for sand to 1x compressed sand`"rid:1x_compressed_sand, minecraft:sand, 9"` through the config file and add a default for compressed sandstone back down to sand by adding a normal recipe in craft tweaker to craft sandstone into sand.

**Comment by Raidobw2** [comment]
Hi, thanks for the suggestion, however this won't be added in the game. I've had a discussion with the modpack dev a few days back, and he confirmed that this is intended to remain as it is, despite many reports asking for this change.
You can read #263 where the question is answered. The reason is that we won't override vanilla behaviour in certain mods, such as this one. You can change it in the config if you want to use it that way.
Thanks anyways!
