### ISSUE TITLE
Jei search is broken and Oreberries are bugged

### ISSUE THREAD

**Issue by Kronosmos** [FTBTeam/FTB-Modpack-Issues#3798]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.5.0

### Describe the bug

When searching something in jei like @planttech etc. its not giving me the right items or all the mods items. And there are no oreberries recipies at all. Like nothing. Even you cant replant oreplants.

### Steps to reproduce

You can try to search something on jei and see what I meant. Plus you can try to plant oreplants and see what I meant again.

### Expected behaviour

Ive expected I can replant oreberries when I encounter them in the cave for the first time. And jei not working well.

### Screenshots

![FTB Unstable 1 20 Forge 13 08 2023 17_56_06](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/101391308/2278f56e-1636-42f3-9f9f-441346d7e60f)

**Comment by raalpe** [comment]
Just to note it is REI you have shown in the picture and not JEI,
i have personally replaced REI with JEI, due to issues with refined storage and AE2.
planttech from my testing seems to work fine both with jei and rei, can you give a a specific issue?
The valid oreberries recipe is in the fifth tab with vat crafting.
For replanting oreberries you need to place them in light level 12.

**Comment by Mrbysco** [comment]
The issue should be fixed in 0.5.1 of OreBerries Replanted which is currently being uploaded to Curseforge

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.

Keep an eye on our social media as we may have something unstable coming out soon.
