### ISSUE TITLE
[Suggestion]: Update Storage Drawers to produce 1xCompact Sand vs Sandstone

### ISSUE THREAD

**Issue by Simon-Bitdiddle** [FTBTeam/FTB-Modpack-Issues#381]
### Modpack

FTB Oceanblock

### Is your suggestion related to a problem? Please describe.

The issue is a minor one but a relatively easy fix to allow the Storage Drawers Compacting Drawer to produce compact sand instead of sandstone, making it more in line with the operation of other RID-based recipes in the modpack

### Mod suggestion

Adding `"rid:1x_compressed_sand, minecraft:sand, 9"` to compactingRules should resolve the problem.

**Comment by Raidobw2** [comment]
Hello, thank you for the suggestion. I've discussed this with the modpack developer the other day, since we were getting a lot of reports about this case, but the behavior to produce sandstone is intended. You can read more about it on #263, where our dev answers the question.
In short, we do not override the vanilla behavior for certain mods, and Storage Drawers happened to be one of them in this modpack. We decided to keep it as it is. That's the primary reason why sandstone is in the current compacting rules.
You can change it in its configuration if you want the other compacting recipe.
Thanks anyways!
