### ISSUE TITLE
[Bug]: java.lang.NullPointerException: Rendering overlay

### ISSUE THREAD

**Issue by basicbox14** [FTBTeam/FTB-Modpack-Issues#382]
### Modpack

FTB Ocean Block

### Modpack version

1.9.0

### Log Files

[crash-2021-11-27_22.14.23-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7611876/crash-2021-11-27_22.14.23-client.txt)

### Describe the bug

When trying to open the game, it suddenly crashed in the loading page

### Steps to reproduce

Don't really know

### Expected behaviour

successfully launch the game

**Comment by Raidobw2** [comment]
Try updating your video drivers for your CPU, for example on Intel's site (US): https://www.intel.com/content/www/us/en/products/sku/196594/intel-core-i51038ng7-processor-6m-cache-up-to-3-80-ghz/downloads.html there's 2 downloads, one seems beta for Windows 11, the other Windows 10.
It's the first time I see that error, and it's an issue with a Renderer (graphics)!

You can also update your Java since you are using `1.8.0_74, Oracle Corporation`. The latest is something like 311 instead of 74.
You can get it at https://www.java.com/en/download/manual.jsp for example (US again).
![image](https://user-images.githubusercontent.com/17010632/143726125-6f4726ed-93c7-444f-928f-e6f370dac9a6.png)
If you use the FTB App you can simply add `-version:1.8+` in the Additional Java Arguments, in the settings for the modpack. If you use another launcher just reference it, it's normally under `%programfiles%/Java`. You'll have to enter the Java folder, then enter the folder that looks like `jre1.8.0_311` for example, then enter `bin` and you will find the Java executable named `java` (or `java.exe` if you have file extensions shown).

Please let us know if that fixed the issue or not, thanks!

**Comment by basicbox14** [comment]
emmmm, I tried jre1.8.0_311, but it still does not work. Plus, I am using a mac system so the link for windows video driver does not work for me. I really do not know what to do. Maybe I will try launching the game using windows system
[crash-2021-11-28_16.44.27-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7613103/crash-2021-11-28_16.44.27-client.txt)
.

**Comment by Raidobw2** [comment]
Odd, it's like the crash listed you had an Intel CPU. Hmm. Maybe MacOS ships Intel CPUs, I'll have to look a bit into that, but it definitely sounds graphics related.

By any chance is it a M1 Mac?

**Comment by basicbox14** [comment]
No, This laptop is a intel core macbook pro. It says it is 2 GHz four core Intel Core i5.

**Comment by Raidobw2** [comment]
Hmm. I've dug in the code with the stacktrace, and it fails at generating some JSON language files. Which language does this Macbook uses?

Open the FTB App, click on the OceanBlock tile > click Settings > scroll down and Open Folder.
You could manually add `kubejs/assets/ftboceanblock/lang/en_us.json` with the contents of https://paste.feed-the-beast.com/view/28ea03a0.
You could also manually add `kubejs/assets/sdrp/lang/en_us.json` with the contents of https://paste.feed-the-beast.com/view/6a2b952b.

Then add this into your Additional Java Arguments in the settings of the modpack, in the FTB App: `-Duser.country=US -Duser.language=en`, this will make it believe it's an english locale from the US.

I'm not sure exactly if that's the error, but it sounds to be that after digging into it. If you can confirm that it worked or not, I could relay information to our mod developer, which made KubeJS.
Thank you!

**Comment by Raidobw2** [comment]
The line in the mod where it crashes, for reference: https://github.com/KubeJS-Mods/KubeJS/blob/15eaf5d38396a9bfa23cc9a3a070d1a8ee210749/common/src/main/java/dev/latvian/kubejs/client/KubeJSClientResourcePack.java#L42

**Comment by basicbox14** [comment]
I use Chinese(mainland, Mandarin). I followed your steps but the game still crashed. Maybe I should change the language of my mac to en(US)?

**Comment by Raidobw2** [comment]
That could likely be a nice workaround, you can try it once. That'd be great if it worked, and that's totally an issue on our side in that case!

You can try that once and revert back to Chinese if you want, we'll have to fix it in the next release if that was the problem.

**Comment by basicbox14** [comment]
Emmmm, it still crashed after I turned my system to en(US). I really do not know what to do now.

**Comment by Raidobw2** [comment]
See KubeJS-Mods/KubeJS#212, try a clean reinstall of the modpack by clearing the `.localCache` folder in your instances folder.

**Comment by basicbox14** [comment]
Oh, it works! Thank you.
