### ISSUE TITLE
[Bug]: Crash when using JEI to search

### ISSUE THREAD

**Issue by TUNEinBattles** [FTBTeam/FTB-Modpack-Issues#384]
### Modpack

FTB OceanBlock

### Modpack version

1.9.0

### Log Files

https://pste.ch/ubogahoqid.rb

### Describe the bug

I go to search essence or hammer it will randomly crash on me.

### Steps to reproduce

1: Open JEI
2: Start searching for anything
3: Crashed Client on 3rd letter

### Expected behaviour

search and find recipes

**Comment by Raidobw2** [comment]
Hello, is this all the log your game generated? Could it be possible to have a crash log or the rest of the log (if there is one), since the info you posted does not make it look like the game crashed.

If you have an AMD GPU you can take a look at #40, people who have that kind of GPU will crash in JEI due to Draconic Evolution's shaders. The fix is also stated in that post, on my last comment.

I've not seen other JEI crashes not related to Draconic Evolution at this point in time, so if you can give me more info or confirm that this was the issue I would appreciate it.
Thank you!

**Comment by TUNEinBattles** [comment]
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7613723/latest.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7613725/debug.log)

I didnt know how to upload the full log. This is everything I got from debug and latest....I will look at the AMD GPU one since I have an AMD. I was able to stream me playing it for over 10 hours and then on a relog I kept crashing on a public server.

**Comment by Raidobw2** [comment]
Hmm. Is there any crash in the `crash-reports` folder, or any file in the modpack folder called something like `hs_err_pid`?

You could try to remove the RoadRunner mod in your mods folder, then try to join the server again. If it's CB multipart that crashes your game while updating neighboring blocks, I have to assume the mod works as intended and so in that case RoadRunner's mixin could be the one causing the issue and the crash, somehow.

Trying to pinpoint the issue, as it might be a mod issue if that trick worked.

Thanks for any other info!
