### ISSUE TITLE
[Bug]: Diamond Apple is not craftable

### ISSUE THREAD

**Issue by gewinner100** [FTBTeam/FTB-Modpack-Issues#387]
### Modpack

FTB Endeavour

### Modpack version

1.7.0

### Describe the bug

The "Diamond Apple" is not craftable

### Steps to reproduce

1. Open a crafting table
2. Try to craft a Diamond Apple (No Recipe shown in JEI and one Apple surounded by 8 Diamonds does not work)

### Expected behaviour

You can receive a Diamond Apple by crafting it

**Comment by Raidobw2** [comment]
Thanks, I'll look at it

**Comment by Vashidu** [comment]
i too have this issue

**Comment by Raidobw2** [comment]
Hello, this appears to be normal behavior. You have to craft the sprouts first and plant them under a leaf block. After a while, they will grow. I don't think bone meal will work to grow it faster. In the media I have random tick speed to 3000 instead of 3, that's why it grows quickly. For me 2-3 apples dropped upon breaking the crop, right-click will not work for that apple. You can try Fortune to increase the yield perhaps. Cheers.
![get_diamond_apple](https://user-images.githubusercontent.com/17010632/148388090-11119b3f-fee8-4a10-a4ed-91bb5e95ca24.gif)
