### ISSUE TITLE
[Bug]: Cant Plant Manyullyn Seeds In Bonsai Pot

### ISSUE THREAD

**Issue by Legomonster33** [FTBTeam/FTB-Modpack-Issues#39]
### Modpack

FTB Oceanblock

### Modpack version

1.1.0

### Describe the bug

title

### Steps to reproduce

1. Try to plant seed
2. Observe

### Expected behaviour

Cant Plant

**Comment by Raidobw2** [comment]
Sunekaer this would require a lot of scripting with KubeJS. Anyways here's the list of all of them from MysticalAgriculture that don't have the botany pot recipe and their mod name next to them, OceanBlock 1.1.0. Includes Manyullyn.

If some of them are not supposed to be planted in botany pots by design, then you could add a lore tag onto them to say so or disable them if they're not supposed to be there.
```
apatite (Thermal)
marble (Chisel)
limestone (Chisel)
basalt (Chisel)
tinker's bronze (Tinker's Construct)
slimesteel (Tinker's Construct)
pig iron (Tinker's Construct)
sapphire (ProjectRed Core)
ruby (ProjectRed Core)
rose gold (Tinker's Construct)
hepatizon (Tinker's Construct)
queen's slime (Tinker's Construct)
manyullyn (Tinker's Construct)
nitro crystal (Powah)
```
