### ISSUE TITLE
[Bug]: Add quest text for the Destruction Gadget quest, Shift Right-Click to configure size

### ISSUE THREAD

**Issue by MajorCooke** [FTBTeam/FTB-Modpack-Issues#390]
### Modpack

FTB Oceanpack

### Modpack version

1.9.0

### Log Files

N/A (nothing appears in the logs about building/destruction gadgets)

### Describe the bug

The destruction gadget doesn't work at all. Certainly seems like a bug, considering <ins>there's a quest for it</ins>. Also, there's limited options in the radial menu for it too.

### Steps to reproduce

Create a new world, cheat in a destruction gadget and right click on things. Nothing happens.

### Expected behaviour

Having an overlay and being able to void blocks/liquids out

### Additional information

Reproduced with a fresh installation of Oceanblock, just to be on the safe side.

**Comment by Raidobw2** [comment]
You gotta use the Radial Menu as well as Shift-right click to configure the depth. By default it won't destroy anything until you configure it.

Can you try that and report here if that was the issue?
Thanks

**Comment by MajorCooke** [comment]
...That'd do it. 

Can someone provide instructions on how to use this in the modpack itself, in the description? Like finding the Chaos Guardian, it took someone actually telling me where to find them at to figure that out instead of having it written in the quest descriptions. 

Assuming players know what to do is not exactly the ideal mindset, especially if they're new here. Draconic Evolution especially as its information tablet is incomplete now.

**Comment by Raidobw2** [comment]
Awesome haha. Most mod interactions it's right-click or shift right-click, just keep that in mind and you'll be good :)

Uncommonly it's left-click or shift left-click instead, or with Control instead of Shift.
99% of the time there's a keybind too.

As for the Chaos Guardian, there's a quest that contains that already:
![image](https://user-images.githubusercontent.com/17010632/143824178-87168f62-ec89-4d37-a55a-70f835d24b12.png)
I'll turn your request into a suggestion for the destruction gadget.

Add details onto quest in misc:
![image](https://user-images.githubusercontent.com/17010632/143824602-24ff91fd-27f0-42c2-a824-0e2745c738db.png)
Users might think it's only the radial menu, but that one also requires Shift Right-Clicking to access stuff like depth and size.

Up to dev to see if he wants to add that in the quests, since that's a Misc chapter and requires a little bit of knowledge from modded Minecraft already (play Academy for example!), or to look up the CurseForge page: https://www.curseforge.com/minecraft/mc-mods/building-gadgets, which contains tutorials.

**Comment by MajorCooke** [comment]
Interesting. I wasn't even checking the chaotic core, I was just looking at the chaos shards since that's what you need first, not the core. The "Pure Chaos!" quest in particular. I think the info about the dragon would be better suited there too.

**Comment by Raidobw2** [comment]
Our modpack dev will see that we he has the time, thanks for commenting on that as well.

**Comment by Sunekaer** [comment]
Hi,
Ill move the spawn info for the guardian to another quest.
The gadget i wont be changing the text regarding.
https://github.com/Direwolf20-MC/BuildingGadgets/wiki
