### ISSUE TITLE
[Bug]: Mekanism Energy Upgrades cause certain machines to use more power not less

### ISSUE THREAD

**Issue by TheYeti** [FTBTeam/FTB-Modpack-Issues#391]
### Modpack

FTB OceanBlock

### Modpack version

1.9.0

### Describe the bug

When placing Energy Upgrades into certain Mekanism machines it causes them to use more power not less when coupled with speed upgrades. 

Example of Chemical Infuser making Sulfur Trioxide: 
- Base 80 RF/t 
- 8 Energy 8 RF/t 
- 8 speed 32k RF/t 
- 8 Energy/8 Speed 204.8k RF/t

Have noted the behavior in the Rotary Condensator, Chemical Infuser, Electrolytic Seperator so far.  

### Steps to reproduce

1. Place machine.
2. Provide power
3. Provide raw resources
4. Insert 8 of each Power & Speed Upgrades

### Expected behaviour

Power usage goes down with energy upgrades not up.

**Comment by quietust** [comment]
It should be noted that Electrolytic Separators don't benefit from Energy upgrades at all, because if they did then you'd be able to burn the hydrogen and create a perpetual motion machine (Mekanism/Mekanism#7257).

**Comment by Sunekaer** [comment]
from dev: 
Q: Why are energy upgrades increasing the energy usage of my machine instead of decreasing it?
A: Some of our upgrades behave differently from machine to machine. In some machines in particular where the default processing rate of the machine is one operation per tick speed and energy upgrades interact in a different way than in some machines. Speed upgrades in these machines increase how many operations per tick actually occur, with the exception that if the per tick energy cost goes above the energy stored in the machine's buffer, it does not operate at "peak" efficiency and instead only performs as many operations per tick as it has energy for. This can then cause installing energy upgrades to "seemingly" increase the per tick energy cost, as each energy upgrade is also increasing the machine's max buffer size. This means that if the operations per tick was limited because of lack of energy, the machine's operation per tick (and energy per tick) goes up as the speed upgrades are allowed to provide their full effectiveness.

Edit this FAQ also has to do with part of what you are seeing:

Q: Why do energy upgrades not make the electrolytic separator use less energy?
A: There are a few machines where speed/energy upgrades behave a bit differently, the one that people notice/ask about the most is the electrolytic separator. A big reason as to why the separator doesn't reduce its power consumption with energy upgrades is to prevent infinite power looping by separating water into oxygen and hydrogen and then burning hydrogen in the gas burning generator (we already have it get separated at 100% efficiency unlike real life where it is quite a bit lower). For specifics to how energy and speed upgrades effect the electrolytic separator see: https://discord.com/channels/554379889122213888/560583846509281280/799018624740229170
