### ISSUE TITLE
[Bug]: Charset Pocket Crafting Table freezes on Shift-clicking Cobble Stairs

### ISSUE THREAD

**Issue by Jonius7** [FTBTeam/FTB-Modpack-Issues#392]
### Modpack

FTB Ultimate Reloaded

### Modpack version

1.10

### Log Files

I cannot find anything in the logs

### Describe the bug

Pocket Crafting Table freezes game on Shift-clicking Cobble Stairs
Game freezes and needs to be restarted

### Steps to reproduce

Obtain a Charset Pocket Crafting Table.
Draw crafting recipe for Cobble stairs
Shift click
Game freezes

### Expected behaviour

Craft Cobble stairs

**Comment by Raidobw2** [comment]
We don't have any active devs on the modpack for the moment, you can try updating the mod causing the error, there's a chance it will resolve it.

Either update that mod, or use version 1.11 of FTB ultimate reloaded (beta) which contains an update to Charset Lib, so it might solve it!

Otherwise don't use the item for now, use AE2 once you get to it, or move a crafting bench around.
