### ISSUE TITLE
[Bug]: Random Game Crashes

### ISSUE THREAD

**Issue by Max-VF** [FTBTeam/FTB-Modpack-Issues#394]
### Modpack

FTB Oceanblock

### Modpack version

1.9.0

### Log Files

latest.log 
https://pste.ch/ihafiwuqiq.md

debug.log 
https://pste.ch/xujupiconu.md (part 1)
https://pste.ch/botizapafa.md (part 2)

### Describe the bug

Nothing in particular causes it from what I can tell. After launching the game and playing for anywhere between 10 minutes to 2 hours, for example, the game will suddenly just close. 
The friend I'm playing with has not experienced the same crashes.

### Steps to reproduce

No idea, I can provide the world file if wanted.

### Expected behaviour

:)

### Additional information

Used to never happen but it feels like its gotten more and more frequent, maybe that's coincidence though.
Maybe the nether painting has something to do with it? I don't think I had any crashes before that. Could be a bunch of other things though idk

**Comment by Raidobw2** [comment]
That sounds just like #40. No crash-report, log ends abruptly, and OceanBlock.

If you have an AMD GPU then it's definitely that.

Type "draconic" in JEI, if it crashes go to that issue 40 for the fix, in my last comment.

For reference, crashes are generated on the root of the modpack folder, and look similar to `hs_err_pid`. They're just commonly called Java or JVM crashes instead.
Let me know if that solved it for you.

**Comment by Max-VF** [comment]
I have an nvidia gpu and typing "draconic" doesn't crash me. The textures for the tools and whatever are pink+black checkerboard though

**Comment by Raidobw2** [comment]
Are there any crash-reports or Java crashes in the format I mentioned earlier, `hs_err_pid`? Any information on these crash reports would help, since the current logs don't show anything wrong, they're normal game logs but truncated (due to the error).

What's the error code that you get when it exits? Exit codes other than 0 usually mean there is a crash report, and exit code 0 in-game would mean it's a Java crash.

**Comment by Max-VF** [comment]
I get an exit code 0
Here are the 3 most recent hs_err_pids

[hs_err_pid28172.log](https://pste.ch/aboniqivul.makefile)
[hs_err_pid21932.log](https://pste.ch/vesumikaga.makefile)
[hs_err_pid31448.log](https://pste.ch/itidosasot.makefile)

**Comment by Raidobw2** [comment]
Thanks for the reply. I've seen that issue once! It's hard to diagnose :/ I think it might be related to hardware.
You played for 33mins, 10mins and 13mins each time before crashing.
Everytime the JVM crashed, not the game itself.
Sounds like you have a machine with 32GB of RAM and you allocate 10GB, normally that's alright. We usually recommend 8GB for a client, up to you. Depends on render distance and textures, 10GB could be justified.
Everytime the JVM crashed while doing work on the `GCTaskThread` it seems. I'm not sure that means anything.

The current compilation events also almost only show rendering events everytime, might be just a coincidence:
![image](https://user-images.githubusercontent.com/17010632/144155654-6878e697-a083-43dc-8e98-7e14368cdfd2.png)

The summary would be:
-Update your Graphics Card drivers, or simply your graphics drivers if they are integrated with your CPU (onboard graphics).
-While playing Minecraft, check in Task Manager -> Resource Monitor, and see if you have a lot of "hard faults" for Java in the memory tab.
-Download a newer version of Java at https://www.java.com/en/download/manual.jsp, and add `-version:1.8+` in the Additional Java Arguments in your launcher. This will make it use the newer Java 8.
![image](https://user-images.githubusercontent.com/17010632/144156164-933925c1-afed-4041-a98d-7af40a576391.png)
-Check the Event Viewer to see if you had hardware defects or errors. Under Windows Journals, look into the Application and System tab right after you experienced crashes.
-Run memtests.

The issue does not look like it's due to the modpack, but rather could be due to some driver failing or hardware having a defect, but that's my opinion.
