### ISSUE TITLE
Wont Launch any Modpacks

### ISSUE THREAD

**Issue by FarmerMoesef** [FTBTeam/FTB-Modpack-Issues#3963]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.20

### Describe the bug

![Capture](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/147177204/2a62df40-4b16-4d4e-8595-31aae9b66af3)

### Steps to reproduce

not
sure

### Expected behaviour

should load

**Comment by manmaed** [comment]
1. Can you run any modpacks from the FTB App?
2. Can you run any  modpacks on other launchers? eg CurseForge, Prism, MultiMC eta.
3. Can you run vinilla fine

If you can run the vanilla game, but can’t run Forge, you may need to turn off the fancy early loading display. To do so, find your minecraft game folder, and edit the config/fml.toml file. Change the “splashscreen” line from splashscreen=true to splashscreen=false Make sure you come discuss your problem on the forge forums or discord, because this shouldn’t be necessary.

**Comment by FarmerMoesef** [comment]
I cant launch vanilla minecraft either because its not letting me download the update for it.

**Comment by FarmerMoesef** [comment]
but i can play any of the modpacks from the tekkit launcher. i can not play any modpacks through the ftb launcher
