### ISSUE TITLE
[Bug]: HDPE Pellet generation in Pressurized Reaction Chamber breaks at speed upgrades higher than 1.

### ISSUE THREAD

**Issue by marburps** [FTBTeam/FTB-Modpack-Issues#401]
### Modpack

FTB Direwolf20 1.16 and FTB Endeavour (Both)

### Modpack version

Direwolf20 version 1.11   , Endeavour  version 1.5.0

### Describe the bug

HDPE Pellet generation in Pressurized Reaction Chamber breaks at speed upgrades higher than 1.

(Not running out of power)

### Steps to reproduce

Create HDPE Pellets in Pressurized Reaction Chamber.
Add speed upgrades: starting from 2 upgrades and everything up, the process halts. 

(Not running out of power)

### Expected behaviour

HDPE pellet generation process should not halt at higher speeds

**Comment by Raidobw2** [comment]
Hello, that behavior is intentional. Very simply, at one speed upgrade the process uses around 700FE/t. The internal buffer of the machine is 800FE without any energy upgrades. When you add a second speed upgrade, the energy usage becomes greater than what the machine can give (the buffer), so the machine stops, that's normal.
The solution: Use energy upgrades to increase the buffer of the machine.
![image](https://user-images.githubusercontent.com/17010632/144341818-50ee120c-787f-4e9c-ab9f-095cb4c3b4fd.png)
