### ISSUE TITLE
Enderiophage only spawns in End Midlands biomes, which don't generate

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Modpack-Issues#4014]
### Modpack

FTB University 1.19

### Modpack version

all

### Describe the bug

Make them spawn in end biomes from Nullscape

### Steps to reproduce

.

### Expected behaviour

.

**Comment by kvnmtz** [comment]
I stumbled upon the same problem in my personal modpack and solved it by making changes to two config files:

1. `config/alexsmobs/enderiophage_spawns.json` (complete file)
```json
{
  "biomes": [
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "nullscape:crystal_peaks"
      }
    ],
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "nullscape:void_barrens"
      }
    ],
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "nullscape:shadowlands"
      }
    ]
  ]
}
```
2. `config/alexsmobs.toml` (replaced these two values)
```toml
enderiophageSpawnWeight = 7
enderiophageSpawnRolls = 0
```

The latter may be unnecessary but I didn't find any enderiophages without adjusting the spawning rates. Maybe I just didn't search for long enough. The former may have some unintended side-effects (can they now spawn in all biomes because I didnt set anything to negate true? I will edit this post if I notice anything like this). I just don't have any experience with adjusting Citadel's SpawnBiomeData. But these changes worked enough for me to also post them here for anyone running into the same problem :)

![grafik](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/70778888/6c02dd86-cecf-4f1c-b1a8-4724e311c0ab)
