### ISSUE TITLE
Force-loaded chunks not staying loaded ON dedicated server

### ISSUE THREAD

**Issue by MicrodenNL** [FTBTeam/FTB-Modpack-Issues#4042]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.1.0

### Describe the bug

chunks are not force loaded when al player are offline 

i have put the setting on Always for Force-loaded chunks
![ftbchunks-world snbt](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/147954609/12d1ab49-dfc5-41b7-9b4b-d43a67cafdae)
 

### Steps to reproduce

no steps

### Expected behaviour

loaded chunks

**Comment by Kadah** [comment]
Does the config change work? If so, the default behavior is safer/intentional and anybody needing always can RTM.

Its maybe more of a documentation issue (of the mod) as this default behavior since this is not mentioned in the [manual for FTB Chunks](https://help.ftb.team/help/en-gb/7-ftb-utilities/21-chunk-claiming). I only found out about this behavior via random Discord comments while looking up something unrelated to explicitly this, though would have been my next query when I discovered this behavior myself later.

**Comment by MicrodenNL** [comment]
No the Config Change did not work on both settings (Always & default ) the chunks are not force loading

**Comment by ibrudiiv** [comment]
Same behavior here on a dedicated server.

**Comment by rich-fs** [comment]
+1 I am having the same issue. As others have said I've changed the config setting force_load_mode to always, restarted the server etc and chunks are not loaded when there is no player online. I'm using a dedicated server and have the latest version of direwolf20. 1.80

**Comment by rdouda** [comment]
I'm following up on the issue related to force-loaded chunks not functioning correctly in FTB Chunks. I'm currently using the following setup:

    Mod Version: ftb-chunks-forge-2001.3.1
    Forge Version: 47.2.20
    Environment: Dedicated server

Issue Description:
Despite having the force_loaded setting to always in the server config file, chunks are not remaining loaded when no players are online.
