### ISSUE TITLE
Mod suggestion: any mods that disables the fire overlay

### ISSUE THREAD

**Issue by ChromaPIE** [FTBTeam/FTB-Modpack-Issues#4223]
### Modpack

FTB Genesis

### Is your suggestion related to a problem? Please describe.

Fire overlay shouldn't be rendered when players got fire resistance. Shouldn't be a huge problem to vanilla but in this pack the Nether ignites, and that's what makes the problem 100x more annoying.

We got a mod called Why Am I on Fire? that exactly does that but sadly that's for Fabric only. For Forge, after my rough searching and browsing, I can't even find a single mod that simply disables the overlay, let alone requiring it to have an effect-sensitive feature, y'all might want to dig deeper into CurseForge or Modrinth to find one.

Or just provide a resourcepack like https://www.curseforge.com/minecraft/texture-packs/low-on-fire

### Mod suggestion

N/A

**Comment by Saereth** [comment]
I searched around and couldnt find any mod to do it, we cant distribute that resource pack either since its all rights reserved so people will need to install it themselves. 

Also if you wear any armor that prevents wasteland radiation (Search wasteland in jei) or like your hazmat suit it will prevent the fire from applying. Later on you can genetically engineer yourself as well so it doesnt happen.
