### ISSUE TITLE
purple heart canisters do not work or max health config set too low

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#4247]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.6.0

### Describe the bug

Each heart provides 2 health. So a full soul amulet - 10 each red, yellow, green, blue, and purple heart canisters - should provide a max health of 120. However, I only get 100 max health equipping a maxed out soul amulet. It's possible the purple hearts do work and some config or other is just set too low, but either way, _at least_ 120 max health should be possible.

### Steps to reproduce

1. Fill a soul amulet with 10 each of the 5 colors of heart canisters.
2. Equip the amulet in its curio slot.
3. Health is 100 not 120.

### Expected behaviour

Max health with full soul amulet should be 120.

**Comment by Medivha** [comment]
I’m almost 100% sure (lets say 95%). Purple gives you no Health it gives you the Totem Undying effect and when triggered(instead of dying you get healed to full health) and gives you a Blue Canister back. (depending on the server config, it has x amount of chance to give it back)

so you get +80 Health(the other 20 is your base value) from Full 10x Red, Yellow, Green, Blue (can see on stats tab inventory with shift over health for what gives what)

source: [Baubley Heart Canisters](https://www.curseforge.com/minecraft/mc-mods/baubley-heart-canisters)

**Comment by DinnerBeef** [comment]
Works as intended. See above comment.
