### ISSUE TITLE
FTB claimed chunks do not prevent Twilight Forest Hydra griefing

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#4279]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.6.0

### Describe the bug

Thank you for including FTB Backup!

### Steps to reproduce

1. Spawn a hydra in claimed chunks with walls.
2. Observe blocks destroyed.

### Expected behaviour

FTB claimed chunks should block hydra griefing.

**Comment by MichaelHillcox** [comment]
Looks like Twilight Forest isn't triggering forge events when attempting to break blocks.

https://github.com/TeamTwilight/twilightforest/blob/1.20.x/src/main/java/twilightforest/util/EntityUtil.java#L61

**Comment by MichaelHillcox** [comment]
This issue is likely related to other issues like the wither also bypassing prevention. When an entity breaks blocks, this is not considered mob griefing (Excluding the creeper and endermen, they're handled specially by minecraft to make it mob griefing)

If it is the case, we've decided to not fix our mod in any way due to it making boss fights trivial which we do not intend to do. 

Are you actually able to spawn the hydra without OP or through natural twilight systems?

**Comment by jlp1528** [comment]
It's possible to get a hydra spawn egg with the capturing enchant or with the mob swab + chicken feed mechanic, then put that egg in an apotheosis spawner.

**Comment by MichaelHillcox** [comment]
That sounds like a complete abuse of mods xD Very creative but definitely abusing a couple of mods systems. The fix here is to likely prevent the hydra being captured using that enchant and the mob swab system.

That's my recommendation to our pack devs :D
