### ISSUE TITLE
I cant install a single mod to FTB Genesis

### ISSUE THREAD

**Issue by Angelo12031** [FTBTeam/FTB-Modpack-Issues#4300]
### Modpack

FTB Genesis

### Modpack version

1.2.2

### Describe the bug

i install it and when i want to go in , it doenst open

### Steps to reproduce

install any mod: like everlasting abilities
go in
doesnt start

### Expected behaviour

It just doesnt ope and the crash report doesnt say so much

**Comment by DiggityMan420** [comment]
I dont think they can help with a mod thats not installed WITH the modpack adding mod is sort of out of there hands. I maybe wrong but this also sound like a app issue not the pack. If they cant reproduce it they cant help since no logs or anything were given .That being said I did try to install "EverlastingAbilities" an i didnt have a problem. i would try uninstalling the pack and re-installing i know with FTB overwolf doesnt like windows 10 for me, So i have to use a microsoft compiled JRE

**Comment by Saereth** [comment]
We arent doing anything to prevent you adding mods, if you wanna ask around in discord if you have issues we can probably help but we dont official support modding the packs on this tracker.
