### ISSUE TITLE
[Bug]: Spelling issues in quest book

### ISSUE THREAD

**Issue by swhitt** [FTBTeam/FTB-Modpack-Issues#432]
### Modpack

FTB Oceanblock

### Modpack version

1.9.0

### Describe the bug

* The quest for the Nether Painting says `Take's` instead of `Takes`
* The quest for the Creative Mana Tablet says `Vaskii` instead of `Vazkii`

### Steps to reproduce

1. Open quest book to `Exploration` for the Nether painting, `Endgame` for the Mana Tablet.
2. View the respective quests

### Expected behaviour

The spelling should be correct

**Comment by Raidobw2** [comment]
Thanks for the report

**Comment by quietust** [comment]
Not exactly a Spelling issue, but the Endgame quest for the Creative Fluid Tank seems to have its description cut off:
`"Finally, something worthy of holding all of "`

**Comment by Raidobw2** [comment]
Thank you very much Quietust for your time! We appreciate that you layed out all those corrections for us (and well formatted too, I have to point that out), we shall correct all of those errors in the quests :^)

**Comment by Kuktar** [comment]
@Raidobw2 

I highly Recommend just using Grammarly. You can fix all of this with a single click. It is free!!!

I was noticing some spelling errors so I just had Grammarly check all the .snbts for FTBquests and it only came back with 118 errors. A large portion is because of silly phrases but about 30 or 40 spelling errors.

I am not a grammar nazi but there was one that had me rolling. "Tesseract" - "will be between" -> "between"

My English teacher used to give me an F for this lol

**Comment by Kuktar** [comment]
woops forgot to add the one i came here to report.

On the Manual Pump. finnicky should be spelled finicky

**Comment by Raidobw2** [comment]
I unfortunately did not do the quests, but thanks for the suggestion. I'll relay it to our modpack dev, which should relay it to the right person! :p 
Thanks for the typo report as well :)
