### ISSUE TITLE
not sure why but server is crashing every two days can someone please help

### ISSUE THREAD

**Issue by AustinismXD** [FTBTeam/FTB-Modpack-Issues#4385]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.8.0

### Log Files

[crash-2023-12-01_19.44.09-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13533515/crash-2023-12-01_19.44.09-server.txt)
[crash-2023-11-28_15.51.36-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13533516/crash-2023-11-28_15.51.36-server.txt)
[crash-2023-11-26_00.29.13-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13533518/crash-2023-11-26_00.29.13-server.txt)

### Describe the bug

Not really a bug but the server I'm running keeps crashing and I don't know how to read a crash report.

### Steps to reproduce

i dont know what to put here

### Expected behaviour

or here

**Comment by TheWolfNations** [comment]
In the server.properties file, set "max-tick-time" to -1 ["max-tick-time=-1"]

**Comment by AustinismXD** [comment]
The hardware should be capable enough. It's got an i3 10300 and 16g of ram. And I haven't used anything that chunk loads til the day before yesterday with the Flux points but all my machines are near world spawn anyway which should be chunk loaded shouldn't it?

**Comment by AustinismXD** [comment]
> In the server.properties file, set "max-tick-time" to -1 ["max-tick-time=-1"]

Would that turn off the backups?

**Comment by TheWolfNations** [comment]
> > In the server.properties file, set "max-tick-time" to -1 ["max-tick-time=-1"]
> 
> Would that turn off the backups?

No impact to backups, max-tick-time just tells the server, if you go above the default value to believe the server is crashed and to restart / shut down.

From the MC Wiki : 
"The maximum number of milliseconds a single tick may take before the server watchdog stops the server with the message, A single server tick took 60.00 seconds (should be max 0.05); Considering it to be crashed, server will forcibly shutdown"

Modded MC due to how many items and blocks tick consistently can breach the 60s tick, so -1 just disables the watch dog.

**Comment by AustinismXD** [comment]
I'll try that thank you

**Comment by AustinismXD** [comment]
update. its still crashing after changing the value and we realized my friends basement was made of thousands of aura blocks. we exchanged them and we can go to and from her house freely but its still crashing here is the crash report
[crash-2023-12-03_11.55.41-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13539778/crash-2023-12-03_11.55.41-server.txt)
