### ISSUE TITLE
[Bug]: Endeavour, hard crash on chunk load.

### ISSUE THREAD

**Issue by JosiahBull** [FTBTeam/FTB-Modpack-Issues#441]
### Modpack

FTB Endeavour

### Modpack version

1.8.0

### Log Files

https://pste.ch/ameholujuj.rb

### Describe the bug

Upon this chunk loading, the server hard crashes. I'm not sure what mod is causing this chunk to be unloadable.

This is a multiplayer server, this is a ""wild"" chunk, with no structures built in it by players.

### Steps to reproduce

1. Load into server
2. Move to location until chunk loads in
3. Entire server crashes, user gets a stack overflow error - other users get server closed.
4. That user cannot log in anymore, as they are loading the damaged chunk.

### Expected behaviour

Moving through the world should be possible without the server crashing.

**Comment by Raidobw2** [comment]
Hello, this could be a mod issue or an issue with Forge.
I assume some feature was going to be generated, or a list containing world gen features errored.
checkForComodification means that some kind of world gen list was being iterated and generally when that happens it's bad to remove an item from that list, as the iterator (like a looker or counter variable) will fail to continue looking up the elements one by one.
I don't see an immediate solution, only what I can think of is to remove mods partially everytime until the culprit is found, likely will be related to world gen if the chunk was never generated.
If you have your world save we can look into it. For now you can remove the player's playerdata file and give them back their inventory. Forbid users to go near that chunk if you can.

**Comment by JosiahBull** [comment]
Yup, already sorted that player out. The chunk has been previously generated and was fine then. Only recently has this issue occurred.

I am happy to provide the world save. Is there a preferred location I can put the file? Not sure how big the save is but I imagine it'll be a chunky upload.

I've told players to avoid that chunk in the meantime - doesn't seem like any others are affected.

**Comment by Raidobw2** [comment]
Well, if you want you could just pass us the region file that contains the chunk data, we can inject it into an existing world and tp to it to see if it crashes, or analyze its contents. Your crash log specifies that:
`Level spawn location: World: (256,69,192), Chunk: (at 0,4,0 in 16,12; contains blocks 256,0,192 to 271,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 8639377 game time, 3248706 day time`
Basically, inside your world folder, there will be a "region" folder. The problematic chunk is stored inside `r.0.0.mca`, so we technically only would need that file to test it, since you also gave us the modpack version. Which, now that I think of it, perhaps 1.10.1 might fix this issue if it was related with a mod, you could try loading the world in SP with an updated client.
Keep us posted and feel free to put the region file here or on some cloud service to share if it's too big for here. Thanks!

**Comment by JosiahBull** [comment]
> Well, if you want you could just pass us the region file that contains the chunk data, we can inject it into an existing world and tp to it to see if it crashes, or analyze its contents. Your crash log specifies that: `Level spawn location: World: (256,69,192), Chunk: (at 0,4,0 in 16,12; contains blocks 256,0,192 to 271,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511) Level time: 8639377 game time, 3248706 day time` Basically, inside your world folder, there will be a "region" folder. The problematic chunk is stored inside `r.0.0.mca`, so we technically only would need that file to test it, since you also gave us the modpack version. Which, now that I think of it, perhaps 1.10.1 might fix this issue if it was related with a mod, you could try loading the world in SP with an updated client. Keep us posted and feel free to put the region file here or on some cloud service to share if it's too big for here. Thanks!
> 
> Edit: Mixed up versions with another modpack while dispatching sorry, you're up to date with 1.8.0, the region file will help investigating further thanks!

Cheers Raidobw2. Find the file attached to this comment.
[r.0.0.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7689900/r.0.0.zip)

**Comment by Raidobw2** [comment]
I've tried to investigate how it crashed, for now I can't find a good reason or explanation. There's some differences in InhabitedTime and LastUpdate but that's normal from what I think, that's described at https://minecraft.fandom.com/wiki/Chunk_format for example.
I cut out Chunk (16, 12) since it was problematic (I couldn't load in either) and let it regenerate with likely a different seed than your server has, and somehow it seemed to have worked as I've now loaded in.
![image](https://user-images.githubusercontent.com/17010632/145516670-087ac05c-d5f2-41f4-8142-1e83b563422f.png)
![image](https://user-images.githubusercontent.com/17010632/145516675-781e71dd-f681-4be2-a9c5-7fac0eb1fedd.png)
Either feel free to delete the chunk yourself with NBTExplorer by opening the region file (the .mca) like below, or I've removed the chunk and let it regenerate, the result is found below the picture as well.
![image](https://user-images.githubusercontent.com/17010632/145516845-63b81801-8993-4419-aec3-6582d08c44e1.png)
[r.0.0.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7690115/r.0.0.zip)

I'll try investigate further later, if you have your world seed I'll create a new world and compare chunk data (obtainable with `/seed` when cheats are on or you are server op), that would be helpful to me.
I hope this at the least fixes the issue for some time until I find another answer!

**Comment by Raidobw2** [comment]
Well good news maybe, I did some mod updates for the upcoming 1.9.0 and tested with your region file (0, 0) and it looks like my game didn't freeze or crash. The chunk appears fine. So I guess this is fixed! 🎉 
![image](https://user-images.githubusercontent.com/17010632/148391288-47c57c0f-a630-4b13-af31-88942f61eb9b.png)

**Comment by JosiahBull** [comment]
Cheers, thanks for your attention to this. :) I'll go ahead and close this issue now.
