### ISSUE TITLE
[Bug]:  Items Being removed on Drop

### ISSUE THREAD

**Issue by BloodRedOne** [FTBTeam/FTB-Modpack-Issues#442]
### Modpack

FTB Oceanblock

### Modpack version

1.9.0

### Describe the bug

Dropped items will be randomly removed after less than a second of being dropped.
It isn't 100% of the time. If I drop a stack of carrots 1 item at a time I will have lost 8-10.
Another example is right click crop and the item shows the gets deleted right after spawned.
Tested in new world and fresh installs of modpack.

### Steps to reproduce

1. Drop items
2. Pickup items

### Expected behaviour

Items should not be instantly deleting on drop from player/barrels/crates/crops/mobs etc.

### Additional information

Also tried on newest mod pack versions.

**Comment by JeffBittle** [comment]
Yeah I was just coming to report this.  I hadn't played a whole lot on 1.9, so maybe I didn't notice it then, but since 1.10.1 came out today, I updated and decided to play for the evening.  A big project I decided to finally tackle was moving my whole sluicing setup into a compact machine.  During the move I could swear some things started going missing, but I wasn't sure until I started moving the Storage Drawers of my clusters over.  When I placed them down inside of my compact machine, my lead drawer had disappeared.  Then when I started picking them back up to put them on the wall in the order I wanted, my iron drawer disappeared when I broke it.  I restored from my backup since it had just happened.  I thought maybe it had something to do with my thermal series magnet, so I turned it off and removed it from my inventory, then tried to move my drawers again.  It seemed to be going fine, but when I broke the last drawer of cinnabar, it disappeared right in front of me.

I have no idea what could cause this, I don't have any absorption hoppers around or anything else that would be picking up loose entities.  I even tried quitting and reloading into the world to see if there was some kind of inventory desync issue, but the items are just straight up disappearing.

**Comment by sharkbite3105** [comment]
I also noticed this issue in 1.10.1 I was only moving stuff around for terraforming purposes. was able to reproduce this by pressing "q" to throw a stack of cobble some sort of despawn bug? possibly something messed up when fixing the AE2 seeds despawning in earlier versions?

**Comment by iammael** [comment]
While this issue states that the bug happens on 1.9.0, nobody has ever reported this on the Discord for 1.9.0 (and I hang out there for a while now), while a lot of reports for 1.10.1 has been made.

Not saying the report is wrong, just that it seems to happen a lot more on the latest beta.

**Comment by soronthar** [comment]
I just came to report this too... It also happened in 1.9.0, but it is definitively more common in 1.10.1. It is more noticeable when vein-mining 64 blocks at once.

**Comment by soronthar** [comment]
I removed WYML and I went from consistently reproducing the problem by rapidly dropping a whole stack item by item, sometimes watching it disappear mid air,  to not missing  a single item.

**Comment by Bimmr** [comment]
I thought I was starting to go crazy... - Can confirm this is happening on 1.10.1

**Comment by Kuktar** [comment]
Also happening to me alot. When i break a Krate like 1/4 of the items just seem to disapeer.

**Comment by rmccarthy1504** [comment]
Happening a lot for our server after the update to 1.9

**Comment by zediious** [comment]
Was there a specific configuration with WYML that was changed in next version to resolve this? I would like to resolve this a bit earlier for my server, without rolling back to an earlier version for the time being.

**Comment by Kuktar** [comment]
After removing WYML it definitly fixed the problem. i narrowed it down to lines 63 and 64 of the wyml.json

	// Set to true to spread the merging of ItemStacks between ticks. (Reduces CPU usage)
	"NORMALIZE_ITEM_STACK_MERGING": true,

Something about it trying to merge the itemstacks to save CPU usage causes it to trash items lol. With that set to false i no longer lose items.

**Comment by Kuktar** [comment]
Nevermind it still happens with that set to false.

**Comment by AlexOrtizzz** [comment]
@Kuktar try wyml 1.1.2 https://www.curseforge.com/minecraft/mc-mods/wyml/files/3556176

**Comment by Kuktar** [comment]
> @Kuktar try wyml 1.1.2 https://www.curseforge.com/minecraft/mc-mods/wyml/files/3556176

works like a charm. thanks for the update!

**Comment by Somnioblivio** [comment]
Seconding that the update to [wyml vers 1.1.12](https://www.curseforge.com/minecraft/mc-mods/wyml/files/3556176) fixed the issue

**Comment by shank3001** [comment]
Just updated the MOD. Hopefully this is a lasting fix. That bug was reeking some serious havoc.

**Comment by shank3001** [comment]
Update!! just finished, well literally just finished the pack and updating the WYML Mod worked like a champ. Now to turn my base into a creative base of paradise. Where everyone is welcome and the steaks are free!!!!
