### ISSUE TITLE
FTB Arcanum Institute  Diamond Promise Acceptor recipe

### ISSUE THREAD

**Issue by LordMatthew0** [FTBTeam/FTB-Modpack-Issues#4571]
### Modpack

FTB Arcanum Institute

### Modpack version

1.3.0

### Describe the bug

JEI shows that the Diamond Promise Acceptor requires a block of diamond and will not work with an alchemical block of diamond. As far as I can tell there is not a way to get real diamonds. 

### Steps to reproduce

Try to craft Diamond Promise Acceptor from EvilCraft. It is impossible to get a diamond block. 

### Expected behaviour

I think the recipie for Diamond Promise Acceptor needs to be changes to include alchemical block of diamond as a substitue.

**Comment by KittenIsLive** [comment]
You're able to get normal diamonds from the dungeons in the Ars Nouveau quest line (accessible after the "Mage's Spell Book" quest, and can also get emeralds from that dungeon which you can transmute into diamonds using the Ars Nouveau Transmute spell. I assume nor being able to use the alchemical diamond is intentional since it says it can't be used to craft advanced magical items.
