### ISSUE TITLE
Direwolf20 1.19 version 1.13 fails to start

### ISSUE THREAD

**Issue by wcdanh2** [FTBTeam/FTB-Modpack-Issues#4580]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.13.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13994858/latest.log)

### Describe the bug

On a fresh install of Direwolf20 1.19 version 1.13 the server fails to start.

### Steps to reproduce

1: download server installer (curl -JLO "https://api.modpacks.ch/public/modpack/101/11610/server/linux" && chmod +x serverinstall_101_11610)
2: run installer (./serverinstall_101_11610)
3: start server (./start.sh)
4: server crashes instead of launching successfully.

### Expected behaviour

Server should load sucessfully

**Comment by adracamas** [comment]
Interestingly enough I have a similar issue but with the windows launcher throwing `Invalid file name: Uppercase 'D' in kubejs/assets/direwolf20/textures/ui/button/DWL_mods_hover.png
` 
recurring over several files.

I get the same in my linux/MineOS server but it doesn't _seem_ to crash the server ( as far as I can tell but I can't access it because the launcher wont load in )

**Comment by adracamas** [comment]
Confirmation of said problem.  Went into the filesystems of both and renamed DWL*.* to dwl*.* and problem seems fixed.
`/kubejs/assets/direwolf20/textures/ui/button` is the location in both.

**Comment by Gaz492** [comment]
This issue should be fixed in the latest version of the pack
