### ISSUE TITLE
Grains of Infinity are not spawning

### ISSUE THREAD

**Issue by DW-Hanson** [FTBTeam/FTB-Modpack-Issues#4586]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12

### Describe the bug

Can't get Grains of Infinity to spawn from lighting bedrock on fire. I'm having the issue on a server and in solo creative mode.

### Steps to reproduce

1. Light bedrock on fire
2. Nothing happens after it goes out.

### Expected behaviour

A 50% chance to spawn Grains of Infinity

**Comment by DW-Hanson** [comment]
I rolled back to 1.11 and it works so it's the latest 1.12 update

**Comment by Suni-Shinobi** [comment]
having flint and deepslate clicking on grinding stone or obsidian still works

**Comment by JoschiZ** [comment]
This may be related to a bug between The Aether and EnderIO that is tracked on the EnderIO side here https://github.com/Team-EnderIO/EnderIO/issues/603 and doesn't seem to be tracked in the Aether side right now,

**Comment by KABLUEE2** [comment]
> having flint and deepslate clicking on grinding stone or obsidian still works

Even this doesn't work in my custom pack

**Comment by JoschiZ** [comment]
I added a new recipe to work around this for now.

`scripts/recipes.zs`

A variant that would add a simple smelt of redstone to grains.
```
furnace.addRecipe("grains_of_infinity_custom", <item:enderio:grains_of_infinity>, <item:minecraft:redstone>, 0, 400);
```

Or another version that adds a craft. Costing redstone and 2 health off of an flint.
```
[<item:minecraft:flint_and_steel>.anyDamage().reuse().transformDamage(2), <item:minecraft:redstone>]);
```

For some reason I liked the idea of redstone, but you can obviously use whatever you want.

**Comment by KABLUEE2** [comment]
The above comment by @JoschiZ solved it for me and is a perfect work around. Thank you so much for this

**Comment by krumble1** [comment]
Looks like @Techjar created [a fix for this](https://github.com/Team-EnderIO/EnderIO/issues/603#issuecomment-1932002926) that was just merged into EnderIO, but while we wait for the release with that fix, here's another idea for an alternate crafting recipe for grains of infinity. Happy to hear any thoughts on this, positive or negative.

- Change the Primitive Alloy Smelter's crafting recipe to use `minecraft:bricks` (the brick block) in place of the grains of infinity.
- Reason: bricks are also used in the recipe for the _Thermal Series_ redstone furnace which is a somewhat thematically similar item, and bricks are still a little bit of a process to make in the early game.
&nbsp;
- Make a Smelter recipe where 1x iron ingot, 1x coal, and 1x deepslate outputs 4x grains of infinity. This recipe should take 3,200 µI / FE.
- Reason: this recipe closely resembles the pattern for creating darksteel, but is balanced by outputting 4 items and using half the smelting energy requirement (darksteel uses 6,400 µI), since grains of infinity is a less rare ingredient than darksteel; also, coal instead of powdered coal is used since the SAG mill cannot be crafted yet and many players may not know about the mechanic of holding flint in an off-hand and coal in the main hand while shift + right-clicking obsidian to make powdered coal.
