### ISSUE TITLE
game hang and possible corruption at specific position of specific world seed

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#4588]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.0

### Log Files

[debug.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13998183/debug.zip)

### Describe the bug

Attempting to generate chunks at -1024, 512 in seed 6820972905642898635 results in an infinite and unfixable game hang. The game also fails to "save and quit" and must be terminated with task manager. Could it have something to do with this line in the log?
[20Jan2024 07:55:30.375] [Server thread/ERROR] [net.minecraft.world.entity.ai.village.poi.PoiSection/]: POI data mismatch: never registered at BlockPos{x=-997, y=4, z=519}
My debug log is 26 MB with the limit being 25 so I had to zip it.

### Steps to reproduce

1. Generate world with seed 6820972905642898635
2. Teleport to -1024 80 512
3. Game hangs.

### Expected behaviour

world should generate without hang

**Comment by jlp1528** [comment]
Disabling Iron's Spells and Spellbooks fixed this. Re-enabling it after the chunks generated seems okay.

**Comment by Ville-Saari** [comment]
I had similar problem. Approaching specific chunk made the single player internal server become unresponsive as soon as my render distance reached that chunk. I could still move around but not interact with the world and mobs didn't move and the only way to exit the game was killing the java from the command line. I determined the exact chunk by approaching it from all cardinal directions moving closer one chunk at a time and exiting the world until I couldn't exit any more. When I had narrowed the problem to a single chunk, I examined the data of that chunk in the region file.

The problem was an entity in a wrong file. There was a Wandering Trader inside the palisade wall of an Evoker Fort that wasn't saved into the entity file but region file instead like entities were saved in old Minecraft versions. When I removed that Wandering Trader and the whole entity list from the chunk data in the region file and moved it to the entity file instead, I could approach the chunk without crashing.

That Wandering Trader was obviously spawned as part of the structure. It was 'jailed' into a cobblestone doghouse with iron door, had no lamas and sold all kinds of Iron's Spells 'n Spellbooks stuff. It also had a forge:spawn_type: STRUCTURE tag in its nbt.
