### ISSUE TITLE
RAM problem without any sense

### ISSUE THREAD

**Issue by pqemis** [FTBTeam/FTB-Modpack-Issues#4603]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.1

### Log Files

Log: https://pastebin.com/XzXkGCSG
[instance.json](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14064429/instance.json)

### Describe the bug

I've been playing this modpack on Local for a while now. yesterday without having updated Java or the modpack, when I try to log in it crashes with the log
"There is insufficient memory for the Java Runtime Environment to continue"
I have 16 GB of RAM
I am not running any other programs on the computer.
I have allowed a full RAM allocation in the FTB configuration
I have tried to update the modpack and java in case they have been updated without me noticing

### Steps to reproduce

press play 

### Expected behaviour

that it loads without memory problems

**Comment by MichaelHillcox** [comment]
It looks like it crashed at the 2GB mark. Your `hs` file didn't upload to pastebin but that's a good thing as it contains sensitive information. Could you instead attach your instance.json?

**Comment by MichaelHillcox** [comment]
It looks like you've allocated 15GB to your instance. This is unneeded, the max I would ever recommend is 9 - 10GB. It also looks like your system only has 16GB of ram which is likely the reason your game is crashing. You're trying to give all of your RAM to minecraft instead of sharing the ram between the different apps on your system.

Try lowering it and try again

**Comment by pqemis** [comment]
I allowed all the RAM after crashing in case it was a memory problem. but I have limited it to 9GB as you suggested and it returns the same crash 
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/157799758/f96e855f-5c1b-4fb9-83e4-2e7c69004023)

**Comment by jlp1528** [comment]
Java is still being told to allocate 14.5 gigs of memory. 8 is more than enough. Even the default 6 is more than enough; I only increased it to 8 because once the RAM allocation fills up the game will lag spike every 5 seconds until restarted. But realistically that should not happen for a LONG time unless you are exploring a lot. Not even the chunk pregenerator mod fills up that much allocated RAM. Reinstall the modpack and reset the settings to default.
