### ISSUE TITLE
Failed to execute asset update task.

### ISSUE THREAD

**Issue by PacDucor** [FTBTeam/FTB-Modpack-Issues#4614]
### Modpack

FTB Presents Direwolf20

### Modpack version

1.12.1

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14101679/latest.log)

### Describe the bug

The game just doesn't want to start
Downloaded base minecraft launcher and started the game just fine.

### Steps to reproduce

1. install overwolf
2. install ftb
3. install direwolf20 pack
4. press play
5. error bubble

### Expected behaviour

the game starts

**Comment by Gaz492** [comment]
If this is still an issue for you, please open a new issue on our app issue tracker.
https://github.com/FTBTeam/FTB-App/issues

**Comment by PacDucor** [comment]
eat my ass you cunt, months waiting and you just close the fucking post without answering the issue.  what a dick

**Comment by Saereth** [comment]
Caused by: java.io.IOException: Data error (cyclic redundancy check) is the error in your log. This is not a pack issue. This is a system OS/Hardware/Configuration issue which we cannot even begin to help you troubleshoot due to liability concerns if we suggest system changes that make your system worse. You'll need to seek help with that issue on support pc support forums.

Furthermore,  Gaz recently came on to help with some of the back log and as this issue is quite old his request was understandable. We will now go all reflect on how best to cook your donkey for consumption. Best of luck!
