### ISSUE TITLE
[Bug]: Corrupt chunk with Building Gadget & Refined Storage

### ISSUE THREAD

**Issue by Stiicko** [FTBTeam/FTB-Modpack-Issues#466]
### Modpack

FTB Oceanblock

### Modpack version

1.10.1

### Log Files

https://mclo.gs/9lzO9Ka

### Describe the bug

Using a "Building Gadget" to build some cables from "Refined Storage" will corrupt the chunk and forcebly shut down the server or crash the game if you are in singleplayer.
Really easy to reproduce.

### Steps to reproduce

1. Have a building Gadget
2. Copy the "cables" from Refined Storage (or else using cables)
3. "Build to me" the cables
4. Crash

### Expected behaviour

For the cables to be where I wanted and not to crash and corrupt the chunk.

### Screenshots

![2021-12-11_21 17 39](https://user-images.githubusercontent.com/95982678/145690481-0a16a5bc-dd65-437f-93de-b625794e83b0.png)
![2021-12-11_21 17 54](https://user-images.githubusercontent.com/95982678/145690482-c19124a9-fc83-45a1-be40-26e3bfa70532.png)
![2021-12-11_21 18 15](https://user-images.githubusercontent.com/95982678/145690485-2b6cdcf0-d0ef-48bc-ad66-7cb87c169857.png)

### Additional information

I could join the world in Singleplayer and it crashed the game when the game Loaded the chunk (I respawned at the spawn when I first loaded the world in Singleplayer).
Do also work with "Exporters" from "Refined Storage". Other cables (I tested "Mekanism","Applied Energistics 2" or "Powah") will work fine.

**Comment by Raidobw2** [comment]
To Sunekaer: There's no blacklist config for Building Gadgets, and the log doesn't show info. Should be easy enough to reproduce and generate a crash report if there's one, in Singleplayer. Could also be just that TileEntities should not be placed by the building gadgets. Replicated by trying to place Furnaces with it for example. Then in that case it's on building gadgets's side to implement only normal blocks.

**Comment by Sunekaer** [comment]
https://github.com/Direwolf20-MC/BuildingGadgets/issues/665

**Comment by Raidobw2** [comment]
😮 Nice!

**Comment by ppozniak** [comment]
So updating to 1.11.0 won't fix previously corrupted chunks, right?

**Comment by Raidobw2** [comment]
No since it's only a config change. You'd have to either restore a backup or use an external program like NBTExplorer/Amulet to trim out the chunk and let it regenerate.
Or remove the problematic cables with one of those programs.

Anyways a backup will be easier if you have one. You can copy-paste region files from the backup to the corrupted world too, that way you lose a bit less data on your players and other region files.
I use chunk coordinate tools by Dinnerbone to find out the region file's name relative to coordinates, maybe that'll be useful to you. https://dinnerbone.com/minecraft/tools/coordinates/

If you can't fix it, give me a visit in the support channel in the FTB Discord with your world download ready and I'll fix it for you.

**Comment by davelien** [comment]
Just experienced the same corruption. I was attempting to copy/paste an area that contained Refined Storage cables and machines, as well as some Integrated Tunnels cables and Energy Exporters. Restored from backup. Lesson learned, I won't try that again. :-)

[crash-2022-01-02_09.37.09-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7799541/crash-2022-01-02_09.37.09-server.txt)

.
