### ISSUE TITLE
[Bug]: Reverted Save File

### ISSUE THREAD

**Issue by cshankyou** [FTBTeam/FTB-Modpack-Issues#468]
### Modpack

FTB OceanBlock

### Modpack version

1.10

### Describe the bug

When I started in OceanBlock in 1.7, my save file got messed up and it started me immediately on a new world when I updated. Then, after playing through on my new world for 1.8 and 1.9, the 1.10 update had me restart and the file that was available for 1.10 was my original lost save! I had a LOT more done on the 2nd save file but I do not know where to locate it? Attempted to downgrade back to 1.9 but that did not fix it, it still was the original lost file. Not sure if anything can be done or explain where to find my other save file? Any aid is appreciated.

cshankyou

### Steps to reproduce

Not really a reproducing issue. Just a weird save file swapping from wherever the saves are held? checked in %appdata% and couldn't find anything.

### Expected behaviour

To have the save file that I had for a while and not the lost one?

**Comment by Raidobw2** [comment]
You can look in your instances folder, there will be a bunch of other folders marked after long identifiers that look a bit like `11e30131-f8ce-4e04-9b77-697b903ae9c0` for example.

It might take you a bit of time, but if you remember the name of your save or approximately when you last played it, then you can look into those folders one by one and open their `saves` folder. Inside there will normally be worlds. Each folder like `11e30131-f8ce-4e04-9b77-697b903ae9c0` represents one modpack you have installed. If you have one of those bugs I saw sometimes, maybe you have multiple OceanBlock instances.

If you have issues finding it, you can run the FTB debug tool to help you find it.

I'm busy with studies for the next ~5 days due to university exams, but if you go in the FTB Discord and type precisely "!ftbdebug" with the exclamation mark in the support channel for example, you'll be given the tool to try and solve it yourself.

Then if you execute that tool it will generate a report. Don't close the screen yet, there's 2 things you can do:
- The report will show you the instance identifier like `11e30131-f8ce-4e04-9b77-697b903ae9c0` and the modpack name, FTB OceanBlock. Look at the blue text. This will help you finding back your save and solving issues if you have multiple OceanBlock instances installed for some reason.
- It will give you a debug code that you can post either in the Discord or here. Here I check less often, but if I manage to get my work done I'll try and spare some time to check your debug code and tell you where your save can be. However, I'll see the same info you will see, so I'm certain you'll be able to sort that out. Ping me in the Discord if you need help with it, my username there is "R3GEN".

Important information:
By default, instances for the FTB App are inside `%localappdata%\.ftba\instances`. I hope you'll be able to recover your save(s), keep me informed!
