### ISSUE TITLE
[Bug]: Can't connect Wireless Energy Crystal to PowerPot MK3

### ISSUE THREAD

**Issue by mortware** [FTBTeam/FTB-Modpack-Issues#474]
### Modpack

FTB OceanBlock

### Modpack version

1.10.1

### Describe the bug

It appears that you can't bind a Draconic Wireless Energy Crystal to a PowerPot MK3
It works fine for PowerPot MK2 - I haven't tested it with the other versions yet.

### Steps to reproduce

1. Connect a Draconic Wireless Energy Crystal to a power source
2. Using the crystal binder, attempt to link the crystal with a PowerPot MK3
3. You'll receive the error "That tile can not supply energy on that side!"

### Expected behaviour

Binding crystals to PowerPots should work? Or shouldn't work for a MK2

**Comment by Raidobw2** [comment]
The problem is you have your crystal in Input mode. In Input mode you're expecting the mk3 pot to generate power for you.

The mk3 for example doesn't generate power but requires some to work. Reconfigure your crystal for that purpose and that should fix it.
Example:
![image](https://user-images.githubusercontent.com/17010632/146115176-4645d179-4e78-4cb5-8c24-16dfbb8ced97.png)
