### ISSUE TITLE
Game Crashed during lanuching.

### ISSUE THREAD

**Issue by soutou233** [FTBTeam/FTB-Modpack-Issues#4746]
### Modpack

FTB Skies Expert

### Modpack version

1.1.0

### Log Files

[hs_err_pid25924.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14391943/hs_err_pid25924.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14391944/latest.log)

### Describe the bug

game crashed during lanuching

### Steps to reproduce

1. launch the game

### Expected behaviour

game crashed

**Comment by Saereth** [comment]
thats a java access violation at a system level not something specific to the pack unfortunately. Could be an issue with java, video drivers, or a myriad of other things. Unfortunately as its not pack specific I cant really offer any further technical assistance due to liability issues. Best of luck
