### ISSUE TITLE
FTB Ocean Block can't craft creative chemical tank

### ISSUE THREAD

**Issue by MiMoertel** [FTBTeam/FTB-Modpack-Issues#475]
### What Operating System

Windows 10

### App Version

1.10.1

### Debug Code

FTB-DBGHELAXAZEBU

### Describe the bug

it is not possible to craft the recipt of creative chemcal tank

### Steps to reproduce

I tryed to craft the creative chemcal tank (CCT) in Ultimate Crafting Table
Schift recipt in over JEI -> no output
place recipt manual -> no output
same in Ultimate Auto Crafting Table same results if I safe recipt it says "0x Air"

### Expected behaviour

get CCT out of Ultimate Crafting Table

### Screenshots

![2021-12-14_13 25 52](https://user-images.githubusercontent.com/79909132/145998308-591e2014-4b34-4f29-8a52-9436f8c759fc.png)

**Comment by Sunekaer** [comment]
Looks like the tanks are placed in wrong order when comparing to JEI
![image](https://user-images.githubusercontent.com/18720460/146044086-7d86d874-9452-43a7-857c-5f41df3db36b.png)

**Comment by Raidobw2** [comment]
I think it just doesn't care about NBT, it seems to take any chem tank and place it in the grid.
![image](https://user-images.githubusercontent.com/17010632/146116905-cbc77f65-e4ef-4df7-9f45-3f40d56385c6.png)
Could add quest info about it, but NBT being messy in modded is usually common so that won't be the last time they see that.

**Comment by Raidobw2** [comment]
Recipe seems to work in latest version 1.11.0
![image](https://user-images.githubusercontent.com/17010632/147752788-b67bf2bb-b08f-47e3-a5cb-42f3c0937ba2.png)
