### ISSUE TITLE
[Bug]: [FTB Oceanblock] Almost all quests do not show up when updating to 1.11.0

### ISSUE THREAD

**Issue by jackodsteel** [FTBTeam/FTB-Modpack-Issues#479]
### Modpack

FTB Oceanblock

### Modpack version

1.11.0

### Describe the bug

After updating to 1.11.0, almost all quests have been removed from the quest book. The only quests visible are Mystical Agriculture and Integrated Dynamics. I don't even have the starting quests.

### Steps to reproduce

1. Have a world in 1.10.1 with quests completed (I had the majority, not sure exactly what you need to trigger)
2. Update world to 1.11.0
3. View quest book

Note: I am on SMP in a team, unsure if that's required.

### Expected behaviour

All existing quests and quest paths should be completed

### Screenshots
![quests](https://user-images.githubusercontent.com/9209504/146119933-5eebea28-d8aa-47be-812e-79077204fbbb.png)

### Additional information

Below is my SNBT file for FTB Quests. Changed file extension from `.snbt` to `.txt` to work with GitHub

[5d94fbac-19ad-42e8-8dd5-e8b985c8b8c2.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7716371/5d94fbac-19ad-42e8-8dd5-e8b985c8b8c2.txt)

**Comment by jackodsteel** [comment]
Hmm, looking in the config, looks like most of the quest chapters aren't in my server config. Copying them in from what was in my client worked to fix it. Unsure why they would have been deleted though, that's likely still a bug.

![quest_config](https://user-images.githubusercontent.com/9209504/146123182-779316a9-d9dc-4c8c-a4d0-3f6cf51af4cd.png)

**Comment by Raidobw2** [comment]
Hmm I haven't been able to replicate it from updating a 1.10.1 server to 1.11.0. We'll look into it quickly if there's anything else we might need to check.
To Sunekaer: Ran 1.11.0 upgrade onto a 1.10.1 with server installer. Seems fine, all config data is there. Could be that the update failed or cut at some files, not sure how those files could have magically disappeared otherwise. If the files are wiped before redownloaded it makes perfect sense, but if they are not wiped and overwritten then I'm in the dark. If you can't replicate either, close the issue and I'll keep an eye open for that kind of stuff in the next days. Thanks.

**Comment by Raidobw2** [comment]
The install logic for the FTB App was rewritten and is slowly being released to the public. This should fix multiple cases of files being missed on an update for example. I will now be closing this.
