### ISSUE TITLE
[Suggestion]: Add some kind of schematic of how the Environmental tech machines should be built

### ISSUE THREAD

**Issue by GriSphera** [FTBTeam/FTB-Modpack-Issues#480]
### Modpack

FTB University 1.16

### Description of the suggestion.

While it's not my case, I've seen many people complain about being unable to build the Environmental machines, because there are barely any guides online and because the autobuild function in-mod doesn't work. There is a in-world preview function, but it is kinda funky and results in phanthom block placing/phanthom blocks in your inventory. 

So my suggestion just goes by suggesting adding screenshots or making a school, or maybe something else. Whatever is better.

**Comment by aaronhowser1** [comment]
Screenshots wouldn't really work since you can't see the details, and schools wouldn't work because you would have to leave to build it

**Comment by Raidobw2** [comment]
Patchouli could do it if you want in that case. Requires a bit of work and adding in a custom book but I can help with that if you want, I've done it before. It has in-world previews and it's in the pack already, might as well use it and learn it. Lmk Aaron.
https://vazkiimods.github.io/Patchouli/docs/patchouli-basics/page-types/#multiblock-pages
https://vazkiimods.github.io/Patchouli/docs/patchouli-basics/multiblocks
![image](https://user-images.githubusercontent.com/17010632/147430231-0be7c232-2da9-47fa-a96c-65f9c45b8018.png)
We could feature request it to Lat maybe if he wants. FTB Quests with schematics or multiblock preview would be massive for players, but that would require a bunch of work from Lat. Maybe Lat could do it with structure files though, since he's messed with it in FTB Structures. It would also make it easier for him, and integrate with KubeJS, his mod.

Here's an example for you Aaron that I've done in a custom modpack for my folks, if you want to quickly see what would the work be like in Patchouli:
```
{
            "type": "patchouli:multiblock",
            "name": "Soul Trap",
            "multiblock": {
                "pattern": [
                    [ "CBA", "DIE", "HGF" ],
                    [ "CJA", "K K", "HJF" ],
                    [ "CJA", "K K", "HJF" ],
                    [ "I I", " 0 ", "I I" ]
                ],
                "mapping": {
                    "A": "minecraft:iron_bars[east=true, north=true]",
                    "B": "minecraft:iron_bars[east=true, north=true, south=true]",
                    "C": "minecraft:iron_bars[east=true, south=true]",
                    "D": "minecraft:iron_bars[east=true, south=true, west=true]",
                    "E": "minecraft:iron_bars[east=true, north=true, west=true]",
                    "F": "minecraft:iron_bars[north=true, west=true]",
                    "G": "minecraft:iron_bars[north=true, south=true, west=true]",
                    "H": "minecraft:iron_bars[south=true, west=true]",
                    "J": "minecraft:iron_bars[north=true, south=true]",
                    "K": "minecraft:iron_bars[west=true, east=true]",
                    "I": "minecraft:iron_block",
                    "0": "soultrap:soul_trap"
                }
            },
            "enable_visualize": true,
            "text": "(Click Visualize even if it appears blank)$(br)And see next page for mobs."
  }
```

**Comment by Raidobw2** [comment]
Proof of concept for you Aaron. Our higher ups will take a look at it later too, it could be useful and the mod is almost in every modpack. I think your packs might be fine using it since their goal is to learn users how to play modded, but in my case it was for kitchen-sinks -- or modpacks that don't have any guidelines at all.

https://user-images.githubusercontent.com/17010632/147657474-17ddc892-7db7-4910-8fbf-f909d668c8d5.mp4

**Comment by Raidobw2** [comment]
FYI There is now a test FTB book in the linked issue above. This is made with the Patchouli mod, which is already integrated in almost every modpack. Feel free to use it to help you build Environmental Tech multiblocks in 1.16.5. Optionally, you can leave a short comment stating your experience with this test, this will be mostly useful to me, maybe Aaron if he likes the idea. :P

All 8 Environmental Tech multiblocks are written in JSON format and available through that test guide, similarly to what was in my proof of concept above. Everything should be intuitive!

Once the test files are added to your game, you simply craft and consume a Mechanical Apple to get started. Cheers.

**Comment by GriSphera** [comment]
Well, I did use it, and it is quite interesting. It seemed that you mentioned that it had a custom advancement that was triggered by getting a new book if the first was destroyed, but I couldn't get it to trigger. Maybe I just understood wrongly, and you were referring to the mechanical apple handling you a new book every time you ate one, which did in fact happen. 

Speaking about it, using a food item as a sort of getting you a new item after consumption is quite an interesting aproach, that at least for me was unheard of. Vanilla milk buckets could somewhat count, but they don't classify as food items. Maybe mod and modpack developers could do something with this. Like eating an apple and getting it's heart which allows you o craft some magic item, eating meat gives you as a residue animal fat, eating this sacred food in this temple gives you a golden beetle larvae, soup gives you a hair, etc.

Now tackling your suggestions.

The visual style of this test, in every aspect.

Quite interesting. I like the mechanical apple texture, but it seems funny that it has a leave when the regular apple doesn't, and also given the fact that it is well, a mechanical apple. But at the end it is still an apple. Not saying that it is bad, just silly. 

Not much to say about the FTB logo item. It is, well, the FTB logo. But some parts of the letters are translucid, which seems odd. The T in particular seems a lot less translucid that the other two, so it's more notorious.

The last texture is the book, which was kinda shocking, is the book. It differs a lot form other modded books because it uses smaller, and as a result, more pixels, which makes details a lot more evident when you hold it and even in the inventories or guis. And I like that. The book doesn't lose detail when you have on your hand, which I consider is a good thing. But talking about details, it could really use more shading overall.

You mentioned four textures and one model, but I couldn't find the last one. If it is the thing that looks like a conduit in the multiblock helper, I can say much about it. I've not met enought conduits to have a solid opinion on them. They are cool I guess. If it isn't the conduit, I'm sorry. It must have flown over my head then.

Does this make it easy to access and build multiblocks?

Well, I could say that it does. Patchouli has a great preview system and is great seeing how far you can get by creating custom books. The only thing I could complain about is not being able to rotate the models. Or at least I don't know how. That's cuz I use the void miners looking at the sky, mining from it. It counts as void. Tecnically any horizontal miner that you can ensure doesn't faces any blocks with its beam also counts. But again, I don't know if that is already in Patchouli, and I don't know if something can be done about it.

Overall, though, it works for me. But you should probably ask someone else, as I mentioned in the original post, I don't really struggle with it myself, at least with ETech. That patchouli keeps track of your progress while building is amazing though.

Other suggestions, issues, or anything you want to mention.

Nothing else really. In general, I like the aproach, and I'd like seeing it reaching further not only in this modpack (if Aaron likes the idea ofc), but in the ones to come.

At least you asked for a short comment. Jeez

**Comment by Raidobw2** [comment]
I asked for a short comment, but any size will do :p people reporting issues here is already appreciated, so I won't ask much more!
Thank you very much for your insight on this. I'll answer some of your questions:

- The textures will likely change. I'm not that good at texturing, this was indeed a test! Yeah the leaf was just to differentiate it from other apples and not making it look like a metal ball, I had to think of something quick :) although we'll probably have a texture artist or someone capable of drawing well to do that! Side note, the fourth texture is the inside of the book, the GUI. That was for the technical people, just so that they know exactly what the files contained. The conduit was a placeholder sort of, and the model is the book itself -- that's how patchouli works.

- Yes, the special advancement thing is linked to the Mechanical Apple. It goes like this: Advancements can be added and have triggers. You can have a trigger be the consumption of an item, and add a reward after eating that item. The reward I give is the book, and I use this technique because the book has special NBT data. Normal recipes don't support NBT data I think, so this was one way to do it! Then when you get that advancement reward, KubeJS resets the advancement, allowing you to eat another apple, and get another guide.

Glad that you mentioned the food crafting, I have not thought of it this way, this is interesting indeed. Hopefully we can do something with that in the future. :D

- About the rotation of multiblocks: I'm unsure if Patchouli can do that. I'll have to check. I can easily make a 2nd file and flip it in the JSON to have a 2nd multiblock to look at in the page (it will point the beam at the sky), but not sure about in-game rotations. I might feature request on Patchouli's tracker, that's a good idea thank you.

It's good that you liked the preview of the multiblock and the progress bar -- it's indeed very useful! That is good information for me, and one of the main factors for implementing this, people have to like it :)

Really cool of you to write that much feedback haha, thanks again!

**Comment by aaronhowser1** [comment]
I could also maybe do a Create Ponder, maybe
