### ISSUE TITLE
Area Upgrade on Modifier Pedestal Not working for Various Upgrades (Tested with Chopper and Fertilizer)

### ISSUE THREAD

**Issue by spoonypanda** [FTBTeam/FTB-Modpack-Issues#4818]
### Modpack

FTB Skies Expert

### Modpack version

1.2.2

### Log Files

N/A

### Describe the bug

Area Upgrade is not working for Chopper (and possibly others, someone said it was the same for the fertilizer upgrade)

### Steps to reproduce

1. Setup the 3x3 area and modifier pedestals
2. Properly link the pedestals
3. Add link card to Modifier
4. Put Chopper Upgrade in chest below modifier pedestal
5. Put items on pedestals as according to JEI entry
6. Black smoke poofs continuously but no item is made.

See screenshots for examples.

### Expected behaviour

Upgrade should appear on pedestal with increased range

### Screenshots

![step3](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/42197654/b5cd8749-52e4-4834-bf97-f62529953019)
![step2](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/42197654/b56540dc-ab12-4280-9363-247b394611cf)
![step1](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/42197654/8a0bdb39-1763-4724-8dd6-29b154860294)

### Additional information

N/A

**Comment by spoonypanda** [comment]
Additional notes:

Tried Speed upgrade, it worked.

Moved the pedestal and chest down 1 y level as well, just in case height was a factor.

**Comment by isochronous** [comment]
I'm also running into this, trying to upgrade the area of effect of an attacker upgrade (gold ingot and obsidian recipe). Pedestals are all linked with a work card, items are put in pedestals in the same order in which the pedestals are linked, modifier upgrade and work card are applied to "main" pedestal, attacker upgrade is in barrel directly below main pedestal. Nothing but black smoke.

**Comment by deathcomp** [comment]
I am seeing the same issue on version 1.3.1.  It's been there for several versions.  I am trying it on the harvest upgrade.  I can apply the speed upgrade fine so I know the setup is correct, but get black particles trying to do the area one.

**Comment by Zonk1987** [comment]
same in 1.3.2

**Comment by Zonk1987** [comment]
Until now in the current version it doesn't work.

**Comment by Mowmaster** [comment]
You need to look at the tooltip on the upgrade itself, most upgrades that can accept the Speed Infusion say ""CAN INCREASE SPEED"" similarly the upgrade needs to say "CAN INCREASE AREA" in order for the area infusion to work.

Due to recipes not being able to be conditioned based off of a config value (normally) there is no nice way as the mod dev to hide this recipe in particular. At best the pack dev could remove the recipe entirely in order to prevent this confusion


AS for how to increase an Upgrades Selection Range, You need RANGE infusions. (The linking range is similarly increased by applying range augments)

**Comment by Saereth** [comment]
this option is now enab led
