### ISSUE TITLE
[Bug]: FTB Ocean block world stuck in 100%

### ISSUE THREAD

**Issue by joacomedel** [FTBTeam/FTB-Modpack-Issues#482]
### Modpack

FTB OceanBlock

### Modpack version

1.11.0 Or 1.10.1

### Log Files

I dont havea  a log ...

### Describe the bug

I had an overflow error that was sent to the menu, I did not crash, now the world remains at 100% and does not load anymore, in other worlds I can enter. 

### Steps to reproduce

I put some cables from the powah mod and after a while using them I got the overflow error that sent me to the menu 

### Expected behaviour

?

**Comment by Raidobw2** [comment]
Restore your world from the `backups` folder. That's accessible from within the modpack folder. On the FTB App your click on your modpack icon, then on Settings. Then you scroll down and click "Open Folder". The `backups` folder will be there. Take one of the zips and extract it to your `saves` folder.

The issue is from the Powah mod once you start using too many cables of the mod. Use Pipez cables instead for the meantime. We're waiting on a mod update on the issue #195. I recommend you stop using Powah cables when you load into your world again.

Let me know if that works for you!

**Comment by Raidobw2** [comment]
Assuming fixed since I gave a solution with the message above and we already have a report on the mod author's Github.
