### ISSUE TITLE
[Bug]: Auxilium caused game not to output the crash report

### ISSUE THREAD

**Issue by Taskeren** [FTBTeam/FTB-Modpack-Issues#483]
### Modpack

FTB OceanBlock

### Modpack version

1.10.1 & 1.11.0

### Log Files

https://paste.ee/p/DSaF0

### Describe the bug

Just cannot start the game.

### Steps to reproduce

/

### Expected behaviour

/

**Comment by Raidobw2** [comment]
You can't use Java 17 for Minecraft 1.16.5. Use Java 8 or Java 11. At maximum Java 15 on some occasions, and if it works.
I see you're using Adoptium, this should be no issue for you to download their Java 11 from their front page :)
![image](https://user-images.githubusercontent.com/17010632/146659477-8d55e7aa-d5ec-4367-b302-7b76ad23c137.png)
![image](https://user-images.githubusercontent.com/17010632/146659512-6d67b350-dd7f-4a86-aa46-c88d05747882.png)
Cheers.

**Comment by Taskeren** [comment]
Thanks.

I’ve fixed the Java version problem. So I renamed the title. Auxilium throws something causing crash-report file not generating. And I visited the auxilium.ftb.dev via browser that responded  a Cloudflare pages with 522 status code.

**Comment by Raidobw2** [comment]
You can remove the mod, it only is a statistic tool for us to help us make modpacks that run on most computers.

There's probably some VPN stuff going on or a restriction on your side -- 522 means the error came from your server according to the world wide web. I'm not too familiar with those things to be honest, so I'd rather not dig into it for answers and I don't think this is a problem with the modpack in particular.
You can investigate on your side if you want, but I know removing the mod will not impact your gameplay and allow you to resume playing.
I've documented your case at FTBTeam/FTB-Mods-Issues#147 so that this can be resolved for others in the future in case they have network issues on their side and not cause a crash.
Have a good day!
