### ISSUE TITLE
[Bug]: Solid canning machine/ Crash

### ISSUE THREAD

**Issue by Thegreatbloop** [FTBTeam/FTB-Modpack-Issues#491]
### Modpack

FTB Sky Odyssey

### Modpack version

1.3.0

### Describe the bug

So I will admit I am not good with technology so I don’t know exactly what is happening and I don’t even know if this is the right place for this but I was just progressing through industrial craft 2 and had made a solid canning machine so I could get fuel rods for a reactor but when I placed it down the game lagged then crashed and now whenever I try to open the world it crashes as well.

### Steps to reproduce

So I went to try and reproduce it in another world and did the exact set up with the canning machine and the same source of power and couldn’t get it to work, after I’ve written this I realized it could be an issue with not having enough ram or something like that (again not good with computers) as I did also have a large setup with like 150+ furnace generators powering a bunch of coin miners as well as some other machines and a extreme reactor however as I don’t know if it is an issue with my computer or the mod pack I’m still going to submit the issue and sorry for wasting time if it is an issue on my end.

### Expected behaviour

Well to be honest I expected it to not crash my game not much else to it

### Additional information

I’m am seriously sorry if the way to fix it is obvious to see and I’ve effectively just wasted you time with this but I just don’t know how to fix it or if this is even how I’m supposed to put in the report.

**Comment by Raidobw2** [comment]
There's 2 ways to go with this, I can blindly tell you a solution without a crash report:
-Update the IndustrialCraft2 mod from https://www.curseforge.com/minecraft/mc-mods/industrial-craft/files/3078604. Get the file and replace the one you have in the `mods` folder (read below), then start the game.
-Or restore a backup and don't use that machine again. In the FTB App for example, click the modpack icon. Then click Settings. Then scroll down and click Open Folder. A view of your File Explorer will open. Navigate inside the `backups` folder. There's a few zips inside, each one of them represents one world, or one backup. Take the latest one and extract it somewhere. Rename the folder of that backupped world and paste it into your `saves` folder. You should be able to load back in, and remember to not use that machine else you'll crash again!

Add your crash log from the `crash-reports` folder if you can, that'll confirm it's really caused by IC2.
Let me know if either of those options work for you.
We don't have that pack under development anymore, maybe we'll update it at some point (and why I keep this issue and others), so that's the best solutions I can give you for now, they should allow you to resume playing.

**Comment by Thegreatbloop** [comment]
oh I looked into the crash report and found that it was due to a ticking block entity and updating the mod seemed to have fixed it so thanks for the help although I probably should have thought of that.

**Comment by Raidobw2** [comment]
Glad to see you got this resolved! Awesome, have fun playing ^-^
