### ISSUE TITLE
[Bug]: FTB Ultimate Anniversary edition 1.1.0 : NO immersive engineering mineral deposits in world when including KubeJS

### ISSUE THREAD

**Issue by Fredric** [FTBTeam/FTB-Modpack-Issues#495]
### Modpack

Kube JS 1605.3.19-build.229
Immersive Engineering 1.16.5-5.0.5

### Modpack version

FTB Annversary edition 1.1.0

### Log Files

https://github.com/BluSunrize/ImmersiveEngineering/issues/5129

### Describe the bug

If the KubeJS mod is included,  The Immersive engineering mods mineral deposits are not generated when i create a new world. If i take KubeJS out if the mods list it works fine. 

It is quite a serious bug since the mineral deposits are a big thing in Immersive engineering and it actually cannot be regenerated. 
The immersive engineering states that this needs to be fixed in KubeJS
https://github.com/BluSunrize/ImmersiveEngineering/issues/5129

### Steps to reproduce

1. Have both kubejs-forge-1605.3.19-build.229.jar and ImmersiveEngineering-1.16.5-5.0.5-140.jar in the mods folder. 
2. start the game and generate a world
3. Grab the "Survey tools" from immersive engineering and try to find mineral deposit (press right mouse for 3 seconds).  This will fail.

If removing Kube JS mod and doing the same steps you will find minerals. 

### Expected behaviour

There should be mineral deposit rendered in the mincraft world

**Comment by Raidobw2** [comment]
Hello LatvianModder, hope you're doing good.
The common config for IE looks fine to me: 
![image](https://user-images.githubusercontent.com/17010632/147428847-205b2d54-1a39-4902-ad8c-897532523715.png)

Apparently removing KubeJS fixes this. However that might not be the cause. The underlying problem might be part of this instead:
![image](https://user-images.githubusercontent.com/17010632/147428870-a6eb0574-1917-462b-a881-4cf5f2dec20c.png)

The only ores that show up in JEI are Electrotine (ProjectRed), Niter (Thermal) and Xen Ore (Xencraft). Not sure if this affects the registry in any way since getting an ore and checking uses works fine. That kinda needs fixing too :P otherwise tips like those become less useful?
![image](https://user-images.githubusercontent.com/17010632/147429267-60861145-998a-4f2d-ae70-1960d66ab4bc.png)

Server side config is as follows:
![image](https://user-images.githubusercontent.com/17010632/147429068-bc020d7d-709d-450e-adf7-fa2082781c20.png)
Looks like it wasn't disabled. Therefore IE might try to use its own ores in a way, but Emendatus Enigmatica replaces them. I really don't know but it's kind of odd.
I don't know how Emendatus Enigmatica works exactly or what is in the scripts, but maybe you know what's up with it. Thanks Lat.

**Comment by MaxNeedsSnacks** [comment]
Found the issue, someone removed the `"immersiveengineering:mineral_veins"` feature by ID :P
(see startup_scripts/worldgen.js)

Should be a trivial fix, just make sure before pushing that it actually *does* use the correct ore blocks to generate the veins (since I'm not 100% sure about that)

**Comment by Raidobw2** [comment]
I actually learned about this 2 days ago :) Sunekaer told me some stuff about KubeJS and world gen. Next time I'll know what to do, thanks Max and Lat for the fix!
