### ISSUE TITLE
Server Crash:  PNC Reinforced Stone

### ISSUE THREAD

**Issue by Niitek** [FTBTeam/FTB-Modpack-Issues#5040]
### Modpack

FTB Skies Expert

### Modpack version

1.6.0

### Log Files

[crash-2024-03-24_03.05.11-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14734908/crash-2024-03-24_03.05.11-server.txt)

### Describe the bug

Server crashes when trying to complete quest for PNC "Reinforced Stone", this happens when picking up the stone or using admin to force complete.

### Steps to reproduce

pick up reinforced stone

### Expected behaviour

quest complete without issue.

**Comment by LeanderBockholt** [comment]
I had a similar problem in Ars Nouveau you can fix this by editing the max time per tick in the server.properties to be more than 60 seconds and that fixed it for me. Is seems this just takes much times if many quests complete again because the questline updated and then the server kills itself. I put it to about 600 seconds and after that you can change it back to the origianl value

**Comment by Saereth** [comment]
this is a good work around yeah, hopefully wont be an issue for future pack updates
