### ISSUE TITLE
productive bees upgrade:simulator don't work

### ISSUE THREAD

**Issue by charllot1** [FTBTeam/FTB-Modpack-Issues#5056]
### Modpack

FTB Skies Expert

### Modpack version

1.6.0

### Describe the bug

when is put upgrade:simulator in bee hive bee doesn't produce any item

### Steps to reproduce

1. put upgrade:simulator in advanced beehive
2. wait for minutes until bee produce item
3. but they never produce item

### Expected behaviour

produce item properly

**Comment by fwaaade** [comment]
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/144380933/07efdfb6-2ba3-42e7-aaca-85793ac52bc4)

If you do just as your steps, that is the expected behaviour. You have to also place the flower (feeding slab or block) one in front and one down (the front is where the hole is)

But some quests for the upgrades and a short explanation would be good since this is really not obvious (I also didn't notice that Upgrade:Block didn't need electrum until I crafted my first upgrade base, so that would also be nice in the quest book).

**Comment by Saereth** [comment]
your slabs are a half block lower than they should be, there is an entire bee book from the mod that is given as part of the akashic tome that goes into great detail on the mods inner workings. The quest book is a very light guide into the changes specific to this pack not a guide on all the intricacies of each mod, this is afterall an expert pack so some learning of the mods is expected.
