### ISSUE TITLE
Steel and energy problem

### ISSUE THREAD

**Issue by Appel89** [FTBTeam/FTB-Modpack-Issues#5247]
### Modpack

FTB Ultimate: Anniversary Edition

### Is your suggestion related to a problem? Please describe.

That version should contain practically everything. But, for example, to make steel you need a device that requires steel to make. In addition, the item duct and energy duct shine when they are gone. In other words, you can't transfer energy from the power plant to the devices that need it, and the devices can't transfer their output anywhere because the item and fluid ducts are missing. However, according to the ftb Wiki, those features belong to that FTB Ultimate: Anniversary Edition

### Mod suggestion

The mod pack lacks mods that are in other versions of ftb Ultimate. And you don't notice these problems right away when choosing a package, but only after you've played for hours

**Comment by Gaz492** [comment]
Unfortunately, it was not possible to include all of the mods that were in previous versions of Ultimate due to them no longer being updated.
As for the issues you mentioned we will take a look at them and release a bug fix if possible, but this pack is considered end of life so it may not get an update to fix these issues.
