### ISSUE TITLE
Pedestals Material Generator not working

### ISSUE THREAD

**Issue by Daelin1977** [FTBTeam/FTB-Modpack-Issues#5286]
### Modpack

FTB Skies Expert

### Modpack version

1.8.1

### Pack has been modified

- [ ] Yes

### Describe the bug

Material Generator from Pedestals says "Needs Tool".  When using upgrade rod also says "No Work Area" even with defined Work Area card inserted.  Will not generate items as supposed to.

### Steps to reproduce

1 Place Pedestal on Block required for generation.
2  holding Material Generator upgrade in offhand right clicking on pedestal
3 holding Work Area Card in offhand, Right click on pedestal
4 link to pedestal on storage with export upgrade installed

### Expected behaviour

Generate Items 

### Screenshots

![2024-06-06_22 05 54](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/123903490/d71b7833-6362-4be6-8a12-f4b908f53b4e)
![2024-06-06_22 05 49](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/123903490/26927344-553b-40b6-9187-ac41146be381)

**Comment by botanySupremist** [comment]
Pedestal documentation is currently very meh, so I'll explain this.

With **nothing in your main hand and a tool in your offhand, right click the pedestal.** This will place that item into the pedestal's tool slot instead of just displaying it.

Pedestals actually simulate breaking the result block with that tool, so for example, if you have a Silk Touch pickaxe, you will get Netherrack instead of Cobbled Netherrack. This is particularly useful with Auto-Smelt tools since they will smelt the result. I have a LOT of glass due to having an Auto-Smelt pickaxe on a Material Generator that would normally produce Sand.

Also, Pedestals don't care about tool durability.
