### ISSUE TITLE
[Bug]: Game crashes on startup.

### ISSUE THREAD

**Issue by Hamaczech** [FTBTeam/FTB-Modpack-Issues#538]
### Modpack

FTB OceanBlock

### Modpack version

1.11.0

### Log Files

https://pastebin.com/4Dpiuxjp

### Describe the bug

Game crashes on startup. Unable to load certain mods. Using MultiMC.

### Steps to reproduce

>Launch MultiMC
>Add instance
>Pick FTB
>Pick FTB OceanBlock version 1.11.0
>Wait until pack downloads
>Launch pack
>Wait as pack tries to load
>Get error message

### Expected behaviour

I expected the game to load without an error.

### Screenshots

![obrazek](https://user-images.githubusercontent.com/89554445/148082572-32a9d498-f407-48ea-841c-d1378d97d7df.png)

**Comment by Raidobw2** [comment]
Hello, for Minecraft 1.16.5 you have to use Java 8 or Java 11. You can specify that in MultiMC's instance settings.
Using Java 17 will not work since it is not compatible with Minecraft 1.16.5 -- in the case of this log CodeChicken lib was the one to break first.
You can also install the modpack on the FTB App if you want to support us, the App uses Java 8 by default.
We try to use the Github only for modpack issues, so if you encounter other errors visit us in the FTB Discord first.
Have a good day!
