### ISSUE TITLE
NeoTech crashes

### ISSUE THREAD

**Issue by Slamicek** [FTBTeam/FTB-Modpack-Issues#5411]
### Modpack

FTB NeoTech

### Modpack version

1.3.0

### Has the pack been modified

No

### Log Files

https://pastebin.com/z8A8Kpz3

### Describe the bug

Minecraft crashes

### Steps to reproduce

1. start instance

### Expected behaviour

No crash

**Comment by WyFryMU** [comment]
Looks like you broke your world with Steve's carts and modern indust pipes. You can try adding this mod to the server, although im unsure if it'll work because it's labeled as Forge not NeoForge but could be worth a shot: https://www.curseforge.com/minecraft/mc-mods/neruina/files/5361855
Otherwise, while the server is starting spam the console with `/setblock -92 86 -110 dirt` and hope that will stop the corrupted steve cart.
Otherwise you might be able to spam console with `/kill @e[type=stevescarts:modular_cart]`
Worst case, you use a backup or try editing the region file. r-1.-1.mca and remove the cart.

**Comment by Slamicek** [comment]
Thank you, will try next week when I have the time.

**Comment by Slamicek** [comment]
Sadly can´t run any commands because it is a single player. The neruina has neoforge but only from game version 1.20.5. and doesn´t work with forge version or for newer mc version.

**Comment by Gaz492** [comment]
You should be able to resolve the crash you are running into by following the guide below.
https://docs.feed-the-beast.com/docs/support/Troubleshooting/ticking-entities
