### ISSUE TITLE
[Bug]: Prefab recipes not working

### ISSUE THREAD

**Issue by Wlkingstyk** [FTBTeam/FTB-Modpack-Issues#551]
### Modpack

University 1.16

### Modpack version

1.4.0

### Describe the bug

In multiplayer server the Prefab recipes are not available to craft such as starting house but moderate house shows recipe. Singleplayer recipes show fine and config files look the same. 

### Steps to reproduce

1. Open JEI interface
2. Search for Moderate house. Click on it to view recipe. 
3. Recipe shows it takes 3 Starting house blueprints. 
4. Click on Staring house in crafting grid preview to see recipe but nothing happens and no recipe showed. 

### Expected behaviour

Expected it to show recipe for starting house.

**Comment by skrrt** [comment]
As of 1.5.0, I seem to be missing almost all the recipes for the other Prefab blueprints even in singleplayer for some reason. Is this still being looked into?

**Comment by NytSong** [comment]
Going to just add that I'm seeing the same thing.  I'm thinking the problem is due to one of the server scripts, specifically removals.js
Seems server scripts don't run on single player?  
Either way, I commented out all the prefab recipe removals in removals.js on my server and all the buildings show again.  It seems by removing prefab:block_compressed_stone you don't get to see any recipes that call for compressed stone.
If that line is commented out (or deleted) it shows the prefab recipe properly and properly shows the compressed stone within that recipe as belonging to the other mod.
There are still some recipes that won't show after doing that though.

I also see above that in 1.5.0 they don't show solo or server.  If these aren't supposed to be crafted, probably shouldn't have them showing in jei. If they are supposed to be craftable... *shrug* dunno
