### ISSUE TITLE
[Bug]: Game freezes after 1 minute of play

### ISSUE THREAD

**Issue by Furious1964** [FTBTeam/FTB-Modpack-Issues#554]
### Modpack

FTB Oceanblock

### Modpack version

1.11.0

### Log Files

https://pastebin.com/x4XxutWe

### Describe the bug

Well, after doing some further testing, I'm getting the same lags/dead freeze even in a fresh install of Oceanblock. I deleted the instance and installed a fresh copy and then I loaded a world created on my Laptop. At first it worked, but after moving around, it froze again with the CPU Wattage staying near 50W. I know it's not a hardware problem as other non-minecraft games run perfectly.

### Steps to reproduce

1. Started Game
2. Loaded World imported from Laptop the New PC
3. Moved around and then checked to see if I can access the ESC Menu
4. Game froze and CPU Wattage dropped to 50W
5. Use Task Manager to kill Processes and had to reboot PC

### Expected behaviour

Expected to be able to not have the game freeze and be able to actually play the world I created on my laptop.

### Screenshots

No screenshots as I always have to reboot system.

### Additional information

It's not a hardware issue as other graphics intensive game can play without a hitch for hours.

Here is the specs for my New PC:

Case: Cougar Panzer EVO RGB.
Motherboard: ASUS TUF GAMING X570-Plus (Wi-Fi).
Processor: AMD RYZEN 9 5950X ZEN 3 3.4GHz.
OS: Windows 10 PRO Version: 21H1 Build: 19043.1466.
Cooler: Cooler Master MasterLiquid ML360R 3 Fan RGB.
PSU: Rosewell Lightning-1300 1300w.
Memory: CORSAIR Vengeance Pro RGB 128GB 3200MHz (OC) 4x32.
Graphics Card: ASUS TUF GAMING RTX 3090 (OC Edition).
SSD Drives: 2 NVMe Seagate Firecuda 2TB M2 2280 and 1 Western Digital Blue 4TB.
NVMe Heatsink: EZDIY-FAB 5V ARGB M.2 Heatsink SSD Cooler with 20mm Cooling Fan.
Remote: SilverStone Technology 2.4G Wireless Remote Computer Power/Reset Switch, USB 2.0 9-pin Interface ES02-USB.
Cables: various cables from CableMod.com and splitters.

Any help would be most appreciated.

**Comment by Raidobw2** [comment]
Hey, not sure what could cause this really. I think I mentioned things on the Discord but I'll mention them again to be sure:
- Update all drivers on the manufacturer's site including GPU ones. https://www.asus.com/Motherboards-Components/Motherboards/TUF-Gaming/TUF-GAMING-X570-PLUS/ > Support > Driver & Utility then fill in the info. GPU you can do that from GeForce Experience normally.
- Do Windows Updates if you have any pending.
- Test with a fresh installation of OceanBlock with between 6 and 8 GB of RAM assigned to minimize external factors.
- Check if you have a software that controls the CPU usage or wattage. Perhaps you might want to revert values to some defaults and test it like that.
- Pretty sure you already did that, but check the Video options in-game and make sure you've set the correct amount of FPS and enabled/disable Vsync to your preference (syncs monitor refresh rate with FPS).
- Take off mipmapping just in case, I know you have NVidia: `Disabling mipmapping on an AMD graphics card will boost FPS. This is because AMD handles OpenGL mipmapping differently than NVIDIA does, and it makes the graphics card work super hard. Open the menu in-game and click Options, then Video Settings. Slide the Mipmap Levels slider to the left to "OFF", and resume playing.`
- Use offthread rendering: `In your modpack folder, open the config folder and the file forge-client.toml with a text editor. Change the setting alwaysSetupTerrainOffthread to true, save the file, and start your game. This setting boosts FPS mostly in Singleplayer, since rendering will be done on a separate thread. It also solves lag related to block placement.`
- Try to play in peaceful and with minimal render distance. This will remove pretty much all possible lag sources if you were to stop moving.

Some fixes I found surfing the web, maybe these could help:
- Open Nvidia Control Panel > Manage 3D Settings, and set Threaded Optimization to Off, and Low Latency Mode to Off. Then hit Apply.
- When the game is opened, set Java to high priority in Task Manager. That view can be seen from the "Details" tab. You right click the program Java and set the priority like in the image.
![image](https://user-images.githubusercontent.com/17010632/149086851-07d2bab4-2359-4e44-9acc-9f99e234d370.png)

Use JVM arguments. Refer to https://www.reddit.com/r/feedthebeast/comments/5jhuk9/modded_mc_and_memory_usage_a_history_with_a/ for that matter. `-Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M`

If none of those things work, I really have no clue. There would have to be a software interfering with other programs such as Java, or perhaps all your components are pulling too much juice from the PSU, somehow. Maybe you want to underclock them as a test. Your power supply is very good and the recommended for that GPU is 850W on the site, and they include the CPU in that calculation, both overclocked, so I really wouldn't think that's possible to overcome that 1300W that you have. I'm in the dark if nothing worked.

I hope this potentially helps or at least helps you find a hint as to why it happens on your PC.

**Comment by Furious1964** [comment]
Nope, didn't work. I have no apps that are set to change the CPU Wattage on a whim, so I guess it's just Windows screwing me over again because it doesn't like the fact that Java is taking a lot of Power. Task Manager always says that its Power Levels are Very High and there's nothing I can do about it. I'm just relegated to playing Modded Minecraft on my Laptop.

**Comment by Raidobw2** [comment]
Did you compare with other modpacks? What about vanilla? Does vanilla Minecraft have that problem as well or it's only modded?

**Comment by Furious1964** [comment]
I'll test that tomorrow.

**Comment by Raidobw2** [comment]
Please do, as well as other points in my original message if you want to, otherwise you can close this ticket.

**Comment by Furious1964** [comment]
Tested with Vanilla and the other Packs and Vanilla was the only one that worked. FTB Packs failed to load world and just hung. Guess the new system just doesn't like Java.

**Comment by Raidobw2** [comment]
The only difference I see here would be that if you ran regular Minecraft without a specific profile, you would play Minecraft 1.18.1/1.18. This uses Java 17.
Most if not all FTB Modpacks currently use an old Java 8. Do you get the same results when playing on vanilla 1.16.5, where it uses Java 8?
You could also update your Java 8 https://www.java.com/en/download/manual.jsp
![image](https://user-images.githubusercontent.com/17010632/149499613-f5961ed7-ce69-47e8-a23a-46e0226f3b19.png)
Then you'll be able to specify it in the Java version on the FTB App:
![image](https://user-images.githubusercontent.com/17010632/149499700-6eec4781-e55a-4824-951a-ebc45162b6ca.png)
Then add `-version:1.8+` in that box:
![image](https://user-images.githubusercontent.com/17010632/149499800-4a0e14a6-9bcd-4b0b-bbad-8c8f14315762.png)
And start your game. Aside from that, did you try my other recommendations above?

**Comment by Furious1964** [comment]
I have that version of Java already and have also put in the Arguments.
https://imgur.com/nb2MWhE
https://imgur.com/AIBpSa0

For Vanilla Minecraft, it uses OpenJDK Platform Binary.
https://imgur.com/tBFH6JZ

Have tested it with multiple Packs...
https://imgur.com/7jKZWU3

and get the same result.
https://imgur.com/kErRMKA

I don't know what is causing this, maybe there's some setting for the RTX 3090 that's wrong, but I don't know which one. In every other Non-Minecraft game I've played, there's no problems whatsoever.

**Comment by Raidobw2** [comment]
Ok, that was good info. Your screenshots helped. I've googled a bit and found some results.
> In every other Non-Minecraft game I've played, there's no problems whatsoever.

Minecraft is almost the only game using Java :) so that's something messing with Java likely.

This caught my eye first in your last screenshot:
![image](https://user-images.githubusercontent.com/17010632/149606818-eb7ac55a-a123-4056-8189-03e4bf451c46.png)
Suspended programs are not a normal thing, and Windows wouldn't block that. Java, especially that version of Java taking 0% is not possible under normal conditions. This has lead me to believe there is a 3rd party program interfering with that Java. Particularly, the web mentions Antiviruses.
You look like you have 3 of them active, perhaps more?
1. Acronis
![image](https://user-images.githubusercontent.com/17010632/149606881-d0c2dfeb-cdc8-4055-96b5-6863268fe303.png)
2. Norton
![image](https://user-images.githubusercontent.com/17010632/149606894-e4e41443-bfe5-4054-aae4-2052152b9902.png)
3. Windows Defender
![image](https://user-images.githubusercontent.com/17010632/149606909-0a194bfd-5e66-4fca-90a4-982b1be51f87.png)

The other Java is a different program, and might be "allowed" by those 3rd party programs somehow. This one behaves like normal:
![image](https://user-images.githubusercontent.com/17010632/149606940-5a4d5899-b3b5-4151-a7df-2fc9b2880b1c.png)

Now, that's your PC and I'm not here to manage it. But in my opinion, 3 antiviruses is overkill. Norton already has an active protection service as well. Not here to give you classes because I don't know your background and competence with technology, but to get a virus you'd need to basically make a mistake or have bad browsing habits.
My recommendation to you is to compare their features and stick with one antivirus, optionally if you really feel the need one extra 3rd party firewall program as well such as MalwareBytes or any other one you find. Windows Defender is OK but paid AVs will likely be better.

Antiviruses aside, if you want to keep your data safe, use backups or cloud services. I personally use OneDrive, Google Drive, etc. Getting infected sucks and would be very unlikely with 3 AVs, but at least you don't lose any data if you have backups -- and that's the important part. Prevent data corruption/ some identity theft with AVs, keep your data safe with backups.
Take it with a grain of salt, but that's my recommendation on that as well. You have OneDrive built-in if you want to use it, if you're not using it already:
![image](https://user-images.githubusercontent.com/17010632/149607374-7ff1d8ab-5467-4c01-8788-c0cfa468755e.png)

Ok so going back on the actual problem, I think one of those programs' active protection is messing with that Java and flagging it, therefore it's put as suspended. AVs usually have "root" access since they have to protect the kernel (Windows is like your car and the kernel its engine, say system32 for common terms), so they very have the power to suspend a program.
I would recommend that you close/disable all AVs and other similar programs and that then you try to play Minecraft. You'll see if that works.
I also don't see all your other programs and it's totally fine, but if you think about other programs that could have the power to suspend other software, please check them out and disable them as a test. Think of stuff that's different from your other 2 PCs in terms of software.

I feel we are near the resolution of this issue. Please let me know about your findings once you have tested that out and if you managed to have it resolved. Thanks for your patience and cooperation!

**Comment by Furious1964** [comment]
The Shield with the Check Mark is Windows Security, it's build into Windows and tells the user whether they have an A/V or not. It usually would default to Windows Defender but if another A/V is installed, it defaults to that one instead. Norton is my go to A/V and I have it on the other machines. As for Acronis, will test if that's the cause and will uninstall it. I only used it when I had to clone an SSD to a larger SSD.

**Comment by Raidobw2** [comment]
Ah I see, I mistook it for Windows Defender then. Thanks for the info!

And awesome!! :) that was a hard one, but persevering payed off. I've learned some info and the next case to come around will be easier for me.
Enjoy the modpack on your new PC, and thanks for playing!

Cheers
