### ISSUE TITLE
Some WARN and ERROR when starting a self-hosted server

### ISSUE THREAD

**Issue by jojofox0815** [FTBTeam/FTB-Modpack-Issues#5591]
### Modpack

FTB Skies Expert

### Modpack version

1.9.0

### Has the pack been modified

No

### Log Files

[log.txt](https://github.com/user-attachments/files/16486802/log.txt)

### Describe the bug

I downloaded and installed the files from the modpack on an Ubuntu server according to the instructions from https://www.feed-the-beast.com/modpacks/server-files. The server also starts and you can play on it, but it has a lot of WARN and ERROR when starting.

### Steps to reproduce

use an ubuntu 24.04 terminal server, download the serverinstall file with the command [curl -JLO "https://api.modpacks.ch/public/modpack/117/12253/server/linux" && chmod +x serverinstall_117_12253] and run it. then run start.sh.

### Expected behaviour

There should be no or not as many warnings and errors when starting. especially not from missing files and recipes

**Comment by Gaz492** [comment]
It's common for modpacks to have warning and error messages show up in the console of both the server and client.

These can be caused by either the mods themselves or if a modpack modifies stuff like crafting recipes it can cause the no crafting recipe to show up if they decide to prevent the ability to craft an item.

As long as the modpack runs correctly, the warning and error messages can be ignored.
