### ISSUE TITLE
Having problem installing server for FTB Unstable 1.21

### ISSUE THREAD

**Issue by QuentinSthl** [FTBTeam/FTB-Modpack-Issues#5601]
### Modpack

Other...

### Modpack version

1.0.1

### Has the pack been modified

No

### Log Files

[latest.log](https://github.com/user-attachments/files/16503308/latest.log)

### Describe the bug

Hello, I'm having trouble installing a server to play with my friend, the start.bat seems to get stuck on Config at C:\Users\quent\Downloads\feed-the-beast.com\config\ftbbackups2.json has changed, reloaded!

And when i try to launch the server with the jar and try to connect to it i get this error:
![image](https://github.com/user-attachments/assets/32ce60fd-5274-4b14-9200-1f2f721d1aca)

 Can you help me ?

### Steps to reproduce

1. Downloading and launching serverinstall_124_12351.exe
2. Run start.bat
3. Get stuck

### Expected behaviour

Be able to play

**Comment by Gaz492** [comment]
If you start the server up using the jar, this will cause it to load up as a vanilla server which is whats causing the issue in your screenshot.

As for the server not starting when using the start file i believe this is due to a client only mod trying to load on the server.
If you go to the mods folder of the server, delete the `ExtremeSoundMuffler-3.48.1-neoforge-1.21.jar`
Now go back to where the start file is and also delete the world folder (this is due to the server starting as a vanilla server, your world would have generated with vanilla chunks around spawn)

Once that is done, start the server up using the start file.
