### ISSUE TITLE
[Bug]: Twilight Forest crashes pack during loading

### ISSUE THREAD

**Issue by Ravensward** [FTBTeam/FTB-Modpack-Issues#572]
### Modpack

FTB Direwolf20 1.16

### Modpack version

1.13.2

### Log Files

[crash-2022-01-18_19.41.23-fml.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7893403/crash-2022-01-18_19.41.23-fml.txt)

### Describe the bug

Modpack crashes during loading, calls out twilight forest mod.

### Steps to reproduce

open FTB app
choose Direwolf20 1.16
click play
click play on the minecraft launcher
crashes during loading.
Error Message:  The Twilight Forrest (twilightforest) encountered an error during the common_setup event phase

### Expected behaviour

I expected the modpack to load.

### Additional information

Tried to load modpack, crashed.  Updated and tried again, still crashes.  Tried downgrading to 1.12 and still crashed.

**Comment by Raidobw2** [comment]
Hi, that was an issue between one specific version of Immersive Engineering and Twilight Forest.
The FTB App update mechanism sometimes fails because of file locks -- looks that happened here. Our devs are looking into it.

To fix this, open the modpack folder in the FTB App. Then you'll enter the `mods` folder. You'll have two twilight forest mods. You want to keep `twilightforest-1.16.5-4.0.870-universal.jar` which is the latest one for the 1.13.2 version of this modpack. Remove the other one. If the files are locked, restart the FTB App and it'll work.

Then start your game again and it should be fine this time. Let me know!

**Comment by Ravensward** [comment]
Thank you, that fixed the issue.
