### ISSUE TITLE
Clicking options Music & Sounds  causes crash.

### ISSUE THREAD

**Issue by tuxokc** [FTBTeam/FTB-Modpack-Issues#5723]
### Modpack

FTB Interactions Remastered

### Modpack version

1.12.2

### Launcher

FTB App

### Has the pack been modified

Yes

### Log Files

https://mclo.gs/R7BT9sj

### Describe the bug

When trying to access the Music & Sounds screen a crash report is generated. Since LoliASM is installed I get to try over and over and over and over again!

### Steps to reproduce

Goto Options, Music and Sounds

### Expected behaviour

Music & Sounds dialog appears.

### Additional information

This likely isn't relevant to the current issue, but several mods in the server download did not match the client versions.  Some were newer in the server, others were newer in the client.  I copied mod files back and forth so both client and server had the newest versions.

**Comment by Gaz492** [comment]
It looks like the issue regarding the music and sounds menu have been fixed in the latest beta version (1.2.0)

As for the server files issue you mentioned, the server installer downloads the mods from the same place as the ftb app would, did you previously update the modpack from an older version or was this a fresh clean install?

**Comment by tuxokc** [comment]
The latest beta (1.2.0) works properly, though I had to disable magicultureintegrations-1.12.2-1.3.1.jar, as that seems to cause a failure to launch for me, but that is another issue.

**Comment by ArtpokeBr** [comment]
If this still persists in the latest pack update, please let us know. I'll close this issue for now though.
