### ISSUE TITLE
Alchemical matter infuser didn't work

### ISSUE THREAD

**Issue by fallenhistory** [FTBTeam/FTB-Modpack-Issues#5764]
### Modpack

FTB Interactions Remastered

### Modpack version

1.2.0

### Launcher

Other...

### Has the pack been modified

No

### Describe the bug

Alchemical matter infuser use pedestal as IO,it only promise one product. but most of the recipe output more than one product. so it didn't work

### Steps to reproduce

Try any recipe but except those one product.

### Expected behaviour

fix it ,use IO bus replace pedestal

**Comment by HappyManAdventures** [comment]
I have the exact same issue. Not sure what the devs were thinking here, the original FTB:I alchemical matter infuser worked perfect. They completely broke deep mob progression by changing the multiblock to this. It also refuses to do fluid recipes, because if you put the pristine matter on it with fluids it just consumes the pristine matter instead of using the fluid aswell. They need a way to select recipes and they need to bring the old multiblock structure back with the IO buses.

**Comment by ArtpokeBr** [comment]
1. we changed the structure to make it look better.
2. Simple fix, now you'll be able to place output buses just like Input Hatches in the structure =)

**Comment by HappyManAdventures** [comment]
still no way to select recipes. pristine slime matter recipes are broken because it just consumes the slime matter first and makes a slimeblock instead of using the fluids too to make the slime pearl.
