### ISSUE TITLE
[Bug]: Can log in to oceanblock server

### ISSUE THREAD

**Issue by Flamebom** [FTBTeam/FTB-Modpack-Issues#579]
### Modpack

FTB Oceanblock

### Modpack version

1.11.0

### Log Files

server log: https://gist.github.com/Flamebom/c23ff0bbad036410a9a2ec8fdb9914f8
client log: https://gist.github.com/Flamebom/32af5c7caaa0da24dd0e4fb4b7b12c65

### Describe the bug

Most of the time, when connecting to my server the game crashes and disconnect me instead of connecting me. Happens to other players as well.

### Steps to reproduce

1. Load the server
2. Load the client
3. Try logging in with client
4. get disconnected

### Expected behaviour

Connect to the server with no problems

**Comment by Raidobw2** [comment]
Hi, this could be a lot of things.
Since it looks like you can play sometimes, it could be due to a network configuration on the server's end. If the server is using a firewall for example.
First things, you should try to cleanly install a server from us, take https://feedthebeast.notion.site/How-do-I-setup-my-own-server-43b4c6b83f264dc6b2fb7a9566864ab0 as an example.
Then you can add your current world to that server, as well as any other files you want to keep. Upload those server files to your host / put them on the local server, whichever you're using.

If you're using an online host, you should ask them about network issues if it persists since they handle that part.
If you're hosting it yourself or on a local machine, you might want to check that machine's firewall rules to allow incoming Java traffic. As well, which is probably already the case, you'll need to open the port for the server, which is port 25565 by default.

Let me know if the problem persists after you've tried those things!

**Comment by Flamebom** [comment]
restarting the server on a clean instance i think fixed the problems
