### ISSUE TITLE
[Bug]: Tempered Jars don't allow sub-zero recipes.

### ISSUE THREAD

**Issue by rosso4001** [FTBTeam/FTB-Modpack-Issues#58]
### Modpack

FTB Oceanblock

### Modpack version

1.1.0

### Describe the bug

Ice, Packed Ice, Blue Ice don't work to make the Tempered glass jar use sub-zero recipes.

### Steps to reproduce

Have a water bucket in inventory
Place ice variant underneath a tempered glass jar
Click on the jar
No recipe to make ice is available.

### Expected behaviour

Cold block under jar should allow sub-zero recipes.

**Comment by Raidobw2** [comment]
Hello! I've talked with the mod dev about this the other day and the interaction with buckets is not working perfectly, as you saw, but using another jar with water is the intended way to do it. Here's the setup that'll make it work for you:
![image](https://user-images.githubusercontent.com/17010632/135696293-852a350e-5d26-430a-90de-fdfa8524ffd6.png)

I'll still forward this issue to the dev, but it might be on low priority since the way to do it with the jars work.

**Mikey, Sune or Jake please transfer this issue to Mod-Issues when possible, this is strictly about FTB Jars, thank you.**

**Comment by rosso4001** [comment]
Thank you.
