### ISSUE TITLE
[Bug]: Crash when left AFK overnight

### ISSUE THREAD

**Issue by kadeska** [FTBTeam/FTB-Modpack-Issues#584]
### Modpack

FTB StoneBlock-2

### Modpack version

1.21.1

### Log Files

[crash-2022-01-25_05.58.18-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7938490/crash-2022-01-25_05.58.18-client.txt)

### Describe the bug

I left the game alone with my inventory open over night. I looked at the game in the morning and it had crashed overnight to a crash menu. 

### Steps to reproduce

Play game... Open inventory... leave AFK overnight... check in the morning. 

### Expected behaviour

I expected to come back to the game right where I was at in the morning.

### Additional information

I had a simple mob spawner set up as well as a bunch of drawers with a drawer controller in my base. I also had a few chickens growing and laying eggs for me to progress through the chicken stuff.

**Comment by Raidobw2** [comment]
Hi, your game ran out of memory overnight `java.lang.OutOfMemoryError: Java heap space`. This is probably not something we can fix I think. I don't know how many things happened overnight but with 5.4GB allocated to the game and with farms running, it'll get saturated quickly if there's a tiny leak or simply too many objects in the game. I have started in-dev updating Stoneblock 2 but it will take some time since I don't want to break anything and keep the pack working.

I'd recommend you allocate more than 5.4GB to the game -- perhaps using 7GB or 8GB would greatly help in your case since you like to leave it open to AFK for resources. You could also use a local server and simply chunkload with FTB Utilities, that would also be a good solution and would not use any graphics over night as well, using your computer's resources without really playing.
Alternate solution would also be to use an online host if you AFK a lot. You can leave the server load to the host and chunkload like you want.

I can't give you another solution -- It ran out of RAM, it needs more if you plan on AFKing. The JVM, especially with modded Minecraft isn't the cleanest solution when it comes to software and might require a restart every now and then.

**Comment by kadeska** [comment]
Thank you for the response. I have since increased the amount of allocated ram to 10gb. An idea for the development team is to set up a profiler to watch the ram usage and see where there might be a memory leak.

**Comment by Raidobw2** [comment]
Will do once I get to it, thanks
