### ISSUE TITLE
[Bug]: This MineTogether is making me rage so bad

### ISSUE THREAD

**Issue by SoftGuardian** [FTBTeam/FTB-Modpack-Issues#591]
### Modpack

FTB Oceanblock

### Modpack version

1.11.0

### Log Files

https://pste.ch/jokorekeve.sql

### Describe the bug

The first time I play an FTB pack is worst than my life, the "sponsor" is making this hard. Each time I click play on the launcher it instantly crashes the game in less than half a second! The logs clearly show it's because of it. I removed the mod, messed with it's configs, enabled& disabled it on the settings, scrolled the whole internet my eyes burning and found nothing useful. Respectfully, a solution please.

### Steps to reproduce

1. Launch the launcher
2. Crash.

### Expected behaviour

Just the game starting

**Comment by Raidobw2** [comment]
Hi, normally after removing the mod from the `mods` folder there shouldn't be more issues caused by it on OceanBlock. The issue might lie somewhere else.

If you have removed the mod and clicked Play on the FTB App to bring up the Minecraft Launcher, you can do a few tests to pinpoint the issue.

Before pressing Play on the Minecraft Launcher, you can close the FTB App. Then press Play in the Minecraft Launcher. If the game starts successfully, a file in the App could have been corrupted somehow. You can backup your instances folder and then reinstall the FTB App by deleting the `.ftba` folder inside your `%localappdata%` (put this path into the box after pressing Windows key + R). Again, make sure you copy-pasted your instances folder somewhere else to keep your worlds safe while you reinstall, otherwise those files will be deleted as you delete the `.ftba` folder.

If you still crash with the FTB App closed (a crash window saying "The game crashed" will always accompany a crash -- if you don't get that window, try rebooting your PC), I would need a game log. The one you posted is the App log, so that kind of log won't show what's wrong with the game. In the modpack folder, you will find the `logs` folder. Inside is a `latest.log` file. This is the game log.

You can also stop by the FTB Discord in the support channel for this kind of issue. Cheers.

**Comment by SoftGuardian** [comment]
The problem is still there, there is no game logs because the game doesn't even launch. I feel like the problem is the jar files specifecally 1.16.5-forge-36.2.20.jar is corrupted and if I try to delete the versions then download it when hitting the play button it either fails or half way done and launch the game which I can't find a solutio to.

**Comment by Raidobw2** [comment]
Ah I see, in that case you can install Forge 36.2.20 for Minecraft 1.16.5 manually with this https://www.notion.so/feedthebeast/Manually-installing-Forge-into-the-FTB-App-d0473bbea1aa43d6ae3830bea686bc13.
This will reinstall the Forge versions, and when you play the game the MC Launcher will download the game versions for vanilla as well since they are a dependency of Forge.

Forge needs a valid `launcher_profiles.json` to be installed, sometimes that file isn't present in good form. If that's the case, you can take the one from vanilla. Copy the one in `%appdata%\.minecraft` and paste it in the FTB App folders at `%localappdata%\.ftba\bin`. Forge should install correctly for sure after that.

In the Discord I have tools and can link you those documents in an instant, next time come there first.
Let me know if that solves it since it looks like a launch issue as you described it. We'll look into other solutions if that didn't work.

**Comment by SoftGuardian** [comment]
This kind of works until forge doesn't install. The error message it says "Failed to download version manifest, can not find client jar URL."
My java version is the latest right now.
And yes I have it set the path required, here is an installer log: https://pste.ch/favepuvewa.nginx

**Comment by SoftGuardian** [comment]
Never mind I had to launch vanilla 1.16.5 then retry and it works! The game launches just fine thank you so much for your help!

**Comment by Raidobw2** [comment]
Awesome, glad to hear that. Enjoy the modpack and have fun!
