### ISSUE TITLE
[Bug]: Massive FPS drop when looking down

### ISSUE THREAD

**Issue by SoftGuardian** [FTBTeam/FTB-Modpack-Issues#596]
### Modpack

FTB OceanBlock

### Modpack version

1.11.0

### Log Files

https://pste.ch/ejidabewor.md

### Describe the bug

When I look in the sky or in front my fps is +80 but when I look down it drops down to 25 or even -20. I have installed Optifine HD G7 and still the same.

### Steps to reproduce

1. Look up, normal performance
2. Look down, performance drop

### Expected behaviour

Just not beeing obnoxious

### Screenshots

![2022-02-03_17 06 24](https://user-images.githubusercontent.com/73778546/152392672-a53c99b8-a836-43d0-b469-000bc0be9813.png)
![2022-02-03_17 05 46](https://user-images.githubusercontent.com/73778546/152393039-82641a47-defd-4eef-afb3-c37efd6730b6.png)

### Additional information

I feel like it's because of the massive amount of mobs and blocks, animated textures underwater
Btw don't count that command I tried to find the issue by going to spectator

**Comment by Raidobw2** [comment]
Hi, please use the Feed the Beast Discord next time, we try to use this Github only for bugs or suggestions regarding Modpacks. I have tools on the Discord and the community can help you as well.
https://ftb.team/discord

I wouldn't use Optifine to gain performance, especially with shaders it tends to have the opposite effect. You do you, but I would remove it.

AMD GPU: Disabling mipmapping on an AMD graphics card will boost FPS. This is because AMD handles OpenGL mipmapping differently than NVIDIA does, and it makes the graphics card work super hard. Open the menu in-game and click Options, then Video Settings. Slide the Mipmap Levels slider to the left to "OFF", and resume playing.

Use offthread rendering: In your modpack folder, open the config folder and the file forge-client.toml with a text editor. Change the setting alwaysSetupTerrainOffthread to true, save the file, and start your game. This setting boosts FPS mostly in Singleplayer, since rendering will be done on a separate thread. It also solves lag related to block placement.

BetterFPS for Render Distance: https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance This will cull chunks in a sphere around you, so some things under the island will not be rendered and this should improve FPS.

EntityCulling: https://www.curseforge.com/minecraft/mc-mods/entityculling Same kind of thing, but will not draw entities that you can't see.

Magnesium: https://www.curseforge.com/minecraft/mc-mods/sodium-reforged Should improve FPS in general, although it might visually break the game. If things look weird, don't keep it and only use the above options.

If you get further issues or have more questions, please use the Feed the Beast Discord and ask in our support channels or pack channels. Thanks.
