### ISSUE TITLE
Sheldonite ore is present in JEI but inaccessible

### ISSUE THREAD

**Issue by Delfayne** [FTBTeam/FTB-Modpack-Issues#5961]
### Modpack

FTB Interactions Remastered

### Is your suggestion related to a problem? Please describe.

Sheldonite is not presently accessible. It presents a more efficient way to reach osmium, and should probably be added to veins on Aurellia to provide incentive to mine it there.

**Comment by keeptpa** [comment]
Actually this kind of case appears a lot, so I would believe it's rather a nerf(ore generation disabled for balance?) or just forgot to enable it. Now I'm gathering osmium by the reactor MK-I using copper and silver. It's still annoying.

**Comment by Delfayne** [comment]
I didn't explicitly disable sheldonite when I wrote the first draft of oregen, I just missed it.

Someone raised this as being a better source of osmium as per JEI and I agree that it makes sense to include it in a future build.

**Comment by keeptpa** [comment]
> I didn't explicitly disable sheldonite when I wrote the first draft of oregen, I just missed it.
> 
> Someone raised this as being a better source of osmium as per JEI and I agree that it makes sense to include it in a future build.

I agree with that, since osmium is still quite hard to obtain even in late game, you still have to deal with the platium sludge in bullk that require a lot of digging. Same to the platium and titanium, it will be great to have them enable in the ore generation. It could be gated behind some state, like after moon or sth.
