### ISSUE TITLE
Bug with sophisticated backpacks and player data

### ISSUE THREAD

**Issue by Gylvaris** [FTBTeam/FTB-Modpack-Issues#6069]
### Modpack

FTB Evolution

### Modpack version

1.0.3

### Launcher

FTB App

### Has the pack been modified

Yes

### Log Files

https://pste.ch/foveyejugi.pl

### Describe the bug

I have no idea what's happening… I have a diamond backpack with feeder upgrade and stack upgrade and 127 cooked beef, after few moments, I can't do anything on the server and after relog on the server console all I see is this error. Probably problem with solonion (spice of life onion) mod.

### Steps to reproduce

1. Have diamond backpack with feeder upgrade, stack upgrade and more than a stack of one food
2. wait a moment or teleport (No idea what's going on with that, maybe then player data is trying to reload)
3. See error (Elevators don't work etc.)
4. After relog you are where your last player data was saved with items u had (This way u can multiply items)

### Expected behaviour

Player data should be saved

**Comment by Gaz492** [comment]
It looks like this may be a mod issue with sophisticated backpacks, there is an update for the mod out which may fix the issue, we will test this update and release a pack update soon
https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/1193

As for you not being able to connect to the server, you could try to edit your player data so that the backpack is no longer feeding you, or restore a world backup.

**Comment by Gylvaris** [comment]
> It looks like this may be a mod issue with sophisticated backpacks, there is an update for the mod out which may fix the issue, we will test this update and release a pack update soon
> https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/1193
> 
> As for you not being able to connect to the server, you could try to edit your player data so that the backpack is no longer feeding you, or restore a world backup.
> 
> 

I was able to join the server, for now I just keep one stack of each food in my backpack.
