### ISSUE TITLE
[Bug]: Modload fail and modpack not quite working

### ISSUE THREAD

**Issue by Stefan08p** [FTBTeam/FTB-Modpack-Issues#608]
### Modpack

FTB Oceanblock

### Modpack version

1.11.0

### Describe the bug

So today I downloaded your mod, installed it and launched on 1.16.5. Then Minecraft just said unable to load 9 mods over and over again. I looked up on the internet and saw that I need forge for them. So I dowloaded forge. they still wouldn't work, so I moved them out of the mods folder, so I could actually launch Minecraft. It actually loaded, but I saw normal 1.16 Minecraft menu with forge. I created a new seed and the mods worked I think but it turned out to be a normal seed, not an island, no ocean, no rafts etc.. Please help me and tell if I'm doing something wrong or what. The mods I moved out were: bamboo everything, botanica, better end and ambientsounds v3(because it said they're not a .jar file), xnetgases, BackTools, Common Capabilities, MysticalCustomization and finally MysticalAgrAdditions. Also I mentioned 9 mods and now I said I deleted just 7, and that's because mysticalcustomization and mysticalagradditions were doubled in the crash menu.                   
Sorry if this is not a bug and I report it as a bug, I just need help.

### Steps to reproduce

No idea, already described it in bug description itself

### Expected behaviour

Someone tell me what I did wrong or what happened and how to fix it

**Comment by Raidobw2** [comment]
Hello, come on the FTB Discord next time, I can link you documents way more easily.

Usually what you got is due to a network connection that is not top notch. That's fine, there's still ways to fix it and our app devs are currently reworking the install procedure to help out those people.

First you want to cleanly reinstall. If you press "Windows Key + R", you can put `%localappdata%\.ftba\instances` and press Ok. This will open up the instances folder. Inside you will delete the `.localCache` folder, and then you will close the FTB App. You will reopen the FTB App and reinstall the modpack. Then play it. If you still get mod errors, you might want to install a server on the side to patch your client. See below.

To install a server, refer to https://feedthebeast.notion.site/Installing-a-Feed-the-Beast-Server-aeaea8a7220945d0ad0357c80c6c9d12. You install the server for OceanBlock v1.11.0 and a bunch of files will appear in the server folder. You will copy the folders `config`, `mods` and `kubejs` and paste them in your client on top of the same folders. Overwrite any files if they prompt you to.
You might have to open the modpack folder in the FTB App to copy the files, it's accessed from the same menu you used to delete the modpack, in the Settings of the modpack, although click on Open Folder this time.
After you've copied the files over, start the modpack in the FTB App.

Side note but installing Forge in the FTB App is a little bit different. That didn't look to be the error here, but in case you want to understand how you were supposed to do it see https://www.notion.so/feedthebeast/Manually-installing-Forge-into-the-FTB-App-d0473bbea1aa43d6ae3830bea686bc13.

If something here fixes the problem, please close the issue. If it still fails, reach me on the FTB Discord directly through direct messages. I'll be offline for a while but you'll see me when scrolling up in the "support" channel, I have the same profile image, although my name on the Discord is "R3GEN".

**Comment by Raidobw2** [comment]
Updated comment for MacOS

**Comment by Stefan08p** [comment]
Thank you
