### ISSUE TITLE
Direwolf20 FTB 1.21.1 Server Migration 1.3 -> 1.4

### ISSUE THREAD

**Issue by ItsTino** [FTBTeam/FTB-Modpack-Issues#6112]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.4

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

https://pste.ch/ijakiyeleh.pl

### Describe the bug

Ubuntu server
FTB Server 1.3
Fresh install into new folder server 1.4 works
Moving 1.3 world or upgrading 1.3 to 1.4 with installer causes unjoinable server

### Steps to reproduce

Create FTB 1.3 Server
Create world
Heavy use of minecolonies which may be relevant
Run 1.4 server installer or 1.4 installer in new folder
Move world if upgraded
Start server
Result: Unjoinable

### Expected behaviour

Server joinable

**Comment by ItsTino** [comment]
Fixed by removing moonrise mod jar from server.

**Comment by Glemoyn** [comment]
I can confirm I also had this issue, and that removing the  Moonrise jar file allowed me to load into the world. Here is my report info while still on this bug report.

### Modpack

FTB Presents Direwolf20 1.21
### Modpack version

1.4
### Launcher

FTB App
### Has the pack been modified

Yes, Added 3 mods,
Byzantine-1.21.1-20
stylecolonies-1.10-1.21
worldedit-mod-7.3.8

Issue still happens if these three mods are removed from the server and/or client


### Log Files

Crash Log: https://pste.ch/imevorumeb.pl
Debug Log: https://pste.ch/awosokogos.pl
### Describe the bug

Shockbyte server
FTB Server 1.3
Moving 1.3 world or upgrading 1.3 to 1.4 with installer causes a server that crashes when you load a MineColony, and the server console returning "Internal Server Error" as a reason for Disconnection. If yo uload into a world while not having a MineColony loaded, it will function fine until you start to load chunks with a MineColony.

I confirmed I could not load into a superflat world where I had placed a level 1 town hall and a level 5 builder.


### Steps to reproduce

Create FTB 1.3 Server
Create world
Create a MineColony on the 1.3 World
Upgrade to 1.4 (issue happens with both SP and MP)
Load World.
If you do not have the MineColony loaded, move until the colony buildings are loaded

Server joinable
### Screenshots

No response
### Additional information

No response

**Comment by becky15675** [comment]
I can confirm this too. Moonrise broke my Minecolony world. Disabled Moonrise and it's fine

**Comment by ItsTino** [comment]
Fixed as of release 1.4.1
