### ISSUE TITLE
Ticking Entity server crash due to Servercore

### ISSUE THREAD

**Issue by JakeHumphries4** [FTBTeam/FTB-Modpack-Issues#6130]
### Modpack

FTB Evolution

### Modpack version

1.1.1

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

https://pste.ch/ijigaxeroz.coffeescript

### Describe the bug

The server crashes when mobs (maybe only zombies) die. Servercore calls "mobCounts." counts," which returns null and crashes the server.

### Steps to reproduce

1. Kill zombie.
2. Zombie causes ticking entity. This doesn't happen every time, only once or twice an hour.

### Expected behaviour

The server shouldn't crash

**Comment by lattaai5** [comment]
Hello, I tried to fix the issue

This is what I did:

Modified the bug report template to include more specific options for FTB Evolution and added a section for server crash information.

I also created pull request: https://github.com/FTBTeam/FTB-Modpack-Issues/pull/6131


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.

**Comment by Saereth** [comment]
reported to mod dev
https://github.com/Wesley1808/ServerCore/issues/120

**Comment by JakeHumphries4** [comment]
Mod dev response resolves this
