### ISSUE TITLE
Exchanging Gadget from Building Gadgets 2 doesn't give exchanged blocks

### ISSUE THREAD

**Issue by GridCube** [FTBTeam/FTB-Modpack-Issues#6137]
### Modpack

FTB Evolution

### Modpack version

1.2.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

when using the exchanging gadget you don't get the exchanged blocks

### Steps to reproduce

1. Use a exchanging gadget
2. it doesn't exchange

### Expected behaviour

it exchanges

**Comment by lattaai5** [comment]
Hello, I tried to fix the issue

This is what I did:

Added FTB Evolution specific options and a field for the exchanging gadget to better capture issues related to this modpack.

I also created pull request: https://github.com/FTBTeam/FTB-Modpack-Issues/pull/6138


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.

**Comment by Saereth** [comment]
I need more info here as this seemed to be working fine for me, what were you exchange to/from?

**Comment by GridCube** [comment]
Tried to test it again today to see how to explain it better... And
realized that I had a Pocket Storage in my inventory and that apparently
the exchanger just sends stone into the pocket storage directly and that's
why I couldn't see the exchange. Sorry, you can close this issue
