### ISSUE TITLE
Evolutionary Matter Quest in Pyramid seems odd.

### ISSUE THREAD

**Issue by togreglove** [FTBTeam/FTB-Modpack-Issues#6141]
### Modpack

FTB Evolution

### Modpack version

1.2.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

The Evolutionary Matter quest (bottom row of pyramid, 5th over) shows a glowing purple stone. The other quests tend to be to create what is shown on their icon, but this one seems to skip the final crafting step to make the glowing purple stone and asks for a collection of items from Hostile Mob networks. 

### Steps to reproduce

Examine quest requirements

### Expected behaviour

Would expect to craft the purple stone with the ingredients.

**Comment by lattaai5** [comment]
Hello, I tried to fix the issue

This is what I did:

Added a new textarea field for quest-related issues in the bug report template. This will help users provide more specific information about quest problems, such as the one described for the Evolutionary Matter quest in FTB Evolution.

I also created pull request: https://github.com/FTBTeam/FTB-Modpack-Issues/pull/6142


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.

**Comment by alfredggttv** [comment]
This is because the "craft" requires 64 of each item that holds NBT data. We couldn't find a crafting recipe method that allowed for us to use stacks of items and NBT data, so the quest just requires the items to "craft" it instead. Hope this helps!
