### ISSUE TITLE
[Bug]: Incomplete set of tags received from OceanBlock server

### ISSUE THREAD

**Issue by Skurritto** [FTBTeam/FTB-Modpack-Issues#624]
### Modpack

Ocean Block

### Modpack version

1.11.0

### Describe the bug

I downloaded the server files from ocean block and "incomplete set of tags received from server" error pops up. someone help? 

### Steps to reproduce

1 downolad a serverinstall_91_2105.exe
2 open it
3 open the start.bat
4 try do enter with computer ip

### Expected behaviour

 I will be able to enter

**Comment by Raidobw2** [comment]
Hello, this happens when the client and the server have different files.
Make sure the server is running with the Forge jar, by default it is if you use the start script to boot the server.

Those folders need to be almost an exact match on the client and the server: `config`, `mods`, `kubejs`. What you can do is take those folders from the server and paste them on your client. Reversely, you can also take the folders from your client and paste them onto the server.

Both times you can overwrite the files. If you do this it will equalize the missing files on either side and you'll be left with two functioning OceanBlock installs, your client and the server.
Let me know if that solved the issue, if it did please close this issue as well.

**Comment by Skurritto** [comment]
No, its doesn't work. I have the same files in both cases and error still up.

**Comment by Sunekaer** [comment]
Please provide server and client log.
