### ISSUE TITLE
ServerHangWatchdog detected that a single server tick took 60000004.00 seconds (~2 years!)

### ISSUE THREAD

**Issue by leon0399** [FTBTeam/FTB-Modpack-Issues#6302]
### Modpack

FTB Evolution

### Modpack version

1.3.0

### Launcher

Prism

### Has the pack been modified

No

### Log Files

https://mclo.gs/BFRHyLH
https://mclo.gs/pAtdwsN

### Describe the bug

Server randomly crashes

### Steps to reproduce

I have all my stuff in a void dim, IDK if this is related. Server has 10GB RAM available

### Expected behaviour

Not to crash

**Comment by alfredggttv** [comment]
ServerHangs usually just come from servers lagging, and the watch dog shuts it down based on a property in your `server.properties` file.

Look for this setting and let me know what it is: `max-tick-time`

If it's set to default (600000), you can try setting it to -1 to disable the watchdog. Otherwise, it might be helpful to run a spark profiler before the server hangs to see what's causing it.
