### ISSUE TITLE
growth accelerator does not work on melons and pumpkins

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#6398]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.7.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

AE2 growth accelerators will speed up the growth of vines but not the spawning of actual pumpkin and melon blocks.

### Steps to reproduce

1. Place and power an AE2 growth accelerator next to a melon or pumpkin vine.
2. Vine grows to full height quickly but melon/pumpkin blocks are not accelerated.

### Expected behaviour

acceleration of pumpkin and melon block spawning as in previous versions of Minecraft

**Comment by ArtpokeBr** [comment]
This is probably due to how these Crops actually work, Growth Accelerators only Apply Random Tick Speed Values to the Seeds so its technically like applying Bone Meal to them, and as you may know, applying bone meal to pumpkins will not make them lay a block faster. Maybe you could reported this to the AE2 Devs [here](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues) and they find a workaround for this, but its very unlikely.
