### ISSUE TITLE
server crashing ftb plexiglass mountain

### ISSUE THREAD

**Issue by moso1503** [FTBTeam/FTB-Modpack-Issues#6473]
### Modpack

FTB Plexiglass Mountain

### Modpack version

1.2.4

### Launcher

Server

### Has the pack been modified

Yes

### Log Files

[crash-2024-12-21_10.23.43-server.txt](https://github.com/user-attachments/files/18218028/crash-2024-12-21_10.23.43-server.txt)

### Describe the bug

i dont know. im having problems with the new server files unlike the old ones. i ran this server for a week but now it just keep crashing im not able to join it anymore

### Steps to reproduce

idk

### Expected behaviour

that the server will run like normal

### Screenshots

![image](https://github.com/user-attachments/assets/dd818004-acdb-4fc9-8219-e7edfdf7eb75)
![image](https://github.com/user-attachments/assets/720e9250-6364-4309-b38c-c3ace770c29a)
![image](https://github.com/user-attachments/assets/31eb7fe3-c060-4adf-b921-393f129a2d02)

**Comment by Gaz492** [comment]
It looks like the server watchdog is killing the server, this normally happens if there is a lot of entities such as thousands of dropped items on the floor.

Try setting the max-tick-time option in the server.properties file to -1 and see if that allows your server to stay online.
It may not let you connect as soon as it has started up, but it may allow it enough time to clear up the issue it was having or allow you to run commands such as `/forge entity list` and `/kill @e[type=item]`.
These commands list the number of items in the world and kill/remove any dropped items in the world.

**Comment by moso1503** [comment]
ty
