### ISSUE TITLE
[Bug]: Stoneblock 2 Crashes at Load

### ISSUE THREAD

**Issue by Warrof** [FTBTeam/FTB-Modpack-Issues#65]
### Modpack

FTB Presents Stoneblock 2

### Modpack version

1.21.1

### Describe the bug

Crash at Modpack Load:  Gives error 0.  Been trying to install this properly since the CurseForge Ver. is no longer maintained.

I have attempted [this](https://forum.feed-the-beast.com/threads/stoneblock-2-issues.305049/) fix by updating LLibrary
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7272074/latest.log)

![ftb stoneblock 2](https://user-images.githubusercontent.com/21962742/135729614-2c8efbc5-397d-443f-a3e8-531fb959d34a.PNG)

### Steps to reproduce

1. In FTB app click play on StoneBlock 2 1.21.1
2. Let load, then click play in Minecraft Launcher.
3. Wait a few seconds then experience crash.

### Expected behaviour

Normal Loading of Modpack after initial install

**Comment by Warrof** [comment]
Tried to uninstall Modpack and FTB app and reinstall everything.  Still getting Error Code 0, but the crash log is different now.

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7272295/latest.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7272296/debug.log)

**Comment by Raidobw2** [comment]
In the first log i see:
```
[12:21:34] [main/FATAL] [FML]: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty.
[12:21:34] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.RuntimeException: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty, your vanilla jar may be corrupt.
```

> your vanilla jar may be corrupt

And after you reinstalled:

```
[14:59:07] [main/ERROR] [FML]: Unable to read the jar file MightyEnderChicken-1.12.2-7.3.0.jar - ignoring
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_51]
```

I'll have more time later on to dig on this, but for now i have general pointers for you (i'm aware you reinstalled):
- Could be the instance still being corrupted because of an unfinished download
- Could be the Minecraft librairies within the FTB App encountering problems
- Could be your instance location not working properly for being on another drive, but this would be a first for me

Solutions for now? It's going to be dirty, but it'll get the job done hopefully. And hopefully you've played vanilla before.
1. Open the FTB App, delete Stoneblock 2.
2. Close the FTB App.
3. Copy `%appdata%\.minecraft\librairies` and paste and overwrite directly onto `%localappdata%\.ftba\bin`.
4. Copy `%appdata%\.minecraft\versions` and paste and overwrite directly onto `%localappdata%\.ftba\bin\`.
5. Open the FTB App, go straight to redownload Stoneblock 2, don't have other stuff running in the background like Steam downloads or anything massive going on your network.
6. Hit Play on Stoneblock 2.

Report back here if that solved it. And the logs were very helpful thank you.
If that didn't work the devs for the FTB App will look into it.

I hope this works for you and that you can enjoy that modpack!
-R3GEN

**Comment by Raidobw2** [comment]
Mikey if this breaks it needs a transfer to FTB App most likely. I'll have them use the debug tool in that case to post the code here.

**Comment by Warrof** [comment]
R3GEN had me use the FTB Debugger, the code I got is FTB-DBGDUPOSEYAYA 

My Internet is kinda sucky right now, so if you are missing something that's my internet's fault.

Will do the Steps outlined above shortly.

**Comment by Raidobw2** [comment]
Before i go for a few hours, i quickly see `Instance install never completed, Ignoring.`. I'll drop the Manual Forge install in case you wanna try that too, i'm just trying to get your game to work so you can play! Leave the ticket open if anything works (but mention it worked please), thanks for your patience.
https://www.notion.so/feedthebeast/Manually-installing-Forge-into-the-FTB-App-d0473bbea1aa43d6ae3830bea686bc13

**Comment by Warrof** [comment]
> 
> 
> In the first log i see:
> 
> ```
> [12:21:34] [main/FATAL] [FML]: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty.
> [12:21:34] [main/ERROR] [LaunchWrapper]: Unable to launch
> java.lang.RuntimeException: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty, your vanilla jar may be corrupt.
> ```
> 
> > your vanilla jar may be corrupt
> 
> And after you reinstalled:
> 
> ```
> [14:59:07] [main/ERROR] [FML]: Unable to read the jar file MightyEnderChicken-1.12.2-7.3.0.jar - ignoring
> java.util.zip.ZipException: error in opening zip file
> 	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_51]
> ```
> 
> I'll have more time later on to dig on this, but for now i have general pointers for you (i'm aware you reinstalled):
> 
>     * Could be the instance still being corrupted because of an unfinished download
> 
>     * Could be the Minecraft librairies within the FTB App encountering problems
> 
>     * Could be your instance location not working properly for being on another drive, but this would be a first for me
> 
> 
> Solutions for now? It's going to be dirty, but it'll get the job done hopefully. And hopefully you've played vanilla before.
> 
>     1. Open the FTB App, delete Stoneblock 2.
> 
>     2. Close the FTB App.
> 
>     3. Copy `%appdata%\.minecraft\librairies` and paste and overwrite directly onto `%localappdata%\.ftba\bin`.
> 
>     4. Copy `%appdata%\.minecraft\versions` and paste and overwrite directly onto `%localappdata%\.ftba\bin\`.
> 
>     5. Open the FTB App, go straight to redownload Stoneblock 2, don't have other stuff running in the background like Steam downloads or anything massive going on your network.
> 
>     6. Hit Play on Stoneblock 2.
> 
> 
> Report back here if that solved it. And the logs were very helpful thank you. If that didn't work the devs for the FTB App will look into it.
> 
> I hope this works for you and that you can enjoy that modpack! -R3GEN


This worked!!!  Thank you!

**Comment by Raidobw2** [comment]
Hmm might have been lag during the download since i've never seen a case like that before.
Happy that it worked though! Every install is cached, meaning every reinstall downloads only the missing (and corrupted?) mods.
Or it could have been the versions and libs (although i think this might not have been the case)!

Issue fixed anyways, so i'll close this! -- i don't think this is a problem with the FTB App, might likely have been internet as you suggested earlier.

**Comment by Marcapus** [comment]
Uhh i have the same problem, my game keeps crashing with code 0, i tried to unistall it but same

**Comment by Marcapus** [comment]
uhhm i tried your method but it is same
