### ISSUE TITLE
[Bug]: forge version cannot run mods

### ISSUE THREAD

**Issue by wazzupduck** [FTBTeam/FTB-Modpack-Issues#663]
### Modpack

FTB endeavour

### Modpack version

1.80

### Log Files

https://paste.feed-the-beast.com/view/0c2b8d70

### Describe the bug

Attempting to load FTB endeavour modpack fails. Error message shows up showing that 4 mods that are part of the pack require a higher version of forge than the modpack launches with. 

### Steps to reproduce

Issue occurs on every attempt at startup. Installed modpack directly and launched from the FTB app to attempt loading. 

### Expected behaviour

Modpack loads with forge 36.2.20 as is required by mods installed.

**Comment by Raidobw2** [comment]
Hello, sadly that's not how it works. Forge does not update automatically when you update the mods.
For example if you add a 1.7.10 mod into Endeavour, should Forge update to 1.7.10? No, because all the other mods would then crash. Modpack developers such as us therefore develop modpacks on a specific Forge version for stability purposes. What we ship works, but we cannot guarantee it will work when you update the mods or change the content because that's out of our control.

If you need to manually update Forge in the future, you can install a new Forge profile in the Minecraft Launcher and copy the files to it. You can also use the CurseForge App which does the same thing, it allows custom modpack creation.

For your current need, you don't need to update Forge. You're not playing on the latest version: https://feed-the-beast.com/modpack/80_ftb_endeavour/versions, the latest is 1.9.0 and already contains all the updates to the mods you want and has been tested as well. Please consider using that version on the FTB App, you will need to check the betas box when installing.

As well, for the future don't paste logs as raw text, anywhere. It's always appreciated when you use a paste service for logs and there are many out there. One for FTB content is https://paste.feed-the-beast.com/, so you can use that one. I've edited your message for that purpose, as it will also give you an example.
I'll be closing this issue, since the solution is simply to update to 1.9.0.

**Comment by wazzupduck** [comment]
I see thank you for the information, I had figured that 1.80 should run normally without the need to update to beta, but this has been helpful.
