### ISSUE TITLE
[Bug]: Mod does not load

### ISSUE THREAD

**Issue by eggsters** [FTBTeam/FTB-Modpack-Issues#664]
### Modpack

FTB University 1.16

### Modpack version

1.4.0

### Log Files

https://paste.feed-the-beast.com/view/f40f8b23

### Describe the bug

2 mods failed to load.

### Steps to reproduce

1. Launch the FTB University game instance using MultiMC
2. Mods failed to load

### Expected behaviour

For the mods to load and the game to start

### Screenshots

![javaw_pLKKN8nGFI](https://user-images.githubusercontent.com/70789106/157853667-bc81df1b-a4a3-48f0-8c64-7ba3ff2ac47a.png)

### Additional information

Using MultiMC and Java 16.0.2, also the same issue on FTB OceanBlock 1.11.0, no other version that I have played does have this error.

**Comment by Raidobw2** [comment]
Hello, you need to use Java 8 or 11, Java 16 will not work for Minecraft 1.16.5.
You can install https://adoptium.net/archive.html?variant=openjdk8&jvmVariant=hotspot and use it to start the modpack.
Use that specific version for your OS, since Java8u321 will not be compatible with OceanBlock and others currently:
![image](https://user-images.githubusercontent.com/17010632/157885126-7b204240-2fb0-4157-add0-556803b13dce.png)
Also, consider using the FTB App if you like our modpacks and would like to support us,
Cheers

**Comment by eggsters** [comment]
Thanks, that fixes it,
