### ISSUE TITLE
[Bug]: Crash when trying to launch latest version with multiMC

### ISSUE THREAD

**Issue by Greymagic27** [FTBTeam/FTB-Modpack-Issues#677]
### Modpack

FTB OceanBlock

### Modpack version

1.11.0

### Log Files

https://paste.ee/p/lrzbN

### Describe the bug

When I try to launch the latest version of oceanblock it crashes. I've not done any changes and I've tried launching it with Java 8, 11 and 16.

### Steps to reproduce

1) Launch the game
2) Observe that it doesn't launch

### Expected behaviour

It should launch

**Comment by Raidobw2** [comment]
Hello, some versions of Java will not work with modpacks that have not had Forge update yet. This is because some changes were done in the Java executables which affected Minecraft, and that was out of Forge's control. The FTB App will take care of choosing the right Java version for you, if you like our modpacks and want to support us consider using it https://feed-the-beast.com/app.

With Minecraft 1.16.5 you want to either use Java 8 or 11. Since it looked like you wanted to use Java 11, then use this one:
https://adoptium.net/archive.html?variant=openjdk11&jvmVariant=hotspot
![image](https://user-images.githubusercontent.com/17010632/158103055-c144be08-5fc2-49d4-b151-d75be75de751.png)

**Comment by Greymagic27** [comment]
That specific version? Or just from that link?

If it's just from that link I already have the latest Java 11 downloaded from there

**Comment by Raidobw2** [comment]
That specific version or below, the latest one will not work because a constructor was removed, so it causes Forge to crash unless it is up to date. In in OceanBlock currently, Forge is not up to date. So you have to use the one I put on the image/link, or lower.
