### ISSUE TITLE
[Crash]: Startup issues

### ISSUE THREAD

**Issue by seafoam211** [FTBTeam/FTB-Modpack-Issues#686]
### Modpack

FTB Oceanblock

### Modpack version

1.11.10

### Logs
https://paste.feed-the-beast.com/view/d6c94386

### Describe the bug

I got a crash screen telling me some mods have errored (it did not explain which mods) and failed to load

### Steps to reproduce

download it using multimc
run it

### Expected behaviour

I expected it to load to the title screen as it had worked previously with no issue.

**Comment by Raidobw2** [comment]
Hi, you cannot use Java 16 to play OceanBlock. You will need to use Java 8 or 11. Due to some changes in the java binary, you will only be able to use specific versions of Java 8 or 11. Use this exact version to start the game: https://adoptium.net/archive.html?variant=openjdk8&jvmVariant=hotspot
![image](https://user-images.githubusercontent.com/17010632/159406898-7a0347f0-a1a2-453b-b8d0-0f68963d87ab.png)

The erroring mod was CBMultipart:
```
Mod File: CBMultipart-1.16.5-3.0.3.122-universal.jar
        Failure message: Failed to load mod
        Mod Version: 3.0.3.122
        Mod Issue URL: https://github.com/TheCBProject/ForgeMultipart
        Exception message: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @4276ad40
```
This is the error: `java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @4276ad40` and it means that a module does not have the correct format, this is because it's expecting Java 11 at most and it's receiving Java 16.

For next time I would ask you to not paste logs as raw text. Please learn to use paste services such as pastebin, or https://paste.feed-the-beast.com/ for Feed the Beast logs. I have edited your message to reflect that change so you can have an example.

As well, consider using the FTB App, since you will not get Java errors on there. We handle the Java versions so you don't have to, and you will get automatic modpack updates.

Please close the issue when this is solved and thanks.
