### ISSUE TITLE
Hello, i need help, all modpack dont work

### ISSUE THREAD

**Issue by zzZver01** [FTBTeam/FTB-Modpack-Issues#687]
Hello, we do not support cracked launchers. `[21:57:32] [Client thread/INFO]: used the old auth tlauncher service`. You will need to buy the Java version of the game on https://www.minecraft.net/ and you can then use the FTB App to play any Feed the Beast modpack https://feed-the-beast.com/app or any other modpacks on CurseForge https://www.curseforge.com/minecraft/modpacks.
Thank you for your comprehension

_Originally posted by @Raidobw2 in https://github.com/FTBTeam/FTB-Modpack-Issues/issues/684#issuecomment-1074713846_.

![Безымянный](https://user-images.githubusercontent.com/101902451/159444042-767546a7-3933-4d1d-aebc-a05d66e69e91.png)

Bro in tlauner can also be played from a licensed account, I don't play from your launcher and courseforge because I don't like overwolf
crash-report https://paste.feed-the-beast.com/view/7b38e41c
please help i cant play minecraft

**Comment by zzZver01** [comment]
https://paste.feed-the-beast.com/view/7b38e41c

**Comment by zzZver01** [comment]
as you wanted, I launched with a license

**Comment by Raidobw2** [comment]
Hi again, I understand, but tlauncher contains pirated software and we do not want to be associated to that. You can also read Minecraft's eula on https://www.minecraft.net/en-us/eula to gain awareness about piracy, which again we do not support, regardless if your account on it is licensed or not.
![image](https://user-images.githubusercontent.com/17010632/159524799-5fa7dbc6-2245-4f62-b1d8-ac103345de23.png)

Now that this has been made clear, the pack you are trying to launch is not made by us, it's made by Darkosto. We did not make SkyFactory 4. If you need support for his modpack, head to his Discord https://discordapp.com/invite/darkosto.

If you need support for a Feed the Beast modpack, use the FTB App and let me know here if you get any errors, or visit the Feed the Beast Discord https://go.ftb.team/discord. You will need to migrate your account to a Microsoft account, please use the articles below to help you in that task:
https://www.minecraft.net/en-us/article/last-call-voluntarily-migrate-java-accounts
https://help.minecraft.net/hc/en-us/articles/4403181904525-How-to-Migrate-Your-Mojang-Account-to-a-Microsoft-Account
If you need help migrating your account or encounter problems, please contact Minecraft Support through their support form: https://help.minecraft.net/hc/en-us/requests/new.

If you need to understand why we or CurseForge changed to Overwolf, read this article: https://forum.feed-the-beast.com/threads/ftb-curseforge-overwolf-and-the-future.303428/.

If you need to understand what data Overwolf collects and how it uses it, read their privacy policy: https://www.overwolf.com/legal/privacy/. Overwolf had to undergo auditing when CurseForge and FTB moved from the Twitch Launcher to the Overwolf Launcher.
![image](https://user-images.githubusercontent.com/17010632/159525600-1aa9177d-34e2-4ab4-a0af-952e1efa8bbe.png)

If your computer is running out of RAM because you have a very low amount while loading a modpack, then simply close Overwolf and the CurseForge or FTB App while the game loads.

Please let me know if you are playing a Feed the Beast modpack from the FTB App and if it fails, in that case I will be able to help. Otherwise, I will be shortly closing this issue since it is not our modpack. This tracker is primarily for bugs, we handle most of the support on the FTB Discord directly.
