### ISSUE TITLE
[Bug]: Builders Paradise halts progress at stage 3

### ISSUE THREAD

**Issue by Skulldefender** [FTBTeam/FTB-Modpack-Issues#739]
### Modpack

FTB Builders Paradise

### Modpack version

1.9.0

### Describe the bug

I want to play Builders Paradise with friends. First start of the game: no problems at all. closed and launched shortly afterwards. Then he couldnt launch. He's stopping at diffrent positions in the progress:  when Initializing mods phase 3 // Thermal Cultivation, when finishing up Just enough items or some others points. I tried using more RAM (up to 12 GB) and put the downloadthreads on 32, but still, it wont start, I use a very newly buildup computer(only 5 months old and no problems since).  It may be significant, that he always stops at the LOG entry:

FTB APP INFO Claening up last 500 messages ... 
Threas-4/INFO FML Using sync timing. 200 frames of Display.update took 13217800 nanos
FTB APP INFO Claening up last 500 messages ... 

After that i can wait till my hair turns grey. I tried reinstalling the FTB App multiple Times, but it didnt help.

### Steps to reproduce

I just press play at the builders paradise icon.....

### Expected behaviour

I starts

### Screenshots

![Screenshot 2022-04-24 185858](https://user-images.githubusercontent.com/104317571/164987640-bb76e9cb-3a79-47a8-95dd-3b8a3acc93d3.png)

**Comment by Raidobw2** [comment]
Hi, after some testing that looks to be an issue with UniDict. Can you try the following?

1. Download the latest UniDict from https://www.curseforge.com/minecraft/mc-mods/unidict/files/3553627
2. Download the latest WanionLib from https://www.curseforge.com/minecraft/mc-mods/wanionlib/files/3597087
3. Open your modpack folder:
![image](https://user-images.githubusercontent.com/17010632/165206605-5a228d37-f5fa-42c9-84b8-48a874d02c0d.png)
![image](https://user-images.githubusercontent.com/17010632/165206650-2d0982c3-08c6-4b99-92ab-08bde55b41b6.png)
4. Delete `UniDict-1.12.2-3.0.8.jar` and `WanionLib-1.12.2-2.5.jar` from the `mods` folder
5. Add the two files you downloaded earlier into the `mods` folder
6. Start the game, it will now use the updated version of those 2 mods
7. Let me know if it freezes or not

*Note that if you are using a server, the server needs to have the two files updated as well. We will have to update this pack in order to fix it for good, if it works this is a workaround for now.

**Comment by Skulldefender** [comment]
Well, we tried it, for some of us it worked… for some not. Looks like a 50/50 chance on getting through. First of all: on my machine it worked, even before i updated the mods, but now i have 2 installed game versions. That was‘nt intended.

I then updated the 2 mods like you described earlier and it still worked. Some of my Friends had the same issue as me and for them it worked only after restarting the starting process 2 times after killing the original Starting process. Now we are still trying to get the updated versions on the Server but thats an other issue. 
Thank you very much for this quick and good advice. It realy helped us to enjoy more of your Content!!



Von: R3GEN
Gesendet: Dienstag, 26. April 2022 04:24
An: FTBTeam/FTB-Modpack-Issues
Cc: Skulldefender; Author
Betreff: Re: [FTBTeam/FTB-Modpack-Issues] [Bug]: stops launching progress(Issue #739)

Hi, after some testing that looks to be an issue with UniDict. Can you try the following?
1. Download the latest UniDict from https://www.curseforge.com/minecraft/mc-mods/unidict/files/3553627
2. Download the latest WanionLib from https://www.curseforge.com/minecraft/mc-mods/wanionlib/files/3597087
3. Open your modpack folder:


4. Delete UniDict-1.12.2-3.0.8.jar and WanionLib-1.12.2-2.5.jar from the mods folder
5. Add the two files you downloaded earlier into the mods folder
6. Start the game, it will now use the updated version of those 2 mods
7. Let me know if it freezes or not
*Note that if you are using a server, the server needs to have the two files updated as well. We will have to update this pack in order to fix it for good, if it works this is a workaround for now.

**Comment by Raidobw2** [comment]
No problem. For your server you can do the same thing and replace the two mods the same way you did them for your game. Let me know if you have other questions, and please leave this issue opened for us to fix this later in the modpack

**Comment by manmaed** [comment]
This issue is stale and pack is no longer being worked on
