### ISSUE TITLE
[Bug]: Terrain spawn in multiplayer is erratic with random blocks (powered rails as grass and water covering vines)

### ISSUE THREAD

**Issue by narokuu** [FTBTeam/FTB-Modpack-Issues#766]
### Modpack

FTB Direwolf20 1.8

### Modpack version

1.0.0

### Describe the bug

Terrain is erratic and spawning random blocks, instead of grass its spawning powered rails. only happening in multiplayer. 

### Steps to reproduce

Generate new multiplayer world
Spawn in 
observe random blocks

### Expected behaviour

grass should spawn and not powered rails, also chunks should not be randomly mashed together

### Screenshots

![MCServerscreenshot1](https://user-images.githubusercontent.com/32495004/168402730-44516b94-9786-43b1-abda-e4e7d8707a71.png)
![mcserverscreenshot2](https://user-images.githubusercontent.com/32495004/168402732-2ccbd678-3fec-4d45-8cca-53a8865a1fae.png)

**Comment by Raidobw2** [comment]
Hello, you will have to use `run.bat` or `run.sh` to start the server. Set your gamemode to creative, open your inventory and grab a modded block, such as limestone from Quark. Try to take that block and place it down, and I think you won't be able to. That's because currently you are likely running a vanilla server without mods. Looks like changes in Forge 1.18 permits connection from modded clients to vanilla servers fully, which could be good in some cases, but in your case it makes the server look corrupted.

We have changed our procedure today to adapt to the changes in Forge 1.18.2, please see https://feedthebeast.notion.site/Installing-a-Feed-the-Beast-Server-aeaea8a7220945d0ad0357c80c6c9d12. Note that we are looking into ways of changing the way we document things, so if other people come across this post and the document is no longer available, simply come ask for information in the FTB Discord. Please close the issue if that did it. You will need to use Java 17 to start the server with the run script.

**Comment by narokuu** [comment]
I am running the server with the shell script, its running on an ubuntu server. I downloaded the files directly from the website using the Advanced Server Installer. Its not a vanilla server.

**Comment by Raidobw2** [comment]
What is the command line you used to start the server? And have you tried recreating the world?

**Comment by narokuu** [comment]
I tried remaking the world, and the command im using to start the sh file is just sh serverstart.sh 

![image](https://user-images.githubusercontent.com/32495004/168406672-66fa58c9-d8a9-423b-82df-41a331ee7475.png)

**Comment by narokuu** [comment]
Should i be using run.sh instead as per your first post? im so used to other installs i do apologize.

**Comment by Raidobw2** [comment]
Forge 1.18 changed the way they ship their software in their installer, and the jar is in a different place. You will need to use run.sh as said on my first post yes. Please use run.sh, or use the jar that is mentioned in that script if you use a custom wrapper.

Our infrastructure team needs to remove the start.sh scripts from those modpacks, since run.sh is the way to do start them now

**Comment by narokuu** [comment]
I am just using the files that come downloaded into the installer. using the start.sh is working however now its crashing out, here is the log
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8692030/debug.log)

**Comment by narokuu** [comment]
deleting and starting over works, changing the server properties gives me this error, using the default one is fine. thank you for the help, I will do testing on my end this weekend, thank you for all the hard work.

**Comment by Raidobw2** [comment]
Here is where it fails:
`Starting Minecraft server on *:25566`

```
[14May2022 02:43:20.745] [Server thread/WARN] [net.minecraft.server.dedicated.DedicatedServer/]: **** FAILED TO BIND TO PORT!
[14May2022 02:43:20.745] [Server thread/WARN] [net.minecraft.server.dedicated.DedicatedServer/]: The exception was: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
[14May2022 02:43:20.745] [Server thread/WARN] [net.minecraft.server.dedicated.DedicatedServer/]: Perhaps a server is already running on that port?
```

If you set the port in `server.properties` that port must be free (not used by other applications) otherwise it will fail to start. If you leave it empty it will use the default one 25565

I'll be closing this as a result of the server working now
