### ISSUE TITLE
[Bug]: Can't Join Multiplayer

### ISSUE THREAD

**Issue by FireBallT69** [FTBTeam/FTB-Modpack-Issues#777]
### Modpack

DireWolf20 1.16

### Modpack version

1.13.2

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8696071/latest.log)

### Describe the bug

I try to join my server and it says "Internal Exception: com.electronwill.nightconfig.core.io.ParsingException: Invalid TOML data: entry "[useeasternnameorder]" defined twice in its table" im just kinda confused

### Steps to reproduce

Install modpack
Make sure it's the correct version
Open modpack
Put in IP: dw20.instantvalley.net
Play

DOESN'T WORK

### Expected behaviour

It should be letting me enter the server

**Comment by Raidobw2** [comment]
Hello, that might be due to a problematic configuration file. I'd recommend to copy-paste your worlds if you have any in that modpack to keep them before reinstalling.

You will have to navigate to your instances folder and delete the `.localCache` file. That is the download cache.

Then simply uninstall the modpack (delete button through the modpack settings), and reinstall it on that version.

Try and join the server, as well as another server in case it still does not work. With two different server tries you will see if it's still an issue with your game or with the first server.

I did not see anything in the log unfortunately, but I thank you for posting it in advance. This allowed me to give you more information instead of asking for the log! :)

**Comment by FireBallT69** [comment]
i have tried re-installing but i haven't tried to go on multiple servers, i will try that. thank you! i will write back if something goes wrong

**Comment by FireBallT69** [comment]
it literally fixed itself, unsure of what fixed it.
