### ISSUE TITLE
[Bug]: Missing loot in Immersive Engineer Wooden Storage Crates

### ISSUE THREAD

**Issue by ingenitor** [FTBTeam/FTB-Modpack-Issues#786]
### Modpack

FTB Direwolf20

### Modpack version

1.18.2

### Describe the bug

Create world, I used seed DW20LP1182WOOHOO
Went to first village with an Immersive Engineering Village
Both Wooden Crates were empty

### Steps to reproduce

Create world, I used seed DW20LP1182WOOHOO
Went to first village with an Immersive Engineering Village
Both Wooden Crates were empty

### Expected behaviour

Wooden Storage Crates should Immersive Engineering related loot

### Screenshots

https://blockshot.ch/K13n

**Comment by quietust** [comment]
Possibly related, the floating tree islands from Forbidden & Arcanus also have empty chests inside them.

**Comment by MacChuck** [comment]
Tested with Terralith disabled on a new world to confirm it happens with default generation, same issue.

**Comment by MacChuck** [comment]
This is caused by Lootr ( https://github.com/noobanidus/Lootr/issues/94 ) Two ways to fix, depending on the desired behavior.

Modify the _lootr-common.toml_ file:

Add `immersiveengineering:crate` to the` additional_chests` config ( `additional_chests = ["immersiveengineering:crate"]` ) which will convert generated crates to chests with the correct loot, but you lose the option to pickup the crate to get them early.
or
Blacklist IE crates from Lootr conversion with this config line for Lootr: `loot_modid_blacklist = ["immersiveengineering"]`

Maybe there's a way to make the IE crates Lootr chests and add a create to the loot table?

Disabling or modifying Lootr does not fix the Forbidden & Arcanus chests in the floating islands.

**Comment by Sunekaer** [comment]
Thanks @MacChuck
