### ISSUE TITLE
[Bug]: DW20 1.18.2 World stuck at 100%

### ISSUE THREAD

**Issue by raflowers** [FTBTeam/FTB-Modpack-Issues#814]
### Modpack

Direwolf20 1.18.2

### Modpack version

1.2.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8746183/latest.log)

### Describe the bug

The mod loader runs as expected and I get to the minecraft start screen. I am able to select a world and it loads the world to 100% but then never actually puts me into the world able to play the game.

### Steps to reproduce

1. Start DW20 1.18.2
2. Select a singleplayer world
3. Let the mod loader run
4. World does not load

### Expected behaviour

I should be allowed into the world and able to play the game

### Screenshots

![DW20 screenshot](https://user-images.githubusercontent.com/48536856/169630623-6a246560-ea02-4ba0-bef3-7a997cf652e5.PNG)

**Comment by Kroptik** [comment]
I was having the same problem. Stuck at 100% on the chunk window when loading.
I used a program (Amulet Editor) to check my world and kept deleting blocks that I had added the last time I played.

The problem was with the Aquatic Entangler from Thermal.
I tested it on some creative worlds. As soon as I placed a working Aquatic Entangler and closed the world, I couldn't get back in it, or I could but the chunks would stop loading, the world would get "stuck" and I would fall into the void forever.

So, if you have one of these, try using that editor and removing that block, see if it solves the issue.

**Comment by raflowers** [comment]
This 100% worked for me. We need to make sure COFH knows about this

**Comment by quietust** [comment]
I just ran into this problem myself, and I wish you hadn't just closed this issue because it hasn't exactly been fixed (and I only thought to look here because I remembered seeing it a few days ago).

**Comment by raflowers** [comment]
> If you wanted to make sure TeamCoFH knew about this, you probably should not have _closed_ the bug report, because now **nobody's** going to know about it unless they manually search for it in the Closed Issues list (which nobody's going to do as long as they're running the latest pack version).

COFH DOES know about it and KingLemming himself told me it was fixed. If it's still happening we need to start a new issue or go in the COFH discord not bitch at me because my personal issue was resolved.
