### ISSUE TITLE
[Bug]: Sorting Sophisticated storage Barrels with stack upgrades can cause items to void

### ISSUE THREAD

**Issue by neograymatter** [FTBTeam/FTB-Modpack-Issues#838]
### Modpack

FTB Presents Direwolf 20 1.18

### Modpack version

1.2.0

### Describe the bug

If a player on a server unbinds middle-mouseclick from the sophisticated storage sort keybind,
 then attempts to middle-mouseclick (mousetweaks sort?) on a sophisticated storage barrel containing stack upgrades and stacks of items greater than 64,
It will be sorted into stacks of 64 and voids any extra items that do not fit in barrel when its only stacked to 64

### Steps to reproduce

On a server
1) unbind middle mouse click from the sophisticated storage sort keybind,
2) Create sophisticated barrel and add stack upgrades
3) Add items to barrel so that they would not fit in without the stack upgrade
4) open up barrel and middle mouse click
5) observe as they are sorted into stacks of 64, and any stacks that don't fit are voided.

### Expected behaviour

It should either sort, or fail to sort; not void items

**Comment by P3pp3rF1y** [comment]
This is caused by InventorySorter which expects all stacks to be at maximum 64. I have IMC compat but that is broken (https://github.com/cpw/inventorysorter/issues/119) in InventorySorter so sophisticatedstorage/backpacks need to be specifically blacklisted in its config in modpacks. But exactly for this reason I have middle click for sorting as default and also handling the sorting with higher priority so that it kicks in before InventorySorter can.

**Comment by Zarkazm** [comment]
Inventory Sorter's blacklist also appears to be broken since at least January.

https://github.com/cpw/inventorysorter/issues/121

**Comment by TheonlyTazz** [comment]
closing this issue as it has become stale
