### ISSUE TITLE
[Bug]: Direwolf20 1.16 Garden Cloche, Sink, and Fluid Cable crash

### ISSUE THREAD

**Issue by StarCustodian** [FTBTeam/FTB-Modpack-Issues#848]
### Modpack

FTB Presents Direwolf20 1.16 

### Modpack version

1.13.2

### Log Files

Error: Signal Exits code: 4294967295

AL lib: (EE) alc_cleanup: 1 device not closed

[crash-2022-05-25_22.09.34-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8782252/crash-2022-05-25_22.09.34-client.txt)

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8782278/latest.log)
nt.txt)

### Describe the bug

When connecting a sink from Cooking for Blockheads to a Garden Cloche from Immersive Engineering using Fluid Cables from Cyclic, the game crashes right as I set the cables to output from the sink. It doesn't matter what tool you use that can change the settings of the cable. It will crash regardless. 

So I found this bug while playing on a server. This has also happened to two other people I've played with, and If you set the pipe's output from the garden, it will also crash the game and make it impossible to rejoin. I found the only fix if you don't load the chunk with the cables and gardens. It will crush anyone who loads the affected chunks. Loading the server to previous backups doesn't fix the problem. I'm using GDLauncher. 

### Steps to reproduce

[Watch video](https://youtu.be/CGnpp5adSW0)

### Expected behaviour

I expected the garden to use the water from the sink without crashing my game.

**Comment by StarCustodian** [comment]
[crash-2022-05-25_22.09.34-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8782239/crash-2022-05-25_22.09.34-client.txt)

**Comment by StarCustodian** [comment]
I placed the game log in the original report

**Comment by Raidobw2** [comment]
Wow that's effectively a bug with one of the mods. Since you said a backup didn't work, I suggest either removing Immersive Engineering or Cyclic from the server, your game and also your friends' games. Removing one or the other clears the blocks for those mods. I'll assume you'd want to keep the garden cloches so you could remove cyclic and use other piping options.

Remove one of the mods after you have copied the original world in case, as a backup.

I can't remember all of them, if pipez is in the pack it can do it. Immersive engineering also has pipes and uses its pump for water (and it works with the sink and costs nothing to transfer, read the guide from the mod). Refined pipes may have some, as well as Xnet can do it if you want to learn it.
