### ISSUE TITLE
[Bug]: low performance even when setting are at lowest

### ISSUE THREAD

**Issue by Killercupcake298** [FTBTeam/FTB-Modpack-Issues#858]
### Modpack

FTB OceanBlock

### Modpack version

1.12.0

### Describe the bug

i have a bug where i join my server and the game is running average 50 ticks behind and making the modpack borderline unplayable

### Steps to reproduce

im not really sure it just started happening when i went to play one day

### Expected behaviour

i just want a solution to know what to do

**Comment by Raidobw2** [comment]
I recommend adding Spark for 1.16.5 to your server https://www.curseforge.com/minecraft/mc-mods/spark and to use the profiler command
![image](https://user-images.githubusercontent.com/17010632/170820386-4b8556ef-3203-41ca-9eb0-f05d5541ef78.png)
You will find the link to the documentation on the front of the CurseForge page as well. Once you've profiled the server, you can post the results here (it's a link). I should be able to help after that.

If you can precise how many players are playing as well and if you added any mods, that will help too.
Specifications of your server will also help, since modded Minecraft can sometimes take a considerable amount of resources to run well.
Thanks in advance
