### ISSUE TITLE
[Bug]: Some recipes in JEI are broken - for example, turtles (CC: Tweaked)

### ISSUE THREAD

**Issue by Sabster** [FTBTeam/FTB-Modpack-Issues#863]
### Modpack

FTB Presents Direwolf20

### Modpack version

1.3

### Describe the bug

Literally that - you can see recipes (some at least) in JEI

### Steps to reproduce

Open JEI
Search for Advanced Turtle
hit R

### Expected behaviour

For it to show the recipe...

**Comment by Sabster** [comment]
This seems to be server only...  When I created a single player world; the recipes (at least for the turtles) were fine...

**Comment by LaBeerwiBi** [comment]
I can confirm this issue is a Multiplayer issue only - currently running the DW20 v1.3.0 server via Windows. This bug makes playing the modpack pretty difficult due to no crafting recipes showing up. JEI will show other methods of obtaining items such as tripwire hooks being obtainable by fishing, but the crafting recipe will not be displayed. 

Someone in the FTB Discord commented (Lam#9216) that updating Oreberries Replanted on both the server and clients from v1.0.6 to v1.0.7 resolved the issue, but I can not confirm this as players on my server can barely manage to figure out how to use the FTB launcher.

**Comment by Raidobw2** [comment]
Hello, thanks for the report, I noticed a similar issue earlier and pushed a hotfix for approval. I'm assuming it will be out in a few hours. A mod version got rolled back and it causes issues, so in the hotfix you will have that mod updated again. I'll keep only https://github.com/FTBTeam/FTB-Modpack-Issues/issues/866 for tracking this problem, and the people in that issue mentioned a fix as well if you want to have it even before the hotfix 1.3.1 is approved and released to the public
