### ISSUE TITLE
[Bug]: None of my Worlds work anymore

### ISSUE THREAD

**Issue by Buzzsport2** [FTBTeam/FTB-Modpack-Issues#877]
### Modpack

FTB University 1.16

### Modpack version

1.5.0

### Log Files

[latest.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8799479/latest.zip)

### Describe the bug

Yesterday on 5/29/22 I was playing on my Minecraft world with no issues whatsoever. Today I decided to boot up minecraft and play on it, for some reason it doesn't work. There has been no updates to the beta version at all. I can make a new world just fine, but when I try to play on a old world it doesn't work. For clarification I have not played on any other version with the world, except for the beta.

### Steps to reproduce

1. Launch FTB University 1.5.0
2. Just launch a old world file. 

### Expected behaviour

The world should launch just fine.

**Comment by TheonlyTazz** [comment]
could you possible provide us with the crash-log(crash-reports\crash-2022-05-30_11.21.14-server.txt)

from what i can read from your latest-log it is crashing due to morpheus.-server.toml?

`net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file morpheus-server.toml of type SERVER for modid morpheus`

maybe you can try to delete that file to let the server regenerate a new one and see if that fixes it

**Comment by Buzzsport2** [comment]
Well I would include it, but the problem is that, the folder doesn't show up at all. I have provided a screenshot to show that it doesn't show up. This is a personal world just as a FYI. Im trying what you suggested now. 
![image](https://user-images.githubusercontent.com/106545035/171035701-2a7b880b-6f88-4024-bd6d-2fa05b63d9d4.png)

**Comment by TheonlyTazz** [comment]
The Crashlog should be here:
```C:\Users\<username>\AppData\Local\.ftba\instances\f2acc6f3-7a53-4d23-bbf3-117be42c1aaa\crash-reports\crash-2022-05-30_11.21.14-server.txt```

**Comment by Buzzsport2** [comment]
Well for me, it doesn't seem to exist, and when I try to go directly to the file path, it says that it doesn't exist. And the screenshot I sent is were it is supposed to be, and what you suggested didn't work

**Comment by Buzzsport2** [comment]
And whilst looking at my config file, it doesn't look like the morpheus config file exists...

**Comment by TheonlyTazz** [comment]
did you change the <username> to your username? the latest.log clearly states there is a crash report and it mentions its crashing because of the morpheus file.
if its a singleplayer world, you can also try removing the morpheus mod as thats used for multiplayer sleep. 
If that doesnt work, I'm uncertain what causes the issue

**Comment by Buzzsport2** [comment]
Yes I did change it to my username on my desktop. Im going to try to remove the mod now, and im still not sure why it doesn't show a crash report folder.

**Comment by Buzzsport2** [comment]
So it didn't work, but now it changed to fast leaf decay config causing the crashes.

**Comment by Buzzsport2** [comment]
Hmm, let me delete every instance of every config file to see what happens.

**Comment by Buzzsport2** [comment]
Well that seemed to do it, thank you for your help, and have a good day!
