### ISSUE TITLE
[Bug]: Create fully breaks bedrock ore.

### ISSUE THREAD

**Issue by therocki** [FTBTeam/FTB-Modpack-Issues#921]
### Modpack

FTB Plexiglass Mountain

### Modpack version

1.0.2

### Describe the bug

When using the create drill on a bedrock ore it completely breaks the block.

### Steps to reproduce

1. Make a Create drill system on a bedrock ores.
2. Start drilling it.
3. Block disappears.

### Expected behaviour

Drops the ore chunk and doesn't break the block.

### Screenshots

https://blockshot.ch/P3pQ

**Comment by Raidobw2** [comment]
Tracking at:
https://github.com/dadobug1111/DadobugBedrockOres/issues/6
https://github.com/Creators-of-Create/Create/issues/3061

**Comment by Saereth** [comment]
Thank you for the update, we'll get it in the pack asap!

**Comment by dadobug1111** [comment]
just make sure the config gets regenned. may break otherwise...

**Comment by Raidobw2** [comment]
Thanks a lot!

**Comment by Raidobw2** [comment]
Reverted Bedrock Ores in the plexiglass mountain update that should release today. Updating it to 1.4.1 made the RFTools builder no longer work. I'll check with the newest version 1.4.2 (which I didn't have time to mess with earlier) if that still happens, most likely I'll put a report to the Bedrock Ores tracker soon.

In short, I'll be checking this issue again soon, this won't be fixed in 1.2.0 yet

**Comment by Raidobw2** [comment]
Ahh if this works on 1.4.2 that's good. It'll be some time again until I can properly fix this since updating to 1.4.2 requires me to make some changes in the ores (I was using some weird ore hacks in 1.3.1 and up to change the block drops and textures, but then you added Thermal compat which I need to switch to).

The builder also has a "loop" option, it's usually what I use for testing. Thanks for letting me know 1.4.2 works, I'll have a look at it in some time for our next modpack update :)

**Comment by Raidobw2** [comment]
Interactions are fixed in 1.2.1+
