### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by picolas1** [FTBTeam/FTB-Modpack-Issues#923]
### Modpack

Item voiding issue with Sophisticated Backpacks

### Modpack version

1.0.2

### Describe the bug

If you have any tier of stack upgrade in a backpack from Sophisticated Backpacks and have more items than it would take to fill the backpack normally, and use the sort inventory feature from Inventory Sorter, it will split the stacks into the vanilla of 64 items, voiding anything that doesn't fit.

### Steps to reproduce

1: Put any Stack size upgrade from Sophisticated backpacks into a backpack from the mod.
2: Fill the backpack with more items than what it would be able to hold with the vanilla of 64 items a stack.
3: Use the sort function from Inventory Sorter (Default MMB).
4: Stacks larger than 64 will be split, voiding any items that does not fit.

### Expected behaviour

Items will be voided

**Comment by picolas1** [comment]
I am really not used to using Github...
This is a bug regarding Plexiglass Mountain.
Sorry

**Comment by Raidobw2** [comment]
Tracked at https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/493
I'll add the binding for new players, though you will need to add it yourself (since I can't change these files for you post-release unfortunately).
Press Escape and open the menu in-game. Go to Options > Controls > Keybinds and type "sort" in the box. Make sure it looks like this:
![image](https://user-images.githubusercontent.com/17010632/172770628-6ebb1dd2-45b2-4d8c-83d7-6a7d77a035c4.png)
Click a keybind box to start assigning a keybind and then press your Middle Mouse click to set it to that.
Then the sorting for the backpack should work fine, as long as those keys are the same.
