### ISSUE TITLE
[Bug]: Recipe conflict induction heater and external heater

### ISSUE THREAD

**Issue by orion-alathorn** [FTBTeam/FTB-Modpack-Issues#965]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.4.1

### Describe the bug

could find nowhere to confirm if this is a bug but also nowhere to confirm this is intended so reporting just in case, the recipe for immersive engineerings external heater as written in the mods own book is the exact recipe for create crafts and additions induction heater and using the recipe only allows the creation of the induction heater

### Steps to reproduce

1. attempt to craft external heater
2. only be able to craft induction heater with the same recipe

### Expected behaviour

be able to craft external heater

**Comment by quietust** [comment]
The Induction Heater appears to function the same as the External Heater, except for the following differences:
1. It consumes 256 RF/t while active, while the External Heater only consumes 8 RF/t to keep a furnace "topped off".
2. It does not require a redstone signal in order to keep an empty furnace running.
3. It *does not work* when a Furnace Engine is attached, which means you can't use it to cheese the production of massive amounts of mechanical energy.

I suspect Create Crafts & Additions did this deliberately to force players to use the Electric Motor instead.

**Comment by orion-alathorn** [comment]
> 1. It consumes 256 RF/t while active, while the External Heater only consumes 8 RF/t to keep a furnace "topped off".
> 2. It does not require a redstone signal in order to keep an empty furnace running.
> 3. It **does not work** when a Furnace Engine is attached (which means you can't use it to cheese the production of massive amounts of mechanical energy) _unless_ a special option is enabled in the mod's configuration - presumably, this was meant to force players to use the Electric Motor instead.

just to add a number 4 to your list, the induction heater does not work with pneumaticcraft blocks as a form of heat generation whereas the external heater does
