### ISSUE TITLE
[Suggestion]: Add Engineer's Decor

### ISSUE THREAD

**Issue by therocki** [FTBTeam/FTB-Modpack-Issues#972]
### Modpack

FTB Plexiglass Mountain

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/engineers-decor
It would be nice if we could get Engineer's Decor. More decoration options are always nice.

**Comment by Raidobw2** [comment]
Hi, we have added this mod at some point in development, but removed it later due to choices. In my attempt to keep PGM lighter than usual, I skipped some mods and added other content mods instead. I was aware of this mod x Immersive Engineering x Create for decoration potential, but I decided to add Create Deco instead. Create Deco and Engineer's Decor shared some similarities so I had made that choice.

I'll also be adding another content mod soon which will add other decoration blocks (Occultism). Thanks for the suggestion even though I will not add this officially to the pack. Feel free to add it to the modpack though, it should normally work fine!
