### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Steve90a** [FTBTeam/FTB-Modpack-Issues#977]
### Modpack

Direwolf20 1.18

### Modpack version

1.5.1

### Describe the bug

Creating a new world will not follow world type selected.  With superflat selected, world generation is default or possibly large biome.  Occurred with each version 1.4 and later, did not try earlier versions.

### Steps to reproduce

1. Create new world
2. Select World Type to "Superflat".  Other options don't seem to have an effect.
3. Select any Preset.  I tried several.
4. Create New World

### Expected behaviour

Expected a world following preset.

### Screenshots

![Screenshot (1)](https://user-images.githubusercontent.com/107735211/174417051-866aae98-06c9-46d6-addf-e0a8f1dacb8d.png)
![Screenshot (2)](https://user-images.githubusercontent.com/107735211/174417052-70cbb64b-9836-4030-bbd3-ddcd927c9213.png)

**Comment by TheonlyTazz** [comment]
My assumption is that Terralith is messing with it, you can disable the mod to make your superflat world
When creating a new world, go to datapacks (it should list all your mods), scroll down to Terralith and disable it. That way it wont overwrite the worldgeneration. This issue is caused bcause Terralith is originally a Datapack, ported to be a Mod

![image](https://user-images.githubusercontent.com/3908847/174429206-6afcaf12-643f-4266-ab4f-844e44b3ddd7.png)

![image](https://user-images.githubusercontent.com/3908847/174428914-21b85946-4a84-4862-b58a-cd0a799f25dc.png)

**Comment by Steve90a** [comment]
Thank you, but disabling the mod as you described did not work.  I had to delete the file for Terralith for the world to generate correctly.
