### ISSUE TITLE
[Bug]: Certus Quartz Crystal recipes unstable in the Enrichment Chamber

### ISSUE THREAD

**Issue by zarillion** [FTBTeam/FTB-Modpack-Issues#984]
### Modpack

FTB Plexiglass Mountain

### Modpack version

1.0.2

### Describe the bug

The Mekanism Enrichment Chamber recipe for Certus Quartz Dust is not stable after server restarts. Sometimes the recipe produces Charged Certus Quartz Crystals, and sometimes it produces regular Certus Quartz Crystals. When it produces charged crystals, regular crystals can be created by enriching Certus Quartz Seeds. When it produces regular crystals, the only way to produce charged crystals is by using the AE2 Charger block.

Its unclear what the intended recipe behavior is. Both situations are automatable, although automating Chargers can be a hassle and is much slower. To work around the issue, we are currently restarting the server until the Charged crystal recipe comes back for the enrichment chamber.

Server running on `Ubuntu 20.04.4 LTS` with `openjdk 17.0.3 2022-04-19`

### Steps to reproduce

1. Restart FTB Plexiglass Mountain server instance.
2. Check status of Certus Quartz Dust recipes in JEI.
3. Repeat until behavior changes.

### Expected behaviour

The Certus Quartz Dust recipe should remain stable after restarts.

**Comment by Raidobw2** [comment]
Hello, I haven't been able to reproduce this on a local server unfortunately. I've rebooted the server 3 times and I could always craft a certus crystal from dust and seeds. What I've done is remove the extra recipes added by JAOPCA, hopefully this should fix it.

If it happens again, press F3 + H to enable advanced tooltips and hover the "?" in the recipe like so:
![image](https://user-images.githubusercontent.com/17010632/174467804-2aa3f484-ba40-45ce-81c0-49f811348cdc.png)

This should show you what adds that recipe. If the problematic recipe shows charged certus quartz as the output in the enrichment chamber, we'll see the mod name and confirm if that was JAOPCA. For now though, I'll consider this fixed in-dev, since that config change removes the dust to crystal recipe

**Comment by zarillion** [comment]
That is indeed what I am seeing:

![image](https://user-images.githubusercontent.com/64381982/174493554-c8157faa-1c99-43e0-81a0-fc09cbba86a0.png)

I tried restarting 3 times yesterday to get it back to the other state but it came up with the JAOPCA recipe 3 times in a row. It must be hardware dependent or maybe related to the JVM args in use. It sounds like the fix you put in place will resolve it in the next release, thanks for looking at it!
