### ISSUE TITLE
[Bug]: When joining a world it stops at 0%

### ISSUE THREAD

**Issue by TheSirHunter** [FTBTeam/FTB-Modpack-Issues#988]
### Modpack

FTB Plexiglass Mountain

### Modpack version

1.0.2

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8936471/latest.log)

### Describe the bug

When I try to join a world, it will stop at 0%

### Steps to reproduce

join a world

### Expected behaviour

I expected to join the world

### Screenshots

https://media.discordapp.net/attachments/983080030248796230/988197512588443728/unknown.png?width=869&height=676

### Additional information

It froze other times when joining the world but those times it said "not responding" and restarting fixed the issue

**Comment by Raidobw2** [comment]
Hi, I'm not sure if I can fix that. It does look like the server config is corrupted `littlelogistics-server.toml is not correct. Correcting`, but other than that I have no other tracks to find the main issue. I've never had this in-dev during the entire development of the pack.

If other people have the same issue repetitively, they can comment here and I'll reopen it. Although since it appears to have been fixed by a restart, I'll close this issue since it's currently resolved.
